### ISSUE TITLE
sqlpp11 fails to check whether selected columns are from their belonged table.

### ISSUE THREAD

**Issue by yixinglu** [rbock/sqlpp11#104]
When I used following codes to test sqlpp11, it also passed successfully and any compile errors didn't throw out.

```c++
  const auto p = test::TabPerson{};
  const auto f = test::TabFeature{};

  auto state = select(p.name).from(f); // it's wrong

  MockDb::_serializer_context_t context;
  ::sqlpp::serialize(state, context);
  std::cout << context.str() << std::endl;
```

After runing test program, I got a wrong SQL string: `SELECT tab_person.name FROM tab_feature`.  Couldn't sqlpp11 check this case?

**Comment by digitalist** [comment]
could you provide create statements for your tables?

**Comment by yixinglu** [comment]
@digitalist I only want to get a SQL string and didn't connect to a database, so I think it needn't  statements to create table, like [the sample examples](https://github.com/rbock/sqlpp11/blob/master/examples/sample.cpp#L41). 

After read the [`from_t`](https://github.com/rbock/sqlpp11/blob/master/include/sqlpp11/from.h#L266) template defination, I didn't find any static checks about the relationship between table and its columns. As far as I'm concerned, there should be some compile errors here.

**Comment by rbock** [comment]
Hi,

sqlpp11 does not perform the final consistency checks when serializing (maybe it should?).

If you want to know if a statement is valid, check `sqlpp::run_check_t<Context, T>::value` or run `sqlpp::run_check_t<Context, T>::_();`, where context is the serializer context of the connector library and T is the type of the statement.

Best,

Roland

**Comment by yixinglu** [comment]
@rbock Thanks for your replay. I have known that `sqlpp::run_check_t<Context, T>::_()` could check the consistency and complain a `no_unknown_tables_in_selected_columns` compile error. That's what I want to see.

This issue could be closed.

Regards
