### ISSUE TITLE
Querying three (or more) tables

### ISSUE THREAD

**Issue by paltoth** [rbock/sqlpp11#105]
Hi Roland,

First, congrats for this cool. library.

Is there a way to query more than two tables? Didn't found any examples, only for two.
Thank you.

Regards, Pál

BTW, at the and of the page https://github.com/rbock/sqlpp11/wiki/Select instead of **result.pop()**; should be **result.pop_front();**

**Comment by rbock** [comment]
Hi Pál,

Glad you like the library :-)

You can chain joins to query more than two tables:

```C++
foo.join(bar).on(foo.id == bar.foo).left_outer_join(baz).on(bar.id == baz.ref);
```

Thanks also for the documentation hint. Fixed.

Best regards,

Roland

**Comment by gggin** [comment]
Can you give us an more full exmaple? like:
```c++
for (const auto& r : db.run(
			sqlpp::select(table.username, table.password, table.salt).from(table.join(role_table).on(table.username == role_table.username)).
				where(table.username == username)))
```

**Comment by gggin** [comment]
I found this 
https://github.com/rbock/sqlpp11/wiki/Select

**Comment by rbock** [comment]
Like this?

```c++
for (const auto& r : db.run(
			sqlpp::select(all_of(foo))
                        .from(foo.join(bar).on(foo.id == bar.foo).left_outer_join(baz).on(bar.id == baz.ref))
                        .unconditionally()))
{
  // ....
}
```

Untested, I hope I got all the parentheses right :-)

**Comment by gggin** [comment]
So Great!
