### ISSUE TITLE
iterate over fields in a row

### ISSUE THREAD

**Issue by matthijs** [rbock/sqlpp11#106]
Hi,

Sometimes I need to get all result fields in another format, say json or something else. In that case it would be nice if I could iterate over the fields in a row object. Let me explain that by an example:

```c++
#include <sqlpp11/sqlpp11.h>

int main(int argc, char **argv) {

    // db connector
    auto config = std::make_shared<sqlpp::postgresql::connection_config>();
    sqlpp::postgresql::connection db(config);

    // could be ciere::json::value (see: https://github.com/cierelabs/json_spirit)
    ciere::json::value result;
    dbtable::users m_users;
    for(const auto &row: db(select(all_of(m_users)).from(m_users).unconditionally())) {

        // Here is the row object
        result["id"] = row.id;
        result["name"] = row.name;
        result["lastname"] = row.lastname;
    }

    // iterate over a row (runtime)
    for(const auto &row: db(select(all_of(m_users)).from(m_users).unconditionally())) {
        for(auto &field: row) {
            result[field.name] = field.value;
        }
    }

    return 0;
}
```

The above example iterates over a row at runtime, but as we know all fields at compile time it would be nice to generate a template function which iterates over the fields in a row object.

Is there a possibility that this could be implemented?

Regards, Matthijs

**Comment by rbock** [comment]
Hi Matthijs,

The row type is a bit similar to a tuple. Each field has its own type. Therefore it would be difficult to iterate over the fields with a for-loop.

It should be quite easy to write some similar `to std::get`, though. Or some kind of apply-method that can be called with a functor that does something for each field.

I'll need to think about this in a bit more detail...

Best,

Roland

**Comment by rbock** [comment]
Hi Matthijs,

Please take a look at develop. I just pushed a change that allows you to do the following:


- You provide some callable, for instance:
```C++
struct to_cerr
{
  template <typename Field>
  auto operator()(const Field& field) const -> void
  {
    std::cerr << get_sql_name(field) << " = " << field << std::endl;
  }
};
```

 - You apply the callable to each result field of a row like this:

```C++
  for (const auto& row : db(select(all_of(t)).from(t).unconditionally()))
  {
    for_each_field(row, to_cerr{});
  }
```

There are two versions of `for_each_field`, one takes a const reference (used here). The other takes the callable by non-const reference, allowing you to modify the callable, e.g. incrementing a counter.

Please be aware that this is not thoroughly tested yet.

Let me know what you think.

Cheers,

Roland

**Comment by matthijs** [comment]
Hello Roland,

I've tested your commit and the few tests I did works like a charm!

```c++
for (const auto& row : db(select(all_of(t)).from(t).unconditionally()))
{
  for_each_field(row, [](const auto &field) {
    std::cout << get_sql_name(field) << ": " << field.value() << std::endl;
  });
}
```

I will test it in my production environment and let you know.

Nicely done!

Regards, Matthijs

**Comment by rbock** [comment]
Hi Matthijs,

Thanks for the feedback! I am looking forward to using C++14, too :-)

Best,

Roland

**Comment by rbock** [comment]
Hi Matthijs,

I guess it works fine?

Please open a new issue otherwise :-)

Cheers,

Roland
