### ISSUE TITLE
Can it be compiled under QT 5.4.1 ?

### ISSUE THREAD

**Issue by xeoshow** [rbock/sqlpp11#107]
Hi, 

I found this is a great project for working with sqlite, very flexiable, while my project is a qt 5.4.1 project, I am using qt-opensource-windows-x86-msvc2013_opengl-5.4.1.exe, does it supported?

Thanks!

Best regards, Jason

**Comment by rbock** [comment]
Hi Jason,

If you're using MSVC, you need the MSVC-2015, Update 2 (or probably later).

As for combining it with qt, I am not sure what you're asking? Are you asking for the qt database abstraction? There is no connector for that yet (afaik), but if you take a look at the existing connector libraries, it is not hard to implement.

Hope that helps?

Best,

Roland

**Comment by xeoshow** [comment]
Thanks so much for kind help!

Best regards, Jason

**Comment by vincent-hui** [comment]
Hi xeoshow,

Do you know how to combine sqlpp11 with Qt?

Thank a lot

**Comment by shishirong** [comment]
> 
Are you making progress that sqlpp11 with Qt .

**Comment by shishirong** [comment]
> 

@vincent-hui  
Are you making progress that sqlpp11 with Qt .
