### ISSUE TITLE
'date.h' file not found while using the library

### ISSUE THREAD

**Issue by balthild** [rbock/sqlpp11#108]
My operating system is Mac OS X 10.11, and I uses CMake as my project's build system.

I've already compiled sqlpp11 with these cmake flags : 
```
cmake -DHinnantDate_ROOT_DIR=/Users/balthild/src/hinnantdate/ -DHinnantDate_INCLUDE_DIR=/Users/balthild/src/hinnantdate/
```
and installed sqlpp11 to `/usr/local/` . 

But when I tried including sqlpp11's header file in my project, it showed the error that can't find the header file of HinnantDate : 
```
/usr/local/include/sqlpp11/chrono.h:30:10: fatal error: 'date.h' file not found
#include <date.h>
```

Hinnant's library doesn't provide any building system config so it's impossible to install the header file it into `/usr/local/include` (Copy-Paste probably wont work, since there's a `tz.cpp` which need compiling).

**Comment by rbock** [comment]
Hi Balthild,

`date.h` is a stand-alone header file. You can copy it anywhere you want. You then need to tell CMake to add the respective directory to the include paths.

Hope that helps.

Best,

Roland

**Comment by balthild** [comment]
I see. Thanks.
