### ISSUE TITLE
read pragma for version management

### ISSUE THREAD

**Issue by daviswalker** [rbock/sqlpp11#110]
I'm interested in doing upgrade management of my table's scheme using PRAGMA user_version. I'm trying to figure out the best way to read the current value of this pragma. I've been looking at custom_query but haven't been able to figure out how to get a value out of it, given that it's not really a select. I'm sure I'm doing something simple wrong, but any suggestions? Thank you very much.

Some sample code of my initial attempt.

        auto c = custom_query(sqlpp::verbatim("PRAGMA user_version"));
        auto i = db_(c);
        std::cerr << i << std::endl;

        auto x = custom_query(sqlpp::verbatim("PRAGMA user_version = "), 1);
        db_(x);

        auto d = custom_query(sqlpp::verbatim("PRAGMA user_version"));
        auto j = db_(c);
        std::cerr << j << std::endl;

**Comment by rbock** [comment]
Hi Davis,

`custom_query` is more for creating database specific versions of `select`, `insert` and the like. You might be able to bend it to do what you want to, but it would take some effort. I haven't tried your code, but I guess you're getting rather horrific error messages?

There is one undocumented (shame on me) function called `eval` that should do the job though:

```C++
auto c = sqlpp::eval<sqlpp::integer>(db_, "PRAGMA user_version");
```

Let me know if that works for you and remind me of documenting :-)

Best,

Roland

**Comment by daviswalker** [comment]
Roland, thanks for the quick response. It looks like eval tries to bend its string to be a select?

exception 'Sqlite3 error: Could not prepare statement: near "AS": syntax error (statement was >>SELECT PRAGMA user_version AS a<<

**Comment by rbock** [comment]
Right, I thought that would work... I am not using `PRAGMA` myself...

Thinking about it, I believe that the following should work, except that there is a bug in sqlpp11.

```C++
SQLPP_ALIAS_PROVIDER(pragma);
```
And then:
```C++
int pragmaValue = db(custom_query(sqlpp::verbatim("PRAGMA writeable_schema"))
                           .with_result_type_of(select(sqlpp::value(3).as(pragma))))
                        .front()
                        .pragma;
```

This should compile, but currently doesn't. I identified one bug already, but there is another one. I am looking for it now.

Best,

Roland

**Comment by rbock** [comment]
Hi Davis,

I think I fixed things now. Please take a look at the develop branches of both, sqlpp11 and sqlpp11-connector-sqlite3

I added a test in the sqlite connector in `tests/SampleTest.cpp`.

Please let me know if it works for you.

Best,

Roland

**Comment by daviswalker** [comment]
Roland, victory! Thank you so much.

**Comment by rbock** [comment]
Thanks for the feedback :-)
