### ISSUE TITLE
offset / limit should be positive values, better check?

### ISSUE THREAD

**Issue by matthijs** [rbock/sqlpp11#114]
Hello Roland,

I have the following piece of code which won't compile due to a check on the integral value.
```c++
    uint32_t offset {0};
    uint32_t limit {10};

    auto qry = select(all_of(table))
        .from(table)
        .unconditionally()
        .limit(limit)
        .offset(offset);
```

.limit and .offset are requiring an integral value (see limit.h at line 201 and offset.h at line 215).

As far as I know, the offset and limit should not be negative so the test could be improved to is_unsigned_integral.

I've checked this for PostgreSQL, before 9.1 it was undefined behaviour and from 9.1 and forward it will result in an SQL error. As far as I see for MySQL it also seems not possible to have negative values for either limit or offset.

Regards, Matthijs

**Comment by rbock** [comment]
Hi Matthijs,

Right, I'll look into that ASAP.

Best,

Roland

**Comment by matthijs** [comment]
As already said on gitter, it works correctly on the develop branch.

Thanks, Matthijs
