### ISSUE TITLE
dynamic_select runtime error

### ISSUE THREAD

**Issue by matthijs** [rbock/sqlpp11#115]
Hello Roland,

When doing something like:
```c++
    auto qry = sqlpp::dynamic_select(db)
        .from(m_table)
        .dynamic_columns()
        .dynamic_where()
        .dynamic_offset()
        .dynamic_limit();

    qry.offset.set(static_cast<int64_t>(offset));
    qry.limit.set(static_cast<int64_t>(limit));
    try {
        auto res = db(qry);
    } catch(const sqlpp::exception &e) {
        std::cerr << e.what() << std::endl;
        return 1;
    }
```

I'll get the runtime error:
ERROR:  syntax error at or near "FROM"
LINE 1: SELECT  FROM users WHERE TRUE LIMIT 10 OFFSET 0

I was expecting a compile time error that the query wasn't allowed without columns.

Regards, Matthijs

**Comment by rbock** [comment]
Hi Matthijs,

The library cannot know at compile time whether or not you add dynamic columns at runtime. It would be possible to issue a clearer exception at runtime, of course.

If you know none of the columns you want to select at compile time, you have to check for yourself, if you are actually selecting anything. The library cannot do that for you.

Best,

Roland
