### ISSUE TITLE
unexpected compile error with dynamic_select

### ISSUE THREAD

**Issue by matthijs** [rbock/sqlpp11#116]
Hello Roland,

When I construct the query as follows and trying to get the results:
```c++
    auto qry = sqlpp::dynamic_select(db)
        .from(m_table)
        .dynamic_columns()
        .dynamic_where()
        .dynamic_offset()
        .dynamic_limit();

    qry.selected_columns.add(m_table.id);
    qry.offset.set(static_cast<int64_t>(offset));
    qry.limit.set(static_cast<int64_t>(limit));
    try {
        for(const auto &row: db(qry)) {
            std::cout << "row.id: " << row.id << std::endl;
        }
    } catch(const sqlpp::exception &e) {
        std::cerr << e.what() << std::endl;
        return 1;
    }
```

I'll get a compile error:
[ 12%] Building CXX object CMakeFiles/management.dir/main.cpp.o
/home/matthijs/Projects/test/main.cpp:40:35: error: no member named 'id' in
      'sqlpp::dynamic_result_row_t<sqlpp::postgresql::connection>'
                        std::cout << "row.id: " << row.id << std::endl;
                                                   ~~~ ^
1 error generated.
CMakeFiles/management.dir/build.make:62: recipe for target 'CMakeFiles/management.dir/main.cpp.o' failed
make[2]: *** [CMakeFiles/management.dir/main.cpp.o] Error 1

I didn't expect this compile error.

Regards, Matthijs

**Comment by rbock** [comment]
Hi Matthijs,

Anything you add to a dynamic clause is not checked (in the same detail) at compile time. In the case of selected columns, it is also not added to the row type as a member. Instead, you have to access such dynamic columns in a map-like manner:

```
   std::cout << row["id"];
```

Best,

Roland

**Comment by matthijs** [comment]
Hi Roland,

Thanks, you probably mean:
```c++
std::cout << row.at("id");
```

I didn't see an operator[] defined in the dynamic_result_row_t struct.

Regards, Matthijs

**Comment by rbock** [comment]
Yes, sorry for that.
