### ISSUE TITLE
Add check to build if all files have complete include directives

### ISSUE THREAD

**Issue by rbock** [rbock/sqlpp11#119]
Every now and then we stumble across a file that does not have a complete set of include directives. This is quite annoying.

I am sure there are tools to check this automatically. Such a tool should be part of the build/test.

**Comment by digitalist** [comment]
are there any examples of such errors in the past git history?

**Comment by rbock** [comment]
See for instance this pull request by @Erroneous1 https://github.com/rbock/sqlpp11/pull/118

**Comment by niXman** [comment]
@rbock +1

**Comment by niXman** [comment]
http://include-what-you-use.org/
