### ISSUE TITLE
MS Visual Studio 2015 support

### ISSUE THREAD

**Issue by gggin** [rbock/sqlpp11#121]
latest dev code with latest sqlpp-mysql-connector compile fail in 2015 
and 0.35 sqlpp I cannot compile with the latest sqlpp-mysql-connector... so I feel confused!
Can you release sqlpp-mysql-connector with sqlpp's version?

**Comment by rbock** [comment]
Hi,

As you can see [here](https://gitter.im/sqlpp11/Lobby), @ACB1337 was able to compile on Windows using the latest release of both, sqlpp11 and sqlpp11-connector-mysql.

Running a rebuild, I can see that there is a problem when trying to compile with MariaDb, something about snprintf which looks really annoying, but should be unrelated.

If you continue having problems, can you send me actual error messages, please?

Best,

Roland

**Comment by gggin** [comment]
```c++
sqlpp::mysql::connection db(config);
		test::User user_table;
		auto x = db.run(sqlpp::select(sqlpp::all_of(user_table)).from(user_table).where(true));
```

1>crow\example.cpp(157): error C2672: 'sqlpp::mysql::connection::run': no matching overloaded function found
1>crow\example.cpp(157): error C2893: Failed to specialize function template 'unknown-type sqlpp::mysql::connection::run(const T &)'
1>  crow\example.cpp(157): note: With the following template arguments:
1>  crow\example.cpp(157): note: 'T=sqlpp::assert_where_arg_is_not_cpp_bool_t'

![image](https://cloud.githubusercontent.com/assets/3293064/18820789/1b05f2a8-83d3-11e6-9a0d-39d0162a532f.png)


Thank you!

**Comment by gggin** [comment]
I found .unconditionally() function compile good!
Please update sqlpp11-mysql-connector's example!

**Comment by rbock** [comment]
The error message is good news. Shows that even though MSVC is swallowing the static assert, you get something to work with.

I updated the README, too. Thanks!
