### ISSUE TITLE
sql inject question

### ISSUE THREAD

**Issue by gggin** [rbock/sqlpp11#122]
I use this library for a few days. I feel so good!
Just a question can this library prevent me from sql injection attach?

**Comment by rbock** [comment]
Glad the library makes you feel good :-)

sqlpp11 escapes all strings using the escape function provided by the connector. That should protect you from code injection.

Actually, it would be good to have some unit tests for that. Maybe you can add a few for the connectors you are using and create a pull request?

Best,

Roland

**Comment by gggin** [comment]
I will try!
