### ISSUE TITLE
Error: datatype "decimal"" is not supported. ?

### ISSUE THREAD

**Issue by Shravan40** [rbock/sqlpp11#127]
Lets say, I have a table name `money` in my database. 
[create table `money` (
`id` bigint(20),
`amount` decimal(10,3),
primary key(id)
)` ](url)

I am trying to convert the `ddl to cpp` using this [python script](https://github.com/rbock/sqlpp11/blob/master/scripts/ddl2cpp) but it don't have support to type decimal. Please add it.

**Comment by rbock** [comment]
What C++ type would you want to have here? Double would be rather simple.

**Comment by Shravan40** [comment]
Since i am dealing with financial numbers, decimal is more accurate.

**Comment by rbock** [comment]
Does C++ have a decimal type?

I am using `long` (C++) and `bigint` (SQL) for financial data.

**Comment by Shravan40** [comment]
No, C++ do not have decimal as basic data type.

But, while going through this [http://stackoverflow.com/a/14096071/1691223](url), i found that some compilers supports though.

**Comment by rbock** [comment]
That is something I do not intend to add to the library, though.

But please look at the present datatypes. If you want support for this decimal class, it should be fairly simple to write the mapping you need.

Or use `bigint`, `long` and some kind of units for your calculations.

**Comment by Shravan40** [comment]
Okay sure,

In my case, I am going to arithmetic operation on multiple returns rates. Hence i am afraid that i might get wrong values because of this [http://stackoverflow.com/q/6831217/1691223](url)

**Comment by rbock** [comment]
That's why you are right to use non-float for your calculations. Personally, I am using long. As long as I am aware of the units, everything is fine.

BTW: Please check how to format urls in comments. Your links do not point to the intended location.

**Comment by rbock** [comment]
Closing this. Please consider writing an extension for decimal values.
