### ISSUE TITLE
HinnantDate being reported found, then not found, in cmake

### ISSUE THREAD

**Issue by biot023** [rbock/sqlpp11#130]
Making the project first tells me that it's found HinnantDate, but then tells me that it couldn't be found.
This is the output from my attempt to build the project:

    cmake .. -DHinnantDate_ROOT_DIR=/src/date/
    ---> Running in 0fccd9d1026b
    -- The CXX compiler identification is GNU 6.3.0
    -- Check for working CXX compiler: /usr/local/bin/c++
    -- Check for working CXX compiler: /usr/local/bin/c++ -- works
    -- Detecting CXX compiler ABI info
    -- Detecting CXX compiler ABI info - done
    -- Detecting CXX compile features
    -- Detecting CXX compile features - done
    -- Found HinnantDate: /src/date
    CMake Error at CMakeLists.txt:32 (find_package):
    Found package configuration file:
    
    /usr/local/lib/cmake/Sqlpp11/Sqlpp11Config.cmake
    but it set Sqlpp11_FOUND to FALSE so package "Sqlpp11" is considered to be
    NOT FOUND. Reason given by package:
    
    Sqlpp11 could not be found because dependency HinnantDate could not be
    found.
    
    -- Configuring incomplete, errors occurred!

I'm afraid I'm not very experienced with CMake -- could you please advise me as to what I've done wrong, here?
Thanks.

**Comment by rbock** [comment]
Hi,

Which project are you trying to build?

@ianda Maybe you can help with this issue?

Best,

Roland

**Comment by biot023** [comment]
Ah, sorry -- this is the postgresql connector for sqlpp11 -- I should post there!

**Comment by rbock** [comment]
@biot023 Thanks for the clarification

@ianda I think you worked on both projects on the CMake scripts. Please take a look. I am honestly not sure where this needs to be fixed.

**Comment by biot023** [comment]
Thankyou so much for looking into this -- some further information is that sqlpp-11 has already been installed, and installing the connector is the next step.
This is happening in a Docker file -- the relevant section is here:

    # INSTALL HinnantDate
    WORKDIR /src
    RUN git clone https://github.com/HowardHinnant/date.git
    
    # INSTALL sqlpp11
    WORKDIR /src
    RUN git clone https://github.com/rbock/sqlpp11.git
    RUN mkdir /src/sqlpp11/build
    WORKDIR /src/sqlpp11/build
    RUN cmake .. -DHinnantDate_ROOT_DIR=/src/date/
    RUN make -j 8
    RUN make install
    
    # INSTALL sqlpp11 postgresql driver
    WORKDIR /src
    RUN git clone https://github.com/matthijs/sqlpp11-connector-postgresql.git
    RUN mkdir /src/sqlpp11-connector-postgresql/build
    WORKDIR /src/sqlpp11-connector-postgresql/build
    RUN cmake .. -DHinnantDate_ROOT_DIR=/src/date/
    RUN make -j 8
    RUN make install

Thanks again,
   Doug.

**Comment by biot023** [comment]
Oh, and the very last bit of the error log invited me to also inspect the file /src/sqlpp11-connector-postgresql/build/CMakeFiles/CMakeOutput.log

Which I've managed to get a dump of, and have created a gist of here: https://gist.github.com/biot023/071fa2c7ff9f8e32161bbaf670205c93

**Comment by rbock** [comment]
Meanwhile I did a fresh install of sqlpp11 (current develop branch), cloned the postgresql connector (master) and ran cmake.

```
~/projects/sqlpp11-connector-postgresql/build$ cmake ../ -DHinnantDate_ROOT_DIR=$PWD/../../date
```

No problems.

Is it possible that you are using an older version of sqlpp11 or the connector?

**Comment by biot023** [comment]
I don't think so -- my install script (above) pulls the latest code from each project's GitHub page.
I'll see if I can install manually over the weekend to see if anything more informative gets reported.
Thanks for trying the fresh install!

**Comment by rbock** [comment]
You might also want to check if maybe you have some cmake files flying around that were once installed by an older version.

**Comment by ianda** [comment]
I am surprised by this error. Roland's idea about old files which are confusing cmake is the best explanation I can think of.

Also, could you try setting `CMAKE_PREFIX_PATH` instead of `HinnantDate_ROOT_DIR`. Are you using `find_package(Sqlpp11 …)` and `find_package(sqlpp-postgresqlTargets …)` in your CMakeLists.txt? In which order? Could you disable `find_package(Sqlpp11 …)` for testing if used?

**Comment by biot023** [comment]
Hi -- doing a `apt-get purge --auto-remove cmake` before installing the latest CMake fixed this, like you suggested.
I then got a PostgreSQL-related error which was fixed by `apt-get install postgresql-server-dev-9.4`.
Thankyou so much for your help!
PS -- sorry about the late reply, I was moving house at the weekend, so it was rather naive to promise I'd look at this then! :)

**Comment by rbock** [comment]
Thanks for the feedback, glad it works now :-)
