### ISSUE TITLE
date.h is not present

### ISSUE THREAD

**Issue by niXman** [rbock/sqlpp11#133]
Hi,

When using the `develop` branch I get the errors that the `date.h` file does not exist.
wtf?

https://github.com/rbock/sqlpp11/blob/develop/include/sqlpp11/data_types/day_point/operand.h#L30

**Comment by mkroman** [comment]
Have you read the [README](https://github.com/rbock/sqlpp11/blob/master/README.md)?

__Date Library:__
sqlpp11 requires [Howard Hinnant's date library](https://github.com/HowardHinnant/date) for `date` and `date_time` data types. Sqlpp11 includes CMake search module for this, but if you didn't install this library system-wide, you need to point cmake to it:

```
cmake -DHinnantDate_ROOT_DIR=/%PATH_TO_HinnantDate_SOURCE%/
```

**Comment by niXman** [comment]
Oh, sorry, my bad!

Closed as noise.
