### ISSUE TITLE
sqlpp11 in Debian and Fedora

### ISSUE THREAD

**Issue by russel** [rbock/sqlpp11#135]
It seems that sqlpp11 is not in the Debian or Fedora repositories, has any effort been made to get it (and associated bits) packaged for these distributions?

**Comment by rbock** [comment]
Hi Russel,

I am not aware of any such efforts. Maybe you could help with that? Or know someone who would?

Since sqlpp11 itself is header-only, that part would probably be quite simple (for someone who knows how to create packages). The connector libraries have rather minimal dependencies, too.

Best,

Roland

**Comment by russel** [comment]
I am neither a Debian nor Fedora packager myself, but I know people who are. That sqlpp11 is header only will make it trivially easy to package. The other packages have to be buildable from source using a build system and compilation system that is packaged. Certainly the SQLite3 connector is easy since it is C++ and CMake (though Meson is the rising star here). If the others connectors are the same then there is no problem, just the getting someone to do the job.

**Comment by rbock** [comment]
Sorry for the late answer, got lost in current turmoils. I'd appreciate if you could reach out to the packagers you know. The other database connectors have the same structure and should therefore be similarly simple to turn into packages.

Best,

Roland

PS: The stl-connector is not in any shape to be packaged.

**Comment by rbock** [comment]
Hi Russel,

I am closing this ticket for now. I'd gladly help package maintainers, of course.

Best,

Roland
