### ISSUE TITLE
Unable to Compile with Visual Studio 2017 RC

### ISSUE THREAD

**Issue by fpark12** [rbock/sqlpp11#140]
It looks like VS2015 is able to compile sqlpp11 but VS2017 RC cannot. Below are the compile errors I got while compiling with VS2017 RC. Is there a work around at the moment?

sqlpp11\sqlpp11/statement.h(129): error C3520: 'Policies': parameter pack must be expanded in this context
sqlpp11\sqlpp11/having.h(238): error C3520: 'T': parameter pack must be expanded in this context

**Comment by fpark12** [comment]
I was able to fix the second compiling error by changing line 240 of having.h from:
      struct _check : logic::all_t<is_expression_t<T>::value...>
to
      struct _check : logic::all_t<is_expression_t<T>::value...>...

**Comment by fpark12** [comment]
I found a hack for the first compile error. I decomposed the none_t into multiple steps. Below is how it looks like. 

	  // work around for msvc bug:
	  // error C3520 : 'Policies' : parameter pack must be expanded in this context
	  using is_missing_policies_t_1 = logic::logic_helper<is_missing_t<Policies>::value...>;
	  using is_missing_policies_t_2 = logic::logic_helper<(is_missing_t<Policies>::value && false)...>;
      using _value_type =
          typename std::conditional<std::is_same<is_missing_policies_t_1, is_missing_policies_t_2>::value,
                                    value_type_of<_result_type_provider>,
                                    no_value_t  // if a required statement part is missing (e.g. columns in a select),
                                                // then the statement cannot be used as a value
                                    >::type;

**Comment by fpark12** [comment]
Pull request submitted.

#141

**Comment by rbock** [comment]
Hi Frank,

Thanks for the report. Looks like variadic templates are even more broken than before.

I won't even try to maintain workarounds for that. Please file bugs at Microsoft. That is the only reasonable way to fix this, I am afraid.

Best,

Roland

**Comment by fpark12** [comment]
Hi Roland,

Thanks for the quick reply. I have to say it is quite unfortunate that the vs2017 compiler seems to be less promising that Microsoft claimed. I think it was still the right thing to open an issue here because people that recently started using vs2017 might run into the same issue. At least we have a readily available hack for those who need it. Let's close this issue for now and I will try to submit a bug report to Microsoft soon.

Frank

**Comment by rbock** [comment]
Thanks for following up on this.

I'd be interested in receiving a link to the bug report once you've submitted it.

Best,

Roland

**Comment by RavenX8** [comment]
So I have this same issue with the latest version of VS2017. Did you happen to ever submit that bug report?

Thanks

**Comment by fpark12** [comment]
I have indeed submitted a bug report but I cannot locate it anymore on the website. The last time I checked they have acknowledged the issue and said they will fix it in the future.

Frank
