### ISSUE TITLE
Some enhancement suggestions for result_t::iterator

### ISSUE THREAD

**Issue by theodelrieu** [rbock/sqlpp11#142]
Hi, awesome library!

It would be really cool if that iterator could be a fully standard conformant one.
For example, I just had an error with MSVC looking for `std::iterator_traits<result_t::iterator>::iterator_category`, while doing something of the sort:

```cpp
// 'auto const' results in a compile error (at the transform call), don't know why
auto rows = db(select(all_of(user)).from(user).unconditionally());
std::vector<cpp_user> vec;

// this breaks on MSVC 2015
std::transform(rows.begin(), rows.end(), std::back_inserter(vec), convert_to_user);
```

1. The `transform` call can be replaced by a for-loop, so that's not a really blocking issue.
2. I have no idea why I cannot store the result of `db(...)` as `auto const` ?

I don't fully remember what's needed for an iterator to be fully conformant, but providing the specialization of `std::iterator_traits` would be really nice.

PS:
I might open another issue for this one, but isn't it possible to have a `size` method on the row object?
My use-case is to call `reserve` on a vector, and right now I have to do a `select(count(...))` to have that info (`std::distance` doesn't work because of `iterator_category` too)

Thanks in advance!

**Comment by rbock** [comment]
Dear Theo,

Thanks for the detailed issue.

Let's start with the `size`. I think there is no portable way to obtain the size for the result set. Some databases just don't offer this information. However, it would be possible to offer it for those databases that have the information, of course.

About the non-constness of the result set: This is similar to an `istream`: It changes internal state while you read it. Depending on the database (and/or the type of connection) you can only forward-iterate the result set, e.g. rows are read on demand from the server and discarded after being read.

Regarding the iterator conforming the requirements, I guess there isn't much missing.

It would be awesome if you could help with this. I think it would be best to start with the iterator. Even if you can't fix the iterator code itself (I know the code isn't easy), you could provide one or more test cases that should work?

Size would be next. I think it would make sense to open a second issue for that.

Cheers,

Roland

**Comment by theodelrieu** [comment]
I see, I'll try to fix the iterator this week then!

**Comment by rbock** [comment]
Great! Let me know if you need support!

**Comment by rbock** [comment]
The iterator issue is fixed, I think. Thanks for your support!

If you want to tackle size(), please create a new pull request.
