### ISSUE TITLE
SELECT FOR UPDATE support?

### ISSUE THREAD

**Issue by sergeken** [rbock/sqlpp11#145]
I'm wondering if there are plans to implemented support for the "SELECT FOR UPDATE" variant of the SELECT statement or anything alike?

**Comment by rbock** [comment]
I wasn't even aware of this, so no, not yet. But it should be fairly easy to add.

Would you like to give it a try?

**Comment by sergeken** [comment]
Hi Roland,

I will try without promises.  It's my attempt to get my head around heavy template code.
The implementation is fairly simple, just add "FOR UPDATE" at the end of the select statement.

Do you suggest to add an .for_update() to the selected?

Serge

**Comment by rbock** [comment]
Hi Serge,

Yes, `.for_update()` sounds about right. You might want to take a look at limit.h. It is probably the simplest clause. Assuming that you don't want to add optional arguments to lock only certain tables, you can drop all the `dynamic` stuff, the `for_update_data_t` will be empty I guess.

The code is not exactly beautiful. I am working on a C++17 version that will be much nicer and easier to comprehend. For the time being, you have to work through the existing stuff. Let me know if you need help.

Best,

Roland

**Comment by sergeken** [comment]
Hi Roland,
I managed to "clone" limit in for_update, removing the dynamic stuff and updated the serializer to emit "FOR UPDATE".  Things seems to compile and tests passes when I use for_update(1u).  I failed to understand how to remove the argument as I got lost in the template code.  I've attached the changes so far.
[for_update.h.txt](https://github.com/rbock/sqlpp11/files/907848/for_update.h.txt)

**Comment by rbock** [comment]
Hi Serge,

That looks pretty good already! You're close :-)

I did not think about the fact that functions with no arguments looks slightly different from those with one or more arguments. Please take a look at

insert_value_list.h
```
auto default_values() const -> _new_statement_t<consistent_t, insert_default_values_t>
{
   return {static_cast<const derived_statement_t<Policies>&>(*this), insert_default_values_data_t{}};
}
```

Best,

Roland

**Comment by sergeken** [comment]
Hi Roland,

I've attached the amended version of Select.md to relfect the for_update() method.
This shall normally be all to close this ticket.
[Select.md.txt](https://github.com/rbock/sqlpp11/files/923721/Select.md.txt)

**Comment by rbock** [comment]
Thanks!

Added for_update text and the missing brace :-)
