### ISSUE TITLE
Add support for PostgreSQL serial types in ddl2cpp

### ISSUE THREAD

**Issue by sergeken** [rbock/sqlpp11#146]
The changes below enables support for PostgreSQL *serial types.

# MAP SQL TYPES
types = {
    'tinyint': 'tinyint',
    'smallint': 'smallint',
    'smallserial': 'smallint',  # PostgreSQL
    'integer': 'integer',
    'int': 'integer',
    'serial': 'integer',  # PostgreSQL
    'bigint': 'bigint',
    'bigserial': 'bigint',  # PostgreSQL
    'char': 'char_',
    'varchar': 'varchar',
    'text': 'text',
    'tinyblob': 'blob',
    'blob': 'blob',
    'mediumblob': 'blob',
    'longblob': 'blob',
    'bool': 'boolean',
    'boolean': 'boolean',
    'double': 'floating_point',
    'float': 'floating_point',
    'date': 'day_point',
    'datetime': 'time_point',
    'timestamp': 'time_point',
    'enum': 'text',  # MYSQL
    'set': 'text',  # MYSQL
    }

ddlAutoValue = Or([
        ddlWord("AUTO_INCREMENT"),
        ddlWord("SMALLSERIAL"),
        ddlWord("SERIAL"),
        ddlWord("BIGSERIAL"),
        ]).setResultsName("hasAutoValue")

**Comment by rbock** [comment]
Hi,

did you just add the lines marked with `# PostgreSQL`?

Thanks,

Roland

**Comment by sergeken** [comment]
Hi Roland,

Yes, these are the lines I did add to your script.  The *serial are matched to the respective *ints and the ddAutoValue has been enriched to capture *serial.

Regards,
Serge

**Comment by rbock** [comment]
Hi Serge,

OK, changed, committed and pushed to develop.

Best,

Roland
