### ISSUE TITLE
Best way to convert between database model & user-defined type

### ISSUE THREAD

**Issue by theodelrieu** [rbock/sqlpp11#148]
Hi Roland,

I wanted to know if there were functions like this in sqlpp:

```cpp
template <typename UDT>
void to_db(sqlpp::connection& db, UDT const& my_type);

template <typename UDT, typename Row>
void from_db(Row const& row, UDT& my_type);
```

Right now I have to relay on a `table_traits<T>` struct (which need a lot of code to do this, and some other things) in my generic container that is using sqlpp.

The two methods above relies on ADL, just like in [JSON for Modern C++ 2.1.0](https://github.com/nlohmann/json/releases/tag/v2.1.0).

I think this would be a great addition to the library (if it's not present already)

**Comment by rbock** [comment]
Hi Theo,

Ah, and then you would like to be able to write

```
db(insert_into(t).set(x));
db(update(t).set(x).unconditionally());
```

or 

```
x = row
```

?

That's not present yet. I have to think about it.

Cheers,

Roland

**Comment by theodelrieu** [comment]
Something along those lines, yes!

Maybe a `convert<T>` or `get<T>` method would be great too, then the `operator T()` would call that method.

**Comment by rbock** [comment]
Putting this on the wish list.
