### ISSUE TITLE
Errors when compiling on VS2015

### ISSUE THREAD

**Issue by sinall** [rbock/sqlpp11#149]
> Severity	Code	Description	Project	File	Line	Suppression State
> Error	C2065	'Clause': undeclared identifier	SQLCipherDemo	c:\users\xxx\documents\visual_studio_2015\projects\sqlcipherdemo\packages\sqlpp11-0.46\include\sqlpp11\hidden.h	47	
> Error	C2923	'sqlpp::hidden_t': 'Clause' is not a valid template type argument for parameter 'Clause'	SQLCipherDemo	c:\users\xxx\documents\visual_studio_2015\projects\sqlcipherdemo\packages\sqlpp11-0.46\include\sqlpp11\hidden.h	47	
> Error	C2977	'sqlpp::serializer_t': too many template arguments	SQLCipherDemo	c:\users\xxx\documents\visual_studio_2015\projects\sqlcipherdemo\packages\sqlpp11-0.46\include\sqlpp11\serializer.h	46	
> Error	C2447	'{': missing function header (old-style formal list?)	SQLCipherDemo	c:\users\xxx\documents\visual_studio_2015\projects\sqlcipherdemo\packages\sqlpp11-0.46\include\sqlpp11\hidden.h	48	
> Error	C2059	syntax error: '<'	SQLCipherDemo	c:\users\xxx\documents\visual_studio_2015\projects\sqlcipherdemo\packages\sqlpp11-0.46\include\sqlpp11\hidden.h	47	
> Error	C2143	syntax error: missing ';' before '<'	SQLCipherDemo	c:\users\xxx\documents\visual_studio_2015\projects\sqlcipherdemo\packages\sqlpp11-0.46\include\sqlpp11\hidden.h	47	
> Error	C2143	syntax error: missing ';' before '{'	SQLCipherDemo	c:\users\xxx\documents\visual_studio_2015\projects\sqlcipherdemo\packages\sqlpp11-0.46\include\sqlpp11\hidden.h	48	
> Error	C1903	unable to recover from previous error(s); stopping compilation	SQLCipherDemo	c:\users\xxx\documents\visual_studio_2015\projects\sqlcipherdemo\packages\sqlpp11-0.46\include\sqlpp11\serializer.h	46	
> Error	C2988	unrecognizable template declaration/definition	SQLCipherDemo	c:\users\xxx\documents\visual_studio_2015\projects\sqlcipherdemo\packages\sqlpp11-0.46\include\sqlpp11\hidden.h	47	
> 

Environment:
VS2015 Update 1
sqlpp11-connector-sqlite3: 0.23
sqlpp11: 0.46
SQLCipher: 3.4.1 (SQLite: 3.15.2)

How could I fix this?

**Comment by rbock** [comment]
Hi,

I am afraid you need to update to a newer version of the compiler. Update 1 is quite old and pretty buggy.

Unfortunately I had reports that the 2017 version also has troubles. Thus, I guess that the latest 2015 Update is probably your safest bet.

Best,

Roland

**Comment by sinall** [comment]
I have already updated VS2015 to Update 3 (the latest version, Update 2 is seems offline), but still have the same errors.

**Comment by rbock** [comment]
Hi,

I have no direct way of testing with Windows. But appyevor is happy, see for instance here: https://ci.appveyor.com/project/rbock/sqlpp11

Copying from the log:
> cmake .. -DCMAKE_CXX_FLAGS="/EHsc /wd4503" -DCMAKE_PREFIX_PATH="C:\projects\date"
> -- Building for: Visual Studio 14 2015
> -- The CXX compiler identification is MSVC 19.0.24215.1

Not what else to tell you. Just look at the code that the compiler complains about.

```C++
  template <typename Clause>
  struct hidden_t : Clause
  {
    hidden_t(Clause clause) : Clause(clause)
    {
    }

    hidden_t(const hidden_t&) = default;
    hidden_t(hidden_t&&) = default;
    hidden_t& operator=(const hidden_t&) = default;
    hidden_t& operator=(hidden_t&&) = default;
    ~hidden_t() = default;
  };

  template <typename Context, typename Clause>
  struct serializer_t<Context, hidden_t<Clause>> // This is line 47
  {
    using _serialize_check = consistent_t;
    using T = hidden_t<Clause>;

    static Context& _(const T&, Context& context)
    {
      return context;
    }
  };
```

And the compiler says:
> include\sqlpp11\hidden.h	47
> Error	C2923	'sqlpp::hidden_t': 'Clause' is not a valid template type argument for parameter 'Clause' 

There's nothing to fix here.

Please check if the version you have installed is indeed 0.46 or 0.47. Please check your compiler again.

I don't know what else I can tell you.

Thanks,

Roland

**Comment by sinall** [comment]
After adding:

> #include <sqlpp11/serializer.h>

in hidden.h, the error disappears.

**Comment by rbock** [comment]
Thanks!

Added and pushed to develop.

I freely admit, that the error message would not have led me to look into adding includes...

Cheers,

Roland

**Comment by sinall** [comment]
Great! I was wondering what's the syntax it is, then realized it is template specialization :)
