### ISSUE TITLE
Compilation error on VS2015 Update 3

### ISSUE THREAD

**Issue by sinall** [rbock/sqlpp11#150]
> Severity	Code	Description	Project	File	Line	Suppression State
> Error	C2668	'std::basic_string<char,std::char_traits<char>,std::allocator<char>>::assign': ambiguous call to overloaded function	SQLCipherDemo	c:\users\xxx\documents\visual_studio_2015\projects\sqlcipherdemo\packages\sqlpp11-0.46\include\sqlpp11\data_types\text\result_field.h	53	
> 

```
    template <typename Target>
    void _bind(Target& target, size_t index)
    {
      target._bind_text_result(index, &text, &len);
      if (text)
        this->_value.assign(text, len);
      else
        this->_value.assign("", 0); // <-- Line 53
      this->_is_null = (text == nullptr);
    }

```

Any idea?

**Comment by rbock** [comment]
That's already fixed in the release 0.47, 

https://github.com/rbock/sqlpp11/commit/be50e15116d1ed8e0538dd15f51365294cc779e5
