### ISSUE TITLE
Does sqlpp11 support executing scripts or raw SQL?

### ISSUE THREAD

**Issue by sinall** [rbock/sqlpp11#151]
Hi, my application needs to run some upgrade scripts in order to upgrade DB installed on clients' machine.

I looked into the examples, didn't find an example talking about running scripts or raw SQL.

I know this library is focusing on type safe. Just want to know if this is flexible enough for my case.

**Comment by rbock** [comment]
You can use the `execute` function. It takes a `std::string`.

**Comment by rbock** [comment]
I assume this is solved. Otherwise please re-open.
