### ISSUE TITLE
put quotes around table and column names to allow reserved words in names

### ISSUE THREAD

**Issue by sergeken** [rbock/sqlpp11#152]
Putting quotes around table and column names in the SQL statements would allow to use reserved words.
For example "insert into posting set order=123" as order is a reserved word.

**Comment by rbock** [comment]
Please see also  #138 opened by @cszawisza

Maybe you could join forces :-)

**Comment by sergeken** [comment]
Why not.

**Comment by Erroneous1** [comment]
Can you just make the column's name "\"order\"" when you create the sqlpp templates for it?

**Comment by sergeken** [comment]
This works very well.  With all our discussion, I'm much more in favor of this approach.  Ideally at some time we could enhance the generator to have a smart escape-generating code with support for various RDBMS's and only for objects with reserved words.
I would for now rather update the documentation describe the manual workaround for objects that uses reserved names.  And propose to reject my pull request.

**Comment by rbock** [comment]
Sounds like a very good plan to me. Would you like to add the respective documentation?

**Comment by sergeken** [comment]
Hi Roland,

Here is an attempt.  Regards,
Serge
[Tables.md.txt](https://github.com/rbock/sqlpp11/files/923730/Tables.md.txt)

**Comment by rbock** [comment]
Thanks! 

Added to the wiki :-)

**Comment by rbock** [comment]
Merged into #199
