### ISSUE TITLE
transactions with regard to connectors

### ISSUE THREAD

**Issue by Erroneous1** [rbock/sqlpp11#154]
In the connector_api/connection.h it has start_transaction, commit_transaction, and rollback_transaction.

In ODBC you start a transaction by turning off autocommit mode. After calling commit or rollback the autocommit mode doesn't change. I could turn on autocommit mode after running commit or rollback. This isn't optimal if the user wants to keep doing new transactions, though I'd imagine most people would only commit or rollback once.

sqlpp11-connector-odbc is currently doing it wrong by running SQL statements instead of using the ODBC functions.

**Comment by rbock** [comment]
I think your approach (turning on autocommit after commit/rollback) is quite reasonable.

But then again, I might be utterly wrong, since I have no ODBC experience at all.

**Comment by Erroneous1** [comment]
Sounds good. I know I personally have never needed to start a transaction right after finishing one. I imagine that changing autocommit mode doesn't take a long time if you do want to keep it in manual commit, but it shouldn't be much worse than someone using a different connector.
