### ISSUE TITLE
Support for storing binary objects

### ISSUE THREAD

**Issue by QuantScientist** [rbock/sqlpp11#156]
Hi,
I would like to pickle a Python object and then persist it to a DB, preferably PosgreSQL, I am currently using SQLAlchemy from python which is very easy. Is there support for that in sqlpp11? How do I specify this type? 

Thanks,

**Comment by rbock** [comment]
sqlpp11 treats blobs as strings, see scripts/ddl2cpp:

```
   'tinyblob': 'blob',
    'blob': 'blob',
    'mediumblob': 'blob',
    'longblob': 'blob',
```

I just glanced at the script in the postgresql connector. That seems to be lacking in that respect, but it is trivial to add, of course.

HTH

Roland

**Comment by rbock** [comment]
I assume this is solved, right? Otherwise please re-open.
