### ISSUE TITLE
Wiki page describing exception handling

### ISSUE THREAD

**Issue by Erroneous1** [rbock/sqlpp11#159]
I'm not sure how to submit a PR for wiki pages, so here's something I wrote for an exception handling wiki page:

sqlpp11 throws a `sqlpp::exception` when it encounters an error. `sqlpp::exception` is a descendant of `std::runtime_error`.

## When to expect an exception

sqlpp11 connectors throw the majority of `sqlpp::exception`s so check your connector's documentation. Generally, you should expect an exception when:

-  Connecting to a database
-  Preparing a statement
-  Executing a statement
-  Retrieving and iterating through result rows

Additionally, the date library used by sqlpp11 may throw `std::runtime_error`. As of 2017-04-08 this only happens when formatting a date using a format string.

**Comment by fpark12** [comment]
Looks good to me. I'll jump in as soon as we finalize the design of async query.

**Comment by rbock** [comment]
Thanks, I just added the page.
