### ISSUE TITLE
Make pool_connection compatible with dynamic_select

### ISSUE THREAD

**Issue by fpark12** [rbock/sqlpp11#162]
@rbock @Erroneous1 

@csboling Mentioned that due to the `pool_connection` being a container type rather than a derived type of `connection`, dynamic_select cannot be correctly constructed without pulling the raw pointer out of the `pool_connection`. Since executing the dynamic_select shouldn't be an issue, I think we can add an overloaded `dynamic_select()` that takes a `connection_pool` or `pool_connection` or even both. One example:

```c++
  template <typename Connection_config, typename Connection_validator, typename Connection,
	  typename Connection_pool, template <typename, typename, typename, typename> typename Pool_connection,
	  typename std::enable_if<std::is_class<Connection>::value, int>::type = 0>
  blank_select_t<Connection> dynamic_select(const Pool_connection<Connection_config, Connection_validator, Connection, Connection_pool>&)
  {
	  static_assert(std::is_base_of<connection, Connection>::value, "Invalid database parameter");
	  return {};
  }

// main.cpp
auto s = dynamic_select(conn1);
```

We might also consider allowing `connection_pool`s to be used just like `connection`, but with an `operator()` which executes the query immediately by creating a dummy `query_task` object:

```c++
template<typename Query, typename Lambda>
void operator()(Query query, Lambda callback)
{
	query_task<connection_pool, Query, Lambda>(*this, query, callback)();
}

template<typename Query>
void operator()(Query query)
{
	operator()(query, []() {});
}
```

**Comment by rbock** [comment]
@csboling: Thanks for the information. I get almost no feedback about
dynamic queries, I sometimes wonder if anybody outside the team I am
working in is actually using them :-)

> @rbock <https://github.com/rbock> @Erroneous1
> <https://github.com/Erroneous1>
> 
> @csboling <https://github.com/csboling> Mentioned that due to the
> |pool_connection| being a container type rather than a derived type of
> |connection|, dynamic_select cannot be correctly constructed without
> pulling the raw pointer out of the |pool_connection|. Since executing
> the dynamic_select shouldn't be an issue, I think we can add an
> overloaded |dynamic_select()| that takes a |connection_pool| or
> |pool_connection| or even both:

@fpark12:
While this would be possible, you would need to add this to every single
clause. For instance select, flags, from, where, group_by, having,
order_by, limit, offset, for_update, ...

Couldn't you just implement operator*() to return a reference to the
connection object?

Btw: Is operator->() working? Seems like it is returning the address of
the unique_ptr.

> We might also consider allowing |connection_pool|s to be used just like
> |connection|, but with an |operator()| which executes the query
> immediately by creating a dummy |query_task| object:

Personally, I prefer the explicit code, i.e. get the connection, do
something with it, maybe do something more.

Obtaining a connection from the pool is not free of cost. Executing
queries directly on the pool, hides the fact that for each call a
connection has to be obtained and returned.

**Comment by Erroneous1** [comment]
I don't think `operator->()` is working. Might want to change `return &_impl;` to `return _impl.get();`. Also adding `operator*()` would be a good way to get a reference.

**Comment by Erroneous1** [comment]
Actually I'm not sure I see the reason to use a `std::unique_ptr<Connection>` instead of a `Connection`. Do some of the connectors not allow the move constructor?

**Comment by rbock** [comment]
Using unique_ptr makes sure that we do not have to care about cleaning up the pointer in case something fails when we give the connection back to be pool :-)

**Comment by fpark12** [comment]
@rbock @Erroneous1 
I have another idea. What if we changed `connection_pool` and `pool_connection` so that they also inherit from the same type that `sqlpp::mysql::connection` does? I think in the essence `connection_pool` and `pool_connection` can be seen as custom connectors. They have more complex behaviors compared to a plain `connection` but nevertheless can execute queries and give results.

The reason why I think `operator*()` would not be the most ideal is because the users probably don't want anything to do with remembering that a `pool_connection` contains a `connection`, I think they probably would prefer to know that `pool_connection` **IS** a `connection` which goes back to the pool by itself upon completing it's work. It makes more sense to me to see it as an augmentation of `connection` rather than a container. I believe the same can be said for `connection_pool`. If we went with the `operator*()` approach, `*connection_pool` would sound ambiguous, because one can guess that it returns a `pool_connection`, or a `connection`. In case it returns a `pool_connection`, one needs to do `**connection_pool` to get the `connection` type, which I think might not be the most optimal.

Frank

**Comment by rbock** [comment]
On 2017-04-11 17:01, Frank Park wrote:
> @rbock <https://github.com/rbock> @Erroneous1
> <https://github.com/Erroneous1>
> I have another idea. What if we changed |connection_pool| and
> |pool_connection| so that they also inherit from the same type that
> |sqlpp::mysql::connection| does? I think in the essence
> |connection_pool| and |pool_connection| can be seen as custom
> connectors. They have more complex behaviors compared to a plain
> |connection| but nevertheless can execute queries and give results.

For pool connection, I agree, but not for the connection pool. The
reason is the same as it was before. If I want to run two or more
queries in one function, then it would be better to obtain a connection
from the pool and use it instead of running those queries on the pool.
In the latter case you would obtain connections over and over again and
wouldn't even notice since the interface is so cute.

> 
> The reason why I think |operator*()| would not be the most ideal is
> because the users probably don't want anything to do with remembering
> that a |pool_connection| contains a |connection|, I think they probably
> would prefer to know that |pool_connection| *IS* a |connection| which

That sounds quite right to me.

A bit of a funny construction, inheriting from sqlpp::connection and
implementing the required interface using a member that also inherits
from sqlpp::connection, but it seems to be the right thing to do.

Cheers,

Roland

**Comment by fpark12** [comment]
Perfect, I'll get started on that soon.

Frank

**Comment by fpark12** [comment]
#158 Changed `pool_connection` so that it inherits from `sqlpp::connection`. Dynamic_select seems to work fine now. You can do the following to use dynamic_select with a `pool_connection`:

```c++
auto conn1 = pool.get_connection();
auto s2 = dynamic_select(conn1);
```
Closing this issue because all changes related to this issue will be tracked through #158.
