### ISSUE TITLE
The documentation should be thoroughly detailed and updated.

### ISSUE THREAD

**Issue by jilvin** [rbock/sqlpp11#164]
The current documentation is not good for beginners. It will be better if we work on it and make it somewhat thorough like django documentation. That will make the library easy to use for everyone.

**Comment by rbock** [comment]
Hi,

While I am aware of that, I struggle with actually writing it in such a way that it is easily understood by beginners. Maybe you could help by providing a chapter?

Best,

Roland

**Comment by jilvin** [comment]
Ok. I will do my best when I get time. Currently involved in a project.

**Comment by rbock** [comment]
I am compiling a wish list out of long-standing issues. Better documentation is certainly one of the items (and probably the one I will be working on myself the most, when I find the time).

Closing this ticket.
