### ISSUE TITLE
Postgres unsupported datatypes

### ISSUE THREAD

**Issue by more10-sundsvall** [rbock/sqlpp11#166]
Generating our model from postgres ddl gives a few errors:

```
$ cat errors.txt | sort | uniq
A) Implement this datatype (examples: sqlpp11/data_types)
B) Extend/upgrade ddl2cpp (edit types map)
C) Raise an issue on github
Error: datatype "bytea"" is not supported.
Error: datatype "character"" is not supported.
Error: datatype "real"" is not supported.
Error: unsupported datatypes.
Possible solutions:
Warning: timestamp is mapped to sqlpp::time_point like datetime
Warning: You have to take care of timezones yourself
You can disable this warning using -no-timestamp-warning

```

**Comment by L3nn0x** [comment]
You should either add it in the python code of ddl or create the corresponding type in include/sqlpp11/data_types depending on what each type is.

**Comment by marten-gustafsson-unit4-com** [comment]
I choose option C). This is generic code, I believe it should be taken care of in master. Since I am only evaluating the library I will not do this now.

**Comment by L3nn0x** [comment]
If you just want to evaluate the library, you could add this to ddl2cpp at line 199:
`"bytea" : "blob",
"character" : "varchar",
"real" : "floating_point",`
This uses the already existing classes, so it might not fit perfectly. (I'm no expert on Postegres, so you might want to adapt it.)

**Comment by rbock** [comment]
Opening a ticket or pull request is the right long term step, of course. Short term, @L3nn0x gave the right hint already. It would be great if you could confirm that this interpretation of types is reasonable (I am not a postgresql expert either).

Thanks!

**Comment by more10-sundsvall** [comment]
Thanks @L3nn0x! 

I have looked into the documentation and the mappings seem reasonable. I will certainly do as you propose.

This ticket can be closed. Or keep it open to get more input and then use it for changes to ddl2cpp.

**Comment by kalterkrieg** [comment]
I need postgresql uuid data type for my project and I tried to implement it using gcc type __int128. I also added the bind to the postgres connector. However when I try to do
```
__int128 userid;
…
auto userTable = sbsdb::AccountsUser{};
select(userTable.username).from(userTable).where(userTable.id == userid)))
```
I get the following errors at runtime
`/usr/local/include/sqlpp11/basic_expression_operators.h:130:39: error: ‘_’ is not a member of ‘sqlpp::check_comparison_t<sqlpp::column_t<sbsdb::AccountsUser, sbsdb::AccountsUser_::Id>, sqlpp::uuid_operand> {aka sqlpp::assert_comparison_rhs_is_valid_operand_t}’
       check_comparison_t<Expr, rhs>::_();`

`/usr/local/include/sqlpp11/postgresql/connection.h:302:56: error: ‘_’ is not a member of ‘sqlpp::run_check_t<sqlpp::postgresql::context_t, sqlpp::statement_t<void, sqlpp::no_with_t, sqlpp::select_t, sqlpp::no_select_flag_list_t, sqlpp::select_column_list_t<void, sqlpp::column_t<sbsdb::AccountsUser, sbsdb::AccountsUser_::Username> >, sqlpp::from_t<void, sbsdb::AccountsUser>, sqlpp::where_t<void, sqlpp::bad_expression<sqlpp::boolean> >, sqlpp::no_group_by_t, sqlpp::no_having_t, sqlpp::no_order_by_t, sqlpp::no_limit_t, sqlpp::no_offset_t, sqlpp::no_union_t, sqlpp::no_for_update_t> > {aka sqlpp::assert_valid_operands}’
         sqlpp::run_check_t<_serializer_context_t, T>::_();`

What did I forget ?

**Comment by rbock** [comment]
Just to be sure: It is a compile time issue, right?

It fails in `include/sqlpp11/basic_expression_operators.h`:

```C++
static_check_t<value_type_of<LhsType>::template _is_valid_operand<RhsType>::value,
                     assert_comparison_rhs_is_valid_operand_t>
```

And `_is_valid_operand` comes is something like this:

```C++
  struct unsigned_integral
  {
    using _traits = make_traits<unsigned_integral, tag::is_value_type>;
    using _cpp_value_type = uint64_t;

    template <typename T>
    using _is_valid_operand = is_numeric_t<T>;
  };
```

Maybe `is_numeric` does not accept `__int128`?

**Comment by kalterkrieg** [comment]
That was indeed a compilation error, I mixed it up with something else.
I replaced
`using _is_valid_operand = is_numeric_t<T>;`
with 
`using _is_valid_operand = is_uuid_t<T>;`
in uuid/data_type.h and it is compiling now !

 I still have an exception when using `select` but that's an issue with the postgresql-connector and not sqlpp11 anymore (I need to implement operator<< for __int128 and that should do)

Thanks

**Comment by rbock** [comment]
Happy to read that :-)

**Comment by ZaMaZaN4iK** [comment]
@rbock Sorry for necroposting but seems like in master branch there is no support for `uuid` data type. Should I do similar truck as @kalterkrieg did? Can you commit to the master branch?

Thank you.

**Comment by ZaMaZaN4iK** [comment]
@kalterkrieg Can you provide please your patch for sqlpp11 for adding `uuid` functionality? Thank you a lot - it will simplify a lot my life :)

**Comment by rbock** [comment]
The fundamental issue is that `__int128` is not standard. Here is a nice blog post about it:
