### ISSUE TITLE
What has  become of ppgen.cpp example?

### ISSUE THREAD

**Issue by niXman** [rbock/sqlpp11#167]
Hi,

Subj.
Any ideas? ;)

**Comment by rbock** [comment]
Oh, my!

The `examples` dir contained mostly examples I used in my first CppCon talk. Having them in the main repo was a mistake to begin with. It led to quite a lot of confusion until I finally deleted October last year.

I am afraid I missed the fact that the `cppgen.cpp` example had been in there, too. I am very sorry for that :-(

I guess we should revive it in `tests` instead.

**Comment by rbock** [comment]
I just pushed to develop, please take a look.

**Comment by niXman** [comment]
Ok, thanks!
