### ISSUE TITLE
date.h not installet

### ISSUE THREAD

**Issue by more10-sundsvall** [rbock/sqlpp11#169]
I have successfully built and installed sqlpp11. However when I try to use it in a program, the compiler cannot find date.h from HinnandDate. 

Since there is no cmake file with HinnandDate it would be nice if sqlpp11 would install these headerfiles as well.

**Comment by Erroneous1** [comment]
HinnantDate has no interest in being an installed library so if we want to install date.h then it should probably be in a subdirectory of sqlpp11. I don't think Howard Hinnant has thought about the situation of a library depending on date.h and having a 3rd project requiring date.h which could be bad if the versions mismatched and the project used something compiled like timezones.

You should be able to use [cmake/Modules/FindHinnantDate.cmake](/rbock/sqlpp11/blob/master/cmake/Modules/FindHinnantDate.cmake) in your own project.

**Comment by giorgiozoppi** [comment]
I experience the same problem. Here with the ubuntu 18.04.

**Comment by rbock** [comment]
Since the date library is a library in its own right, it is not sqlpp11's place to install it in a place it considers right.
You might be able to use conan or vcpkg. I haven't tested it, but they should be handling the dependencies.

**Comment by giorgiozoppi** [comment]
I simply cloned and installed worked smoothly.
