### ISSUE TITLE
Parameter binding for connection::execute

### ISSUE THREAD

**Issue by thomasmarsh** [rbock/sqlpp11#17]
Although the intention of sqlpp11 is to encourage expression tree usage over raw strings, there are still times when it is useful to pass a simple string SQL statement where no table static table definition can be relied on (for pragmas, working with `master`, etc.). Rather than rely on string quoting regimes and lexical casts, it would be helpful to have bound arguments to `connection::execute()`. For example:

    bool writableSchema = /*...*/;
    db->execute("PRAGMA writeable_schema = ?", writableSchema);

Jan Nikolas has implemented a nice variadic implementation which accomplishes this type of functionality utilizing variadics: http://boost-talk.blogspot.com/2012/04/sqlite-oop-v2-c11.html. It seems like it wouldn't be too hard to add on to sqlpp11.

**Comment by rbock** [comment]
custom_query is now usable since release 0.30
