### ISSUE TITLE
QUESTION: Should I merge connector libraries into the main repository?

### ISSUE THREAD

**Issue by rbock** [rbock/sqlpp11#174]
Hi there,

When I created sqlpp11, I decided to place the connector libraries into separate repositories.

These days I wonder if that was the right decision? I am tempted to merge the connectors into the main repository. In particular when changing the interface (like what's currently happening with the transaction isolation level), it would certainly be easier to have just one repo.

It would also be easier for contributors: You could write a connector library, add it to the main repo without the obligation to maintain it forever.

On the other hand, sqlpp11 would grow quite a bit that way. You would need to checkout connector code that you might not be interested in. Also, neither can I test all connectors myself, nor can appveyor or travis.

I'd be interested to learn about your opinions.

Thanks,

Roland

**Comment by more10-sundsvall** [comment]
Separate repos, but with tighter control from the core team.

**Comment by Erroneous1** [comment]
Agreed. While sqlpp11 is currently header-only, the connectors are compiled. Being able to just include specific connectors (or write your own) is a great way to go instead of macro enabling.

That said, I see connectors as an extension of sqlpp11. So if there is some feature provided by the connector - i.e. transaction levels - that isn't common to all/most sql then it should be up to the connector to provide the additional overloaded functionality where possible. It might be nice to do some testing mechanism to make sure a connector conforms to what is required by sqlpp11.

**Comment by matpen** [comment]
I agree they should be separate repos. As for the integration, what about git [submodules](https://git-scm.com/book/en/v2/Git-Tools-Submodules) or [git-repo](https://gerrit.googlesource.com/git-repo/)? That way, one can check out the optional connector from within the working copy of the library. I have no experience with any of them, but they seem to fit the bill.

I think testing can be automated in the same way, simply by activating/deactivating the tests depending on whether or not the submodule was checked out.

Regarding connector contributions "that one might not want to maintain forever", I think communication is the key: if the original developer wants, he can simply let @rbock fork it and regard the fork as the "main" repo.

**Comment by Erroneous1** [comment]
Since we're using CMake we could add it if it is enabled in cmake using `add_subdirectory`. We could do this using git submodules or by merging. We could also design sqlpp11 to be useable as an `add_subdirectory` for another project so they wouldn't need to have it installed on the system.

**Comment by volka** [comment]
I just experienced that implementing a change in the core and several connectors can be quite a hassle (and will result in lots of unsuccessful CI builds) as the branches do not sync well. Being able to branch the core and all connectors at once might be helpful, but on the other hand that should also be solvable with some changes to the CI config.

I  see some issues with regards to submodules and pull requests (see e.g. https://stackoverflow.com/questions/7174347/what-is-a-good-workflow-for-submodule-forks for a discussion), but think that would be the most "standard" way of doing this without actually merging the repos.

Having "central" copies of the repos for all connector might be helpful as e.g. the PostgreSQL connector seems to be "inactive" at the moment. Might be matthijs is just on vacation or busy at the moment, or he stopped maintaining. In that case a central copy for further development would help.

**Comment by Erroneous1** [comment]
After thinking about it, I've changed my opinion. If we merge the connectors with each connector in a subdirectory and use add_subdirectory it would be easy for projects dependant on sqlpp11 and a connector and for package maintainers to enable what they need.

I'm not sure that submodules are all that necessary. I don't have experience with setting up CI but I'd bet it is easier to do when you don't have to checkout each submodule wouldn't need to set up their own CI. Having everything in a single repo would make it much easier for connectors to implement new breaking changes. Also it'd be easier to ensure there's standard tests for each connector.

**Comment by rbock** [comment]
Thanks for the all your input!

I'll merge connectors into the main repository some time soon.*

 - the current situation with the postgresql connector is not good, @cszawisza does not have the time to maintain his fork, @matthijs is nt answering to pull requests or emails. Of course, somebody could create yet another fork, but I'd rather see more people working on the main repository than being thinned out.
 - Having everything in one repository makes it so much easier to add new features and test them with the various connectors. Especially if you have to do testing via CI.
- Of course, new connectors could still be in separate repositories. Thus, experimental stuff could mature and later be merger (or never, that's up to the individual developers).
- FYI, I already added some connector-specific code to the sqlpp17 draft. Feels good :-)

I'll start with mysql and sqlite3 and then move on to postgresql. Since I am currently not using postgresql, I might need some help with the migration. In particular, there are some pull requests applied to @cszawisza's branch that are not applied to @matthijs' branch and vice versa.

Best regards,

Roland

* "soon" being when I find some spare hours to do this.

**Comment by volka** [comment]
That sounds great. Another good point why this is useful: I just now saw that @cszawisza's fork existed, and realized some of my changes are already in there. Will make life easier :+1:

**Comment by sergeken** [comment]
I fully subscribe to your rationale.  As a postgresql user, I do suffer from the issues of "forks".  Having a central one with changeable owners avoids the thinning.  I shared all my changes to @cszawisza after not hearing from @matthijs.  IMHO, @cszawisza's fork is the most up to date.

I'm ok to participate to the testing of the connector and, as for all of us, as time permits.

**Comment by cszawisza** [comment]
Hi! I've finally managed to merge all changes from my fork into upstream @matthijs repo, also I'm closing all issues that I think are now fixed. 
To clarify current situation with postgresql connector lib, my fork will no longer by maintained, all changes will be done on @matthijs repo
And I promise to merge all requests more frequent then now :)
BTW, thanks for contribution!

**Comment by rbock** [comment]
Hi @cszawisza 

Awesome! If I interpret the mails correctly, you have merge rights in @matthijs repo now?

Since you did not comment on the idea of merging repositories: Would you rather continue to have a separate repository for the postgresql connector? Or is the cleanup you did to be seen as preparation for merging repos?

Thanks!

Roland

**Comment by cszawisza** [comment]
Yes, I have full rights to @matthijs repo 

IMHO we could add to sqlpp an option to clone requested connector via cmake 

```
if(NOT EXISTS ${CONNECTOR_INCLUDE_DIR} AND CONNECTOR_NEEDED)
    execute_process(COMMAND git submodule update --init -- connector/foo
                    WORKING_DIRECTORY ${CMAKE_CURRENT_SOURCE_DIR})
    # do some more stuff with connector lib
endif()
```

then simple option in cmake would clone/build/install needed library

**Comment by sergeken** [comment]
Hi @cszawisza,
This is great news.  I'll drop my fork (that I forked from yours).  I'll update my repos on my system to point to @matthijs.

**Comment by rbock** [comment]
Time flies.
I added merging repositories to the wish list I am currently compiling.
