### ISSUE TITLE
New MariaDB Features

### ISSUE THREAD

**Issue by Erroneous1** [rbock/sqlpp11#175]
I'm just putting this out there, but these features look cool. [https://mariadb.com/topic/json/](https://mariadb.com/topic/json/) details 2 new features: dynamic columns and JSON functions.

Dynamic columns look like it makes groups of column optional. I guess I'd think of it like this:
```c++
struct columns {
  std::string name;
  std::string format;
  double price;
  union {
    struct movie {
      std::string rating;
      int duration;
      std::string aspect_ratio;
    };
    struct book {
      std::string author;
      int page_count;
    };
  } attr;
};
```
This looks like the perfect time to use a c++17 std::variant.

JSON functions allows you to interact with JSON data in a column, which is pretty cool.

JSON functions should be easy enough to implement in sqlpp11, but dynamic columns look a bit more complicated. I haven't looked at the maria db API to see what they do (if anything), but it seems to bring up a lot of questions.

**Comment by rbock** [comment]
That would actually be a good use case for std::variant :-)

Thanks for the link!

**Comment by Erroneous1** [comment]
It looks like for dynamic columns you define it as a blob. [https://mariadb.com/kb/en/mariadb/dynamic-columns-api/](https://mariadb.com/kb/en/mariadb/dynamic-columns-api/)

I think you could do something like
```c++
struct dynamic_column_value; //DYNAMIC_COLUMN_VALUE wrapper

template<class SubTable...>
std::vector<sqlpp::dynamic_column_value> blob_to_dynamic(std::string& blob)
{
  DYNAMIC_COLUMN column;
  column.str = blob.data();
  column.length = blob.length();
#ifndef NDEBUG
  check_dyncol_result(mariadb_dyncol_check(&column));
#endif
  uint column_count = 0;
  check_dyncol_result(mariadb_dyncol_column_count(&column, &column_count));
  std::vector<sqlpp::dynamic_column_value> r(column_count);
  for(uint i = 0; i < column_count; ++i) {
    check_dyncol_result(mariadb_dyncol_get_num(&column, i, r[i].get()));
  }
}
```

That's just one possible implementation of course. It might be a lot nicer to make a dynamic column class, maybe with `operator[](const std::string&)` and `operator[](const uint&)` for accessing by column number or by column name (which may not be available).

Apparently this has been around since MariaDB 5.3 but I never heard of it until the last MariaDB newsletter.

**Comment by volka** [comment]
PostgreSQL and Sqlite support something similar:

https://www.postgresql.org/docs/9.6/static/datatype-json.html
https://sqlite.org/json1.html

Everyone seems to implement the query interface in a different way (as usual, although SQL 2016 should actually standardize this, see e.g. these slides: https://pgconf.ru/media/2017/04/03/20170317H2_O.Bartunov_json-2017.pdf)

This would actually be very nice to have to add "ad-hoc" structured data to the interface. But I would leave out the parsing and just provide text, so one can use a nice JSON API for this as required (e.g. https://github.com/nlohmann/json offers a very nice C++ interface)

**Comment by rbock** [comment]
Added to the wish list I am compiling.
