### ISSUE TITLE
Upon compiling with Visual Studio 2017 I get 17 errors in statement.h and having.h

### ISSUE THREAD

**Issue by juandent** [rbock/sqlpp11#176]
all errors have this general format:

'Policies': parameter pack must be expanded in this context..

Also, how do I connect the mysql connector library to sqlpp11? 

Its been about a year that I played with this amazing library. Now I  trying to see if I can get some real work done!

Thanks for any help,

Juan Dent

**Comment by rbock** [comment]
Dear Juan,

This is almost certainly a bug in MSVC 2017. It works with clang and gcc and older versions of MSVC. Can you try to reproduce a minimal example and report a bug? I'll experiment a bit with different ways of expressing the same code.

Looking at the tests in the mysql connector should show you what you need to do:

Regarding the mysql connector:
You create a mysql connection object and then execute sqlpp11 statements with it.

Best,

Roland

**Comment by rbock** [comment]
Hi Juan,

MSVC 2017 should now be able to compile the library on the develop branch as well.

Please let me know if it works for you as well. I'll create a release, then.

Best,

Roland

**Comment by juandent** [comment]
Dear Roland 

I get these errors when trying to compile sqlpp11 solution so I don't see how to create a reproducible bug 

I might soon start a C++ course for engineers in Intel Costa Rica and was wanting to show how to access MySQL via your magnificent library 

Any help here will be much appreciated 

Best regards
Juan Dent

**Comment by rbock** [comment]
Dear Juan,

Did you see my earlier message that I updated the code? The compile bugs should be gone (on branch develop).

For using MySQL: Please take a look at how the tests for the MySQL connector work. If you have specific questions afterwards, please let me know.

Cheers,

Roland

**Comment by juandent** [comment]
Dear Roland!

Yes indeed! I just downloaded the develop branch and it compiles perfectly!

Thanks!

Juan Dent
