### ISSUE TITLE
How to install with Buckaroo (with PostgreSQL connector)

### ISSUE THREAD

**Issue by biot023** [rbock/sqlpp11#182]
Hi -- I've seen that there is a [package for sqlpp11](https://www.buckaroo.pm/project/rbock/sqlpp11) in [Buckaroo's packages](https://www.buckaroo.pm) which fills me with joy!
I couldn't find any of the connectors on there, though.
Is that an oversight, or a TODO, or have I misunderstood how to install sqlpp11 in this case?
Or is the support for Buckaroo even officially supported?
Thanks,
   Doug.

**Comment by rbock** [comment]
Hi Doug,

I am not involved in the Buckaroo. I suggest you get in touch with them (and maybe help them creating such packages :-) ).

Cheers,

Roland

**Comment by biot023** [comment]
Ah, I see -- I saw their package was based off your repo and thought that meant it was built here.
Do you know who does build it?
I'll have an investigate if not, there must be some way of finding out.
And when I'm a bit more familiar with Buck and Buckaroo, I'll maybe have a look into how to get the connectors working as Buckaroo packages.
Cheers, Roland!
   Doug.

**Comment by rbock** [comment]
I would assume that the people who created Buckaroo also created this package, but that is just a wild guess...

**Comment by biot023** [comment]
And I'm allowed to get in touch with them, too? Humble little me?
That is an exciting prospect... ;)

**Comment by rbock** [comment]
I feel like I am missing some context between the lines, but yes, of course, why not?

**Comment by biot023** [comment]
Oh god, no, I'm just gibbering after too much coffee -- I'll stop now, it's hardly the place -- thanks again for your advice!
