### ISSUE TITLE
Support for INSERT OR UPDATE

### ISSUE THREAD

**Issue by L3nn0x** [rbock/sqlpp11#183]
Hello,

It would be interesting to add support for `INSERT OR UPDATE`.

The MySQL syntax is as follow:
`INSERT INTO table (a, b, c) VALUES (1, 20, 68) ON DUPLICATE KEY UPDATE a=a+1`
Which can be read as follow: insert values a, b, c with data 1, 20, 68 respectively. If the primary key already exists, update a with a+1. Existing values won't be changed. A WHERE clause can be added to the UPDATE statement.

The SQLite doesn't have that command. However, the same behavior can be achieved with the following statements:
`INSERT OR IGNORE INTO <table>(<primaryKey>, <column1>, <column2>, ...) VALUES(<primaryKeyValue>, <value1>, <value2>, ...); `
`UPDATE <table> SET <column1>=<value1>, <column2>=<value2>, ... WHERE changes()=0 AND <primaryKey>=<primaryKeyValue>;`
It is to be noted that it is done with two statements, possibly leading to race conditions. To be atomic, one can use the `INSERT OR REPLACE` statement, which replaces any statement already existing (and thus, setting all non provided fields to their default value). I found a command online that allow an `INSERT OR REPLACE` command to keep the data unmodified about the line being replaced:
`WITH new (name, title, author) AS ( VALUES('about', 'About this site', 42) )
 INSERT OR REPLACE INTO page (id, name, title, content, author)
 SELECT old.id, new.name, new.title, old.content, new.author
 FROM new LEFT JOIN page AS old ON new.name = old.name;`
It basically selects the line being replaced and replace it with the already existing data. I'm not sure if that can be achieved in sqlpp11 though.

The PostgreSQL syntax is:
`INSERT INTO tablename (a, b, c) values (1, 2, 10) ON CONFLICT (a) DO UPDATE SET c = tablename.c + 1;`
The conflicting key must be precised (here it's a), and a WHERE clause can be added to the UPDATE statement. The SET keyword must be used, as if it was a normal UPDATE statement.

Thank you.

**Comment by juandent** [comment]
Does sqlpp11 support SQLite ?

Regards
Juan Dent

**Comment by rbock** [comment]
@L3nn0x Thanks for the detailed issue! This will definitely take some time, but I'll look into it as soon as I find a few spare hours.

@juandent See https://github.com/rbock/sqlpp11-connector-sqlite3

**Comment by L3nn0x** [comment]
Thank you very much.

**Comment by sergeken** [comment]
This raises the questions if sqlpp has to support non standard SQL statements. 

The proper "standard" would be to implement merge.  [Merge (SQL)](https://en.wikipedia.org/wiki/Merge_(SQL)) but only very few databases do implement it and in various non standard way as above.

**Comment by rbock** [comment]
@sergeken sqlpp11 does not need to support to support non-standard SQL (and should not), but the connector libraries could.

**Comment by sergeken** [comment]
I agree with @rbock to keep sqlpp standard conformant.

**Comment by fnc12** [comment]
[sqlite_orm](https://github.com/fnc12/sqlite_orm) does support `REPLACE` (`INSERT OR REPLACE`) query with `replace` member function. `REPLACE INTO` exist in sqlite3 so it is gotta be in any sqlite frontend IMHO

**Comment by Markus2k** [comment]
Hello Roland,

We have met a while ago at a few MUCplusplus meetings which where organized by Daniel.
I am currently trying to use your sqlpp11 library implementation and i also ran into the problem that I need the "insert if not exists" - feature.

Do you have planned this feature?
Or is there already an estimation when its going to be released.

Thanks in advance for your nice library and I will hopefully see you at one of the next meetups.

Regards,
Markus

**Comment by rbock** [comment]
Hi Markus,

Which database are you using? There is insert_or_ignore for sqlite3.

Cheers,

Roland

Btw: The next meetup is on the 25th :-)

**Comment by ociotec** [comment]
@rbock Any plan for a meetup in Madrid?

**Comment by Markus2k** [comment]
Thanks for the fast replay Roland.

insert_or_ignore is working nicely in combination with the multiInsert feature. 
I didnt know i could use the sqlite connector implementation directly.

Thanks a lot for the work you have done !

**Comment by rbock** [comment]
@Markus2k Glad to help :-)
@ociotec No plans yet and I need to finish a few things first...

**Comment by andr-04** [comment]
Hello. I try to construct `ON DUPLICATE KEY UPDATE` query to MySQL using dynamic custom query entities. But I'm confused: am I on the right way? What to use, could someone give an example of it?

**Comment by rbock** [comment]
While you could use custom queries, I suggest extending the mysql connector library, if you want to do it more often...

If you look at `include/sqlpp11/sqlite3/insert_or.h`, it should give you a starting point (although it is arguably simpler).

**Comment by andr-04** [comment]
I saw... First view was terrible...

**Comment by rbock** [comment]
Looking into the MYSQL documentation, I begin to understand, what you mean. Implementing all variants would be rather painful, I assume.

Whipping up something usable would not be that hard, though:

Let's start with using a custom query:
```
const auto comma = sqlpp::verbatim(",");
db(custom_query(sqlpp::insert_into(t).set(t.beta = "sample", t.gamma = true), 
   sqlpp::verbatim(" ON DUPLICATE KEY UPDATE "), t.beta = "sample", comma, t.gamma = false));
```

The part that starts with `sqlpp::verbatim` is something you probably would want to wrap into an object.
You don't have to go crazy about it. Writing a class that can be used in the following way should be simple:

```
auto odku = dynamic_on_duplicate_key_update(db, t.beta = "sample");
odku.add(t.gamma = false);
db(custom_query(sqlpp::insert_into(t).set(t.beta = "sample", t.gamma = true), odku.verbatim());
```

You could serialize the constructor arguments and then append anything that comes in via `.add()`. The `verbatim()` then returns `::sqlpp::verbatim(_serialized_assignments)`

**Comment by andr-04** [comment]
Yes, I went by the way of writing 3 parts of custom query.

There is no problems with `INSERT` and __verbatim__ parts now. For the last part I tried to reuse `update_list.h`, but unfortunately all goes to copy-paste it.

**Comment by rbock** [comment]
`INSERT OR UPDATE` is supported by the postgresql connector.

I added this to the wish list I am currently compiling. Closing this ticket.
