### ISSUE TITLE
inf double value

### ISSUE THREAD

**Issue by dirkvdb** [rbock/sqlpp11#184]
Reading a value of type DOUBLE from a database that has value Inf, returns 0.0.
I would expect it to return std::numeric_limits<double>::infinity()

I'm using the sqlite3 connector. I'm not sure if this is a connector issue or not.

Same for NaN values I guess, haven't tested them though.

**Comment by rbock** [comment]
Thanks for the report.

Care to dig a bit how such values are returned by the underlying sqlite3 library? That would help me solving the issue.

Best,

Roland

**Comment by dirkvdb** [comment]
I did a small experiment and it seems like the returned type for inf and nan values is SQLITE3_TEXT

This code reads the nan/inf values to a double:
```
... query code

switch (sqlite3_column_type(stmt, i)) {
case (SQLITE3_TEXT): {
    double value = atof(reinterpret_cast<const char*>(sqlite3_column_text(stmt, i)));
    std::cout << value << "\n";
    break;
}
```

**Comment by rbock** [comment]
Cool, thanks!

Can you check the code on branch develop? It would be awesome if you could add a test for INF/NAN via pull request.

**Comment by dirkvdb** [comment]
The code works for me, I created a PR with additional floating point tests
