### ISSUE TITLE
static assertion failed: connection cannot run something that is neither statement nor prepared statement

### ISSUE THREAD

**Issue by shuangye** [rbock/sqlpp11#187]
I don't quite understand what this compilition error means. 
I was trying to store the `sql::connection db` somewhere (a glocal var, a struct/class field), so I can use it across different functions. But when I called something like this:
```
namespace sql = sqlpp::sqlite3;
class my_class {
    sql::connection   &mConnection;
};
void init() {
    my_class.mConnection(sql::connection(config));
}
void query() {
    for (const auto& row : my_class.mConnection(sqlpp::select(all_of(table)).from(table).unconditionally())) {
        /***/
    }
}
```
I got this static assertion failed.

I know the sql::connection object is not copy-able. But I want to setup the connection in an `init` function, and use it in different functions. Finally, release the connection in a `deinit` function.

**Comment by rbock** [comment]
The static_assert indicates that the statement is incorrect, not the connection.

Can you check your statement separately (in the sample that would be something like `const auto s = sqlpp::select(all_of(table)).from(table).unconditionally();`

Best,

Roland

**Comment by shuangye** [comment]
Sorry, I'm not familiar with C++. I use the C programming paradigm, i.e., apply for some resource in an `init` function and pass out as a `handle`. Then use the handle somewhere.
Also, I plan to export C++ functions as C functions so they can be called in C code. Thus, any C++ specific things should be abstracted, e.g., class as `void*` (Handle).

```
namespace sql = sqlpp::sqlite3;

class DBM_Sqlite3 {
public:
	sql::connection            &mConnection;
private:
};

int DBM_init(const char *pDbPath, DBM_Sqlite3 **_pSqlite3)
{
	int ret = 0;
	sql::connection_config config;
	const auto table = HouseAreas{};
	DBM_Sqlite3 *pSqlite3 = NULL;
	
	pSqlite3 = (DBM_Sqlite3 *)malloc(sizeof(*pSqlite3));	

	config.path_to_database = string(pDbPath);
	config.flags = SQLITE_OPEN_READWRITE;
	config.vfs = "";
	config.debug = false;
	config.password = "";
	try {
		pSqlite3->mConnection(sql::connection(config));        /* static assertion failed */
	}
	catch(sqlpp::exception e) {
		ret = EINVAL;
		goto _failure;
	}
	
	*_pSqlite3 = pSqlite3;
	return 0;

_failure:
	free(pSqlite3);
	return ret;
}


int DBM_query(sql::connection& connection)
{
	const auto table = MyTable{ };
	for (const auto& row : connection(sqlpp::select(all_of(table)).from(table).unconditionally())) {
		std::cout << "ROW row.uuid: " << row.uuid << ", row.cusr: " << row.cusr << std::endl;		
	};
	return 0;
}


int test_sqlpp11(int argc, char* argv[])
{		
	DBM_Sqlite3 *pSqlite3 = NULL;
	DBM_init(argv[1], &pSqlite3);
	DBM_show(pSqlite3->mConnection);
	// DBM_deinit(handle);
		
	return 0;
}
```

The `static assertion failed` is at the `pSqlite3->mConnection(sql::connection(config));` line, not in the `DBM_query` function.

**Comment by rbock** [comment]
I see. There are several things going wrong here. The most crucial ones are that you're trying to store the connection as a reference (but your connection is a temporary) and that you are trying to construct your DBM_Sqlite3 object twice (but are calling the call-operator instead, which is where the static_assert is coming from).

The following should compile:

```
class DBM_Sqlite3
{
public:
  sql::connection mConnection;

  DBM_Sqlite3(sql::connection_config config) : mConnection(config)
  {
  }

private:
};

typedef void* DBM_Sqlite3Handle;

int DBM_init(const char* pDbPath, DBM_Sqlite3Handle* pHandle)
{
  int ret = 0;
  sql::connection_config config;
  DBM_Sqlite3* pSqlite3 = NULL;

  pSqlite3 = (DBM_Sqlite3*)malloc(sizeof(*pSqlite3));

  config.path_to_database = std::string(pDbPath);
  config.flags = SQLITE_OPEN_READWRITE;
  config.vfs = "";
  config.debug = false;
  config.password = "";
  try
  {
    pSqlite3 = new (pSqlite3) DBM_Sqlite3{config}; /* Placement new */
  }
  catch (sqlpp::exception e)
  {
    ret = EINVAL;
    goto _failure;
  }

  *pHandle = pSqlite3;
  return 0;

_failure:
  free(pSqlite3);
  return ret;
}
```

Hope this helps.

Best,

Roland

**Comment by shuangye** [comment]
Thank you! It works! Now I can export it as pure C API to externals. Thank you very much.

**Comment by rbock** [comment]
Cool!
Just make sure that you destroy the connection cleanly when you are done using it (in a context that knows its real type). Otherwise you will have a resource leak.
