### ISSUE TITLE
Custom data type wrappers for column data

### ISSUE THREAD

**Issue by Erroneous1** [rbock/sqlpp11#189]
Is it possible to have a custom data type wrapper for a column? It'd be nice to have a special data type to represent a key for a specific table (for instance a `user_id` type that has a member of type uint64_t, explicit constructors, no math operators, and must be explicitly converted to a uint64_t for serialization). Then other tables that also contain that specific key could return that specific type.

Here's how I'm thinking it could be used:
```c++
class user_id_t {
  uint64_t d;
public:
  user_id_t() : d(0) {}
  explicit user_id_t(uint64_t D) : d(D) {}
  explicit operator uint64_t() const { return d; }
};
bool operator ==(user_id_t a, user_id_t b)
{ return uint64_t(a) == uint64_t(b); }
bool operator !=(user_id_t a, user_id_t b)
{ return uint64_t(a) != uint64_t(b); }

//and similar class for book_id_t

//...
auto user = row.user_id;
auto book = row.book_id;
std::cout << "User ID: " << user << '\n'; //Error: no operator<<(std::ostream&, const user_id_t &)
std::cout << "User ID: " << uint64_t{user} << '\n'; //Fine, explicit operator uint64_t()
if(user == book) std::cerr << "same as book\n"; //Error: no operator==(const user_id&, const book_id_t&)
```

Maybe if sqlpp::make_traits took another argument for final conversion type (defaults to 1st argument) it could explicitly construct and convert between the underlying type and the abstraction type for serialization and deserialization. We could also restrict the mechanism to require the wrapper class to be explicitly convertible to and from the underlying data type. This might also make the ability to do foreign keys more doable (I can accept a user_id_t, but not a uint64_t).

It could also be used for more than just keys though. You could have std::chrono::micro_seconds, an ipv4 class, UUID strings, URL, JSON, etc.

**Comment by rbock** [comment]
I have read this a couple of times now, and I am still not sure what you want to accomplish or which current problem you want to solve?

**Comment by Erroneous1** [comment]
It isn't so much of a problem as a feature request. Most database libraries only care about POD and string datatypes, not contextualized data.

One of the (underutilized) features you can have with C++ is free abstractions to have context for your datatypes. We already have std::chrono::*seconds as an example. You can convert between milliseconds, nanoseconds, and even days/months/years using Howard Hinnant's date library without knowing that there are X seconds in a year. Underneath is is just an int64_t but C++ abstraction provides context (freely).

It might be nice to be able to wrap a field type in a similar abstract datatype automatically. So if you have a BIGINT column that has nanosecond values you could wrap the data as std::chrono::nanoseconds. Then if you did something like:
```c++
std::chrono::milliseconds sum{0};
for(auto&& row : query) {
   sum += std::chrono::milliseconds{row.interval}; //row.interval is a std::chrono::nanoseconds type
```
If row.interval was wrapped as a std::chrono::nanoseconds then you could get a compile time error since interval represents nanoseconds and can't be converted to milliseconds (though int64_t could be).

You could then use this mechanism for other things. Foreign keys can be enforced for instance. Say you had the following tables:
```SQL
CREATE TABLE users (
  user_id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  user_name VARCHAR(255)
  user_pass VARCHAR(255)
);
CREATE TABLE sessions (
  session_id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  user_id BIGINT UNSIGNED,
  session_cookie VARBINARY(255),
  session_start TIMESTAMP,
  session_activity TIMESTAMP,
  FOREIGN KEY user_id REFERENCES users(user_id)
);
```
Then you could have wrapper classes like this:
```c++
template<class T>
class basic_key
{
  T data;
public:
  basic_key(T d) : data(d) {}
  explicit operator T() const { return data; }
};
struct user_id_t : basic_key<uint64_t>
{
  explicit user_id_t(uint64_t id) : basic_key<uint64_t>(id) {}
};
struct session_id_t : basic_key<uint64_t>
{
  explicit session_id_t(uint64_t id) : basic_key<uint64_t>(id) {}
};
```
Then if you try to do something like this:
```c++
for(const auto& row : db(select(sessions.session_id).from(sessions).where(sessions.user_id = 42)) {
...
```
It fails because 42 isn't a user_id_t. But we could explicitly say `session.user_id == user_id_t{42}` or use a user_id_t from a previous query.

**Comment by rbock** [comment]
Got it. Yes, that would certainly be possible.

I can see the value for values with units, like your microseconds example, or for formatted data like JSON. For unit-less numbers like ids, such types seem to add clutter without much value in my experience.

It should not be hard to get started with this. Datatypes are defined in the data_types directory.

**Comment by Erroneous1** [comment]
I think the way to think about it is that an auto-incrementing primary key like a pointer. With POD data types we are passing void pointers. With abstract types you give those 4-8 bytes meaning and context.

**Comment by rbock** [comment]
I get that.

But I have seen code that has specific id types for all the different entities and that had exactly the same bugs as all other code as the `id` was mindlessly converted to `user_id` where the compiler asked for it.

However, that should not stop you. For integral wrappers, we could probably have some template datatype that can hold a user_id, item_id, etc.

**Comment by rbock** [comment]
BTW, not there yet, but I believe that this is going to be almost trivial with sqlpp17 :-)

**Comment by rbock** [comment]
I have my doubts that this will be feasible in sqlpp11.

Closing. Maybe we can get more concrete in a later version (sqlpp17 is probably not going to be finished, but I am still using it for experiments).
