### ISSUE TITLE
Possible specifying database name?

### ISSUE THREAD

**Issue by thomasmarsh** [rbock/sqlpp11#19]
Hi Roland,

Perhaps I missed it while browsing the code, but is there a way to specify the database in a query? I need to work with multiple databases (e.g., via `ATTACH` in SQLite), and I am unable to perform operations outside of the `main` (default) database. E.g., I perform the following:

    ATTACH 'a.db' AS a;
    ATTACH 'b.db' AS b;
    SELECT t1.foo, t2.bar FROM a.my_table AS t1, b.my_table AS t2 WHERE t1.id = t2.id;

Currently, I'm unaware of a mechanism to provide such queries in a type-safe manner.

**Comment by rbock** [comment]
Hi Thomas,

I finally got to this one. You can now do

```
  sql::connection_config config;
  config.path_to_database = ":memory:";
  auto other = db.attach(config, "other");
  auto right = schema_qualified_table(other, TabSample{}).as(sqlpp::alias::right);
```

`right` then evaluates to `other.tab_sample`.

The attach method is currently implemented for the sqlite connector only.

Cheers,

Roland
