### ISSUE TITLE
Output iterator out of the custom query

### ISSUE THREAD

**Issue by adiog** [rbock/sqlpp11#193]
The library is pretty neat!

Is there an easy way to use the output iterator with custom SQL?

I have been using custom code generators and so far it looks very promising. Basic CRUD works like a charm, but there is a scenario, when I would like to execute custom SQL and use already generated code.
I do not find straightforward how to handle the output of custom query. All I see is that default return type for raw sql executors is an error code. I am looking for a simple solution like:

for(auto& row : db(custom_select(all_of(gen::Table{})).sql(custom_sql)))
{
    use_existing_dispatcher&lt;gen::Table&gt;(row);
}

Could you give me some hints how to achieve this goal?

I have been stumbling upon the code, but I have not found any convenient conversion to result_t of custom query - none of the following option would work (please mind that these are very dummy trial-and-error attempts):
```
for(auto row : db(custom_sql))
for(auto row : eval(custom_sql))
for(auto row : eval<sqlpp::all_of(gen::Table{})>(db, custom_sql))) // is eval atomic?
for(auto row : db.execute(sqlpp::custom_query(sqlpp::verbatim(custom_sql)).with_result_type_of(all_of(gen::Table{}))))
```

I have not understood the whole type structure behind the library, but at least here the code might be giving some clues:
```
struct prepared_select_t
  {
...
    using _result_row_t = typename Statement::template _result_row_t<Database>;
...
    auto _run(Database& db) const -> result_t<decltype(db.run_prepared_select(*this)), _result_row_t>
    {
      return {db.run_prepared_select(*this), _dynamic_names};
    }
...
```
while here the return type seems not be convertible to result_t..
```
  template <typename Database, typename... Parts>
  struct custom_query_t : private detail::custom_parts_t<Database, Parts...>::_result_methods_t
{
...
    template <typename Db>
    auto _run(Db& db) const -> decltype(std::declval<_methods_t>()._run(db, *this))
    {
      _run_check{};  // FIXME: dispatch here?
      return _methods_t::_run(db, *this);
    }
...
```    

Thanks for your help and indulgence!

**Comment by rbock** [comment]
Hi,

Sounds like an interesting project!

Your last attempt is pretty close. The following should work:

```
for (const auto& row : db(
  sqlpp::custom_query(sqlpp::verbatim(custom_sql))
    .with_result_type_of(select(all_of(gen::Table{})))))
{
  // ...
}
```

Best,

Roland

**Comment by rbock** [comment]
Pushed an example to the develop branch, see tests/CustomQuery.cpp

**Comment by adiog** [comment]
Thank you! :)
You have saved me a lot of time.
It works, so now I will have to find out why. It is a perfect brain teaser. The maze of types.

**Comment by rbock** [comment]
Thanks for the feedback!
