### ISSUE TITLE
Add sqlpp11 to vcpkg

### ISSUE THREAD

**Issue by rbock** [rbock/sqlpp11#194]
Hi,

I recently received an email by Andrew Pardoe (Program Manager Visual C++ Compiler and Tools):

> Hey, I notice that sqlpp11 isn't part of VCPkg [1]. 
> We do test all of the VCPkg catalog regularly. Have you considered adding it?
> 
> 1. https://github.com/Microsoft/vcpkg

This would definitely help to prevent regressions like #181.

I am very much a Linux guy. It would therefore be awesome if one of the Windows users could help with this :-)

Cheers,

Roland

**Comment by Praying** [comment]
and after a year,still no one help?

**Comment by L3nn0x** [comment]
From what I can see it's really easy: https://github.com/Microsoft/vcpkg/pull/4327/files
Change the README and the CMakeFile.

**Comment by WopsS** [comment]
I created a pull request for that (https://github.com/Microsoft/vcpkg/pull/4747), let's see if it gets accepted.

**Comment by rbock** [comment]
Awesome! Thanks @WopsS !

**Comment by WopsS** [comment]
No problem :)

**Comment by gocarlos** [comment]
> I am very much a Linux guy. It would therefore be awesome if one of the Windows users could help with this :-)

vcpkg is not multi platform

**Comment by rbock** [comment]
Thanks for the good news!
