### ISSUE TITLE
How to remove using join

### ISSUE THREAD

**Issue by MatthieuTexier** [rbock/sqlpp11#196]
Hi Roland,
Thank you for this great library.
I face a problem trying to call:
`remove_from(A.inner_join(B).on(B.a_id == A.id)).where(B.id == 1))`
but the resulting SQL is 
`DELETE FROM A INNER JOIN B ON B.a_id = A.id WHERE B.id=1`
That is not a correct SQL, I would expect:
`DELETE A FROM A INNER JOIN B ON B.a_id = A.id WHERE B.id=1`
Is there a way to build that request?
Thanks,
Matthieu

**Comment by rbock** [comment]
Hi Matthieu,

Thanks for the report. There seems to be a check missing to prevent joins in the FROM clause.

You could use using though. Like this:

```
remove_from(A).using_(B).where(B.a_id == A.id and B.id == 1);
```

Best,

Roland

**Comment by MatthieuTexier** [comment]
Hi Roland,
Thanks, I was and I'm still not aware of using_ semantic but it works.
Best
Matthieu

**Comment by rbock** [comment]
Yeah, delete is a strange beast that is handled differently by almost every database engine, it seems.
