### ISSUE TITLE
sql union operator support ?

### ISSUE THREAD

**Issue by anton-potapov** [rbock/sqlpp11#20]
does sqlpp11 support union operator ?

**Comment by rbock** [comment]
Hi,

Finally, I got to looking into unions: I just pushed a first version of union_ member function. It has almost no compile-time checks included yet. These will follow in the next few days.

Cheers,

Roland

**Comment by rbock** [comment]
UNION support is now included in releases > 0.30

Please use tests/UnionTest as guideline for the time being. Documentation will follow step by step...
