### ISSUE TITLE
Replace db.run with db in the wiki

### ISSUE THREAD

**Issue by Voultapher** [rbock/sqlpp11#204]
Places like [insert](https://github.com/rbock/sqlpp11/wiki/Insert) still showcase the old api.
Fix:
Replace `db.run` with `db`

Error places:
- https://github.com/rbock/sqlpp11/wiki/Dynamic-Select#dynamic-columns
- https://github.com/rbock/sqlpp11/wiki/Functions#aggregate-functions
- https://github.com/rbock/sqlpp11/wiki/Insert
- https://github.com/rbock/sqlpp11/wiki/Remove
- https://github.com/rbock/sqlpp11/wiki/Update

**Comment by rbock** [comment]
Fixed, thanks!
