### ISSUE TITLE
Questions reg. Android/Custom SQLite functions

### ISSUE THREAD

**Issue by freekee1** [rbock/sqlpp11#206]
Hello,

first I have to say, this is a really great project. Thanks for making this lib!
I'm currently evaluating if it would be suitable/feasible for use in a specific project. (Context: C++ project using Qt for multiple mobile platforms.)
As I couldn't find answers to some questions, I'm hoping to get some answers here:
1. Has the library be used on Android and iOS before (or does it work there at all)? Are there maybe any resources regarding building/using it on these platforms? Esp. in combination with the SQLite3 connector and SQLCipher (all of that would need to work).

2. Is it possible (i.e. are there facilities) to introduce/use custom SQLite functions (registered with sqlite3_create_function) in SQL statements (i.e. using sqlpp11, for example in a select(...) call)? From looking at the code, for using them it seems one could implement a function like in sqlpp11/functions.h. Is that all or will more code have to be added in other places?

Thank you very much in advance for any help! If I overlooked some information, please just point me to it, I'll gladly take any bone thrown at me. ;-)

// EDIT: Another question just came up: May it be possible to grab "only" the composed SQL statement as a string, to then pass it on manually (e.g. to Qt's SQL framework)?

Kind regards.

**Comment by rbock** [comment]
Hi,

> first I have to say, this is a really great project. Thanks for making this lib!

My pleasure :-)

Regarding your questions:

 1. Android/iOS: I can't remember feedback about Android/iOS. I take that as a good sign, considering that I got a lot of feedback from Windows users when that did not work... But I would certainly like to know! SQLCipher can be used with the sqlite3 connector. If the connector works at all on those platforms, it should work with SQLCipher, too.
 2. Yes, functions can be added like you described.
 3. Yes, in the connector library, look into `include/sqlpp11/sqlite3/connection.h`, a function like `bind_result_t select(const Select& s)`. It serializes the expression tree. You could do the same and pass the string somewhere else, of course. 

Let me know how this works out for you!

Cheers,

Roland

**Comment by freekee1** [comment]
Thanks for the answer! Sounds at least worth a try, I'm on it now ...
One more question regarding the SQLite3 connector though: Is there a way to not link against an SQLite3 lib (but incorporate the amalgamation sources or at least link statically, since in our current code, we do just the former? Couldn't find an option yet (of course, last resort could be hacking the CMakeLists.txt I guess ...).

**Comment by rbock** [comment]
There is no option. I'd be happy to accept a pull request for this :-)

Looking forward to reading about results!

**Comment by freekee1** [comment]
Had to work on a few urgent things first, back on this one. :-)
Now I've successfully built the SQLite3-connector with SQLCipher support. The tests run fine, except for the floating point one, where a "0" value seems to end up in the database instead of "inf".

But ... when building our own application (with QMake), linking against "sqlcipher" and "sqlpp11-connector-sqlite3", there are several "unresolved reference" errors pointing to symbols which, according to "dumpbin /SYMBOLS", are actually not present in "libsqlpp11-connector-sqlite3.a". ("sqlite3_errmsg", "sqlite3_last_insert_row_id", and some more).
Seems strange ... from what I see in the CMakeLists.txt, the tests aren't linked against anything else.
Any ideas? I'm investigating, very likely a stupid mistake of mine, but I couldn't seem to find the cause yet.

(Btw., I once had our QMake-based app built and running with sqlpp11 and SQLite3, but without SQLCipher, and directly having the amalgamation sources (sqlite3.c) as part of the project.)

Thanks a lot in advance!

**Comment by rbock** [comment]
Hi,

The float results (inf vs. 0) are surprising, but unless you have `inf` or `NaN`, that should not be too bad (the longer I think about it, the more I consider that a hack anyway, since sqlite3 does not _really_ support non-finite values, but hat just as an aside).

The functions you mention should be provided by sqlcipher. have you tried compiling the tests with sqlcipher?

Best,

Roland

**Comment by freekee1** [comment]
Yes, I think so. I built the SQLite3-connector with "mingw32-make all", which also built the test executables. (Configuring SQLCipher libs/dirs in CMake beforehand, of course.) They're definitely linked to SQLCipher (requiring "libsqlcipher-0.dll" to be present). That's what gets me confused (that is, why the tests build fine linking against the very same libs as our own project ...).

kind regards

**Comment by rbock** [comment]
Don't be too hard on yourself, linker errors are sometimes really hard to track!

But cool, sounds like you're all set then :-)

**Comment by freekee1** [comment]
Thanks for the kind words. ;-) It just feels impolite to bother people with problems without having them thought through myself. (From symbol resolution errors, linker configuration seems not far fetched.)

Anyways ... Just as an update, I've meanwhile been able to also build the connector for SQLCipher for Android as well and it seems to work fine there, too. (CMake support for Android has really become quite comfortable.) Maybe if I find the time, I'll see if I can run the tests on Android, too. But for now, my few working test queries to our DB have to suffice. :-)
Only had to "hack" the data library because it uses some C++11 functions not present in the gnustl C++ runtime (default before Android NDK r16), so I had to implement them myself. But no big deal. This shouldn't even be necessary with current NDKs or when just using libstdc++ if you can.

Next stop is implementing our custom SQL functions, but I hope that this time it's really just implementation, no more build-related hassle.

**Comment by rbock** [comment]
Thanks for the update. Sounds very good!

With the basics working, I guess we can close the ticket.

If you have questions about implementing custom SQL functions, let me know in a separate ticket.
