### ISSUE TITLE
inserting floating point nan/inf values

### ISSUE THREAD

**Issue by dirkvdb** [rbock/sqlpp11#209]
Today I came across an insert statement that wanted to insert a floating point value into the database using the sqlite connector.
Example
```
db(insert_into(fp).set(fp.fp = std::numeric_limits<double>::quiet_NaN()));
```
This fails with the message:
```
Sqlite3 error: Could not prepare statement: no such column: nan (statement was >>INSERT INTO fp_sample (id,fp) VALUES(0,nan))
```

I was looking in the code how this could be fixed. And tried to modify sqlpp11/data_types/floating_point/operand.h like this.

```
template <typename Context>
struct serializer_t<Context, floating_point_operand>
{
  using _serialize_check = consistent_t;
  using Operand = floating_point_operand;

  static Context& _(const Operand& t, Context& context)
  {
    if (std::isnan(t._t))
      context << "'NaN'";
    else
      context << t._t;
    return context;
  }
};
```
This worked for me using the sqlite connector but I'm not convinced this is a correct db agnostic solution after reading [this stackoverflow question](https://stackoverflow.com/questions/45756557/inserting-nan-value-into-mysql-database)
What is your opinion about this?

Would it be better to translate the NaN values to NULL?

**Comment by rbock** [comment]
Thanks for the research!

Reading this, my first impulse was to go with `NULL`, but it might be a `NOT NULL` column...

So I am not sure yet.

**Comment by rbock** [comment]
It would be possible to specialize the `serializer` for MySQL and potentially other databases that do not support `NaN` or `+-Inf`. Those specializations could then throw an exception.

**Comment by dirkvdb** [comment]
That seems like the best solution to me indeed. Translating to NULL also has the ugly property of being asymmetric. You read different values compared to what you wrote.

Can you give a hint as to how this can be implemented then I can create a pull request if it is not too complicated as I am not very familiar with the sqlpp internals which can be challenging :-)

Does the sqlpp11 library have knowledge about which connector is being used?

**Comment by rbock** [comment]
Hi Dirk,

You already found the right place:

```
template <typename Context>
struct serializer_t<Context, floating_point_operand>
```
`Context` is a database-specific type. sqlpp11 know none of them. Instead, you have to specialize serializer_t in the individual connector libraries.

For instance, in the mysql connector, there is `include/sqlpp11/mysql/serializer.h`, containing

```
  template <typename First, typename... Args>
  struct serializer_t<mysql::serializer_t, concat_t<First, Args...>>
```

This serializes string concatenation using the `CONCAT` function instead of the operator `||` which is used by sqlpp11's default implementation.

Cheers,

Roland

**Comment by rbock** [comment]
I believe this is done. Please open a new issue if there are still open aspects.
