### ISSUE TITLE
sqlp11 status

### ISSUE THREAD

**Issue by sdminonne** [rbock/sqlpp11#21]
Roland, 
what's the status of sqlpp11? I remember one year some discussion in boost mailing list but then I didn't see more info.
Is the lib still under development?
Any plan to submit to boost to be reviewed?

Thanks in advance

**Comment by rbock** [comment]
Salvatore,

Thanks for the interest!

The library is still under development. There are a lot of changes in
the development version for instance, especially with respect to the
quality of compile time error messages. I also plan a few changes for
dynamic queries.

With respect to submitting to boost: I still plan to do that, but I am
not sure about the time line. From what I see, sqlpp11 would benefit
greatly from C++17. A boost version might depend on that version.

Best,

Roland

**Comment by rbock** [comment]
I'll close this, OK?

Please do not hesitate to follow up by email or github :-)

**Comment by sdminonne** [comment]
Roland, thanks for the info.
