### ISSUE TITLE
Definition of sqlpp::logic::not_t seems erroneous

### ISSUE THREAD

**Issue by juandent** [rbock/sqlpp11#210]
Hi Roland,
I hope I am wrong but I found that the definition of ```not_t``` is flawed. It appears to allow variadic parameters but ```not_impl``` cannot handle that. The code is:

```
    template <bool>
    struct not_impl;

    template <>
    struct not_impl<true>
    {
      using type = std::false_type;
    };

    template <>
    struct not_impl<false>
    {
      using type = std::true_type;
    };

    template <template <typename> class Predicate, typename... T>
    using not_t = typename not_impl<Predicate<T>::value...>::type;
```

Now if we define a predicate like this:
```
template<typename T>
struct IsIntegral
{
	static constexpr bool value = std::is_integral<T>::value;
};
```

Then the following code fails to compile:

```
using not_integrals = not_t<IsIntegral, int, float>;
```

whereas this code compiles fine:

```
using not_integrals = not_t<IsIntegral, int>;
```

As far as I can tell, since I searched all the code for sqlpp11, there is never a variadic call to this type ```not_t```, so that the problem is dormant, hidden and harmless. It seems to me this is a sleeping bug.

Just wanted to alert you if I am right.

Best regards,
Juan Dent

**Comment by rbock** [comment]
Hi Juan,

Good find. `not_t` should not be a variadic template. 

Fixed on the develop branch.

Thanks,

Roland
