### ISSUE TITLE
Stuck in understanding statement_t definition

### ISSUE THREAD

**Issue by juandent** [rbock/sqlpp11#211]
Hi Roland,

Excuse me for this question (i.e. it is not really an issue), it's just that I am stuck trying to understand the definition of statement_t (precisely its super classes):

```
template <typename Db, typename... Policies>
  struct statement_t : public Policies::template _base_t<detail::statement_policies_t<Db, Policies...>>...,
                       public expression_operators<statement_t<Db, Policies...>,
                                                   value_type_of<detail::statement_policies_t<Db, Policies...>>>,
                       public detail::statement_policies_t<Db, Policies...>::_result_methods_t
```

So my questions are:

1. Doesn't this inheritance create an infinite recursion?
"expression_operators<statement_t<Db, Policies...>, value_type_of<detail::statement_policies_t<Db, Policies...>>>"
1. what are the policies? Which classes substitute here and what are their reason of existence?

Sorry to ask - but my head has been spinning to get this and I am stuck. I try not to bother... I have been understanding a lot else pretty okay.

Regards!!
Juan Dent

**Comment by juandent** [comment]
This might be helpful to other non-experts in C++ template metaprogramming...

Juan :-)

**Comment by rbock** [comment]
Hi Juan,

It is not recursion. It is a form of CRTP, passing the statement type as template parameter to its own base classes. The reason why this is not an infinite recursion is that the statement type at this point is essentially just forward declared.

Policies represent the clauses (e.g. FROM and WHERE). Look at specializations of this, for instance in select.h.

That is probably the toughest part of the library. If you wrap your head around this variadic CRTP, everything else is pretty harmless :-)

Hope that helps.

Cheers,

Roland
