### ISSUE TITLE
Do not camelCase table and column names in ddl2cpp

### ISSUE THREAD

**Issue by sjoubert** [rbock/sqlpp11#213]
I was wondering the reasons for transforming the table and column names in the ddl2cpp script. The `toClassName` and `toColumnName` specifically will [Cc]amelCased the original names so that a table `my_table` and `my_column` will have a class and member representation of `MyTable` and `myColumn`.
I find it weird and would prefer using the actual DB names in my code.

* Are there any reason for this behavior?
* Would you be open to change it or add an option to the script to get verbatim DB names in C++?

**Comment by rbock** [comment]
The reason is simple: That happens to be the naming convention in the projects I am using the library for :-)

I would gladly accept a pull request that adds an option for generating snake_case.

**Comment by marmand** [comment]
Hello,

An approximate good reason could be that '_' is a wildchar. So not having
it in SGBD identifiers could be a good practice.

Regards,
