### ISSUE TITLE
ddl2cpp doesnt work if multiple index keys are in the dump.

### ISSUE THREAD

**Issue by ghost** [rbock/sqlpp11#217]
The script will ommit table from the final result if multiple keys are specified in the ddl like this:
`
....
  'ModifiedByName' varchar(60) DEFAULT NULL,
  'ModifiedById' varchar(128) DEFAULT NULL,
  'Note' varchar(1000) DEFAULT NULL,
  UNIQUE KEY 'Id' ('Id'),
  KEY 'IX_UserLogin_email' ('Email'(109)),
  KEY 'IX_UserLogin_Name' ('FirstName'(55),'LastName'(55))
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
`

It also breaks if commas are on the last row/key/definition in the create table parentheses block

A work around is to generate your dump file with this command
`mysqldump -d -u $(SQLUSER) -h $(DBHOST) $(DBNAME) | sed -e "/^\s\sKEY/d" | sed -e 's/)\,/)/g' > tmp/dump.ddl`

**Comment by rbock** [comment]
Thanks for the report!

Would you like to try adjusting the script? Your pull request would probably be faster than me right now :-)

**Comment by bmr1** [comment]
Sorry i dont know python. Its no rush, the command above solves the problem

**Comment by rbock** [comment]
OK, will look into it later (tagged it as "help wanted", hoping for somebody to jump in and do a pull request :-) )

**Comment by rbock** [comment]
I added "More test cases for DDL files" onto the wish list I am compiling.
