### ISSUE TITLE
bool in where clause

### ISSUE THREAD

**Issue by bmr1** [rbock/sqlpp11#222]
is it possible to put a boolean value inside a where expression? 
something like this
`.where(id.isValid() && model.Id == id)`
where `isValid()` returns a bool

**Comment by bmr1** [comment]
nevermind. i found dynamic selects which are close enough

**Comment by rbock** [comment]
Great :-)

BTW: Untested, but switching the operands of the `&&` expression should work as well:

```
.where(model.Id == id && id.isValid())
```
