### ISSUE TITLE
Question reg. performance of sqlpp11 + SQLCipher.

### ISSUE THREAD

**Issue by freekee1** [rbock/sqlpp11#224]
Hi,

I'm currently testing sqlpp11 with the SQLite3 connector for an SQLCipher database, and encountered some performance/speed issues I cannot quite explain.

I'm running the very same simple "SELECT * FROM Table" statement, i.e. "db(select(all_of(table)).from(table).unconditionally())", once using the Qt SQL classes (QSqlQuery), and using sqlpp11. The database is the same file. The tests are run independently (no parallel accessing the file).
Now the sqlpp11 version takes (on my machine) at least 150x as long as the Qt-based version, which operates on the string at runtime.
That makes for quite a bad runtime performance with sqlpp11 and lets lots of timing-critical tests fail.

I wouldn't think that the sqlpp11 implementation, or the connector's implementation, has that much of an impact. On the other hand, I have no idea what might be the issue. Debug messages (config.debug = true) yield no further information. The queries all execute successfully and all seem to return correct results.

Is there anything I might have overlooked, any mistake I might have made, anything I could take a look at to resolve this? I still don't think that this is the "final result" which I would have to live with (or abandon sqlpp11 ... which I would not like to do.)

**Comment by rbock** [comment]
That is a bit of a surprise.

I heard from people replace Qt SQL with sqlpp11 because of performance a few weeks ago. That was for MySQL, though.

If you have debug on, that would slow things down considerably. Is it possible that you compiled without optimization?

**Comment by freekee1** [comment]
I only turned the debug switch on after the first measurements (that added another ~10-15ms in this case).
I've used different compiler settings (if you are referring to compiler optimization). Compiler is MinGW 5.3, optimization with -O2 yielded the best results, but still about 5ms difference, which doesn't change much. (-O3 didn't make much of a difference either.)

**Comment by rbock** [comment]
Without more details about the code, the query, the tables, the amount of data, etc,  I'll have a hard time guessing what causes the slow-down.

Not making any promises, but if you could send me a complete example (both sqlpp11 and Qt)? That would help me doing some analysis.

**Comment by freekee1** [comment]
Sorry for the way too long delay! It seems this issue can be closed with the conclusion "my fault, but don't ask me why" ...

(I had written a test application, which yielded surprising results, namely that the QtSQL execution times were suddenly pretty much the same as with sqlpp11.
On the other hand, I have no clue really why in our "full blown" application the QtSQL-times are so much shorter. I've tried to look at anything I could think of, incl. possible caching somewhere, different means of measuring the time, threading issues, possibly multiple parallel db connections, etc. etc., but couldn't make out the cause (yet!).
However, when measuring the time over many executions, e.g. looping over the same statement 1000+ times, the sqlpp11-based implementation quickly surpasses the QtSQL-performance again (i.e. shorter times).
Therefore, it was decided for now to start porting our application to sqlpp11 despite those pesky oddities. Sadly, not my task anymore, for now ... but when I have some time, I'll definitely have another look at the timing discrepancies. Unveiling the secret, yet another goal before death! :-)).

**Comment by rbock** [comment]
Thanks for letting me know!

Given that I expect the next version of sqlpp (sqlpp17) to be considerably faster, this is pretty good news :-)

However, it is quite surprising that the sqlpp11 version is "gaining" speed like that. Maybe there is some bad branch prediction going on in the beginning?

I'll close the issue for now, but I certainly look forward to when you have time to figure this out in more detail!

Cheers,

Roland
