### ISSUE TITLE
How to check if a table exists?

### ISSUE THREAD

**Issue by freekee1** [rbock/sqlpp11#229]
Hi,
a (yet another) beginner's question: Is there a way using sqlpp11 to check if a specific table exists in a database?
It seems there is no standard-SQL way to do so, but maybe some facility/interface which the respective connectors can then implement (because seemingly every implementation has some way of doing it)? I didn't find anything yet, however, but maybe my eyes just failed me again ...

Thanks a lot in advance!

kind regards

**Comment by rbock** [comment]
Hi,

There is no dedicated function that tests for table existence. You can combine `custom_query` and `verbatim()`

```
SQLPP_ALIAS_PROVIDER(tableExists);
[...]

custom_query(sqlpp::verbatim("SOME BOOL EXPRESSION"))
   .with_result_type_of(select(sqlpp::value(bool).as(tableExists)));
```

As you wrote, the connectors could probably do this more elegantly.

What you be the use case for this? If you need the table but are unsure if it exists, couldn't you just run `CREATE TABLE IF NOT EXISTS`?

**Comment by freekee1** [comment]
Thank you for the insightful answer, as always!
Yes, you might be right that "CREATE TABLE IF NOT EXISTS" could be used. I wasn't entirely asking on my behalf, so the exact context is beyond my knowledge right now. But it might very well be just a bad hack. :-)
*If* it should nonetheless prove necessary to actually have an "existence check", we might as well extend the SQLite-connector (and the connector interface, for that matter) I guess. In that case, I'll report back if an acceptable "generic" should come out.

Otherwise, thanks for the info, good to know there's nothing yet which I might have overlooked.

kind regards.

**Comment by rbock** [comment]
Thanks for the feedback, have fun with that :-)
