### ISSUE TITLE
Find a way for specific connectors to add data type support to ddl2cpp

### ISSUE THREAD

**Issue by sjoubert** [rbock/sqlpp11#230]
I open this issue following #221 to track further improvements that should be required to enhance ddl2cpp. The idea is to find a way for specific connectors to extend the common data type support of the script.

Currently, the script has knows and handles some specific types from SQLite and PostgreSQL but we should find a way for any connectors to provide its own type mapping without having to modify the upstream script.

**Comment by rbock** [comment]
I am putting this on the wish list I am compiling.
