### ISSUE TITLE
Execute custom query without create model (struct)

### ISSUE THREAD

**Issue by vaggeliskls** [rbock/sqlpp11#235]
Could i execute a raw custom query and iterate without creating a model ? 
Custom query examples uses a model in order to select and iterate. 
Example: User type and execute his query.
Thanks in advance.

**Comment by rbock** [comment]
I am not sure I understand the question. Can you be more specific in your example? e.g. how you would like to use it in code?

**Comment by vaggeliskls** [comment]
I want to use sqlpp11 (PostgreSQL driver) along with crow micro web framework.
**Scenario**:
User sends a http request with his SQL query in the body of the request ( select * from table_cpp ). The system must execute the query and return the json result. 

So can i execute a query without the use of model?
**Possible solution 1**
**FROM**
`db(select( all_of(t).as(t)).from(t)`
**TO**
`db(select( "*" ).from("table_cpp ")`

P.S. I suppose that the solution 1 is not supported. I state this as an example of possible enhancement of this library that used by other ORMs (typeORM).

**Possible solution 2**
db.execute(R"(select( "*" ).from("table_cpp ");)")
How to iterate this object ? or convert to json ?

P.S. Congratulation of your great work.

**Comment by L3nn0x** [comment]
I don't think this is possible with this library as it's relying on a compile-time schema. If your tables don't change you could have something like
```if (table == "table_cpp") { table_cpp t{}; db(select(all_of(t)).from(t)); }
else if (table == "table2_cpp") { table2_cpp t{}; db(select(all_of(t)).from(t)); }```

**Comment by rbock** [comment]
If you want to allow your users to just send _any_ query, then this library cannot help you.

If parts of the query are known at compile time, then it might make sense to use it. For instance, if the selected columns are known, then you can make use of the result structure.

**Comment by ahmadudin** [comment]
Hi @rbock , can I use this library to handle Postgres JSON data type

**Comment by rbock** [comment]
This is a more a question for the postgres connector library. I'd say.

As far as I know, it does not contain specific json operators or functions. However, adding new functions is not very hard.

Note: I am closing this ticket. If you want to ask more details about this, I suggest opening a ticket for the Postgres connector.

Best,

Roland

**Comment by campisano** [comment]
> I want to use sqlpp11 (PostgreSQL driver) along with crow micro web framework.
> **Scenario**:
> User sends a http request with his SQL query in the body of the request ( `select * from table_cpp` ). The system must execute the query and return the json result.
> 
> So can i execute a query without the use of model?

There is a way to use sqlpp::verbatim to use a plain SQL query, and .with_result_type_of() to define the type of each result and .as() to define aliases:

`
        std::string sql ="SELECT typname, typlen, typinput, typoutput FROM pg_type;";                                                          
        auto statement = custom_query(sqlpp::verbatim(sql))                                                                                    
            .with_result_type_of(select(                                                                                                       
                                     sqlpp::value("").as(sqlpp::alias::a),                                                                     
                                     sqlpp::value(0).as(sqlpp::alias::b),                                                                      
                                     sqlpp::value("").as(sqlpp::alias::c),                                                                     
                                     sqlpp::value("").as(sqlpp::alias::d)                                                                      
                                     ));                                                                                                       
                                                                                                                                               
        for(const auto & row : db(statement))                                                                                                  
        {                                                                                                                                      
            std::cout << "name: " << row.a << " len: " << row.b                                                                                
                      << " in: " << row.c << " out: " << row.d << std::endl;                                                                   
        }
 `

`
name: bool len: 1 in: boolin out: boolout
name: bytea len: -1 in: byteain out: byteaout
name: char len: 1 in: charin out: charout
name: name len: 64 in: namein out: nameout
name: int8 len: 8 in: int8in out: int8out
name: int2 len: 2 in: int2in out: int2out
name: int2vector len: -1 in: int2vectorin out: int2vectorout
name: int4 len: 4 in: int4in out: int4out

`

**Comment by campisano** [comment]
@rbock there is a way to do an insert statement with a plain sql query like the select above?

**Comment by rbock** [comment]
@campisano You could do something like this:

```C++
custom_query(sqlpp::verbatim("INSERT INTO tab_sample VALUES()")).with_result_type_of(insert_into(f));
```
Not sure why you would want to do that, though :-)

**Comment by campisano** [comment]
Thanks @rbock 

the follow code

    custom_query(sqlpp::verbatim("INSERT INTO tab_sample VALUES()")).with_result_type_of(sqlpp::insert_into(sqlpp::alias::a));

returns an error

    error: static assertion failed: argument for into() must be a table

should I use something like 'verbatim_table' maybe?

howerver, I would like to try to use sqlpp without define tables, and I want to do the following insert returning an autogenerated ID: is it possible?

    std::string sql = "INSERT INTO ticket (high, last, timestamp, bid, vwap, volume, low, ask, open) VALUES () RETURNING id;";
    auto statement = custom_query(sqlpp::verbatim(sql)).with_result_type_of(insert_into(sqlpp::value(0).as(sqlpp::alias::a)));

**Comment by rbock** [comment]
@campisano This is probably the closest you can get:

```C++
custom_query(sqlpp::verbatim("INSERT INTO tab_sample VALUES()")).with_result_type_of(sqlpp::insert());
```
The string is you responsibility. It will return the id of the insert (`RETURNING id` should be fine). It does not know anything about placeholders, though.

**Comment by campisano** [comment]
Thanks again @rbock !
the follow code works for my purpose

    std::stringstream sql;
    sql << "INSERT INTO tab_sample ("
        << "foo, bar"
        << ") VALUES ("
        << 10 << ", " << 20
        << ") RETURNING id;";

    auto statement = sqlpp::custom_query(sqlpp::verbatim(sql.str()))
      .with_result_type_of(sqlpp::select(sqlpp::value(0).as(sqlpp::alias::a)));
    
    for(const auto & row : db(statement))
    {
        std::cout << "ID: " << row.a << std::endl;
    }
