### ISSUE TITLE
tvin std::optional

### ISSUE THREAD

**Issue by dirkvdb** [rbock/sqlpp11#238]
I am currently in the situation that I want to store double values in the database, the doubles are stored in an std::optional and I want to store NULL when the optional does not contain a value.

I there a way to customize the sqlpp::tvin implementation to be aware of std::optional?

My current attempt at creating a helper function does not compile, the errors are beyond me :-)

```
template <typename FieldType, typename ValueType>
static auto optionalFieldValue(const std::optional<ValueType>& opt)
{
    FieldType field;
    field = sqlpp::null;
    if (opt.has_value()) {
        field = opt.value();
    }

    return field;
}

void Database::addVar(std::optional<double> val)
{
    _db(insert_into(Table).set(
        Table.UNCERTAINTY = optionalFieldValue<decltype(table.UNCERTAINTY)>(val)
    ));
}
```
This hits the assert:
`error C2338: at least one argument is not an assignment in set()`

Any ideas how this can be accomplished?

**Comment by rbock** [comment]
Glad this worked out :-)

I probably should update the description. All the basics are working, but there are a couple of details missing and some aspects should be written in a more elegant way. And the documentation is non-existent.

**Comment by rbock** [comment]
Putting support for std::optional onto the wish list I am currently compiling.
