### ISSUE TITLE
Is there a way to change table name dynamically

### ISSUE THREAD

**Issue by clear-m** [rbock/sqlpp11#239]
Hi there!

First of all thanks for your libs!

As it usually happens I would like to use your lib in a way that it probably should not  be used but I wish to use common table schema with only table name changed.

I did noticed someone already used sqlpp::verbatim_table #79 to achive such behavior. 

I wounder is it actually possible now or should I use different struct for each different table name with the same schema ?

Thanks for great job again!

**Comment by rbock** [comment]
Hi,
Just to make sure I get this right: You have multiple tables that the exact same columns?

What is the drawback of having multiple classes representing those tables? They are created with code generator (typically), so it is not the effort of typing, I guess.

I don't think that using `verbatim_table` is a good idea.

You could write your own table class. If you look at the generated code, it is rather simple. You could replace that with a version that contains a variable with the "real" name. You would have to specialize `name_of<T>::template char_ptr<Context>()` (with `T` being your table, `Context` being the serialization context of your database connector).

However, I would advise against it. The library would use the "common" name to do compile time checks, while you modify the name at runtime. That sounds like a recipe for disaster.

Hope that helps :-)

Cheers,

Roland

**Comment by clear-m** [comment]
Thank you for answer 👍

>Just to make sure I get this right: You have multiple tables that the exact same columns?

this is exactly exactly what I have

>The library would use the "common" name to do compile time checks, 

that is awesome and It is really useful but the reason why I am searching for runtime name modification is that I have db with ~50 tables with exact the same columns
also I have feature request to add more tables via config during runtime in one of my projects

**Comment by rbock** [comment]
Do you need to join these tables?

**Comment by clear-m** [comment]
> Do you need to join these tables?
I don't need to join those tables just now but It may be handy later - who knows?

Are there are any hints about join and dynamic tables names ?

**Comment by clear-m** [comment]
OK - thank you again for help!
Sorry for my english (I am from Russia actually) ;)

**Comment by rbock** [comment]
Thanks, and no worries, your English is just fine :-)

Let me know if you need help with writing that table class.
