### ISSUE TITLE
Large increase of size of library/executable after adding new DB queries

### ISSUE THREAD

**Issue by SMelanko** [rbock/sqlpp11#241]
We are working on some kind of customer relationship management application. There is a lot of DB queries and related code stuff. At some point, we noticed that the size of the executable and library became huge. And more features are added, bigger size of the application. For example, debug version of the library is about 1.5GB. Also, I would like to admit that we are using [PostgreSQL connector](https://github.com/matthijs/sqlpp11-connector-postgresql) which is based on sqlpp11. It might be because of Specs and Repos template implementation but we are not sure. We have checked files using [bloaty](https://github.com/google/bloaty) tool but it did not show exactly where the problem is. 

Have someone noticed/experienced such issue?

I do not say that the problem in the library, just wonder what it can be.

Thank you!

**Comment by rbock** [comment]
Hi

sqlpp11 creates template expressions, which are certainly not small in debug mode. A growth to GBs seems excessive, though. We are using it quite a bit as well (with MariaDB) and haven't seen this kind of growth.

To give you an idea of the size of a query, try dropping a complex `where` part of a `select` and measure the size change.

I have not invested into reducing the size of the resulting binary, especially debug versions. I assume that quite a bit of memory could be saved by not exposing symbols (try `nm` on your library). Hiding sqlpp11-related symbols will definitely have some impact, but I have no data. I would be very interested in the results if you could do some measurements.

Best,

Roland

**Comment by SMelanko** [comment]
Hi @rbock 

We are going to check it and will let you know.

**Comment by rbock** [comment]
I did not get any new data, closing this one.

BTW, I did add `suppress symbol export` onto the wish list I am compiling. That might be helpful here as well.
