### ISSUE TITLE
Select stament get all row's

### ISSUE THREAD

**Issue by r2range** [rbock/sqlpp11#245]
not quite sure but it will only return 1 row (first one).

        for (const auto& row : db_(sqlpp::select().flags(sqlpp::all).columns(players.muted).from(players).where(players.muted != "0")))

or

	for (const auto& row : db_(sqlpp::select().columns(players.muted).from(players).where(players.muted != "0")))

both will only return the first row instead of all rows.

**Comment by rbock** [comment]
The `sqlpp::all` flag just adds `ALL` to the query.

If you really want to have all rows, you should express it like this:

```
for (const auto& row : db_(sqlpp::select(players.muted).from(players).unconditionally()))
```

**Comment by r2range** [comment]
Thank you for youre answer i tested it out but sadly i will still only get the first row.

https://i.imgur.com/DK4CmWW.png


here is the full code 

	TArray<FString> GetPlayerMuted()
	{
		TArray<FString> mutedtill;		
		const auto& players = Players{};
		try
		{
		
		
			
		
			
			
		//	for (const auto& row : db_(sqlpp::select().columns(players.muted).from(players).where(players.muted != "0")))
			for (const auto& row : db_(sqlpp::select(players.muted).from(players).unconditionally()))
			{	
				
				
				
				//mutedtill.Add(row.muted.text);				
				FString groups_fstr(row.muted.text);
				groups_fstr.ParseIntoArray(mutedtill, L",", true);
				reply += FString::Format(TEXT("GetPlayersMuted={} \n"), mutedtill.GetData()->ToString());
				break;
			}
		}
		catch (const std::exception& exception)
		{
			Log::GetLog()->error("({} {}) Unexpected DB error {}", __FILE__, __FUNCTION__, exception.what());}
		
		Log::GetLog()->info("Called 1");
		Log::GetLog()->info(reply.ToString());
		return mutedtill;
	}

**Comment by rbock** [comment]
```
break;
```
That might have something to do with it :-)

**Comment by r2range** [comment]
That fixed my probleem no clue how i missed that.

**Comment by rbock** [comment]
This kind of mistakes is why I wrote the library in the first place. Happened to me all the time when writing SQL in strings.

Glad that it worked out now :-)
