### ISSUE TITLE
Why not Support oracle?

### ISSUE THREAD

**Issue by qqqqzl** [rbock/sqlpp11#250]
Oracle database is very common，Can you provide oracle connector?

**Comment by rbock** [comment]
Hi,

Yes, it would be nice to have an Oracle connector. However, I am afraid, I don't have the resources to do that. 

But if you give it a try yourself, I can help you with it.

Best,

Roland

**Comment by qqqqzl** [comment]
Thanks, I will try myself.

Best Wish

**Comment by rbock** [comment]
Great!

Let me know how it goes.

Cheers,

Roland

**Comment by giorgiozoppi** [comment]
In this matter it will nice to have an ODBC connector instead of a sql ones.

**Comment by rbock** [comment]
There is an ODBC connector: https://github.com/Erroneous1/sqlpp11-connector-odbc

**Comment by giorgiozoppi** [comment]
Args...i was cloning your mysql and creating a connector via odbc for SQLServer on linux...Good to know,  it will save me time:
https://github.com/giorgiozoppi/microservice-demo/tree/master/src
Thanks,
Giorgio.

**Comment by rbock** [comment]
Regarding Oracle, see also #282 

Closing this one. I won't write an Oracle connector myself (but I'd support the effort if you were to try to create one yourself).
