### ISSUE TITLE
Update

### ISSUE THREAD

**Issue by r2range** [rbock/sqlpp11#252]
I might be doing something wrong here but here goes.

Before i had 

db_(sqlpp::remove().from(players).where(players.time == row.time.text));

i am trying to update it to 0 instead of remove i tried the following.

db_(sqlpp::update(players).where(players.time == row.time.text).set(0));

this doesnt work sadly.

**Comment by matthijs** [comment]
If the field time is an integer field use:
```c++
db_(sqlpp::update(players).where(players.time == row.time.text).set(players.time = 0));
```

If it is a text field:
```c++
db_(sqlpp::update(players).where(players.time == row.time.text).set(players.time = "0"));
```
