### ISSUE TITLE
Compilation error with combination of dynamic_from and dynamic_where

### ISSUE THREAD

**Issue by MatthieuTexier** [rbock/sqlpp11#255]
Hello,

I have a compilation error when combining dynamic_from and dynamic_where, see following example.

auto s = dynamic_select(db, table_a.id).dynamic_from(table_a).dynamic_where();
if (!b_id.empty()){
        s.from.add(dynamic_join(table_b).on(tables_a.b_id == table_b.id));
        s.where.add(without_table_check(table_b.id == b_id));
}

error: static assertion failed: expression uses tables unknown to this statement in where::add()
static_assert(Policies::template _no_unknown_tables<Expr>::value

Thank you for your help.
Matthieu

**Comment by MatthieuTexier** [comment]
I'm not using the latest version of the sources, please ignore this ticket.

**Comment by MatthieuTexier** [comment]
Tested on the current version and still failling

**Comment by MatthieuTexier** [comment]
sorry fro the noise again :-( it's compiling now using without_table_check

**Comment by rbock** [comment]
No worries :-)
