### ISSUE TITLE
ddl2cpp // real data type was deleted with merge

### ISSUE THREAD

**Issue by snikulov** [rbock/sqlpp11#257]
Following pull request #227 was deleted with https://github.com/rbock/sqlpp11/commit/a643095958958ea4072d001233bff4d5b3400ead#diff-28f3e7e4a10669732b25975cf968289eL222

Should I resubmit this pull request or you've fixed it per this issue?

**Comment by rbock** [comment]
Thanks for the hint. Not sure what happened there, probably a badly resolved merge conflict.

Anyway: This is now fixed on develop.

**Comment by snikulov** [comment]
Fixed in 0.58
