### ISSUE TITLE
CREATE TABLE PPGen

### ISSUE THREAD

**Issue by jameyboor** [rbock/sqlpp11#258]
On the PPGen examples there are some snippets of syntax examples that contain table properties such as `SQLPP_DROP_IF_EXISTS` and `SQLPP_CREATE_IF_NOT_EXISTS`. However, these don't work. Seeing as PPgen was worked on in 2016 is it ever going to be added?

Perhaps handy to ping the creator @niXman

**Comment by niXman** [comment]
Hi,

Read please: https://github.com/rbock/sqlpp11/issues/63

I'm sorry, but at the moment I can't work for free because I was left without work...

**Comment by jameyboor** [comment]
I see, thank you. That's awful to hear. If it turns out this feature is critical for me I'll let you know and support you through donations to add it.

**Comment by rbock** [comment]
I added table creation to the wish list I am compiling. Closing this ticket.
