### ISSUE TITLE
What is Connection interface(important for connection_pool)?

### ISSUE THREAD

**Issue by fraillt** [rbock/sqlpp11#262]
I noticed, that mysql and sqlite connection constructor accepts config in different forms. As a result one of them doesn't work when used in connection_pool.
In older version mysql worked, but in #190 it was changed, as compile fix. Now it works with sqlite, but fails with mysql. What is a correct approach?
Should config be accepted by value or by shared_ptr?
Either mysql or sqlite must change, but this project must set the rules.

**Comment by rbock** [comment]
The connection pool is work in progress (with very little involvement from my side). I am not sure if it is widely used, but would guess that the answer is currently no.

The connectors on the other hand are used my quite a few people. Thus, changing the interface of those would cause some concern.

In sqlpp17, I ended up having specific pools for each connector.

That being said: I am not convinced that having a connection pool for sqlite3 actually makes sense?

**Comment by rbock** [comment]
connection pools are on the wish list I am compiling. Closing this issue.
