### ISSUE TITLE
Google Spanner thoughts?

### ISSUE THREAD

**Issue by nickolasrossi** [rbock/sqlpp11#263]
I am considering taking a crack at a connector for Google Spanner.

Spanner supports plain SQL over a grpc connection. However, it does not have the concept of prepared statements. All SQL statements are just strings with the values inside them.

Any hints on how I would handle the impedance mismatch with your prepared statement interfaces?

**Comment by rbock** [comment]
Nick,

if it does not have prepared statements, then the easiest solution would be to not implement the `prepare` method.

If C++17 is an option for you, then you might want to look into sqlpp17. The code is easier to grok, I believe.

Best,

Roland

**Comment by rbock** [comment]
Adding connectors is on the wish list, I am currently compiling.
