### ISSUE TITLE
CMake namespace

### ISSUE THREAD

**Issue by xsacha** [rbock/sqlpp11#264]
The CMakeLists uses no namespace when it installs.
However, the Config file adds a single executable in the sqlpp11:: namespace (https://github.com/rbock/sqlpp11/blob/develop/cmake/Sqlpp11Config.cmake#L41).
For consistency here, should everything be exported using the same namespace?

Also would that namespace be sqlpp11:: or Sqlpp11:: considering the export and package name has a capital S, requiring a find_package(Sqlpp11).

**Comment by rbock** [comment]
Hi Sacha,

I am a CMake illiterate but I like consistency. So yes, I think everything should have the same namespace. I would prefer lowercase, but since `Sqlpp11` is already being used for find_package, I guess we should stick with that.

I'd welcome a pull request.

Best,

Roland

**Comment by rbock** [comment]
Closing this as I am rather incompetent when it comes to cmake...
