### ISSUE TITLE
error: invalid application of ‘sizeof’ to incomplete type '...'

### ISSUE THREAD

**Issue by pete842** [rbock/sqlpp11#265]
I have some troubles getting sqlpp11 working on my project.
When I include `sqlpp11.h` header, I get the following CMake compilation error (on travis, with Ubuntu Xenial) : 
```
/usr/local/include/sqlpp11/mysql/connection.h:89:11:   required from here
/usr/include/c++/7/bits/unique_ptr.h:76:22: error: invalid application of ‘sizeof’ to incomplete type ‘sqlpp::mysql::detail::connection_handle_t’
  static_assert(sizeof(_Tp)>0,
```

And the same occurs on my system (Arch) :
```
/usr/local/include/sqlpp11/mysql/connection.h:89:11:   requis depuis ici
/usr/include/c++/8.2.1/bits/unique_ptr.h:79:16: error: utilisation invalide de « sizeof » sur le type incomplet « sqlpp::mysql::detail::connection_handle_t »
  static_assert(sizeof(_Tp)>0,
```

Since I have absolutely no clue about what is causing this error in my code, I am really stuck and was hoping someone could help me there.

Sorry if this doesn't have anything to do with your lib.

Thanks !

**Comment by pete842** [comment]
I forgot to tell that I use https://github.com/rbock/sqlpp11-connector-mysql as well, of course. 

Please tell me if I have to move my issue to this repo.

**Comment by rbock** [comment]
Hi,

Yes, it would help if you moved the issued to the mysql connector. Please also try to create a minimal example that shows the behavior. That would be super helpful.

Thanks!

Roland

**Comment by pete842** [comment]
Wow ! Thanks for the quick feedback.

I will try to do that as soon as possible, you can close this issue :blush:.

Many thanks,
Pierre

**Comment by rbock** [comment]
I just happened to see you message and had a few spare minutes :-)

**Comment by pete842** [comment]
Hi, 
Just to give you a feedback:
I didn't open a new issue because I found a simple solution to my problem.
It was coming from a part of the code I didn't wrote and that I wasn't even considering because of the lack of precision of the error message. 

Thanks :)
