### ISSUE TITLE
"not all selected columns are made of aggregates, despite group_by or similar"

### ISSUE THREAD

**Issue by xnxin** [rbock/sqlpp11#266]
```C++
 auto sql = sqlpp::select(orders.orderId, orders.momoId, sqlpp::sum(account_frozen.orderId).as(left_num))
            .from(orders.join(account_frozen)
            .on(orders.orderId == account_frozen.orderId))
            .group_by(account_frozen.orderId)
            .having(orders.momoId == "412448059");

    auto result = conn_->run(sql);
```
When i try to compile this, it will raise an error, like below

```
/usr/local/include/sqlpp11/portable_static_assert.h:41:7: note: expanded from macro 'SQLPP_PORTABLE_STATIC_ASSERT'
      static_assert(wrong_t<T...>::value, message); \
      ^             ~~~~~~~~~~~~~~~~~~~~
/usr/local/include/sqlpp11/statement.h:240:7: note: in instantiation of function template specialization 'sqlpp::assert_no_unknown_aggregates_t::assert_no_unknown_aggregates_t<>' requested here
      _run_check{};  // FIXME: Dispatch?
      ^
/usr/local/include/sqlpp11/mysql/connection.h:250:18: note: in instantiation of function template specialization 'sqlpp::statement_t<void, sqlpp::no_with_t, sqlpp::select_t, sqlpp::no_select_flag_list_t, sqlpp::select_column_list_t<void, sqlpp::column_t<momo::Orders, momo::Orders_::OrderId>, sqlpp::column_t<momo::Orders, momo::Orders_::MomoId>, sqlpp::expression_alias_t<sqlpp::sum_t<sqlpp::noop, sqlpp::column_t<momo::AccountFrozen, momo::AccountFrozen_::OrderId> >, left_num_t> >, sqlpp::from_t<void, sqlpp::join_t<sqlpp::pre_join_t<sqlpp::inner_join_t, momo::Orders, momo::AccountFrozen>, sqlpp::on_t<sqlpp::binary_expression_t<sqlpp::column_t<momo::Orders, momo::Orders_::OrderId>, sqlpp::op::equal_to, sqlpp::column_t<momo::AccountFrozen, momo::AccountFrozen_::OrderId> > > > >, sqlpp::no_where_t<true>, sqlpp::group_by_t<void, sqlpp::column_t<momo::AccountFrozen, momo::AccountFrozen_::OrderId> >, sqlpp::having_t<void, sqlpp::binary_expression_t<sqlpp::column_t<momo::Orders, momo::Orders_::MomoId>, sqlpp::op::equal_to, sqlpp::text_operand> >, sqlpp::no_order_by_t, sqlpp::no_limit_t, sqlpp::no_offset_t, sqlpp::no_union_t, sqlpp::no_for_update_t>::_run<sqlpp::mysql::connection>' requested here
        return t._run(*this);
```

How do i resolve this error?

**Comment by rbock** [comment]
results are not grouped by `orders.momoId`, and it is not used with an aggregate function like `sum`.

You should not use that in `having` and you should not select it (some databases allow it, but it does not make sense and in most cases leads to undefined results.

In this particular case, since you already know the value of `momoId`, there is no need to select it, and you can move the `having` condition into the `where` clause.

**Comment by xnxin** [comment]
Sorry ,That's my fault. When I got this error,I found the same issue, the answer says the group by column is wrong, so I tried to change the column to fix the error, but still failed, I test the sql on mysql database, it works, but when i use sqlpp it will raise error just like i said, I'll upload the sql later. Thanks for your work, and this library is awesome.

**Comment by rbock** [comment]
Thanks!

Looking forward to a "correct" wrong example then :-)

**Comment by xnxin** [comment]
I run sql `SELECT orders.orderId, orders.momoId, SUM(account_frozen.orderId) as left_num FROM orders LEFT JOIN account_frozen ON orders.orderId = account_frozen.orderId GROUP BY orderId` with `Navicat` it's work fine.
But why it raise compile error when I transfer to sqlpp with c plus puls
```C++
SQLPP_ALIAS_PROVIDER(left_num);
auto sql = sqlpp::select(orders.orderId, orders.momoId, sqlpp::sum(account_frozen.orderId).as(left_num))
            .from(orders.join(account_frozen)
            .on(orders.orderId == account_frozen.orderId))
            .group_by(orders..orderId);
```

and I want to know is there have any function just like `IFNULL` in sql. Thank for your help.

**Comment by rbock** [comment]
`orders.momoId` is an undefined value. It could be any within the group. Some database engines accept this kind of query, but some don't.
You can "repair" this by saying `min(orders.momoId)`. This is defined and should be accepted by the library and every database.

There is no `IFNULL`, but a `CASE` statement, for instance:

```
sqlpp::case_when(t.alpha.is_null()).then(0).else_(t.alpha).as(t.alpha)
```

Personally, I would try to avoid this in the SQL code.

**Comment by xnxin** [comment]
OK, thanks, I'll try this later, maybe I should find an another solution for IFNULL. Thanks for your help.
