### ISSUE TITLE
Where clause with "in" expression (from array)

### ISSUE THREAD

**Issue by pete842** [rbock/sqlpp11#267]
Hi !

I'm currently looking for a way to write the following SQL query :
```
SELECT id, name FROM table WHERE id IN (1, 2, 3,...)
```

I understand that I can write something like this :
```
auto select = select(table.id, table.name).from(table).where(table.id.in(1, 2, 3));
```

My problem is that I want to use an array (of any kind) instead of the expression `(1, 2, 3)`.
I also consider to work with a `dynamic_select`, but I understood that every `where` clauses that I'll add will be bounded with an `and`. So that won't do the trick.

Sorry if there is an obvious solution to my problem, but I admit having some struggles to find what I am looking for in the wiki. I am considering writing some doc for the wiki and doing a PR when I'll be more confident with this lib ;)

Pierre

**Comment by rbock** [comment]
Hi Pierre,

You can so something like:

```
table.id.in(sqlpp::value_list(std::vector<int>({1, 2, 3}))
```

Contributions to the documentation would be very much appreciated. The documentation probably the weakest spot of the library.

Best,

Roland

**Comment by pete842** [comment]
Nice! It works perfectly!

Many thanks,

Pierre

**Comment by rbock** [comment]
You're welcome :-)
