### ISSUE TITLE
Having trouble with join

### ISSUE THREAD

**Issue by juandent** [rbock/sqlpp11#268]
Hi Roland,

I am beginning to use the connector for sqlite3 and have successfully written the following join which gives me too many columns (I only want all of food's columns and one food_type column):

```
	for(const auto& row: db(sqlpp::select(all_of(food).as(left), all_of(food_types).as(right)).from(food.join(food_types).on(food.typeId == food_types.id)).unconditionally()))
	{
		std::cerr << ">> row.left.typeId: " << row.left.typeId << " row.right.name: " << row.right.name
		<< " row.left.name: " << row.left.name
		<< std::endl;
	}
```
This runs fine. However this does not... I get 

> ambiguous access of 'name'

```
	for (const auto& row : db(sqlpp::select(all_of(food), food_types.name).from(food.join(food_types).on(food.typeId == food_types.id)).unconditionally()))
	{
		std::cerr << ">> row.typeId: " << row.typeId 
			<< " row.name: " << row.name
			<< std::endl;
	}
```

Probably something very simple to correct right?

Regards,
Juan Dent

**Comment by juandent** [comment]
Where can I find samples?

**Comment by rbock** [comment]
Hi Juan,

You have a result with two columns called `name`. This gives you a result struct with two members called `name` (via inheritance). Accessing them simply by `row.name` is ambiguous.

Thus, you need to change the name of one column. You can do this using the `as` method you already used above. For instance

```
food_types.name.as(right)
```

There are quite a few examples in the tests in sqlpp11 (not exactly the documentation one would be hoping for, I know, help with that would be appreciated).

Best,

Roland
