### ISSUE TITLE
How to capture all rows into a std::vector?

### ISSUE THREAD

**Issue by juandent** [rbock/sqlpp11#269]
Hi Roland,

I am trying to fill a std::vector with all the rows from a result set but can't seem to get it right.
I am trying to get the type of a row via the iterator. This is my present code:

```
using iterator_type = decltype(db(sqlpp::select(all_of(epi)).from(epi).unconditionally()).begin());

std::vector<iterator_type> rows;

for(iterator_type  b = db(sqlpp::select(all_of(epi)).from(epi).unconditionally()).begin();
	b != db(sqlpp::select(all_of(epi)).from(epi).unconditionally()).end();
	++b)
{
	rows.push_back(*b);
}
```
Sorry, very confused right now... BTW, can rows be copied? Does begin() return an iterator into the result set?

Also, how can one access individual fields by position? Sort of std::get<0>(res)..

Regards,
Juan Dent

**Comment by juandent** [comment]
What am I trying to do? Well, I need an automatic way to get the fields displayed in a row of a grid...Also, I need access to all the rows resulting from a query in order to process them - thus the std::vector<>

**Comment by rbock** [comment]
Hi Juan,

You can't copy rows. They might contain data that would be invalidated once you advance to the next row.
If you need to store a result somewhere, you need to store the content of a row in a struct.

Best,

Roland

**Comment by juandent** [comment]
got it! That rows cannot be copied makes sense. I have created a struct for the row. Thanks!
