### ISSUE TITLE
GROUP_CONCAT support

### ISSUE THREAD

**Issue by LouisDuVerdier** [rbock/sqlpp11#270]
Hello,

I'm using your library and I think you did a great job on it.

However I'm facing an issue: I would like to know if you would have any possibility to do a GROUP_CONCAT with it. I cannot find anything related, so I tried a verbatim (note that the PK of the example table is OwernID, GroupID, MsgID - it is an association table, it has no other field):

```
sqlpp::select(
          mytable.OwnerID,
          mytable.GroupID,
          sqlpp::verbatim("GROUP_CONCAT(MsgID)").as(myalias)
          )
      .from(mytable)
      .group_by(mytable.OwnerID, mytable.GroupID)
      .unconditionally();
```

Unfortunately, I get rejected by static assertions because of the verbatim part (I also tried with mytable.MsgID for the as() but I get the same result):

`error: static assertion failed: not all selected columns are made of aggregates, despite group_by or similar`

Would you have any solution for this? I know that "count()" itself works but I cannot find anything related to group_concat.

Thanks you,
Louis

**Comment by rbock** [comment]
Hi Louis,

GROUP CONCAT is currently not supported by sqlpp11. I am not entirely sure if it is standard SQL? I think it is more of a MYSQL specialty?

In any case: I see two ways to tackle this.

 - you could add a version of the `verbatim` function that claims to be an aggregate, see aggregate functions like `count`.
 - you add a group_concat function.

Looking at the existing functions should give you enough pointers of how to do it. If not, let me know, I will help.

I would welcome a pull request :-)

Cheers,

Roland

**Comment by LouisDuVerdier** [comment]
Hi Roland,

Thanks for your answer, I could make a first approach following your second proposal:

```
namespace sqlpp
{
  struct group_concat_alias_t
  {
    struct _alias_t
    {
      static constexpr const char _literal[] = "group_concat_";
      using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
      template <typename T>
      struct _member_t
      {
        T group_concat;
        T& operator()()
        {
          return group_concat;
        }
        const T& operator()() const
        {
          return group_concat;
        }
      };
    };
  };

  template <typename Expr>
  struct group_concat_t : public expression_operators<group_concat_t<Expr>, integral>,
                   public alias_operators<group_concat_t<Expr>>
  {
    using _traits = make_traits<value_type_of<Expr>, tag::is_expression, tag::is_selectable>;
    using _nodes = detail::type_vector<Expr, aggregate_function>;
    using _can_be_null = std::false_type;
    using _is_aggregate_expression = std::true_type;

    using _auto_alias_t = group_concat_alias_t;

    group_concat_t(const Expr expr) : _expr(expr)
    {
    }

    group_concat_t(const group_concat_t&) = default;
    group_concat_t(group_concat_t&&) = default;
    group_concat_t& operator=(const group_concat_t&) = default;
    group_concat_t& operator=(group_concat_t&&) = default;
    ~group_concat_t() = default;

    Expr _expr;
  };

  template <typename Context, typename Expr>
  struct serializer_t<Context, group_concat_t<Expr>>
  {
    using _serialize_check = serialize_check_of<Context, Expr>;
    using T = group_concat_t<Expr>;

    static Context& _(const T& t, Context& context)
    {
      context << "GROUP_CONCAT(";
      serialize(t._expr, context);
      context << ")";
      return context;
    }
  };

  template <typename T>
  auto group_concat(T t) -> group_concat_t<wrap_operand_t<T>>
  {
    static_assert(not contains_aggregate_function_t<wrap_operand_t<T>>::value,
                  "group_concat() cannot be used on an aggregate function");
    static_assert(is_expression_t<wrap_operand_t<T>>::value, "group_concat() requires an expression as argument");
    return {t};
  }
}  // namespace sqlpp
```

It is not perfect, it for example lacks of the possibility to specify a separator and to specify a specific serializer depending on the DB type (for example PostgreSQL, Oracle, SQLite, etc. - because it's indeed not completely standard) but it works. :)

Thanks,
Louis

**Comment by rbock** [comment]
Hi Louis,

Looks good, indeed.

Regarding the separator: Can't you just add another argument?

```
auto group_concat(T t, const std::string& separator) -> group_concat_t<wrap_operand_t<T>>
```

Regarding the serializer, I see two options to deal with this.
  - add respective versions to the individual connectors (see for instance `insert_or` for sqlite3)
  - have function and type in sqlpp11, and add the individual serializers to the connector libraries, see the respective `serializer.h`

I am not too familiar with group concat. Based on a cursory search yesterday it seems to me that the function is not even called the same in different databases (e.g. array_agg in postgresql)? That makes me lean towards the first version.

Best,

Roland

**Comment by LouisDuVerdier** [comment]
Hi Roland,

For this part I would prefer to let anyone more experienced take the subject, because I'm not very familiar either with group_concat. I've seen there are alternatives such as array_agg, others also have a group_concat but depending on the database, there might be other parameters such as "ORDER BY" and so on. Having a parameter "separator" is a first step but for others such as ORDER BY that might be more complex to set up (unless by simply providing another verbatim that has the aggregate trait to avoid to manage the complexity).

Best regards,
Louis

**Comment by rbock** [comment]
As discussed, `GROUP CONCAT` needs to got to the respective connector libraries.

Closing it here (although maybe I will still go ahead and move the connectors maintained by myself into the main repository).
