### ISSUE TITLE
WHERE NOT EXISTS in INSERT is not supported ?!!

### ISSUE THREAD

**Issue by aminaramoon** [rbock/sqlpp11#272]
I have watched most of your talks and I was keen to try sqlpp11, I recommended sqlp11 for CPP client API for our Postgres DB in my company. today a couple of my teammates came to me asking if the library supports a simple query as follows:

"INSERT INTO GroupPathMapping(unique_gid, path_id) "
        " SELECT %(unique_gid)s, %(path_id)s "
        " WHERE NOT EXISTS (SELECT * FROM GroupPathMapping "
        " WHERE unique_gid=%(unique_gid)s "
        " AND path_id=%(path_id)s);"

at the moment I haven't found anything in the tests and examples and also the online documents poiting at this, so I decided to ask a question here

**Comment by rbock** [comment]
Personally, I would not consider this a simple query :-)

You could do something like this:

```
const auto x = 17;
custom_query(insert_into(foo).columns(foo.omega),
       select(sqlpp::value(x).as(foo.omega))
           .from(foo)
           .where(not exists(select(foo.omega).from(foo).where(foo.omega == x))));
```

I added small fix on develop. With that, it serializes to 

```
INSERT INTO tab_foo (omega) 
SELECT 17 AS omega FROM tab_foo 
WHERE (NOT EXISTS(SELECT tab_foo.omega FROM tab_foo WHERE (tab_foo.omega=17)))
```

That is what you need, right?

**Comment by aminaramoon** [comment]
yes, that is what we need. Thanks. I really wish you had better documentation for this library, but at the same time, I understand writing the documentation is probably the least interesting and most time-consuming part of building a library.

**Comment by aminaramoon** [comment]
We tried what you suggested, but in postgres, we get the custom query serialized to:

INSERT INTO tab_foo (omega) VALUES
SELECT 17 AS omega FROM tab_foo 
WHERE (NOT EXISTS(SELECT tab_foo.omega FROM tab_foo WHERE (tab_foo.omega=17)))

which throws an exceptio because of bad syntax

**Comment by rbock** [comment]
Better documentation is on the wish list I am currently compiling.
