### ISSUE TITLE
New adaptors for hunter cmake

### ISSUE THREAD

**Issue by edwardbr** [rbock/sqlpp11#274]
Hi I thought you would like to know that I have forked your code to work with the hunter cmake packaging solution.  I hope that you find it useful.  It is not fully tested so I have not made a pull request onto the Hunter repository.

https://github.com/edwardbr/sqlcipher
https://github.com/edwardbr/sqlpp11-connector-mysql
https://github.com/edwardbr/sqlpp11-connector-sqlite3

Here is a typical config.cmake file that provides the necessary initialisation parameters.
[config.cmake.txt](https://github.com/rbock/sqlpp11/files/3183958/config.cmake.txt)

And here is what you might have in your CMakeLists.txt file:

cmake_minimum_required(VERSION 3.13)

list(APPEND CMAKE_MODULE_PATH ${CMAKE_SOURCE_DIR}/cmake)
set(CMAKE_MODULE_PATH ${CMAKE_MODULE_PATH} "${CMAKE_SOURCE_DIR}/cmake/Modules/")

include(HunterGate)

message(STATUS "[project] CMAKE_TOOLCHAIN_FILE: ${CMAKE_TOOLCHAIN_FILE}")

option(HUNTER_STATUS_DEBUG "Hunter debug info" OFF)
HunterGate(
    URL "https://github.com/ruslo/hunter/archive/v0.23.165.tar.gz"
    SHA1 "5a73f91df5f6109c0bb1104d0c0ee423f7bece79"
    LOCAL
)

set(HUNTER_KEEP_PACKAGE_SOURCES ON)

project(demo)

set(CMAKE_CXX_STANDARD 11)

hunter_add_package(date)
find_package(date CONFIG REQUIRED)

if(NOT ANDROID)
    hunter_add_package(MySQL-client)
    find_package(MySQL-client CONFIG REQUIRED)

    hunter_add_package(sqlpp11-connector-mysql)
    find_package(sqlpp11-connector-mysql CONFIG REQUIRED)
endif()

hunter_add_package(Sqlpp11)
find_package(Sqlpp11 CONFIG REQUIRED)

hunter_add_package(sqlcipher)
find_package(sqlcipher CONFIG REQUIRED)

hunter_add_package(sqlpp11-connector-sqlite3)
find_package(sqlpp11-connector-sqlite3 CONFIG REQUIRED)

add_executable(${PROJECT_NAME} "main.cpp")
target_link_libraries(${PROJECT_NAME}  
    INTERFACE 
        date_interface 
    PUBLIC 
        sqlpp11 
        sqlpp11-connector-sqlite3::sqlpp11-connector-sqlite3 
        sqlpp11-connector-mysql::sqlpp11-connector-mysql 
        MySQL::libmysql
        sqlcipher::sqlcipher
)

Regards
Edward

**Comment by rbock** [comment]
Sorry for taking so long to respond.
Thanks for taking the time to add sqlpp11 support for the hunter project. I must admit that I am not very up to date with package management tools. I currently have no plans to get involved in any of them.

As this is just a message, I am closing the issue.
