### ISSUE TITLE
Documentation for adding missing features to sqlpp11

### ISSUE THREAD

**Issue by aminaramoon** [rbock/sqlpp11#275]
I have a quick question, we are in the process of transforming our database state handler class from python to c++ (Postgres), and we decided to go with sqlpp11. one feature that we use very commonly is RETURNING unique_id on insert. however, this is not supported by sqlpp11.

at the moment what we do is using a custom query with the returning type of select(unique_id), however, we would much rather change the header file to make the library natively supporting commands like 
DO NOTHING ON CONFLICT, or RETURNING "" 
than using custom queries with verbatim.

what is the best way to go about this? I read the library and I was able to successfully add support for do_nothing_on_conflict to the insert statement, but the case for RETURNING an id seems to be a much more complicated problem.

is there an internal developer guide or something that we can use ?!!

**Comment by rbock** [comment]
Hi,

there is no developer guide, but there are basically two steps: 

1. Implement new clause(s), e.g. RETURNING. Using existing steps as templates, this is mainly a matter of replacing strings. It is a lot of boilerplate, sorry about that, but it is not that bad in the end.
2. Implement a new insert statement that contains this new clause. This is quite simple, you basically just combine a couple of clauses, see for instance `insert.h`

Your new clause is a bit special in that it turns the `insert` into something that can have one or more values. This looks more like the return value of a select. Your new clause needs to inform the statement that it changes the behavior of `insert`.
This is done by specifying `tag::is_return_value` and the `_result_methods_t` template.

I would assume that `select_column_list.h` is closest to what you need. It looks a bit daunting, I know, but again, you mainly need to change a few names/strings in here, I think.

An (albeit much simpler) example of a connector-specific statement can be found in the sqlite connector, see https://github.com/rbock/sqlpp11-connector-sqlite3/blob/master/include/sqlpp11/sqlite3/insert_or.h

It is not going to be trivial, but it is not going to be horribly complex either, I guess.

Let me know if you get stuck, I can try to help.

Cheers,

Roland

**Comment by MatthieuTexier** [comment]
'returning' is already defined in the postresql connector and that's great but not 'on conflict', that would be a nice to have.

**Comment by rbock** [comment]
> 'returning' is already defined in the postresql connector

Cool, and it is added to a postgresql-specific version of `insert` already...

`on conflict` should be a walk in the park in comparison :-)

**Comment by aminaramoon** [comment]
Thanks, I would let you know if we got stuck

**Comment by rbock** [comment]
Documentation is on the wish list I am currently compiling out of "old" issues.
I'll add a specific wish for "Adding missing features" and close this ticket.
