### ISSUE TITLE
Recursive CTE with join

### ISSUE THREAD

**Issue by MatthieuTexier** [rbock/sqlpp11#276]
Hello,
I'm trying to implement this recursive CTE on postgresql:

`WITH RECURSIVE a AS (
SELECT categories.id,categories.parent_id FROM categories WHERE categories.name LIKE('act%') UNION SELECT categories.id, categories.parent_id FROM categories INNER JOIN a ON categories.parent_id = a.id
) SELECT * FROM a`

the CTE part is dynamic so I end up with code like this actually:
`auto select_categories = dynamic_select( db, tb_categories.id,  tb_categories.parent_id ).from( tb_categories ).dynamic_where();`
`for ( const auto &category_name : filter.category_names ) {`
`        select_categories.where.add( tb_categories.name.like( glob_to_like( category_name )));`
`}`
,then I build the CTE
`const auto cte = sqlpp::cte( sqlpp::alias::a ).as( select_categories );`
`const auto sub_categories = cte.union_all( select( cte.id, cte.parent_id ).from( cte ).unconditionally());`
,and use it later
`sqlpp::with(sub_categories)(select( sub_categories.id ).from( sub_categories );`

I did read the Wiki and your answer to issue #226 but I still can't figure out how to implement sub_categories with the join.
I'm sorry to bother you and I hope you can help me.
Best regards.

**Comment by rbock** [comment]
I am not using CTEs outside of the library. Thus, I always need some time to wrap my head around it, too.

I'll come back to you as soon as I can.

Best,

Roland

**Comment by rbock** [comment]
I finally got around to looking into this in more detail. I am afraid the library has two bugs in this area:

Using this table definition:
```
CREATE TABLE tab_category (
        id BIGINT primary key,
        parent_id BIGINT,
        name varchar(255)
);
```
The following _should_ work:

```C++
#include <category.h>

#include <sqlpp11/sqlpp11.h>
#include <tests/MockDb.h>

int main()
{
  constexpr auto tabCat = test::TabCategory{};
  const auto selectCategories = select(tabCat.id, tabCat.parentId).from(tabCat).where(tabCat.name.like("%act%"));
  const auto initialCte = ::sqlpp::cte(sqlpp::alias::a).as(selectCategories);
  const auto recursiveCte = initialCte.union_all(select(tabCat.id, tabCat.parentId)
                                                     .from(tabCat.join(initialCte).on(tabCat.id == initialCte.parentId))
                                                     .unconditionally());
  const auto query = with(recursiveCte)(select(recursiveCte.id).from(recursiveCte).unconditionally());

  ::MockDb::_serializer_context_t printer = {};
  const auto serializedQuery = serialize(query, printer).str();
  std::cout << serializedQuery << '\n';
}
```

However, the `on` is confused and sees missing tables (as can be seen in this static assert message `"from() argument has to be a table or join expression"`.
And if you (illegally) were to replace the `on` with `unconditionally`, you would see that the CTE is not simply represented as `a` but as the initial query.

Fixable, of course, but will take a few more days, I am afraid, as I am a bit short on time, currently.

**Comment by rbock** [comment]
Copied the wrong assert text: `on() condition must not depend on other tables`.
That is the one failing.

**Comment by rbock** [comment]
Turns out the fix less is complex when not thinking too hard about it :-)

I pushed to develop. I tested with the code above (using postgresql). I also added a test to `tests/With.cpp`.

Please give it a try and let me know.

**Comment by MatthieuTexier** [comment]
Thanks Rolland, that looks good.
I'm in holidays for a week (without computer :-))
I will test ASAP and let you know.

**Comment by MatthieuTexier** [comment]
Thank you Roland, it works fine :-)

**Comment by rbock** [comment]
Thanks for the feedback!
