### ISSUE TITLE
Missing assert?

### ISSUE THREAD

**Issue by matthijs** [rbock/sqlpp11#281]
I expected a static_assert when trying the following.
```c++
model::TabFoo foo;
model::TabBar bar;

auto sql = sqlpp::select(foo.gamma, bar.c_int).from(foo).unconditionally();
```

**Comment by rbock** [comment]
Hi,

you will see a static_assert, once you try to execute the query.

In the current code, the library cannot know if this will be used standalone or as a sub-select. The latter might be perfectly valid if the "outer" query supplies `bar`.

Makes sense?

Cheers,

Roland

**Comment by matthijs** [comment]
Yes, that makes sense.
