### ISSUE TITLE
Oracle connector issues

### ISSUE THREAD

**Issue by tendriu** [rbock/sqlpp11#282]
Hello,

I'm currently preparing Oracle connector and I have some problems. 
First with **offset** and **limit** keywords.
Oracle support these functionality in a little different way.
Eg:
**LIMIT**:  `FETCH NEXT [N] ROWS ONLY`
**OFFSET**:  `OFFSET [N] ROWS`
I solve these issues by specialize structture:
 `serializer_t<oracle::serializer_t, dynamic_limit_data_t<Database>>` 

The second problem, for Orace, order of theses command should be reversed.
It means, first "OFFSET" and then "LIMIT".
How I can do this?
I have found template `<typename Database>  using blank_select_t = ...` in select.h file.

Many thanks.
Andrzej Tatar

**Comment by rbock** [comment]
Hi Andrzej,

Regarding the first part: Awesome! Specializing the serializer to get a different representation is the right way to do it.

For the second problem I spontaneously see two options:
  - write an oracle-specific version of the select-statement and specialize the serializer to reject the generic one.
  - specialize the statement serializer to swap limit and offset before serializing them.

The second option is harder to do and requires more template magic, but I think that it will pay off in the long run.

Best,

Roland

**Comment by tendriu** [comment]
Thank you for the quick answer.

I have another problem, this time with **dynamic_where**. 
In default is adding boolean value:
`return dynamic_where(::sqlpp::value(true)); `(where.h, line:344)
and dynamic query generate sql like this: `"... WHERE 1 ..."`.
This is correct for eg. MySQL but not for Oracle.
I made a workaround by specialize:
```
inline auto serialize(const sqlpp::boolean_operand& t, oracle::serializer_t& context)
{
	context << "(1=1)";
}
```

It works, but it seems that is wrong way.

**Comment by rbock** [comment]
We could replace `::sqlpp::value(true)` with something else that indicates that there is no condition, which would allow us to handle it more cleanly in the serializer.

**Comment by tendriu** [comment]
Yes, very good idea. 
It will be very nice if you make this change.

Best regards

**Comment by rbock** [comment]
Hi,

I just pushed the respective commit. This is much cleaner, indeed.

Note: I am closing this ticket. Please open a new one if you run into more issues with writing the Oracle connector.

Thanks and best regards,

Roland
