### ISSUE TITLE
No member "update_list" in "dynamic_update()" ?

### ISSUE THREAD

**Issue by zhuangyan-stone** [rbock/sqlpp11#284]
`auto u = sqlpp::dynamic_update(db,  table).dynamic_set().where(table.id = 1ULL);
   u.update_list.add(table.field = 1);
`

Would got a compile error : "no member named update_list in ……"

Howto use "dynamic_update()"? 
thanks.

**Comment by rbock** [comment]
```C++
auto u = sqlpp::dynamic_update(db, table).dynamic_set().where(table.id = 1ULL); 
u.assignments.add(table.field = 1);
```
