### ISSUE TITLE
limit MUST have "unsigned " parameter

### ISSUE THREAD

**Issue by zhuangyan-stone** [rbock/sqlpp11#285]
`auto rows = db(select(t.id).from(t).unconditionally().limit(3U)); // <-- 3U
bool rows.empty(); // <--- OK, rows have  a member-function named "empty()"
`
BUT:
`auto rows = db(select(t.id).from(t).unconditionally().limit(3)); //<-- 3
bool rows.empty(); // <--- FAIL, rows now haven't  a member-function named "empty()"
`

Is this a bug or a design feature?

**Comment by rbock** [comment]
In the compiler error messages you will see:

```
error: static assertion failed: argument for limit() must be an unsigned integral expressions
```

Negative values for `limit` or `offset` would be strange, wouldn't they?
