### ISSUE TITLE
two table join - error 'attempting to reference a deleted function'

### ISSUE THREAD

**Issue by RotateAt60MPH** [rbock/sqlpp11#287]
Hi there.

I have two tables 'Cohort' and 'Learner'.  'Cohort' has a one-to-many relationship to 'Learner'.

Table Cohort:
id (PK)
name

Table Learner:
id (PK)
name
cohort_id (FK)

In one retrieve, I am trying to retrieve all Learners that have a cohort id = to number.  This is what I tried:

```
// needed because both tables have an 'id' and 'name' column?
SQLPP_ALIAS_PROVIDER(cId);
SQLPP_ALIAS_PROVIDER(cName);
...
void test::testJoin( int id )
{
  const auto a = Cores::Cohort{};
  const auto b = Cores::Learner{};

  auto rows = db(select(a.name.as(cName), a.id.as(cId), all_of(b)).from(a.join(b).on(a.id == b.cohortId)).where( a.id == id );

  for ( const auto& row : rows )
  {
    ...
  }

}
```

But it will not compile. I get a 'attempting to reference a deleted function' error.  Looks like the function is marked as deleted in result_row.h.  If that's the case, how should the select be set up?

Any suggestions appreciated!

**Comment by rbock** [comment]
The code looks OK to me, except the missing closing brace of `db(...)`.

If that should be just a copy/paste mistake ant the problem persists: Could you paste the table definitions (so that I could run it through the ddl2cpp) and a short piece of code that should compile (see https://stackoverflow.com/help/minimal-reproducible-example)?

Thanks,

Roland

**Comment by RotateAt60MPH** [comment]
Weird.  I rebuilt the Visual Studio pre-compiled header and I updated sqlpp11 from vcpkg and the problem went away.  Some bizarre gremlin in there somewhere.  Closing issue.  Thanks for the attention.

**Comment by rbock** [comment]
Thanks for the follow-up :-)
