### ISSUE TITLE
Trim in where

### ISSUE THREAD

**Issue by tendriu** [rbock/sqlpp11#288]
Hi,

Sorry for my stupid question, but how I can prepare query as belove:

`db(select(all_of(dev)).from(dev).where(sqlpp::trim(dev.Code) == "ABC"));`

Current version is not able to compile due **sqlpp::trim** function.
I didn't find example for this.

Best regards
Andrzej

**Comment by rbock** [comment]
Hi Andrzej,

Thanks for asking. Not a stupid question at all. It was a subtle bug in the trim function (it was configured to be treated as an aggregate function like `COUNT`. It is fixed on develop now.

Please let me know if it works out for you.

Best,

Roland

**Comment by tendriu** [comment]
Thank you so much, it works now.

Best
Andrzej
