### ISSUE TITLE
Question: is possible to use query or result set as not 'auto'?

### ISSUE THREAD

**Issue by RotateAt60MPH** [rbock/sqlpp11#289]
Hi All.

It seems like the most common pattern to read and iterate through a database query is this:

```
    auto rowSet = db(select(...) );
    for ( const auto& row : rowSet ) { <do stuff with 'row'> }

```

The query and the result set have to be declared as 'auto' because the definitions of these objects are very complex and dependent on the columns you are selecting.

But I am wondering if there is any way to add helper 'default column' typedefs when you convert DDL script into proxy classes.  Ultimately, it would be a lot cleaner to be able to pass around retrieved rows, of a certain select column profile, in order to centralize row processing.  

I hate to scrape the definition out of the debugger and create typedefs manually since if roland changes the underlying sqlpp11, it could break all those typedefs.  Kinda fragile.

**Comment by Erroneous1** [comment]
I think the best thing to do would be to construct something like a `std::vector<std::tuple</*data types*/>>` or your own class and pass that around. The only issue then would be that it would need to fill the data at once instead of one row at a time.

**Comment by rbock** [comment]
> I think the best thing to do would be to construct something like a `std::vector<std::tuple</*data types*/>>` or your own class and pass that around.

Or make `row_t<...>` convertible to `std::tuple<...>`. Easier said than done, but I am actually thinking about back-porting the way columns are represented in sqlpp17. The types would still be non-trivial, but converting to tuple would be considerably simpler.

**Comment by Erroneous1** [comment]
Being able to use a tuple would be interesting. Would that let you use the C++17 structured bindings to do something like:
```c++
for(auto [ID, Name, ContactName, Address, City, PostalCode, Country] : db(query)) {
}
```
That would be very nice. Personally I think making your own structure for a specific select makes sense when you want to pass it back and forth across an interface.
```c++
struct Customer {
  std::uint64_t ID;
  std::string Name;
  std::string ContactName;
  std::string Address;
  std::string City;
  std::string PostalCode;
  std::string Country;

  Customer() noexcept = default;

  template<class RowT>
  Customer(RowT&& row)
    : ID{row.customer_id}
    , Name{std::move(row.customer_name)}
    , ContactName{std::move(row.contact_name)}
    , Address{std::move(row.address)}
    , City{std::move(row.city)}
    , PostalCode{std::move(row.postal_code)}
    , Country{std::move(row.country)}
  {}
};
```

**Comment by rbock** [comment]
If there were specializations for `std::tuple_size`, `std::tuple_element` and `get<I>(const Row&>`, then structured binding would be possible.

I also prefer converting rows into some struct you want to pass around, too.

BTW: In your code, you should use `std::forward` instead of move.

**Comment by zhengminlai** [comment]
> Hi,
> 
> `I have made similar functionality:
> 
> ```
> template<class Db, class... Args>
> class SqlppResultDeduction
> {
> 	template<class... TC>
> 	struct ColumsDeduction
> 	{
> 		template<class Col, typename std::enable_if<!std::is_base_of<sqlpp::table_base_t, Col>::value, int>::type = 0>
> 		static const auto& GetColumns(const Col&)
> 		{
> 			return std::declval<Col>();
> 		}
> 
> 		template<class... Cols>
> 		static auto GetColumns(const sqlpp::table_t<Cols...>& tab)
> 		{
> 			return sqlpp::all_of(tab);
> 		}
> 
> 		using Type = typename sqlpp::detail::make_select_column_list_t<void, decltype(GetColumns(std::declval<TC>()))...>::_nodes;
> 	};
> 
> 	template<class... Cols>
> 	static auto GetResult(const sqlpp::detail::type_vector<Cols...>&)
> 	{
> 		using selectType = decltype(sqlpp::select(std::declval<Cols>()...));
> 		using char_result_type = decltype(std::declval<Db>().select(std::declval<selectType>()));
> 
> 		return sqlpp::result_t<char_result_type, sqlpp::result_row_t<Db, sqlpp::make_field_spec_t<selectType, Cols>...>>();
> 	}
> public:
> 	using Type = decltype(GetResult(std::declval<typename ColumsDeduction<Args...>::Type>()));
> };
> 
> template<class Db, class... Args>
> using SqlppResult = typename SqlppResultDeduction<Db, std::decay_t<Args>...>::Type;`
> ```
> 
> And you can use it like this:
> 
> ```
> `SqlppResult<sqlpp::mysql::connection, DbModelType> GetAll()
> {
>      sqlpp::mysql::connection con;
>      const DbModelType model{};
> 
>      return con(sqlpp::select(all_of(model)).from(model).unconditionally();
> }`
> ```
> 
> Regards

this doesn't work...

**Comment by Erroneous1** [comment]
I think what you'd want to do to accomplish this is something that stores all of the results when it is constructed so that you don't have to worry about the entire template of the result_t. Many database libraries get around large and complex templates by using inheritance or unions to store results, while sqlpp11 only stores the actual data that would be used by that specific column.

Please see [my earlier reply](https://github.com/rbock/sqlpp11/issues/289#issuecomment-528852364) on this subject. Here you can see how you might construct a specific entity named `Customer` from whatever the result actually is. This object could then be easily passed around across libraries. You could also make a static function to make a vector of customers like so:

```c++
class Customer {
...
template<class Result>
static std::vector<Customer> all_rows(Result&& res)
{
    std::vector<Customer> ret;
    ret.reserve(res.size());
    for(auto&& row : res)
        ret.emplace_back(row);
    return ret;
}
};
```

Without c++14's copy elision you might want to do `return std::move(ret);` instead.

**Comment by zhengminlai** [comment]
I have explained my concern in detail under this issue: 
https://github.com/rbock/sqlpp11/issues/380
Thank you so much for help:)
