### ISSUE TITLE
One letter mistake in wiki

### ISSUE THREAD

**Issue by rajkod** [rbock/sqlpp11#29]
Sorry if it's too much trivial :)

In https://github.com/rbock/sqlpp11/wiki/NULL ( tvin() explanation ):

select(all_of(tab)).from(tab).where(tab.alpha == sqlpp::tin(a)); 
=>
select(all_of(tab)).from(tab).where(tab.alpha == sqlpp::tvin(a));

**Comment by rbock** [comment]
Thanks, fixed it :-)
