### ISSUE TITLE
discuss about model, migration and object association support(inspired by Ruby on Rail's Active Record)

### ISSUE THREAD

**Issue by joshuafc** [rbock/sqlpp11#290]
This is a cool project!
I mainly use C++, and have used Ruby on Rails to write a simple website backend. I was impressed by its [`ActiveRecord`](https://guides.rubyonrails.org/active_record_basics.html).

It define database changes(add/remove/modify tables/columns) into migrations. Every migration is a file, with a version number in its filename. Here is a sample of its content:
```
class CreatePublications < ActiveRecord::Migration[5.0]
  def change
    create_table :publications do |t|
      t.string :title
      t.text :description
      t.references :publication_type
      t.integer :publisher_id
      t.string :publisher_type
      t.boolean :single_issue
      t.timestamps
    end
    add_index :publications, :publication_type_id
  end
end
```
 A version number also saved in database to indicate the database version. When we run `migrate` command,  migrations which version number bigger than the one at database will be run in order. So we can upgrade database compatible with out additional work.

The `ActiveRecord` can also "embed" objects by specify their relationships.

> In Rails, an association is a connection between two Active Record models. 
> Rails supports six types of associations:
> belongs_to
> has_one
> has_many
> has_many :through
> has_one :through
> has_and_belongs_to_many

With that, we can easy to write program like 
```
    // get name of author of the book
    std::string author_name = book.author().name()
    // find all books that have same author with the book . 
    std::vecotr<book> bks = book.author().books ()
    // find the owner's name of the group which the author of the book belong to.
    std::string authors = book.author().group().owner().name()
```
rather than 
```
    auto author = Author::find(book.author_id);
    std::string author_name = author.name;

    auto author = Author::find(book.author_id);
    std::vecotr<book> bks = Book::find_all(author.author_id)

    auto author = Author::find(book.author_id);
    auto group = AuthorGroup::find(author.group_id)
    auto owner = User::find(group.owner_id)
    std::string name = owner.name
```

Is there have some plan, or Is there someone interested to use database like that.:
- 1. save database changes (add/remove/modify tables/columns) to migration file.
- 2. write a tool to load migration files in version order and run it if its verson number large than database one.
- 3. write a tool to load migration files in version order and generate c++ headers by the database model described by migration files. Support association like above examples.

I think it would be very convenient to operate the database in this way. Welcome to discuss.

**Comment by rbock** [comment]
Hi Joshua,

Thanks for reaching out!

I am quite sure this would be interesting to quite a number of people. I consider it out of scope for sqlpp11, but I think it would be possible to build this kind of functionality on top of it.

Maybe a great project for yourself?

Cheers,

Roland

**Comment by joshuafc** [comment]
Thanks for your suggestion.

I will do some technical verification, and try to start the project if I am sure I can hold it.

In additional, does sqlpp11 support association between tables now? 
If I defined table struct `TableA`,  can I write `using _value_type = TabelA;` at some column of table b.

**Comment by rbock** [comment]
> In additional, does sqlpp11 support association between tables now?

No, it has no notion of associations.

**Comment by rbock** [comment]
Closing this issue (hoping that you take up the task, of course :-) )
