### ISSUE TITLE
Inserting to a mysql 'datetime' column

### ISSUE THREAD

**Issue by RotateAt60MPH** [rbock/sqlpp11#292]
I have a mysql table that looks like this:

```
CREATE TABLE `revision` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `created_at` datetime DEFAULT NULL,
  `updated_at` datetime DEFAULT NULL,
) 

```
And I'm trying to insert a record, but cannot get the assignment to the datatime fields right.  
Here's my code snippet that I adapted from tests/DateTime.cpp

```
  const auto table = Cores::Revision{};
  sql::connection db(_pParent->GetDbConnection());
  db(insert_into(table).set(
    table.createdAt = std::chrono::system_clock::now(),
    table.updatedAt = std::chrono::system_clock::now()
  ));

```
I keep getting the following error:

`1>d:\devel\include\vcpkg\installed\x64-windows\include\sqlpp11\column.h(90): error C2338: invalid rhs assignment operand
`

What should the datatype be to assign to a datetime column?

Thanks!!

**Comment by RotateAt60MPH** [comment]
Ok - figured it out.  The problem had to do with a third party library, which stupidly playing around with typedefs around std::chrono::system_clock.  Removing this library fixed the problem.  Closing this issue.

**Comment by RotateAt60MPH** [comment]
Hmm, I fixed the problem with the library and updated to the latest version of sqlpp11, via vcpkg, and the problem has come back with a different system_clock.  So, I'd like to reopen this with the following snippet:

```
  db(insert_into(table).set(
    table.createdAt = ::sqlpp::chrono::time_of_day(std::chrono::system_clock::now()),
    table.updatedAt = ::sqlpp::chrono::time_of_day(std::chrono::system_clock::now())
  ));
```

**Comment by rbock** [comment]
`time_of_day` gives you a, well, time of day, not a `date + time`. In MySQL lingo, you would need a `TIME` column for that.

For the given column, you would want a `std::chrono::timepoint`. For instanc, you could use

```
table.createdAt = std::chrono::system_clock::now()
```

**Comment by rbock** [comment]
Together with #293 I consider this issue closed. Please feel free to re-open, if you think otherwise :-)

**Comment by Erroneous1** [comment]
For a SQL `TIME` column I think you'd want a [date::time_of_day](https://howardhinnant.github.io/date/date.html#time_of_day).  `std::chrono::system_clock::timepoint` really should be used for specific point in time. You'd make one from `std::chrono::duration` using `date::make_time(Duration)` so for the time right now in UTC:
```c++
auto tp = std::chrono::system_clock::now();
auto dp = date::floor<date::days>(tp);
auto time = date::make_time(tp - dp);
```
