### ISSUE TITLE
Document TabDateTime table DDL in sample.sql

### ISSUE THREAD

**Issue by RotateAt60MPH** [rbock/sqlpp11#293]
It would be useful if the CREATE TABLE for 'TabDateTime' could be added to tests/sample.sql so we can follow the various tests in tests/DateTime.cpp that use it.

**Comment by rbock** [comment]
Good point!

This also showed that there is a case missing in the `ddl2cpp` script: `TIME` needs to be converted to `::sqlpp::time_of_day`. Maybe nobody is using that? It is a rather odd data type, I think.

Fix is committed and pushed to develop.
