### ISSUE TITLE
Serialization operator "-" with negative number.

### ISSUE THREAD

**Issue by mikurys** [rbock/sqlpp11#294]
There is some problem with serialization queries with operator "-" with negative numbers.
For example, this code:
```c++
const int minusOne{ -1 };
auto select{ sqlpp::select((table.RID-minusOne).as(sqlpp::alias::a)).from(table) };
```
Generates sql like:
```sql
SELECT (TABLE.RID--1) AS a FROM TABLE
```
Where two minus ("--") means comment in sql.
Adding space after first minus or adding parenthesis will solve the problem.

**Comment by rbock** [comment]
Very good find! I'll fix it asap.

**Comment by rbock** [comment]
I pushed a fix on develop, please check.

**Comment by mikurys** [comment]
Now operator- as well as operator-= is working great on version bb77cc14591c8f2dc4b40d09def57eb76ec95ae8.
Thanks
