### ISSUE TITLE
Fetch result problem.

### ISSUE THREAD

**Issue by giorgiozoppi** [rbock/sqlpp11#296]
My problem is now that after the creation and call from stored procedure, it gets called correcty,
i need to pipe the result and fetch the.
 std::string rate_executor::create_query_string() const
  {
      std::string
      baseQuery1{"SELECT CONCEP as ConceptCode"};
      std::string baseQuery2{""};
      std::string baseQuery3{" FROM spORLWebDispoTarifas(@Comisionista = '%1%',@FecSalida= '%2%',@HSalida= '%3%',"};
      std::string baseQuery4{" @FecRetorno='%4%',@HRetorno= '%5%',@Oficina= '%6%',@OficinaRet= '%7%',@OnewayAuto = 1,@FecRegistro = '%8%',@NoStopSell = '%9%')"};
      return baseQuery1 + baseQuery2 + baseQuery3 + baseQuery4; 
  }
std::string rate_executor::prepare_quote_query (const model::rate_quotation & quotation) const
{
    // boost format is not thread safe
    std::lock_guard <std::mutex> format_guard(_format_mutex);
    std::string base = create_query_string();
    int topsell = quotation.ignore_stop_sell ? 1 : 0;
      auto query =
      boost::format (base) % quotation.broker_code % quotation.departure_date % quotation.departure_hour % quotation.return_date % quotation.return_hour 
      % quotation.pickup_office_code % quotation.drop_office_code % quotation.registration_date % topsell;
    return  boost::str(query);
}
  void rate_executor::rate (const model::rate_quotation & quotation, std::function<void(const std::vector<model::quotation_details>&)> func)
  {
    rating::RateTable table;
    std::chrono::time_point <std::chrono::system_clock > startTimer;
    if (_enable_perfcounters)
    {
	    startTimer = std::chrono::system_clock::now ();
    }
    auto  cleanup = sqlpp::custom_query (sqlpp::verbatim ("COMMIT"));
    auto querystring = prepare_quote_query (quotation);
    std::cout << "QUERY TO BE EXECUTED: " << querystring << std::endl;
    auto query= sqlpp::custom_query (sqlpp::verbatim (prepare_quote_query (quotation)));
    (*_db) (cleanup);
    **auto result2 = ((*_db) (query)).with_result_type_of(select(all_of(table)));**

The above line is wrong.
 /home/giorgio/redis/redisperformance/src/rate_executor.cpp: In member function ‘void rating::rate_executor::rate(const model::rate_quotation&, std::function<void(const std::vector<model::quotation_details>&)>)’:
[build] /home/giorgio/redis/redisperformance/src/rate_executor.cpp:82:38: error: request for member ‘with_result_type_of’ in ‘(&((rating::rate_executor*)this)->rating::rate_executor::_db.std::unique_ptr<sqlpp::odbc::connection>::operator*())->sqlpp::odbc::connection::operator()<sqlpp::custom_query_t<void, sqlpp::verbatim_t<sqlpp::no_value_t> > >(query)’, which is of non-class type ‘size_t’ {aka ‘long unsigned int’}
[build]       auto result2 = ((*_db) (query)).with_result_type_of(select(all_of(table));
[build]                                       ^~~~~~~~~~~~~~~~~~~
[build] /home/giorgio/redis/redisperformance/src/rate_executor.cpp:82:72: error: ‘table’ was not declared in this scope

Should i put in sqlpp::verbatim_t the rating::RateTable?

**Comment by rbock** [comment]
Hi Giorgio,

Can you do something about the formatting? This is really hard to read.

`table` seems to be declared just a few lines above the error message, so I am assuming that the code and the reported error message do not really correlate?

You should call `with_result_type_of` on the query, not on the result.

Hope that helps a bit already.

Best,

Roland

**Comment by giorgiozoppi** [comment]
Dear all,
Ok at end was the odbc support still very green.  Since i am using sybase i need odbc. The interface of connection should allow to the user to format the queries using paramteres. It forces directly to the usage of your kind of linq language, some user might like more freedom. It would be nice to have something similar:
auto queryText = "Select * from Cats where Color =%Color% and Age > :Age";
auto dynamicParameters = new sqlpp11::dynamic_params<string, int>({{ "Color", "Blue },
												  { "Age", 2 }}});
auto prepared = db.prepare(queryText,dynamicParameters);
for(auto && row : db(prepared))
{
std::cout << row.color << std::endl;
}
Is it feasible? how is it difficult to do that?

**Comment by rbock** [comment]
Hi,

Can you invest at least a tiny amount of effort in formatting the code in your question?

Also, I am totally lost what this is about? Does this have to do anything with the original issue? Or did you maybe want to post this somewhere else entirely? How does ODBC play into this?

What is your beef with the current interface for prepared statements (and parameters)?

Thanks,

Roland

**Comment by giorgiozoppi** [comment]
Ok, I mixed two issues in one.  Forget the odbc stuff. I close this and opened one more centered in the question.
