### ISSUE TITLE
New generic inteface feasibility

### ISSUE THREAD

**Issue by giorgiozoppi** [rbock/sqlpp11#297]
Hello Roland,
The second part of my previous question was about the feasibility of a more generic 
interface not binded to your primitives.  The rationale for this is that it would be lead to 
more flexibilty and it will allow any kind of queries like in C# world with dapper.
https://github.com/StackExchange/Dapper
In dapper we have:
```
var sql = "SELECT * FROM Invoice WHERE Kind IN @Kind;";
using (var connection = My.ConnectionFactory())
{
	connection.Open();
	var invoices = connection.Query<Invoice>(sql, new {Kind = new[] {InvoiceKind.StoreInvoice, InvoiceKind.WebInvoice}}).ToList();
}

```
In a similar world would be:

```
auto queryText = "Select * from Cats where Color =%Color% and Age > :Age";
auto dynamicParameters = new sqlpp11::dynamic_params<string, int>({{ "Color", "Blue },
{ "Age", 2 }}});
auto prepared = db.prepare(queryText,dynamicParameters);
for(auto && row : db(prepared))
{
std::cout << row.color << std::endl;
}
```
Is it feasible? how is it difficult to do that?

**Comment by giorgiozoppi** [comment]
Hi Roland,
Uhm looks like a constexpr to be parsed and enforce but i dont have yet enough spare cycles to do.

**Comment by rbock** [comment]
Closing this as out of scope for sqlpp11 (but could be a nice project)

**Comment by data-man** [comment]
@giorgiozoppi
Try [sqlite_orm](https://github.com/fnc12/sqlite_orm).
