### ISSUE TITLE
how to conditionally insert a null or FK value?

### ISSUE THREAD

**Issue by RotateAt60MPH** [rbock/sqlpp11#299]
Hi all.

I have a mysql table with an optional foreign key that I'm trying to insert into.  I can't figure out a way how to code the insert when I need to insert a NULL, if there foreign key relationship is not there and set the foreign key column to a value if the relation is there.

The only way I've found this to work is to do an INSERT, following by a conditional UPDATE - setting the foreign key column.  Obviously, this isn't efficient.

With a stock 'insert_into' does anyone have any hints on how I might do this?

Thanks!

**Comment by rbock** [comment]
Hi,

You can use `value_or_null`:

```
sqlpp::value_or_null(7); // gets interpreted as 7
sqlpp::value_or_null<sqlpp::integral>(sqlpp::null); // gets interpreted as "integral" NULL
```

Or you can use `tvin` (stands for "trivial value is null"):

```
sqlpp::tvin(7); // gets interpreted as 7
sqlpp::tvin(0); // gets interpreted as NULL
sqlpp::tvin("seven"); // gets interpreted as 'seven'
sqlpp::tvin(""); // gets interpreted as NULL
```

(I am thinking about deprecating tvin, though, it is too implicit)

Or you use `case_when`:

```
sqlpp::case_when(condition).then(7).else_(sqlpp::null); // interpreted as SQL case expression
```

My recommendation is `value_or`.

Best,

Roland

**Comment by RotateAt60MPH** [comment]
Excellent.  Thanks!
