### ISSUE TITLE
Generic data member accessor with std::function to comparision in when statement

### ISSUE THREAD

**Issue by carloscbl** [rbock/sqlpp11#301]
Hi!
Nice Work and looking for the Cpp17 version!

i got user_exists, to get user existence, but i wanted to generalized in gen_exists by capturing type of table T and data_member_accesor by calling like this:

```cpp
using test_prot::Users;
std::function<string(test_prot::Users)> data_member = &Users::username;
gen_exists<test_prot::Users>(username, data_member);
```
So i would do the comparison with the correct column for generic tables like in:

> where( data_member_accessor(table) == unique_val )

```cpp
template<typename T>
bool gen_exists(string unique_val, std::function<string(T const&)> data_member_accessor){
    auto & db = mysql_db::get_db_lazy().db;
    T table;
    if (!db(select(table.json).from(table).where( data_member_accessor(table) == unique_val )).empty()){
        return false; //Already exists;
    }
    return true;
}

bool user_exists(string username){
    auto & db = mysql_db::get_db_lazy().db;
    test_prot::Users usr;
    if (!db(select(usr.json).from(usr).where(usr.username == username )).empty()){
        return false; //Already exists;
    }
    return true;
}
```

But im looking in the generated code and there is some nesting and im loosing it.
How would it be?

Much thanks!

**Comment by rbock** [comment]
Hi,

I am a bit confused by this line:

```
std::function<string(test_prot::Users)> data_member = &Users::username;
```

What is the string doing there? Also, the column type has a call operator, but this seems overkill in Age of Lambda.

How about the following:

```
template<typename T>
auto get_data_member = [](){};

template<>
auto get_data_member<Users> = [](){ return Users{}.username; };
```

Best,

Roland

**Comment by carloscbl** [comment]
Wohaa! works perfectly, much much thanks!
Closing this!
