### ISSUE TITLE
Contribute to wiki :/

### ISSUE THREAD

**Issue by carloscbl** [rbock/sqlpp11#304]
Hi!
Seems in the wish-list to improve wiki contributions.

For now i will paste here:
**Select.md** at the end:
## JSON reading as currently unsupported feature

```C++
void read_db_json()
{
    auto &db = mysql_db::get_db_lazy().db;
    std::stringstream sql;
    sql << "SELECT json->>\"$.username\" FROM users";

    auto statement = sqlpp::custom_query(sqlpp::verbatim(sql.str()))
                         .with_result_type_of(sqlpp::select(sqlpp::value("username").as(sqlpp::alias::a)));

    for (const auto &row : db(statement))
    {
        std::cout << "ID: " << row.a << std::endl;
    }
}
```
------------------
**Remove.md** at the end:
## Removing using multiple tables as condition:

```C++
test_sqlpp::Users usr;
test_sqlpp::UsersForms usr_forms;
test_sqlpp::Forms form_;

db(remove_from(usr_forms).using_(usr, form_, usr_forms).where( 
    usr_forms.iduser == usr.id 
    and usr.username == username 
    and usr_forms.idform == form_.id
    and form_.name == form_name
    ));
```

**Comment by rbock** [comment]
Thanks! I'll add that, soon.

**Comment by rbock** [comment]
I added the suggested text for `remove`. Thanks again.

However, I am a bit confused by the select example. Wouldn't something like this be easier?

```C++
    auto statement = sqlpp::select(sqlpp::value("json->>\"$.username\"").as(sqlpp::alias::a))
           .from(users)
           .unconditionally();
    for (const auto &row : db(statement))
    {
        std::cout << "ID: " << row.a << std::endl;
    }
}
```

Untested.

**Comment by carloscbl** [comment]
It is resulting in "SELECT 'json->>\"$.username\"' AS a FROM users", note the ' ',
and is returning: json->>"$.username"
That way would be more practical and easier, but can we get ride of the single quotes' '?
without them it works perfectly

regards!

**Comment by rbock** [comment]
Sorry, my bad. This should work, though (you were very close yourself):

```C++
select(sqlpp::verbatim(R"--(json->"$.username")--").as(sqlpp::alias::a))
   .from(users)
   .unconditionally();
```

**Comment by carloscbl** [comment]
`MySQL debug: Executing: 'SELECT json->>"$.username" AS a FROM users'
MySQL debug: Constructing result, using handle at 0x5555558a2060
MySQL debug: Accessing next row of handle at 0x5555558a2060
ID: NULL
`
in the debuger "a" is empty, even if the expresion generated is correct
Doesn't bind correctly from a verbatim maybe?

**Comment by rbock** [comment]
Here we go. This time I tested :-)

```
  select(
    sqlpp::verbatim<sqlpp::text>(
       R"--(JSON_UNQUOTE(JSON_EXTRACT(data, "$.key")))--")
       .as(test::value))
     .from(tab)     
     .unconditionally();
```
The path operators (`->` and `->>`) don't seem to work with alias names, which is why I am using the JSON functions.

A commit that demonstrates the functionality in a test will follow, soon.

**Comment by rbock** [comment]
Documentation has been moved to `docs/`
