### ISSUE TITLE
Using Y2038-unsafe call

### ISSUE THREAD

**Issue by carloscbl** [rbock/sqlpp11#307]
Hi,
I was passing cpp check on my repo and got:
"select is Y2038-unsafe"
For each sqlpp::select used, no exception.
I think this is related with use 32 bit timers of any kind, for example 
```C++
time_t to_ = system_clock::to_time_t(interval.to);
    cout << ctime(&to_) << endl;
```

ctime is marked with the same problem.

Best regards!

**Comment by rbock** [comment]
Hi, 

I'd say this is likely to be a false positive.

Cheers,

Roland

**Comment by carloscbl** [comment]
Perfect!
Thanks!
