### ISSUE TITLE
connection pool?

### ISSUE THREAD

**Issue by lsj3210** [rbock/sqlpp11#308]
Does sqlpp11 support a connection pool? What do I need to do?

**Comment by MacDue** [comment]
It does not seem to right now. There is some very old connection pool code left in the repo but it does not seem to compile (or if it does it seems to be specific to the mysql connector). You might have more luck though.

**Comment by MacDue** [comment]
I found that if you fix this line in `connection_pool.h`: https://github.com/MacDue/sqlpp11/commit/2240d3d0894a570792767172cd9cf59e1d45d89e, add `is_valid()` (e.g https://github.com/MacDue/sqlpp11-connector-postgresql/commit/4499c9f01ddd2fd512a2f094a458346c07970562) to your connectors connection implementation, and explicitly initialize the templates e.g. 
```cpp
    static auto dbpool = sqlpp::make_connection_pool<
      sqlpp::postgresql::connection_config,
      sqlpp::reconnect_policy::auto_reconnect,
      sqlpp::postgresql::connection>(dbconfig, pool_size);
```
Then it will compile (& run), but I don't know if it's any good (for example I can't see where the re-connection policy is used -- but maybe I'm blind).

**Comment by rbock** [comment]
See #397
