### ISSUE TITLE
Support for ALTER TABLE in ddl2sql

### ISSUE THREAD

**Issue by RelayrMA** [rbock/sqlpp11#311]
I'm just starting with sqlpp11.
I'm going to CREATE all the tables at startup, in case they are not present yet.
But what if I need to add some rows eventually?
The best migration strategy would be to use the same CREATE TABLE as initially but add ALTER TABLE just after it, so it works with no database, old database and up-to-date as well.

But then - I'd like to have a single ddl file used both for sqlpp11 table definitions and for table creations. Which doesn't work now because ddl2cpp doesn't support ALTER TABLE.

Any chance to get this implemented?

**Comment by rbock** [comment]
Hi,

My strategy has always been to manage the table structure outside of the application. For instance, if you want to add a column, you add it to the table (nullable or with default value), then you update the software. Or when you want to drop a column, you first stop using it in the application, then you drop it from the table.

I also maintain the current production table structure separate from the `ALTER TABLE` commands: One file contains the table structure (including a table representing the "version"). In parallel to that, there is a sequence of patch files that migrate the table structure from one version to another.

That being said: I am not sure how `ddl2cpp` could support ALTER TABLE? What would it do with such commands?

Best,

Roland

**Comment by rbock** [comment]
Closing.

ddl2cpp is not going to support ALTER TABLE.
