### ISSUE TITLE
Support for OVER() clause

### ISSUE THREAD

**Issue by MacDue** [rbock/sqlpp11#315]
Would it be possible to get basic support for the OVER() clause at some point?
I'd help (me) out with doing some simple pagination. 

```sql
SELECT hp, COUNT(1) OVER() as total_quests 
from active_quests 
LIMIT 3 OFFSET 1;
```
I'd expect the sqlpp syntax to be something like:
```cpp
 select(active_quest_tbl.hp, count(1).over().as(total_quests))
.from(active_quest_tbl)
.limit(3u)
.offset(1u);
```
I'm interested in implementing it myself, I see that I'd need to implement an expression type `over_t` & an operator `.over()` but I'm kinda unsure on the details of implementation (and stuff like limiting it aggregate functions).

**Comment by rbock** [comment]
Hi,

Wow, I wasn't even aware of `OVER` until this morning. Thanks for pointing me to it :-)

The short answer is: Yes, it would be possible.
See for instance here: https://github.com/rbock/sqlpp11/blob/6d2b64eff9ecbed300cf8c7d2a50c5dd87ca7d71/include/sqlpp11/aggregate_functions/count.h#L59

As of now, I see two options (there are probably more):

- You can follow this style and let the aggregate functions inherit from another CRTP base class that provides the `over` member function.
- You can add a one-line  `over` member function to each of the aggregate functions, which dispatches to a free `over` function.

In both cases, the `over` function would return a new `over_t<Expression>` object. 

These days I am leaning towards the second option and would start with that free function.

Does that help to get you started? Let me know if you get stuck.

Cheers,

Roland

**Comment by MacDue** [comment]
Thanks, I managed to get a basic implementation working :).
I went with the first method as I preferred the resulting syntax a little more -- a closer match to the sql.
#316 

There are more features to over that I've not implemented yet though (that could be tackled in the future too).
