### ISSUE TITLE
[Question] Reference for adding custom function

### ISSUE THREAD

**Issue by faizol** [rbock/sqlpp11#318]
Hi,
 I just found out about this library a couple weeks ago and thank you so much for this wonderful library. 

I have a couple questions about the templates and hoping that anyone could give me a heads up on where I can find closest references/examples in order to do these
1) to include nested functions in insert, for example;
.add(t.gamma = true, t.beta=functionA("cheesecake", functionB("approved")));

2) to use function in select statement roughly like this;
select (t.gamma == functionC("cheesecake", t.gamma)) where(t.delta ==1))

Thank you.

regards,

**Comment by rbock** [comment]
Hi,

Can you give a more concrete example for those functions (including the resulting SQL)? I don't really get what you are trying to do here.

Best,

Roland

**Comment by faizol** [comment]
Hi,
Thanks for replying to my question. I tried to find examples from the existing functions on how to get it be used as arguments inside other functions, much like this SQL example (algo function as argument inside encrypt function);
1. insert into user_tbl (username, password) values ( 'testuser', encrypt('testpasswd', algo('blowfish')) );

As for the second question, I think I get a gist on how to go about it but still it would be helpful if there is a reference from existing functions that I could refer to.
2. select (password = decrypt('testpasswd', password)) from user_tbl where username = 'testuser';

Thank you so much for your help. Really appreciate it.

regards,

**Comment by rbock** [comment]
Hi

There are essentially two scenarios here:

1. You want to call a C++ function: Then just do it. It just has to return a value that is compatible to with the expression you want to use it in.
2. You want to use an SQL function that is not supported yet. In that case you can either use a quick hack with `verbatim` or you can implement an extension to sqlpp11. Take a look at similar functions. It might look a bit scary at first glance, but it is not that bad (let me know if you need help).

That being said: I guess the example is not real, but just to mention it, you do not want to store encrypted passwords in your database. Salted hashing is what you are looking for.

Best,

Roland

**Comment by faizol** [comment]
Thank you so much for the reply and sorry for couldn't explain the scenario properly. You are right that the scenario is like the second scenario that you've mentioned. I did test the library using verbatim and I could get the right result, but it feels like a hack (like the note to replace verbatim with "unsafe_query").

Just a thought, since this is probably not gonna be the last time someone will ask on what is the best way to support custom functions, especially the more popular the library is. Probably a rough guidelines in the documentation should be enough for the users if they have to add some in-house functions with this library?

Again thank you for taking your time to answer to my question.

Best regards,
