### ISSUE TITLE
unintended 'diagnostic' strings left in code?

### ISSUE THREAD

**Issue by RotateAt60MPH** [rbock/sqlpp11#319]
I recently upgraded to 0.58-3, via vcpkg, and I noticed something new.  I have a console application and when I read from a table I see repeated

my_string:
my_string:
my_string:
my_string:
...

messages displayed to stdout/err.  The statement that generates these messages is fairly innocuous.  I just step over a 'for' statement and I see the messages.

`
  const auto table = Cores::SchedulableCapacity{};
  sql::connection db( _pParent->GetDbConnection() );
  auto s = dynamic_select( db, all_of( table ) ).from( table ).dynamic_where();
  s.where.add( table.id == objInfo.GetId() );

  for ( const auto& row : db( s ) )
`

I don't think this happened in the previous version.  The query seemed to work, though.

**Comment by rbock** [comment]
Hi,

Thanks for the report. This was accidentally introduced into the mysql connector in January 2019. Seems like not too many people are using date-time in mysql...

It should now be fixed (but I am not sure how quickly it will be updated in vcpkg).

Best,

Roland

**Comment by back-marker** [comment]
I also noticed this yesterday. I am on Windows.
vcpkg currently show `0.26` version for mysql connector while `0.27` has the fix and latest seems to be `0.29`. For sqlpp also now i check it show `58.3` although latest is `59`.  Seems something could be wrong with updates?

**Comment by rbock** [comment]
Hi,

Thanks for the report.

I have absolutely no experience with vcpkg. Who can pick this up?

Cheers,

Roland

**Comment by rbock** [comment]
I am guessing this is fixed in vcpkg by now, too. Otherwise, file a bug there :-)
