### ISSUE TITLE
Questions about SQLPP_ALIAS_PROVIDER and referencing aliases inside a SELECT

### ISSUE THREAD

**Issue by Toxe** [rbock/sqlpp11#322]
Hello, I might be missing something here but I have a couple of questions regarding aliases.

First, the code and data I am talking about:

- The whole project itself: https://github.com/Toxe/cpp-sql/tree/921c8eb610db7204ea2531e855566f6197fe37cc
- Here is a simple example program that works without a problem (but that I want to change, more on that below): [sqlpp11_mysql.cpp](https://github.com/Toxe/cpp-sql/blob/921c8eb610db7204ea2531e855566f6197fe37cc/sqlpp11_mysql.cpp)
- A small [database script](https://github.com/Toxe/cpp-sql/blob/921c8eb610db7204ea2531e855566f6197fe37cc/ships.sql) with table and data definitions.

### 1. Where can I call SQLPP_ALIAS_PROVIDER to create a new alias?

So far I was only able to call `SQLPP_ALIAS_PROVIDER` outside of `main()`. Though the documentation and examples make it look like I should be able to call it from somewhere in my code, for example right before my `db(select(...))` calls?

If I change my code in line 87 to look like this...

```cpp
SQLPP_ALIAS_PROVIDER(feet)

for (const auto& row : db(select(ships.id, ships.model, ships.length, (ships.length * 3.2808).as(feet)).from(ships).where(ships.length <= 20))) {
    std::cout << row.id << ": " << row.model << " = " << row.length << " meters (or " << row.feet << " feet)\n";
}
```

...then I get the following errors in Clang and GCC: https://gist.github.com/Toxe/e7501e766872d34788000ecba85ed5f7

These make it sound like declaring an alias inside main() is not possible?  

`../sqlpp11_mysql.cpp:87:1: error: templates cannot be declared inside of a local class`

`../sqlpp11_mysql.cpp:87:1: error: invalid declaration of member template in local class`

### 2. Is it possible to reference an alias in a HAVING or ORDER BY clause?

I have this SELECT (line [84](https://github.com/Toxe/cpp-sql/blob/921c8eb610db7204ea2531e855566f6197fe37cc/sqlpp11_mysql.cpp#L84)):

```sql
SELECT id, model, length, length * 3.2808 AS feet
  FROM ships
 WHERE length <= 20
```

And this code:

```cpp
db(select(ships.id, ships.model, ships.length, (ships.length * 3.2808).as(feet)).from(ships).where(ships.length <= 20))
```

But lets assume that instead I want to execute this, ordering by the alias "feet" (and please ignore the fact that this is just a dumb example and that I can of course order by "length"):

```sql
SELECT id, model, length, length * 3.2808 AS feet
  FROM ships
 WHERE length <= 20
 ORDER BY feet DESC;
```

Would it be possible to change the `select()` code from above to something like this?

```cpp
[..].from(ships).where(ships.length <= 20).order_by(feet.desc()))
```

If I try that I only get a compiler error.

Same problem with a HAVING clause like this:

```sql
SELECT ship_class, COUNT(*) AS col_count
  FROM ships
 GROUP BY ship_class
HAVING col_count > 1
 ORDER BY col_count DESC
```

Would it be possible somehow to write something like this, where I reference the alias in `having()` and `order_by()`?

```cpp
select(ships.shipClass, count(ships.shipClass).as(col_count))
    .from(ships)
    .unconditionally()
    .group_by(ships.shipClass)
    .having(col_count > 1)
    .order_by(col_count.desc())
```

(Sorry for the long post but I wanted to provide enough information.)

**Comment by rbock** [comment]
Hi,

Thanks for the detailed questions.

`SQLPP_ALIAS_PROVIDER` has to be called outside of functions. The macro creates a type which is then used as a template parameter as soon as you use it in a query. C++ demands this type to be defined outside of a function.

Referencing an alias in the manner you are hoping for is not possible as of now. It would be quite a challenge to allow this in the library.

What you can do, of course, is something like

```C++
const auto shipCount = count(ships.shipClass);
select(ships.shipClass, shipCount.as(col_count))
    .from(ships)
    .unconditionally()
    .group_by(ships.shipClass)
    .having(shipCount > 1)
    .order_by(shipCount.desc())
```
(Untested)

If we wanted to allow referencing the, I think it would look like this (which is actually not that different in the C++ code, but would generate the slightly cleaner SQL you are looking for).

```C++
const auto shipCount = count(ships.shipClass).as(col_count));
select(ships.shipClass, shipCount)
    .from(ships)
    .unconditionally()
    .group_by(ships.shipClass)
    .having(shipCount > 1)
    .order_by(shipCount.desc())
```
(Not currently valid code)

I am not sure if the effort of allowing this in the library would be worth it, though.

Best,

Roland

**Comment by Toxe** [comment]
Hey Roland, thanks for the clarifications.

Only being able to use `SQLPP_ALIAS_PROVIDER` at global scope is a bit of a bummer but okay, if that's how it is then that's fine. In that case I might actually switch to using some of the `sqlpp::alias::` aliases or (in a real application) move the code into a small .cpp file of its own, if possible.

As for referencing an alias in HAVING or ORDER BY, I tried your suggestion from above and this works exactly as I wanted:

```cpp
const auto ships_count = count(ships.shipClass);

select(ships.shipClass, ships_count.as(col_count))
    .from(ships)
    .unconditionally()
    .group_by(ships.shipClass)
    .having(ships_count > 1)
    .order_by(ships_count.desc())
```

Which, looking at the debug output, turns into this:

```sql
SELECT ships.ship_class,COUNT(ships.ship_class) AS col_count
  FROM ships
 GROUP BY ships.ship_class
HAVING (COUNT(ships.ship_class)>1)
 ORDER BY COUNT(ships.ship_class) DESC
```

Though looking at the SQL I now wonder how a "real" SQL server would handle aliases.

Does this `SELECT ... COUNT(*) AS foo ... HAVING foo ... ORDER BY foo` actually always turn into `SELECT ... COUNT(*) ... HAVING COUNT(*) ... ORDER BY COUNT(*)`? And the alias is really just syntactic sugar to make the statement more readable and spare my poor fingers a bit of typing? I think I never thought about that, and my days of actually learning SQL are too far gone and maybe I should freshen up a bit at some point. 😉

Though now there is another point I wonder about. Where do for example `count()` and `select()` come from? Why are they in the global namespace? I don't see a `using namespace sqlpp` anywhere and I get that this is for convenience but to be honest I would prefer that they would not get added to the global namespace automatically but only on demand.

**Comment by rbock** [comment]
> Does this `SELECT ... COUNT(*) AS foo ... HAVING foo ... ORDER BY foo` actually always turn into `SELECT ... COUNT(*) ... HAVING COUNT(*) ... ORDER BY COUNT(*)`?

I can't tell for sure. This is a great question for stackoverflow, I think 

What I can tell you is that `count()` and `select()` live in namespace `sqlpp` (actually, the C standard library adds another `select` to the global namespace, but that's their fault :wink:). If you are wondering why you can call them as if they were in the global namespace: Look for ADL (argument dependent lookup) in C++, for instance here: https://en.cppreference.com/w/cpp/language/adl

ADL is why operator overloading works the way it does.

**Comment by Toxe** [comment]
Oooh you are totally right, I didn't think of that!

BTW, now that you pointed out that it is possible to use something like count() outside of select(), which I didn't realize before, I am able to change my `SELECT ... AS feet` example from my initial post to this, which is pretty much what I wanted:

```cpp
const auto feet = ships.length * 3.2808;

select(ships.id, ships.model, ships.length, feet.as(sqlpp::alias::f))
    .from(ships)
    .where(feet <= 100)
    .order_by(feet.desc())
```

Which, funny enough, allows me to (well, kinda) write something _that isn't even allowed in SQL_, because this would be something like `SELECT ... AS feet ... WHERE feet <= 100` but referencing an alias in WHERE is not allowed.

Though this of course actually turns into `SELECT ... (ships.length*3.2808) AS f ... WHERE ((ships.length*3.2808)<=100)` and is not using an alias _at all_ but, you know, the C++ code kinda looks like it and is pretty concise to write.

Aaaaand... I think this covers all my questions. Thanks for your quick help, I'll close this now. 😄
