### ISSUE TITLE
Prepared statement with limit - cannot compile

### ISSUE THREAD

**Issue by ZaMaZaN4iK** [rbock/sqlpp11#323]
Hello.
I use `sqlpp` with `sqlpp11-postgresql-connector`.
I am trying to work with prepared statement with `limit` functionality, but cannot compilke it. 
E.g. this code compiles and works fine:
```
auto preparedSelect = m_connection.prepare(sqlpp::select(settingsTable.name, settingsTable.value)
                         .from(settingsTable)
                         .where(settingsTable.name == parameter(settingsTable.name)));
    preparedSelect.params.name = name;

    auto result = m_connection(preparedSelect);
```
But this isn't:
```
auto preparedSelect = m_connection.prepare(sqlpp::select(settingsTable.name, settingsTable.value)
                         .from(settingsTable)
                         .where(settingsTable.name == parameter(settingsTable.name))
                         .limit(1));
    preparedSelect.params.name = name;

    auto result = m_connection(preparedSelect);
```
with the following error:
```
error: no member named 'params' in 'sqlpp::assert_prepare_statement_t'
```

Did I miss anything?

**Comment by ZaMaZaN4iK** [comment]
Also I've tried without prepared statement - still fails.
```
m_connection(sqlpp::select(userTable.login)
                         .from(userTable)
                         .where(userTable.login == login || userTable.email == email).limit(1));
```
I have this error:
```
error: static_assert failed due to requirement 'integral_constant<bool, false>::value' "argument for limit() must be an unsigned integral expressions"
  SQLPP_PORTABLE_STATIC_ASSERT(assert_limit_is_unsigned_integral,
```

**Comment by rbock** [comment]
Hi,

Well, as the message says, it expects an unsigned integer: Try `.limit(1u)`.

Given that you are the second person to stumble over this in a short period of time, I am tempted to change the requirement.

**Comment by ZaMaZaN4iK** [comment]
@rbock Thank you a lot! It works. Sorry - it was very stupid from my side. However, in documentation you have an example with simple `int` :) 

So please for now at least update documentation about such behavior: https://github.com/rbock/sqlpp11/wiki/Select

And sorry again :(

I think it can be closed for now.

**Comment by rbock** [comment]
No need to be sorry :-)

Thanks for the hint regarding the documentation!
