### ISSUE TITLE
Return value of insert

### ISSUE THREAD

**Issue by ZaMaZaN4iK** [rbock/sqlpp11#324]
Hi!
I am trying to get an id of just inserted row with `sqlpp11` without additional select call. Below is my code:
```
static auto preparedInsert =
            m_connection.prepare(sqlpp::insert_into(passwordTable)
                .set(passwordTable.hash = parameter(passwordTable.hash), passwordTable.salt = parameter(passwordTable.salt),
                     passwordTable.hashSettingsId = parameter(passwordTable.hashSettingsId)));
    preparedInsert.params.hash = hash;
    preparedInsert.params.salt = salt;
    preparedInsert.params.hashSettingsId = hashSettingsId;

    int result = m_connection(preparedInsert);
    // How to get just inserted id?
    return result;
```
There is no documentation in `sqlpp11` which describes required behaviour in such cases. By default SQL without additional `RETURNING` caluse returns count of changed rows.

However seems like there is some inconsistency with `sqlpp11`. `sqlpp11` with your `sqlite-connector` returns last inserted row_id (what happens if an user inserts multiple rows - I don't know). `sqlpp11` with PostgreSQL connector returns count changed rows (as usual SQL query).

So my questions are:
* How to solve my probem (get an id/ids of just inserted row)? Is it possible now to solve it with `sqlpp11`  without additional `SELECT`? Possibly some `returning()` modifier for `insert` operator in `sqlpp11` about which I don't know?
* What is the required return value for `INSERT` statement in `sqlpp11`? Last inserted id, count of changed rows, anything else?

Thank you/

**Comment by rbock** [comment]
Hi,

Thanks for pointing this out. The sqlite3 and mysql connectors return the latest inserted row id. I was not aware of the postgresql return value. There is also no formal description regarding the expected return value. My bad.

- You might try to change the behavior of the postgresql connector, but that might break existing code, of course. It also would not yield all ids in case of a multi-row insert.
- There is no ready to use `RETURNING` clause, but you could use a `custom_query` with `.with_result_type_of`, see examples.
- You could implement a `returning` clause.

Best,

Roland

**Comment by ZaMaZaN4iK** [comment]
@rbock Thank you for the detailed answer! However, I didn't understand, what is from your point of view desired return value of `insert`? Last inserted row id (as it done for sqlite and mysql)? If yes, I am ready to fix PostgreSQL connector to make it consistent with other connectors (I think it's better to make backward-incompatible change but fix inconsistency).

**Comment by rbock** [comment]
Yes, from my point of view, the desired return value of insert is last inserted row id.

I agree with your view on making a change (but it is not my repo, and therefore not my decision).

**Comment by ZaMaZaN4iK** [comment]
Don't worry - I will try to upstream such change into upstream. However, if upstream is "dead", that's a good chance to become a `sqlpp11-connector-postgresql` maintainer :)

**Comment by matthijs** [comment]
@ZaMaZaN4iK I guess I'm not dead yet... ;-)

The returning statement is implemented in the PostgreSQL connector. For returning you should just add '.returning(passwordTable.id) to your prepared statement and after that you can use the result as if it was a select.

That's how it is implemented in the postgresql connector.

**Comment by rbock** [comment]
@matthijs Great! Thanks for chiming in :-)

**Comment by ZaMaZaN4iK** [comment]
@rbock It works like a charm! Thank you a lot.

P.S. Possibly this hint also should be documented (and possibly I will try to update upstream docs with such example).

**Comment by ZaMaZaN4iK** [comment]
@matthijs Sorry. I am happy to hear that you still maintain PostgreSQL connector :)

**Comment by neel** [comment]
@matthijs @ZaMaZaN4iK Is it implemented ? Because currently it seems like I am getting number of rows inserted as return value.

**Comment by matthijs** [comment]
@neel Please open an issue on sqlpp11-connector-postgresql about this. Can you also provide a minimal example so that we can comment on that?
