### ISSUE TITLE
Assigning Single Char with Sqlpp11 Fails Compilation

### ISSUE THREAD

**Issue by nuertey** [rbock/sqlpp11#326]
Should a char element be assignable in the standard way? Like so: element = 'A';

I am observing that for a table defined thus:
```
CREATE TABLE orders (
    timestamped  timestamp NOT NULL,
    symbol       varchar(8) NOT NULL,
    side         char NOT NULL,
    price        integer NOT NULL,
    quantity     integer NOT NULL
);
```
And performing the below as a test, the second char assignment case does not compile.

```
        if (readyOrder.m_OrderSide == ProtocolDefinitions::OrderSide_t::BUY) 
        {
            m_TheDatabaseConnection(insert_into(ordersTable).set(
                 ordersTable.timestamped = dt, 
                 ordersTable.symbol = readyOrder.m_StockTickerSymbol.data(),
                 ordersTable.side = "B", // This standard string way with double-quotes compiles and works.
                 ordersTable.price = readyOrder.m_Price,
                 ordersTable.quantity = readyOrder.m_Quantity));
        }
        else if (readyOrder.m_OrderSide == ProtocolDefinitions::OrderSide_t::SELL)
        {
            m_TheDatabaseConnection(insert_into(ordersTable).set(
                 ordersTable.timestamped = dt, 
                 ordersTable.symbol = readyOrder.m_StockTickerSymbol.data(),
                 ordersTable.side = 'S', // This standard char way with single-quotes does not compile.
                 ordersTable.price = readyOrder.m_Price,
                 ordersTable.quantity = readyOrder.m_Quantity));

        }
```
In case it helps for debug, the compilation error in the second case is:
```
/usr/local/include/sqlpp11/column.h: In instantiation of ‘sqlpp::assignment_t<sqlpp::column_t<Table, ColumnSpec>, typename sqlpp::wrap_operand<T, void>::type> sqlpp::column_t<Table, ColumnSpec>::operator=(T) const [with T = char; Table = Model::public_::orders; ColumnSpec = Model::public_::orders_::Side; typename sqlpp::wrap_operand<T, void>::type = sqlpp::integral_operand]’:
SessionManager.cpp:392:37:   required from here
/usr/local/include/sqlpp11/column.h:90:7: error: static assertion failed: invalid rhs assignment operand
       static_assert(_is_valid_assignment_operand<rhs>::value, "invalid rhs assignment operand");
       ^~~~~~~~~~~~~
``` 
It would be nice if the standard char way of assignment could also work. That way I can reduce a lot of my boilerplate by not performing if conditionals on my char underlying enum types and then doing the appropriate double-quote assignments. I could then simply do:
```
        Model::public_::orders ordersTable;

        m_TheDatabaseConnection(insert_into(ordersTable).set(
             ordersTable.timestamped = dt, 
             ordersTable.symbol = readyOrder.m_StockTickerSymbol.data(),
             ordersTable.side = Utility::ToUnderlyingType(readyOrder.m_OrderSide),
             ordersTable.price = readyOrder.m_Price,
             ordersTable.quantity = readyOrder.m_Quantity));
```
Thanks

**Comment by Erroneous1** [comment]
You might be better off defining your size column as `tinyint` or sticking with `"B"`. Without knowing for sure I'd say `tinyint` would likely allow you to use `'B'` though it would be binary comparison and not lexicographical. Keep in mind that in SQL even if you say `'B'` it's still a string and not a character value. You can't, for instance, say `SELECT 'Z' - 'A'` to get 26.

This is what I get when I try in mariadb:
```
select CAST('Z' AS CHAR) - CAST('A' AS CHAR);
+---------------------------------------+
| CAST('Z' AS CHAR) - CAST('A' AS CHAR) |
+---------------------------------------+
|                                     0 |
+---------------------------------------+

1 row in set, 2 warnings (0.001 sec)
show warnings;
+---------+------+---------------------------------------+
| Level   | Code | Message                               |
+---------+------+---------------------------------------+
| Warning | 1292 | Truncated incorrect DOUBLE value: 'Z' |
| Warning | 1292 | Truncated incorrect DOUBLE value: 'A' |
+---------+------+---------------------------------------+
```

**Comment by nuertey** [comment]
That makes sense @Erroneous1 . It seems sometimes we forget that the types within the DB are rather moreso for 'our viewing pleasure' than for the DB itself being strongly-typed. I will stick to using "S". Now that I know the assignment format the DB expects, it should be fairly straightforward for me to adapt my received characters with a utility lambda into that format. That allows me to fulfill my goal of avoiding all that boilerplate conditionals.

Done! Tried such an approach and it works. 

You can close this issue. Thanks.

**Comment by rbock** [comment]
Thanks @Erroneous1 !

On the C++ side of things: The way the library interprets C++ types, it has to decide whether something is a text, an integral value, a date, etc. The dual nature of `char` cannot be modeled with the current code. 

sqlpp11 is following `std::is_integral`, which is `true_type` for char.

Stay safe and Happy Easter!
