### ISSUE TITLE
Inserting size_t value greater than 2^63.

### ISSUE THREAD

**Issue by egorpugin** [rbock/sqlpp11#327]
Hi,

I found an issue in my code.
I calculate `auto h = std::hash<String>()(...);`.
Then I insert h into INTEGER row which is int64_t datatype in sqlpp.

I got `h == 17032080461028570721`. It was transformed into SQL like
```
INSERT INTO file (path,hash,last_write_time) VALUES('D:/dev/swst/pkg/a0/98/902f/src/sdir/sw.cpp',17032080461028570721,x'6A7974838612D601')
```

And this query makes inserted value float (double) or whatever incorrect value.
I've added `file.hash = (int64_t)h,`, so value became negative and it is inserted properly now.

sqlite3 explicitly says that input integer must be signed.
https://www.sqlite.org/datatype3.html
INTEGER. The value is a signed integer, stored in 1, 2, 3, 4, 6, or 8 bytes depending on the magnitude of the value.

Isn't sqlpp11 must cast input integers to int64_t to prevent such errors?

cc: @ZaMaZaN4iK (FYI)

**Comment by rbock** [comment]
Hi,

Can you post a short example program? Would make it easier for me to comment.

Thanks,

Roland

**Comment by egorpugin** [comment]
https://github.com/SoftwareNetwork/sw/blob/master/src/sw/core/input_database.cpp#L57
I've fixed line 72 to overcome the issue.

**Comment by rbock** [comment]
Thanks,

I think it will be necessary to write a specialization in `sqlpp11/sqlite3/serializer.h` for unsigned integers.

Should not be too hard to do, but I am a bit swamped these days. Feel free to give it a try :-)

Best,

Roland

**Comment by ZaMaZaN4iK** [comment]
Is this problem specific to sqlite or all connectors are affected?

**Comment by egorpugin** [comment]
sqlite
I opened ticket in wrong repo.

**Comment by egorpugin** [comment]
See https://github.com/rbock/sqlpp11-connector-sqlite3/pull/71
