### ISSUE TITLE
failed to compile against GCC/Clang 10 (Fedora 32)

### ISSUE THREAD

**Issue by faizol** [rbock/sqlpp11#329]
Hi,
I just upgraded my system to Fedora 32 which uses gcc-10, and it seems that Sqlpp11 failed to compile when using either gcc-10 or clang-10.
```
include/sqlpp11/detail/type_set.h:63:43: error: ‘size_t’ was not declared in this scope; did you mean ‘std::size_t’?
```
and ‘uint8_t’ is not a member of ‘std’ in include/sqlpp11/data_types/blob/data_type.h file.

**Comment by rbock** [comment]
Hi,

I don't have gcc=10 available right now. clang-11 works fine (with -stdlib=libc++). I assume gcc's standard library got stricter.

Can you try adding `#include <cstdint>`, please?

Let me know if it works, for instance by creating a pull request :-)

Thanks!

Roland

**Comment by faizol** [comment]
I created a pull request to update data_type.h and type_set.h to make it compilable using gcc-10.
Thanks.
