### ISSUE TITLE
Sybase Connector

### ISSUE THREAD

**Issue by Martini-edv** [rbock/sqlpp11#33]
I start implementing a sybase connector for sqlpp und I found some issues that is not easy to implement with sybase. I used this skeleton and I am currently a bit in trouble to implement this.

As far as I can see the statement will be executed and then the resultset is read row by row and for each row every single variable is filled with some bind option column by column. Is this true or am I missunderstanding something?

Sybase supports binding, but before the first row is read, you have to specify the variables for each column and bind it directly, meaing with each row you read the varibables are filles by Syase.

Is this kind of binding support, too?

**Comment by rbock** [comment]
How you implement those "bind" calls is up to the requirements of the database.

What you write about Sybase sounds like the way that sqlite does it, too. Can you take a look at the sqlilte3 connector and see if that matches? You might also take a look at the two different result types in the mysql connector. The bind_result, which is used for prepared statements, could be similar (in fact, the basic idea is pretty much the same as with the sqlite3 connector).

Let me know :-)

Regards,

Roland

**Comment by Martiniclan** [comment]
Currently I have looked at SQLITE3 and there I found out, that there is no real binding. SQLITE3 extecute the statement, gets the row and THEN gets the value from the result set column into the variable seperately ... as far as I have understood this.

In Sybase I have to bind the variables BEFORE any row is read. Therefore infact, there is no need to do anything when a row is fetched.

But I will try to get the MySQL stuff tomorrow to see, if it different there.

BR Michael

**Comment by rbock** [comment]
I think I understand the idea better now. The MySQL stuff is a bit different from sqlite3, but still not exactly what you are looking for.

But it should be possible, though. You could do the binding when the first row is fetched and do nothing for all following rows...

Best,

Roland

**Comment by rbock** [comment]
Going through the current issues, I wondered if you are still interested in creating a connector to Sybase?  It should certainly be possible and might be even more interesting now, with that pull request that will allow compilation with MSVC.

Let me know if I can help.

Cheers,

Roland

**Comment by Martini-edv** [comment]
Well, I have created the connector within a project in a company, so it is up to them to upload this connector. Their development network have had no access to the WWW for me, so I could not upload it here, sorry. Works fine, added new error handling instead of raising exeptions which speeds up the processes.

BR
Michael

**Comment by rbock** [comment]
OK, the good news is: It is definitely possible :-)

Alternative error handling sounds interesting, too, of course.

Best,

Roland

**Comment by juandent** [comment]
Hi roland!

Please check an issue in github so I can continue to help 

Regards
Juan

**Comment by juandent** [comment]
Roland,

Attempting to push gives me permission denied to juandent

what’s next ?

Regards,
Juan

**Comment by juandent** [comment]
Hi Roland,

 

Please take a look  at the change made in https://github.com/juandent/sqlpp11

See if you agree with my solution…

 

Regards,

Juan

**Comment by knedlsepp** [comment]
This is also on my wishlist.

**Comment by rbock** [comment]
I am compiling a wish list. This goes onto it.

Closing the ticket.
