### ISSUE TITLE
Build errors with Clang 10

### ISSUE THREAD

**Issue by ZaMaZaN4iK** [rbock/sqlpp11#331]
Hi!
I've tried to compile your library with Clang 10 and got the following errors: https://pastebin.com/Cnd8yLHJ

Can you try to fix it? Thank you.

**Comment by ZaMaZaN4iK** [comment]
Seems like in file `type_set.h` you missed proper include for `size_t` type. Adding `#include <stddef.h>` fixes the problem.

Btw, if you use C++, think about using `std::size_t` instead (with `cstddef` header).

**Comment by faizol** [comment]
> Seems like in file `type_set.h` you missed proper include for `size_t` type. Adding `#include <stddef.h>` fixes the problem.
> 
> Btw, if you use C++, think about using `std::size_t` instead (with `cstddef` header).

Thanks, I've changed the pull request as you've suggested.

**Comment by ZaMaZaN4iK** [comment]
@faizol Pedantically, that's not right fix. `cstddef` header guarantees that `std::size_t` will be available, but doesn't guarantee availability `size_t` without `std::`. `stddef.h` guarantees that `size_t` will be available. So in your PR: 
* replace `#include <cstddef>` with `#include <stddef.h>`

And it'll be awesome fix :)

**Comment by faizol** [comment]
> @faizol Pedantically, that's not right fix. `cstddef` header guarantees that `std::size_t` will be available, but doesn't guarantee availability `size_t` without `std::`. `stddef.h` guarantees that `size_t` will be available. So in your PR:
> 
>     * replace `#include <cstddef>` with `#include <stddef.h>`
> 
> 
> And it'll be awesome fix :)

done.

**Comment by ZaMaZaN4iK** [comment]
@rbock Can you please create a release with compilation fixes for GCC 10? Thank you.

**Comment by rbock** [comment]
Done.
