### ISSUE TITLE
optional field in insert

### ISSUE THREAD

**Issue by neel** [rbock/sqlpp11#332]
I have an optional form field `created`. If there is a date set in created then I'll insert that date. Otherwise null or the default value of that field will be inserted. Or that field will not be set in the insert statement. Like the following.

        std::tm tm = {};
        std::istringstream ss(created);
        ss >> std::get_time(&tm, "%D");
        auto created_time = std::chrono::system_clock::from_time_t(std::mktime(&tm));
        
        wee::Zones zones;
        const auto results = _connection(
            sqlpp::postgresql::insert_into(zones).set(
                // ...
                zones.type      = type, 
                zones.user      = loggedin_user.id()
                zones.created = created.empty() ? default_value : created_time // ?? how to achieve this ?
            ).returning(zones.id)
        );

**Comment by rbock** [comment]
You can do this using `dynamic_insert`. Something like the following should work:

```C++
    auto statement = 
        sqlpp::postgresql::dynamic_insert_into(zones).dynamic_set(
            // ...
            zones.type      = type, 
            zones.user      = loggedin_user.id()
            zones.created = created.empty() ? default_value : created_time // ?? how to achieve this ?
        ).returning(zones.id);
    if (!created.empty())
       statement.insert.add(created_time);
    const auto results = _connection(statement);
```

**Comment by neel** [comment]
The dynamic insert have a different signature. It also takes the connection along with the table. Is there a reason for that ? Do I still need to pass that to the `_connection` ?

```
    template <typename Database, typename Table>
    constexpr auto dynamic_insert_into(const Database&, Table table) -> decltype(blank_insert_t<Database>().into(table))
    {
      static_assert(std::is_base_of<connection, Database>::value, "Invalid database parameter");
      return {blank_insert_t<Database>().into(table)};
    }
```

**Comment by neel** [comment]
@rbock  How will I specify the field ?

**Comment by rbock** [comment]
Yes, I wrote that code without testing. Now, still without testing, but hopefully a bit closer to the real thing:
```C++
    auto statement = 
        sqlpp::postgresql::dynamic_insert_into(_connection, zones).dynamic_set(
            // ...
            zones.type      = type, 
            zones.user      = loggedin_user.id()
        ).returning(zones.id);
    if (!created.empty())
       statement.insert_list.add(zones.created = created_time);
    const auto results = _connection(statement);
```
And yes, you need to pass the connection with the table. Serialization depends on the type of the connector and it is required for type erasure in the dynamic part.

**Comment by neel** [comment]
Currently I am using `sqlpp::value_or_null_t`. This is what I am doing.

```
sqlpp::value_or_null_t<sqlpp::time_point> created_at(sqlpp::null);
if(!created.empty()){
    std::cout << created  << std::endl;
    std::tm tm = {};
    std::istringstream ss(created);
    ss >> std::get_time(&tm, "%Y-%m-%dT%H:%M:%S.000Z");
    boost::posix_time::ptime created_time(boost::gregorian::date(tm.tm_year+1900, tm.tm_mon+1, tm.tm_mday));
    boost::posix_time::ptime epoch(boost::gregorian::date(1970, 1, 1));
    boost::posix_time::time_duration diff = created_time - epoch;
    std::chrono::time_point<std::chrono::system_clock, std::chrono::microseconds> created_time_chrono(std::chrono::microseconds(diff.total_microseconds()));

    created_at = sqlpp::value_or_null_t<sqlpp::time_point>(created_time_chrono);
}

wee::Zones zones;
auto statement =  sqlpp::postgresql::insert_into(zones).set(
    // ...
    zones.user      = loggedin_user.id(),
    zones.created   = created_at
).returning(zones.id);
        
```

**Comment by rbock** [comment]
And if `NULL` is the default, then that is the way to go, I'd say :-)

**Comment by neel** [comment]
What is the equivalent of `insert_list` for dynamic update ? I tried `update_list` but that didn't work.

**Comment by rbock** [comment]
`assignments`

**Comment by neel** [comment]
Tried `assignments`. 

        sqlpp::value_or_null_t<sqlpp::time_point> deleted_at(sqlpp::null);
        if(!deleted.empty()){
            std::cout << deleted  << std::endl;
            std::tm tm = {};
            std::istringstream ss(deleted);
            ss >> std::get_time(&tm, "%Y-%m-%dT%H:%M:%S.000Z");
            boost::posix_time::ptime deleted_time(boost::gregorian::date(tm.tm_year+1900, tm.tm_mon+1, tm.tm_mday));
            boost::posix_time::ptime epoch(boost::gregorian::date(1970, 1, 1));
            boost::posix_time::time_duration diff = deleted_time - epoch;
            std::chrono::time_point<std::chrono::system_clock, std::chrono::microseconds> deleted_time_chrono(std::chrono::microseconds(diff.total_microseconds()));
        
            deleted_at = sqlpp::value_or_null_t<sqlpp::time_point>(deleted_time_chrono);
        }
        
        wee::Zones zones;
        auto statement =  sqlpp::postgresql::dynamic_update(_connection, zones).dynamic_set(
            zones.type      = type, 
            zones.geometry  = geometry, 
            zones.created   = created_at
        ).where(zones.id == id).returning(zones.id);

        if(is_deleted){
            statement.assignments.add(
                zones.isDeleted = is_deleted,
                zones.deleted   = deleted_at
            );
        }


getting compilation error.

`error: no matching function for call to ‘sqlpp::update_list_t<sqlpp::postgresql::connection, sqlpp::assignment_t<sqlpp::column_t<wee::Zones, wee::Zones_::Type>, sqlpp::text_operand>, sqlpp::assignment_t<sqlpp::column_t<wee::Zones, wee::Zones_::Geometry>, sqlpp::text_operand>, sqlpp::assignment_t<sqlpp::column_t<wee::Zones, wee::Zones_::District>, sqlpp::text_operand>, sqlpp::assignment_t<sqlpp::column_t<wee::Zones, wee::Zones_::Ward>, sqlpp::text_operand>, sqlpp::assignment_t<sqlpp::column_t<wee::Zones, wee::Zones_::Pincode>, sqlpp::text_operand>, sqlpp::assignment_t<sqlpp::column_t<wee::Zones, wee::Zones_::Details>, sqlpp::text_operand>, sqlpp::assignment_t<sqlpp::column_t<wee::Zones, wee::Zones_::Locations>, sqlpp::text_operand>, sqlpp::assignment_t<sqlpp::column_t<wee::Zones, wee::Zones_::Created>, sqlpp::value_or_null_t<sqlpp::time_point> > >::_impl_t<sqlpp::detail::statement_policies_t<sqlpp::postgresql::connection, sqlpp::update_t, sqlpp::single_table_t<void, wee::Zones>, sqlpp::update_list_t<sqlpp::postgresql::connection, sqlpp::assignment_t<sqlpp::column_t<wee::Zones, wee::Zones_::Type>, sqlpp::text_operand>, sqlpp::assignment_t<sqlpp::column_t<wee::Zones, wee::Zones_::Geometry>, sqlpp::text_operand>, sqlpp::assignment_t<sqlpp::column_t<wee::Zones, wee::Zones_::District>, sqlpp::text_operand>, sqlpp::assignment_t<sqlpp::column_t<wee::Zones, wee::Zones_::Ward>, sqlpp::text_operand>, sqlpp::assignment_t<sqlpp::column_t<wee::Zones, wee::Zones_::Pincode>, sqlpp::text_operand>, sqlpp::assignment_t<sqlpp::column_t<wee::Zones, wee::Zones_::Details>, sqlpp::text_operand>, sqlpp::assignment_t<sqlpp::column_t<wee::Zones, wee::Zones_::Locations>, sqlpp::text_operand>, sqlpp::assignment_t<sqlpp::column_t<wee::Zones, wee::Zones_::Created>, sqlpp::value_or_null_t<sqlpp::time_point> > >, sqlpp::where_t<void, sqlpp::binary_expression_t<sqlpp::column_t<wee::Zones, wee::Zones_::Id>, sqlpp::op::equal_to, sqlpp::unsigned_integral_operand> >, sqlpp::postgresql::returning_column_list_t<sqlpp::postgresql::connection, sqlpp::column_t<wee::Zones, wee::Zones_::Id> > > >::add(sqlpp::assignment_t<sqlpp::column_t<wee::Zones, wee::Zones_::IsDeleted>, sqlpp::boolean_operand>, sqlpp::assignment_t<sqlpp::column_t<wee::Zones, wee::Zones_::Deleted>, sqlpp::value_or_null_t<sqlpp::time_point> >)’`

**Comment by neel** [comment]
Also tried to add the time_point directly without using `value_or_null` that also didn't work

            std::chrono::time_point<std::chrono::system_clock, std::chrono::microseconds> deleted_time_chrono(std::chrono::microseconds(diff.total_microseconds()));
            statement.assignments.add(
                zones.isDeleted = is_deleted,
                zones.deleted   = deleted_time_chrono
            );

**Comment by rbock** [comment]
Similar to `insert_list`, try adding one assignment at a time.
