### ISSUE TITLE
Sort by count subquery

### ISSUE THREAD

**Issue by neel** [rbock/sqlpp11#333]
I want to select some columns of user table and a subquery on another table. The subquery contains a count. I want to use that count to sort the rows. So I am using `order_by(count.asc())` But this is giving compilation errors.
```
select(
    users.id, 
    users.first_name, 
    users.last_name, 
    select(count(zones.id))
        .from(zones)
        .where(zones.user == users.id)
)
.from(users)
.order_by(count.asc())
.unconditionally()
```
So I aliased `count` as `entries`

```
SQLPP_ALIAS_PROVIDER(entries);
select(
    users.id, 
    users.first_name, 
    users.last_name, 
    select(count(zones.id))
        .from(zones)
        .where(zones.user == users.id)
        .as(entries)
)
.from(users)
.order_by(entries.asc())
.unconditionally()
```

This is also giving compilation errors

`error: ‘sqlpp::no_select_column_list_t::_base_t<sqlpp::detail::statement_policies_t<void, sqlpp::no_with_t, sqlpp::select_t, sqlpp::no_select_flag_list_t, sqlpp::no_select_column_list_t, sqlpp::no_from_t, sqlpp::no_where_t<true>, sqlpp::no_group_by_t, sqlpp::no_having_t, sqlpp::no_order_by_t, sqlpp::no_limit_t, sqlpp::no_offset_t, sqlpp::no_union_t, sqlpp::no_for_update_t> >::_new_statement_t<sqlpp::assert_selected_colums_are_selectable_t, sqlpp::select_column_list_t<void, sqlpp::column_t<wee::TabUser, wee::TabUser_::Id>, sqlpp::column_t<wee::TabUser, wee::TabUser_::FirstName>, sqlpp::column_t<wee::TabUser, wee::TabUser_::LastName>, sqlpp::table_alias_t<entries_t, sqlpp::select_pseudo_table_t<sqlpp::statement_t<void, sqlpp::no_with_t, sqlpp::select_t, sqlpp::no_select_flag_list_t, sqlpp::select_column_list_t<void, sqlpp::expression_alias_t<sqlpp::count_t<sqlpp::noop, sqlpp::column_t<wee::Zones, wee::Zones_::Id> >, sqlpp::count_alias_t> >, sqlpp::from_t<void, wee::Zones>, sqlpp::where_t<void, sqlpp::binary_expression_t<sqlpp::column_t<wee::Zones, wee::Zones_::User>, sqlpp::op::equal_to, sqlpp::column_t<wee::TabUser, wee::TabUser_::Id> > >, sqlpp::no_group_by_t, sqlpp::no_having_t, sqlpp::no_order_by_t, sqlpp::no_limit_t, sqlpp::no_offset_t, sqlpp::no_union_t, sqlpp::no_for_update_t>, sqlpp::expression_alias_t<sqlpp::count_t<sqlpp::noop, sqlpp::column_t<wee::Zones, wee::Zones_::Id> >, sqlpp::count_alias_t> >, sqlpp::select_column_spec_t<sqlpp::statement_t<void, sqlpp::no_with_t, sqlpp::select_t, sqlpp::no_select_flag_list_t, sqlpp::select_column_list_t<void, sqlpp::expression_alias_t<sqlpp::count_t<sqlpp::noop, sqlpp::column_t<wee::Zones, wee::Zones_::Id> >, sqlpp::count_alias_t> >, sqlpp::from_t<void, wee::Zones>, sqlpp::where_t<void, sqlpp::binary_expression_t<sqlpp::column_t<wee::Zones, wee::Zones_::User>, sqlpp::op::equal_to, sqlpp::column_t<wee::TabUser, wee::TabUser_::Id> > >, sqlpp::no_group_by_t, sqlpp::no_having_t, sqlpp::no_order_by_t, sqlpp::no_limit_t, sqlpp::no_offset_t, sqlpp::no_union_t, sqlpp::no_for_update_t>, sqlpp::expression_alias_t<sqlpp::count_t<sqlpp::noop, sqlpp::column_t<wee::Zones, wee::Zones_::Id> >, sqlpp::count_alias_t> > > > >’ {aka ‘struct sqlpp::assert_selected_colums_are_selectable_t’} has no member named ‘from’`

**Comment by rbock** [comment]
Sub queries as named values are not well supported, I am afraid. `select(...).as(something)` creates a sub-select that can be used as a table. The selected columns are the columns of that table, e.g.

```
  auto rowCount = select(t.alpha, count(t.alpha)).from(t).unconditionally().group_by(t.alpha).as(sqlpp::alias::a);
  db(select(f.omega, rowCount.count)
         .from(f.join(rowCount).on(f.omega == rowCount.alpha))
         .unconditionally()
         .order_by(rowCount.count));
```
This is not exactly what you want, but probably the closest the library can get you without serializing sub expressions and using them as verbatim strings.
