### ISSUE TITLE
Thread Safe connection object message type 0x54 arrived from server while idle

### ISSUE THREAD

**Issue by neel** [rbock/sqlpp11#336]
I am getting several messages like the following 
```
message type 0x54 arrived from server while idle
message type 0x44 arrived from server while idle
message type 0x44 arrived from server while idle
message type 0x44 arrived from server while idle
message type 0x44 arrived from server while idle
message type 0x43 arrived from server while idle
message type 0x5a arrived from server while idle
```

and then a exception is thrown.
```
terminate called after throwing an instance of 'sqlpp::postgresql::failure'
  what():  No result set given
```

The related information of this message says the connection object is being used from multiple threads. So is the sqlpp11 connection object thread safe ?

**Comment by neel** [comment]
I am using it in a web service that runs in multiple threads. So all controllers makes SQL queries from different threads. If I want to keep a specific single thread for database operation then I need to queue queries. But these queries are heavily templated objects.

**Comment by matthijs** [comment]
You can also create a database connection pool and fetch a database connection when you need one. Then you can add proper protection in the pool that prevents race conditions.

**Comment by neel** [comment]
What about putting a single mutex before sending every query to the database ? Will that still give the same error message as the connection object is used from a thread which is different from the creation thread ?

**Comment by rbock** [comment]
It seems to me that you are misreading the comments: You totally can talk to the database from multiple threads. But you need multiple connection objects. And you have to be careful about sharing one connection with multiple threads. The details of what is allowed and what not depend heavily on the database.

The simplest strategy is to have one connection per thread.

As @matthijs indicated, with postgresql you can handle the necessary protection in a connection pool. I cannot add details to that, as my postrgresql experience is rather limited. So my recommendation is to study the postgresql documentation.

**Comment by matthijs** [comment]
@rbock I meant that you need to implement a connection pool yourself. PostgreSQL does not have connection pooling itself. There are several options but thats out of scope for this issue I think.

The easiest is to have one connection per thread as you already said.
