### ISSUE TITLE
ddl2cpp error

### ISSUE THREAD

**Issue by RoyBellingan** [rbock/sqlpp11#337]
Using revision 37078eb2833cfd56ec96f6139720304548330928
When using a DDL like that
 CREATE TABLE `comparison` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `ts` int(10) unsigned NOT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp()
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

Invoking with
ddl2cpp somewhere/s1.sql somewhere/s1 "ns1"

Produces

#ifndef NS1_S1_H
#define NS1_S1_H

#include <sqlpp11/table.h>
#include <sqlpp11/data_types.h>
#include <sqlpp11/char_sequence.h>

namespace ns1
{
} // namespace ns1
#endif

Really no idea how to debug, I arrive at line 306 
tableCreations = ddl.parseFile(pathToDdl)

pycharm think a bit and nothing happens.

**Comment by rbock** [comment]
Hi,

I have yet to find a good way to debug what's happening in pyparsing. My (clumsy) method is to remove stuff from the DDL until it works. Then figure out what needs to be changed in the parsing rules to allow for the offending line to be parsed correctly, too.

In this case it is the trailing `current_timestamp()`. Would you like to create pull request to fix this?

If you want to go above and beyond, you might want to restructure the code a bit to allow for better debugging. For example, we could identify tables first, then parse those one by one (printing an error message if that fails). Within a table, we could identify columns and constraints first, then parse them in detail one by one (again printing error messages on failure).

Just an idea. There might be better approaches to debug pyparsing.

**Comment by RoyBellingan** [comment]
Ciao rbock.
Sorry but when I see python code my brain shuts down -.-

For me Is way easier to rewrite all C++ and be able to follow step step by step, in the same time.

I'm still evaluating to use this software package, is super good, but also out of my reach at the moment. I am inclined to use it, but I first have to understand how it goes with our work flow.

Bye

**Comment by rbock** [comment]
Hi Roy,

It might be more consistent to have it all in C++. Some interface libraries offer support, I think.

Let me know if you need to support with figuring out the workflow.

Best,

Roland

**Comment by RoyBellingan** [comment]
I do not promise nothing herr rbock.
But I will try to see what I can do, again I really do not think my coding level is on par with this lib, so a task like that can be a decent starter!

**Comment by rbock** [comment]
Got it, no promise. But it would be a great starter, indeed :-)
