### ISSUE TITLE
wiki/Dynamic-Select page code example do not work

### ISSUE THREAD

**Issue by RoyBellingan** [rbock/sqlpp11#338]
A few minor bug in  https://github.com/rbock/sqlpp11/wiki/Dynamic-Select#dynamic-columns  

   auto s = dynamic_select(db).dynamic_columns(foo.id).from(foo); 
is missing the where condition (like .unconditionally() )

Error reported is 

 ‘void __for_begin’ has incomplete type
  for (const auto& row : db(s)){
                             ^

In addition the method at is called with square braket, 
   std::string name = row.at["name"];
it should be
   std::string name = row.at("name");

Bye

**Comment by rbock** [comment]
Thanks for the hints!
