### ISSUE TITLE
C++20: ambiguous overloads for operator==

### ISSUE THREAD

**Issue by dermojo** [rbock/sqlpp11#342]
When building with Clang 10 in C++20 mode, a lot of comparison operators are now ambiguous.

Example:

    /home/daniel/git/sqlpp11/tests/Interpret.cpp:100:21: error: use of overloaded operator '==' is ambiguous (with operand types 'const sqlpp::column_t<test::TabBar, test::TabBar_::Alpha>' and 'parameter_t<value_type_of<sqlpp::column_t<test::TabBar, test::TabBar_::Alpha> >, sqlpp::column_t<test::TabBar, test::TabBar_::Alpha> >' (aka 'parameter_t<sqlpp::integral, sqlpp::column_t<test::TabBar, test::TabBar_::Alpha> >'))
      serialize(t.alpha == parameter(t.alpha), printer).str();
                ~~~~~~~ ^  ~~~~~~~~~~~~~~~~~~
    /home/daniel/git/sqlpp11/include/sqlpp11/basic_expression_operators.h:127:10: note: candidate function [with T = sqlpp::parameter_t<sqlpp::integral, sqlpp::column_t<test::TabBar, test::TabBar_::Alpha> >]
        auto operator==(T t) const -> _new_binary_expression_t<equal_to_t, T>
             ^
    /home/daniel/git/sqlpp11/include/sqlpp11/basic_expression_operators.h:127:10: note: candidate function (with reversed parameter order) [with T = sqlpp::column_t<test::TabBar, test::TabBar_::Alpha>]

Any ideas how to prevent this / work around this issue?
Thanks!

**Comment by rbock** [comment]
I sure hope that this is bug in clang (maybe it is getting confused by CRTP), because this compiles:

```C++
class X
{
    public:
      template <typename T>
      constexpr bool operator==(const T&) const 
      {
        return true;
      }
};

class Y
{
    public:
      template <typename T>
      constexpr bool operator==(const T&) const 
      {
        return false;
      };
};

int main()
{
    static_assert(X{} == Y{});
    static_assert(not (Y{} == X{}));
}
```

Can you try with a recent gcc, too? Mine is a couple of months old right now.

**Comment by dermojo** [comment]
GCC 10 works fine, this only happens with Clang. To trigger this synthetically, the example needs to be modified a bit:

```cpp
class Foo {};

class X
{
    public:
      template <typename T>
      constexpr Foo operator==(const T&) const 
      {
        return Foo{};
      }
};

class A : public X {};
class B : public X {};

int main()
{
    Foo f = A{} == B{};
    return 0;
}
```
My guess is on CRTP. I'll see if I can get any info from the LLVM team.

**Comment by rbock** [comment]
Thanks for investigating! If you file a bug, please add a link here as well.

**Comment by dermojo** [comment]
Thanks for your help.
I opened https://bugs.llvm.org/show_bug.cgi?id=46508 to investigate this.

**Comment by dermojo** [comment]
After some investigation, I came up with a very "hacky" workaround (just FYI):
```cpp
serialize(t.alpha.operator ==(parameter(t.alpha)), printer).str();
```
Calling the member function directly avoids overload resolution on the binary operator, but this is far from ideal...

What bothers me is this (from [cppreference](https://en.cppreference.com/w/cpp/language/overload_resolution)):

> If a rewritten `operator==` candidate is selected by overload resolution for an `operator @` (which is either `==` or `!=`), its return type must be (possibly cv-qualified) `bool`, and `x @ y` is interpreted as the rewritten expression: `y == x` or `!(y == x)` if the selected candidate is a synthesized candidate with reversed order of parameters, or `!(x == y)` otherwise, using the selected rewritten `operator==` candidate.

My take on this is that overload resolution shouldn't kick in here because `operator==` for expressions doesn't return a `bool`.
I'm trying to find the right paper to verify this...

**Comment by dermojo** [comment]
The problems is fixed(?) by adding these to `column_t`:
```cpp
using expression_operators<column_t<Table, ColumnSpec>, value_type_of<ColumnSpec>>::operator==;
using expression_operators<column_t<Table, ColumnSpec>, value_type_of<ColumnSpec>>::operator!=;
```

This seems to avoid overload resolution and ambiguity (by avoiding `==` / `!=` on the common base class).
The test suite passes, but I'll keep an eye on it while rebuilding/retesting our code base.

**Comment by dermojo** [comment]
A quick update:
I don't think it's a clang bug, I think it's by design in C++20:

According to [over.match.oper](http://eel.is/c++draft/over.match.oper), overload resolution for `==` always considers the reversed order of parameters as well (so `a==b` also always has to consider `b==a`). Since both overloads result in a different function call, I understand the ambiguity.
I'm still trying to figure out why GCC doesn't complain about this. Maybe their implementation isn't as complete here, I need to look at the sources.

**Comment by rbock** [comment]
Thanks for the link. I have yet to read it in detail. But there has to be a preference (e.g. for the original order). Otherwise there would be ambiguity all over the place.

**Comment by dermojo** [comment]
An update about GCC:
After digging through the sources (which aren't as easy to read as Clang's...), it seems that GCC currently avoids overload resolution.

From the original [patch](https://gcc.gnu.org/legacy-ml/gcc-patches/2019-11/msg00353.html):
> My handling of non-dependent rewritten operators in templates can still use
some work: build_min_non_dep_op_overload can't understand the rewrites and
crashes, so I'm avoiding it for now [...]

(There's an according FIXME in the sources.)

As far as I understand the changes with C++20, ambiguity may pop up in several places in favor of "sane" code (where a==b should do the same as b==a).

**Comment by rbock** [comment]
cppreference (no the standard, but usually pretty close) confirms that there is a preference:

> Overload resolution in this case has a final tiebreaker preferring non-rewritten candidates to rewritten candidates, and preferring non-synthesized rewritten candidates to synthesized rewritten candidates.

This is how the ambiguity should be prevented.

**Comment by dermojo** [comment]
Thanks for the update. I found the matching standard in [over.match.best](http://eel.is/c++draft/over.match.best), specifically [2.8](http://eel.is/c++draft/over.match.best#2.8) and [2.9](http://eel.is/c++draft/over.match.best#2.9).
I'll update the llvm ticket accordingly and add a reference to the commit.

**Comment by rbock** [comment]
Thanks for the extended research and discussion as well as the fix!
