### ISSUE TITLE
Update with a different table

### ISSUE THREAD

**Issue by neel** [rbock/sqlpp11#346]
This is what I am currently doing. Is there any way to shorten this ? Like `projects.mutate == "contributor" and check membership table for M2M`

            wee::Memberships memberships;
            auto membership_results = _connection(select(memberships.user).from(memberships).where(memberships.user == loggedin_user.id() and memberships.project == id));
            bool is_contributor = membership_results.size();
            wee::Projects projects;
            if(is_contributor){
                auto statement =  sqlpp::update(projects).set(
                    projects.name        = name.value(),
                    projects.label       = label.value(),
                    /* some other fields */
                ).where(projects.id == id and (projects.owner == loggedin_user.id() or projects.mutate == "member" or projects.mutate == "contributor"));

                _connection(statement);
            }else{
                auto statement =  sqlpp::update(projects).set(
                    projects.name        = name.value(),
                    projects.label       = label.value(),
                    /* some other fields */
                ).where(projects.id == id and (projects.owner == loggedin_user.id() or projects.mutate == "member"));

                _connection(statement);
            }

**Comment by rbock** [comment]
To be honest, I am not sure what you are trying to do here. Maybe a sub-select using `exists`?
Also, if the `.set()` call is the same in both branches, you might want to look into `boolean_expression` for the `where` condition.
Or you might consider using `dynamic_update` (not documented in the wiki, but similar to `dynamic_select`)

**Comment by neel** [comment]
In PostgreSQL one can update `t1` while with `from t2` so that both of these tables can be used while constructing the update query. Like the following.

```
UPDATE t1
SET t1.c1 = new_value
FROM t2
WHERE t1.c2 = t2.c2;
```
sqlpp already has the `from` clause but its restricted for `select` queries only. But its usable in update queries too. I hope it will make the queries like the one mentioned above easier.

**Comment by rbock** [comment]
@matthijs That might be an interesting extension for the postgresql connector?

I think you have multiple options here, e.g.

  - I believe that using `exists` in the `where` clause should be possible, see for instance https://stackoverflow.com/a/9023959/2173029
  - custom_query allows you to combine clauses and (where necessary) verbatim strings.
