### ISSUE TITLE
Does this library support JSON manipulation?

### ISSUE THREAD

**Issue by remz1337** [rbock/sqlpp11#347]
Hello,

went through the documentation but couldn't find anything related to this. Does this library support JSON manipulation?

Thanks

**Comment by rbock** [comment]
Hi,

The short answer is no. But there's been a brief discussion [here](https://github.com/matthijs/sqlpp11-connector-postgresql/issues/83) recently: It would be possible to add a json data type with the appropriate member functions.

So if you or anybody reading this are looking for a coding challenge, you found one :-)
