### ISSUE TITLE
Pull in the Date Time lib via cmake

### ISSUE THREAD

**Issue by Leon0402** [rbock/sqlpp11#348]
Hi,

I would like to suggest to pull in the date lib via FetchContent. This would make it a lot easier to use! 

I had a look at the lib and it seems like FetchContent is supported and actually the preferred way https://github.com/HowardHinnant/date/blob/master/CMakeLists.txt. 

Would you be open for that? I might could help you with this.

**Comment by rbock** [comment]
Hi Leon,

Thanks for the suggestion. I was not aware of FetchContent before, but quickly glancing at the documentation, this sounds good, indeed.

I guess the next step after that would be to something similar for the connector libraries?

**Comment by Leon0402** [comment]
Yeah that would have been in deed the next thing I suggested :)
It has one drawback though, it requires at least cmake 3.11 in order to be available. I would even recommend 3.14 because that simplified the usage of FetchConent by introducing FetchContent_MakeAvailable().
Cmake just released 3.18, so I think bumping up the cmake version to 3.14 would be justified.

If that's okay I would send in a pull request.

**Comment by rbock** [comment]
3.14 is about 1.5 years old, which is not a lot, but I would hope that most users can cope (I am on 3.16).

Let's go for it and push people to update their packages where required :-)

Regarding examples: Sure, the tests are compiled and executed. And you could use the library to serialize SQL expressions (dialects are supported in the connector libraries, only, though).

**Comment by Leon0402** [comment]
Great, I will work on it!

I just saw https://github.com/rbock/sqlpp11/issues/174, is there any progress? That might be relevant for the next step you mentioned. With fetchContent usage would be really easy then, because you basically just have to link then against the connector you need (linking against the core lib will be done automatically) and you can switch easily.
With find_package() the situation is similar, you can make the connectors components, so usage would look like
```
find_package(sqlpp COMPONENTS sqlite3 REQUIRED)
```
and again you would get a target of the sqlite3 connector in this case and it would have a dependency on sqlpp. 

In my opinion, we should work on a clean cmake structure in order to make this happen. Otherwise you will end up with a 500 line top level cmake file.

**Comment by rbock** [comment]
Hi,

Regarding #174 : I don't think I will make this happen any time soon, although I still believe that it would be the right thing to do in the long run.

As for the cmake structure: This is no thanks to me, as I am very much a cmake illiterate, but thanks to a number of great contributors, who helped straighten this out :-)

I am looking forward to your changes!
