### ISSUE TITLE
How can i get raw sql string from sqlpp::select

### ISSUE THREAD

**Issue by KondratovRoman** [rbock/sqlpp11#356]

**Comment by KondratovRoman** [comment]
https://github.com/rbock/sqlpp11/issues/151

**Comment by KondratovRoman** [comment]
Is there support for sql window functions?
Such as dense_rank(), row_number()...

`SELECT` dense_rank()  OVER (ORDER BY name)`

**Comment by rbock** [comment]
Hi,

Those are not supported directly. Adding functions to the DSL is not hard, though.

In the meantime, for this case, I think I would use `verbatim`.

**Comment by KondratovRoman** [comment]
Hi, ty for answer.
What about raw sql string from sqlpp::select/insert/update?

**Comment by KondratovRoman** [comment]
How i understand, verbatim use's for custom_query. For example:
`custom_query(sqlpp::verbatim("INSERT INTO sample_values VALUES()")).with_result_type_of(sqlpp::insert_into(sqlpp::alias::a));`

I want to get raw sql string from std::select. It seems like this
`std::string raw_string   =  sqlpp::giveMeStringFromSqlp(sqlpp::select(tbl_TARGET_MODEL.TMID).from(tbl_TARGET_MODEL).unconditionally())`

**Comment by rbock** [comment]
Do you want the serialized query string? You can get this via the serializer of the respective connector library.

Or do you want to get the raw result as yielded by the database?

**Comment by ZerQAQ** [comment]
I have the same question, how can I get the serialized query string? just like this:

```C++
std::string sql_string = serialize(update(tbStudent)
    .set(tbStudent.age = 25)
    .where(tbStudent.sid.in(1, 2, 3)));
std::cout << sql_string <<std::endl;
// output: UPDATE Student SET age=25 WHERE Student.sid IN(1,2,3)
```

Is there a function like serialize?

**Comment by rbock** [comment]
Yes, it is called `serialize`. You can see how it is used in tests and in the connectors.
