### ISSUE TITLE
on duplicate key update

### ISSUE THREAD

**Issue by niclar** [rbock/sqlpp11#357]
How would I do the "ON DUPLICATE KEY UPDATE" part of an insert e.g

INSERT INTO tbl (id, a, b, c) VALUES (?, ?, ?, ?) ON DUPLICATE KEY UPDATE a = ?, b= ?, c= ?

in sqlpp11 ? 

Great lib!

**Comment by rbock** [comment]
Thanks :-)

I see two options: 

- custom query
- write a clause to be added to the insert statement

The latter takes more time, of course. I am also not sure if it should be added to sqlpp11 or to the respective connectors (postgresql does not it, I think).

I am happy to help, if you would like to give it a try :-)

**Comment by niclar** [comment]
Yeah any extensions should probably be in the connector..

 -Just begun with the lib & short of time of cause, so maybe at a later stage .

 I'll try and decompose it in primitive statements for now

**Comment by rbock** [comment]
Actually, take a look at: tests/CustomQuery.cpp

It has a primitive example of how to write "ON DUPLICATE KEY UPDATE" :-)

**Comment by niclar** [comment]
perfect, many thanks. I'll give it a try

**Comment by niclar** [comment]
the example don't seem to play well with the sqlpp::mysql::connection...

error C2512: 'sqlpp::mysql::serializer_t': no appropriate default constructor available

**Comment by rbock** [comment]
Note that for mysql, you need to pass the connection as constructor argument to the serializer context:

```C++
  struct on_duplicate_key_update
  {
    std::string _serialized;

    template <typename Db, typename Assignment>
    on_duplicate_key_update(Db& db, Assignment assignment)
    { 
      typename Db::_serializer_context_t context{db};
      _serialized = " ON DUPLICATE KEY UPDATE " + serialize(assignment, context).str();
    }

    template <typename Db, typename Assignment>
    auto operator()(Db& db, Assignment assignment) -> on_duplicate_key_update&
    {
      typename Db::_serializer_context_t context{db};
      _serialized += ", " + serialize(assignment, context).str();
      return *this;
    }
    
    auto get() const -> sqlpp::verbatim_t<::sqlpp::no_value_t>
    { 
      return ::sqlpp::verbatim(_serialized);
    }
  };
```

This is very much untested. Let me know if it works.

**Comment by niclar** [comment]
Testing this again and it seems like the above generates invalid syntax i.e braces following ON DUBLICATE KEY UPDATE  is not allowed. What is the succinct way of removing these braces ?

**Comment by rbock** [comment]
You need to be more specific. Can you provide a real example?

Note, there has been an example in `tests/mysql/usage/CustomQuery.cpp` for a while which seems to work just fine:

```
    db(custom_query(sqlpp::insert_into(tab).set(tab.beta = "sample", tab.gamma = true),
                    on_duplicate_key_update(db, tab.beta = "sample")(db, tab.gamma = false).get()));
```

gets successfully executed as:

```
INSERT INTO tab_sample (beta,gamma) VALUES('sample',1)  ON DUPLICATE KEY UPDATE beta='sample', gamma=0
```

Maybe you could extend that one?
