### ISSUE TITLE
Add support to compile with VS2013?

### ISSUE THREAD

**Issue by suluvai** [rbock/sqlpp11#36]
Hi Roland,

I appreciate your work on Sqlpp11 library, quite impressed with the concept and would like to use it in my project but unfortunately your code does not compile with VS2013. Can you please add support to get this compile with VS2013?

I know you mentioned somewhere you have used C++11 features that were not supported by VS 2013 compiler but there are alternatives you can use bu substituting with equivalent boost library implementation. 

Can you please add support to get this compile using MSVC 2013?

Thanks
Praveen

**Comment by rbock** [comment]
Hi Praveen,

As discussed in issue 34 (https://github.com/rbock/sqlpp11/issues/34), not even the CTP6 of MSVC-2015 has sufficient C++11 support. Back in August 2014, the current build of MSVC still had troubles with static_assert (this did not compile then: https://gist.github.com/rbock/b573ee3d024902998e3e).

I see no (reasonable) way to replace these things with boost equivalents. And quite frankly, even if I did, I would not want to do it. I'd rather spend my time improving the library and hoping for the MS compiler to finally catch up.

Of course, if you believe to be able to rewrite those parts of the library that stop it from compiling with MSVC 2013, please feel free to do so. I'll gladly link to your project.

Best,

Roland

**Comment by Popovich** [comment]
Seems MS fixed it (https://gist.github.com/rbock/b573ee3d024902998e3e)
Try the latest online version of the compiler (updated on Jun 1 2015)
http://webcompiler.cloudapp.net/

**Comment by rbock** [comment]
The question was about MSVC-2013 (not 2015). There is some hope left for MSVC-2015, but as of now, that also seems problematic.

```C++
struct A
{
  static constexpr const char _literal[] =  "hello_world";
};
```

This does not compile even with the June-1 version. The compiler accepts the constexpr outside the struct though. See also: https://github.com/rbock/sqlpp11/issues/43#issuecomment-107643085

**Comment by Popovich** [comment]
struct A
{
  static constexpr const char* _literal =  "hello_world";
};

compiles fine :)

**Comment by rbock** [comment]
That does not help me, I think. Take a look at
include/sqlp11/alias_provider.h or tests/Sample.h

If that can be done with const char*, then we're getting somewhere :-)
