### ISSUE TITLE
Issue with sqlpp11/parameter.h

### ISSUE THREAD

**Issue by back-marker** [rbock/sqlpp11#368]
Seems this `sqlpp11/wrap_operand.h` is not included in `parameter.h` file but it uses `wrap_operand_t` type from it. 
I was facing this issue where if the the `parameter.h` was included in a header file it didn't compile but if in a .cpp file it compiles. Was able to track it to this issue to be related to `wrap_operand_t` not being present.

**Version**: `sqlpp11_0.60_x64-windows-static`
**Repro**: Create a cpp file with just
```cpp
#include <sqlpp11/parameter.h>
```
This fails to compile but below succeed
```cpp
#include <sqlpp11/wrap_operand.h>
#include <sqlpp11/parameter.h>
```

Let me know if I missed anything or something is wrongly configured on my end?
Thanks,

**Comment by rbock** [comment]
Thanks for pointing this out. Fixed on develop.
