### ISSUE TITLE
I want to use NOW() and DATE_SUB() function in mysql

### ISSUE THREAD

**Issue by ZerQAQ** [rbock/sqlpp11#369]
but they seem not be provided.

I want to execute statement like
```
select ..., NOW() as db_time, ....from ...
```
or
```
select * from ... where ..., tb.field < DATE_SUB(NOW, INTERVAL xx SECOND)
```

**Comment by rbock** [comment]
You can use things like

```
insert_into(tabDateTime)
      .set(tabDateTime.colTimePoint = std::chrono::system_clock::now());
```

And do date/time calculations in C++ instead of SQL.

Adding DATE_SUB to the library would be possible, but quite tedious.

**Comment by ZerQAQ** [comment]
I know, but programs may be running in many machine, It's hard to make sure the consistency of time, which lead some problem.

the database is only running on one machine, that is why I want to use NOW()

**Comment by rbock** [comment]
I would argue that your machines should be using a time server. And network latency will make consistency of time an illusion anyway.

But if you really want to use `NOW()` then `sqlpp::verbatim` might be your friend.
