### ISSUE TITLE
I want to use limit function in update statement

### ISSUE THREAD

**Issue by ZerQAQ** [rbock/sqlpp11#370]
but it doesn't work
```
auto sql = sqlpp::update(orm::kTStudent).set(orm::kTStudent.name = "test").limit(1u);
```
```
1.cpp:29:80: error: ‘sqlpp::no_update_list_t::_base_t<sqlpp::detail::statement_policies_t<void, sqlpp::update_t, sqlpp::single_table_t<void, orm::TStudentXx>, sqlpp::no_update_list_t, sqlpp::no_where_t<true> > >::_new_statement_t<sqlpp::consistent_t, sqlpp::update_list_t<void, sqlpp::assignment_t<sqlpp::column_t<orm::TStudentXx, orm::t_student_xx_field::Fname>, sqlpp::text_operand> > > {aka struct sqlpp::statement_t<void, sqlpp::update_t, sqlpp::single_table_t<void, orm::TStudentXx>, sqlpp::update_list_t<void, sqlpp::assignment_t<sqlpp::column_t<orm::TStudentXx, orm::t_student_xx_field::Fname>, sqlpp::text_operand> >, sqlpp::no_where_t<true> >}’ has no member named ‘limit’
     auto sql = sqlpp::update(orm::kTStudent).set(orm::kTStudent.name = "test").limit(1u);
                                                                                ^~~~~
```

**Comment by ZerQAQ** [comment]
it seem it work if I add no_limit_t here
```
// update.h line 107
  using blank_update_t = statement_t<Database, update_t, no_single_table_t, no_update_list_t, no_limit_t, no_where_t<true>>;
```

**Comment by rbock** [comment]
Not all databases support `ORDER_BY` and `LIMIT` in `UPDATE` or `DELETE` queries. But 

a) You can define your own (`no_order_by_t` and `no_limit_t` should go after the `no_where_t`, though)
b) We could add a mysql-specific form of update to the mysql  connector library.

**Comment by ZerQAQ** [comment]
How can we add a mysql-specific form of update to the mysql connector library?

The only way I come up with is to predefine the marco SQLPP11_UPDATE_H and rewrite update.h.

But it require user to include connector first than sqlpp11.

**Comment by rbock** [comment]
See for instance https://github.com/rbock/sqlpp11-connector-sqlite3/blob/master/include/sqlpp11/sqlite3/insert_or.h

**Comment by ZerQAQ** [comment]
So if we add a mysql-specific form of update to the mysql connector library. we need to use update like this?
```
sqlpp::mysql::update(...).set(...).limit(1u);
```

**Comment by rbock** [comment]
Right, you would use that one when you need it.

Alternatively, you could use an sqlpp::custom_query, see for instance https://github.com/rbock/sqlpp11/blob/develop/tests/CustomQuery.cpp#L93

**Comment by rbock** [comment]
Implemented on develop.
