### ISSUE TITLE
Error using update(...).set(...).limit(2u)

### ISSUE THREAD

**Issue by zhengminlai** [rbock/sqlpp11#373]
Sorry to bother you again. 

I want to use `sqlpp::update(..).set(..).limit(2u)` in my project.

I found that it is same with the pull request: https://github.com/rbock/sqlpp11-connector-mysql/pull/71

I modified the source code of sqlpp11-connector-mysql according to the PR (and remove the redundant struct and serializer as suggested), re-compiled the code, and successfully passed the test of `update(..).set(..).limit(...)`.

However, when I use it in my own project, it turns out the error like `sqlpp update has no member named limit`.

I have checked the `/usr/local/include/sqlpp11/mysq/` and `/usr/local/lib` directory (especially the static lib`libsqlpp-mysql.a`), which is all fine.

What else should I do to enable my project to use `update(..).set(..).limit(2u)`?

Thanks.

**Comment by rbock** [comment]
No worries. I suspect you are missing namespace qualification, as this is specific for the mysql-connector.

```
sqlpp::mysql::update(...).order_by(...).limit(...);
```

**Comment by zhengminlai** [comment]
Thank you very much! 

It is fine using `sqlpp::mysql::update(..).order_by(..).limit(..)`. But it goes wrong when using `sqlpp:update(...).order_by(..).limit(..)`.

I think it is strange to use both sqlpp::update(..) and sqlpp::mysql::update(..) in my project. What can I do to enable the `order_by` and `limit` in namespace `sqlpp` (not only `sqlpp::mysql`) so that I can use `sqlpp:update(...).order_by(..).limit(..)`?

Thank you!

**Comment by rbock** [comment]
This is working as intended. The idea is to highlight that this is specific to mysql and if you ever want to migrate to some other database this might require some extra care.

I would assume that the vast majority of your remove/update calls do not require `order_by` and `limit`?

**Comment by zhengminlai** [comment]
Yes, that makes sense. Thank you very much for your support!
