### ISSUE TITLE
How to convert ::sqlpp::chrono::microsecond_point to local time?

### ISSUE THREAD

**Issue by zhengminlai** [rbock/sqlpp11#374]
sqlpp11 will parse and store mysql's datetime object in ::sqlpp::chrono::microsecond_point, I want to convert it to localtime formatted string as 'YYYY-MM-DD HH:MM:SS'. Then I write the following function:

```
std::string DateTimeToString(const ::sqlpp::chrono::microsecond_point &date) {
  char buf[32];
  std::time_t now_c = std::chrono::system_clock::to_time_t(date);
  // utc to local time
  std::tm now_tm = *std::localtime(&now_c);
  strftime(buf, 32, "%F %T", &now_tm);
  return std::string(buf);
}
```

But the result string is still the UTC time string, not my local time string. Did I miss something?

And another question, how do you store mysql's `date` object in sqlpp11? I also need to write a method to convert `date` to formatted `string`. Thank you.

**Comment by rbock** [comment]
At first glance, your translation looks good to me. Can you add '%Z' to the format string?

Also, since we are using the date library anyway, consider 
https://github.com/HowardHinnant/date/wiki/Examples-and-Recipes#the-current-local-time

Dates are stored as 

`using day_point = std::chrono::time_point<std::chrono::system_clock, days>;`

**Comment by zhengminlai** [comment]
I just added %Z to the formated string and it outputs `CST`, but it is still not in consistent with local CST time (in other words, it is still same as UTC time).  I am really confused :(

**Comment by rbock** [comment]
Can you use gmtime instead of localtime for comparison?

**Comment by rbock** [comment]
And of course: Can you double-check the value in the database?

**Comment by zhengminlai** [comment]
It is correct using gmtime. Why gmtime works but localtime does not?

**Comment by zhengminlai** [comment]
Also, I don't know how to convert `string` to `day_point`. Can you help me?

**Comment by zhengminlai** [comment]
I write a method to convert `datetime string`  to `::sqlpp::chrono::microsecond_point ` as follows:
```
::sqlpp::chrono::microsecond_point StringToDateTime(const std::string &date_time_str) {
  std::istringstream in(date_time_str);
  ::date::sys_seconds tp;
  // format: 2000-06-04 14:11:00
  in >> ::date::parse("%F %T", tp);
  return tp;
}
```
But I cannot find any method in `date` library to help me convert `string` to `day_point` :(

**Comment by rbock** [comment]
Regarding gmtime/localtime: I am not an expert at all. stackoverflow might be a better address.

You could use something like this for parsing:

```
  day_point dp;
  // format: 2000-06-04
  in >> date::parse("%F", dp);
```

**Comment by zhengminlai** [comment]
Thanks for your support.

**Comment by zhengminlai** [comment]
Hello, I figure out the time conversion bug, let's see: https://github.com/HowardHinnant/date/issues/689

According to that,  we suggest `sqlpp11` to store the mysql's `datetime` type as `date::local_time<std::chrono::microseconds>` so that it won't cause trouble for users interpreting the time, thank you.

**Comment by rbock** [comment]
Hmm. I need to think about this for a while. I am not exactly a fan of local_time.

I also wonder why this has not occurred elsewhere before? I guess most people are using UTC for their systems?

**Comment by zhengminlai** [comment]
Probably yes.

**Comment by rbock** [comment]
So one thing you could do would be to just

```
db.execute(R"(SET time_zone = '+00:00')");
```

This sets the time_zone for the current connection. This seems to have the desired results.

**Comment by rbock** [comment]
Btw, in tests using column type `DATETIME` I only saw issues with `DEFAULT CURRENT_TIMESTAMP`.
The column type `TIMESTAMP`is known to be prone to timezone magic.

**Comment by zhengminlai** [comment]
In our project, the mysql database reads the system_time_zone (which is CST) as its timezone, and we are not supposed to change it mannually.

**Comment by zhengminlai** [comment]
The `datetime` type is set as `NULL` by default in our project.
