### ISSUE TITLE
The return value of transaction's `commit()` and `rollback`

### ISSUE THREAD

**Issue by zhengminlai** [rbock/sqlpp11#375]
I have the following transaction code:
```
auto tx = start_transaction(db);
db(remove_from(tbStudent).where(tbStudent.sid == 1));
db(insert_into(tbStudent).set(tbStudent.sid = 6,
                            tbStudent.name = "test6",
                            tbStudent.age = 60));
tx.commit(); // or tx.rollback();
```
I want to know what 's the meaning of the `commit` and `rollback`'s return value, thanks.

**Comment by rbock** [comment]
The return value is `void`?

**Comment by zhengminlai** [comment]
Yes, but what if it fails when `commit` or `rollback`? It will throw an exception?

**Comment by zhengminlai** [comment]
I think the doc should add a chapter to introduce `transaction`. For now, I do not really know how to initialize a transaction (how to set isolation level?), and if the `commit` or `rollback` will throw an exception when it fails. Please help me cause my project is very urgent :(

**Comment by zhengminlai** [comment]
I have read the code and figured it out, thanks.

**Comment by rbock** [comment]
Glad to read that!
