### ISSUE TITLE
Error when using `std::distance` to get the result size of `select` statement

### ISSUE THREAD

**Issue by zhengminlai** [rbock/sqlpp11#377]
Hi, I write the following code to add some easy-to-use interfaces for sqlpp:

``` C++
namespace sqlpp{
template <typename Statement>
struct Result {
  Result() {}
  Result(const Statement &s, ::sqlpp::mysql::connection *db);

  int status;
  decltype(::sqlpp::mysql::connection(std::make_shared<::sqlpp::mysql::connection_config>())(
      Statement{})) data;

  int size();
};

template <typename Statement>
Result<Statement>::Result(const Statement &s, ::sqlpp::mysql::connection *db) {
  try {
    this->data = (*db)(s);
    this->status = 0;
  } catch (const sqlpp::exception &e) {
    std::cout << std::string("sqlpp exception: ") + e.what() << std::endl;
    this->status = -1;
  }
}

template <typename Statement>
int Result<Statement>::size() {
  return std::distance(this->data.begin(), this->data.end());
}
}
```
And I use them in my project like this:
``` C++
auto result = sqlpp::Result(sql_no_lock, db_conn); // sql_no_lock is a select statement
LOG("result size -> " << result.size());
const auto &row = result.data.front();
LOG("result size -> " << result.size());
GET_DATA_FROM_ROW(row, target_obj); // copy row data's fields to target_obj's fields
```

It seems like there is something wrong with the `result.size()` method because the output of the above code will be like this:

``` Log
[2021-08-09 20:48:10.577] [22395] [ info  ] result size -> 1 [tango_merchant_db_mch_enter_utils.cc:115] [QueryMchEnterByWhereCond]
[2021-08-09 20:48:10.577] [22395] [ info  ] result size -> 0 [tango_merchant_db_mch_enter_utils.cc:117] [QueryMchEnterByWhereCond]
[2021-08-09 20:48:10.577] [22395] [ error ] query db data exception:accessing value in non-existing row [tango_merchant_db_mch_enter_utils.cc:123] [QueryMchEnterByWhereCond]
```
Can you tell me why invoking two times of `result.size()` gives different results? Is there any other way to simply write a `size()` method for the result of `select` statement? 

Thank you.

**Comment by zhengminlai** [comment]
And the same error appears when I use iterator to get the size of `select` result:
```
template <typename Statement>
int Result<Statement>::size() {
  int cnt = 0;
  for(auto it = this->data.begin(); it != this->data.end(); it++){
    cnt++;
  }
  return cnt;
}
```

**Comment by rbock** [comment]
It is an input iterator. You can traverse it only once.

Some databases offer the size of a result (eg mysql) others don’t (eg postgres). As of today the size is not offered by any connector library.

**Comment by zhengminlai** [comment]
So how could I add a `size()` method for the result set? Our project needs that method very urgently :(

**Comment by rbock** [comment]
Two options:

- You execute a `count` query. In case you want to do pagination, that would be the right thing to do anyway, IMHO
- You modify the result_t to give you access to the native handle, which would give you access to the size, in case of MySQL

If you choose the latter, you might want to think about creating a pull request.

Personally, I would go with the former: Either you want to use the full result set, then you can count while processing the data. Or you want to paginate, then count might be cheaper anyway.

**Comment by zhengminlai** [comment]
I think about another option to copy the results out and store them in a vector called `data`, I write following code:
```
template <typename Statement>
struct Result {
  using Entity = decltype(((::sqlpp::mysql::connection(
      std::make_shared<::sqlpp::mysql::connection_config>())(Statement{})).front()));

  Result() { this->size = 0; }
  Result(const Statement &s, ::sqlpp::mysql::connection *db);
  int size();

  int status;
  std::vector<Entity> data;
  int _size;
};

template <typename Statement>
Result<Statement>::Result(const Statement &s, ::sqlpp::mysql::connection *db) {
  this->_size = 0;
  try {
    decltype(::sqlpp::mysql::connection(std::make_shared<::sqlpp::mysql::connection_config>())(
      Statement{})) rst_set;
    rst_set = (*db)(s);
    for (auto it = rst_set.begin(); it != rst_set.end(); it++) {
      data.push_back(*it);
      this->_size++;
    }
    this->status = 0;
  } catch (const sqlpp::exception &e) {
    TRPC_LOG_ERROR(std::string("sqlpp exception: ") + e.what());
    this->status = -1;
  }
}

template <typename Statement>
int Result<Statement>::size() {
  return _size;
}
```
But the code cannot successfully compile with some type or template errors, and I do not know how to fix it :(

**Comment by zhengminlai** [comment]
I think I would prefer the second option, because there are some consistency problem when executing the same query for two times. I looked into the code in `sqlpp11/include/sqlpp11/result.h` and `sqlpp11-connector-mysql/src/char_result.cpp`, but I've got no idea how to modify the code to add a `size()` method:(

**Comment by zhengminlai** [comment]
Uh, I add a `size()` method in `sqlpp11-connector-mysql/src/char_result.h` and implement it in `sqlpp11-connector-mysql/src/char_result.cpp` like this:

```C++
int char_result_t::size() {
  return mysql_num_rows(_handle->mysql_res);
}
``` 
then I now can use `result.size()` in our project.

Should I also need to add that method to `bind_result.h`? What is the difference between `char_result` and `bind_result`?

**Comment by rbock** [comment]
Thanks for digging :-)

Yes, please create a pull request. A test would be great, too

**Comment by rbock** [comment]
Ah, I see the pull request is already there :-)

**Comment by zhengminlai** [comment]
PR is here: https://github.com/rbock/sqlpp11-connector-mysql/pull/78
