### ISSUE TITLE
How to know if the selected `date` or `datetime` value is `NULL`?

### ISSUE THREAD

**Issue by zhengminlai** [rbock/sqlpp11#378]
Suppose there is a `date` field  in MySQL table `person` called `born_date`, which is allowed to be `NULL`.

I wrote the following method to convert  `date` to `string`:
```C++
std::string DateToString(const ::sqlpp::chrono::day_point &date) {
  //  I think I need to know if the date is empty first
  char buf[32];
  std::time_t now_c = std::chrono::system_clock::to_time_t(date);
  std::tm now_tm = *std::gmtime(&now_c);
  // format: 2000-06-04
  strftime(buf, 32, "%F", &now_tm);
  return std::string(buf);
}
```
I find that when the value of `born_date` in MySQL is `NULL`, the `DateToString(born_date)` returns `1970-01-01`, which is actually the beginning of `utc time`.  

Hence, I want to ask that how can I know if the `born_date` is `NULL` after `sqlpp` fetches it and stores it in `:sqlpp::chrono::day_poin`? And how can I distinguish `NULL` value from a real `1970-01-01` `date` value? Same question remains for `datetime`.

Thanks.

**Comment by rbock** [comment]
You can query `date.is_null()`.

**Comment by zhengminlai** [comment]
`::sqlpp::chrono::day_point` has no member named `is_null()`, `is_null()` is in `result_field`, how can I define a method that pass the `date` or `datetime` result_field as parameter? For example, I can rewrite my method in a way like this:
```C++
std::string DateToString(result_field_date &date) {
  if(date.is_null()) {
    return "";
  }
  char buf[32];
  std::time_t now_c = std::chrono::system_clock::to_time_t((::sqlpp::chrono::day_point )date);
  std::tm now_tm = *std::gmtime(&now_c);
  // format: 2000-06-04
  strftime(buf, 32, "%F", &now_tm);
  return std::string(buf);
}
```

**Comment by rbock** [comment]
Yeah, I did not notice that you were passing a day_point in the original code.

The new code looks reasonable to me :-)
