### ISSUE TITLE
How to inject the selected `row` data to a user-defined `model`?

### ISSUE THREAD

**Issue by zhengminlai** [rbock/sqlpp11#380]
Hey rbock, sorry to bother you again. I want to write a general method that could automatically inject the selected row data to an entity. 

Suppose there is an entity structure:
```C++
struct Student {
  int id;
  string name;
};
```
which is consistent with the table in MySQL:
```SQL
create table `student` (
   `id` int(11) primary key,
   `name` varchar(20) NOT NULL DEFAULT ''
)ENGINE=InnoDB 
```
`sqlpp` will parse the `student` table into class `TStudent`.

The problem is that when using `select` statement to get the results, I have to mannually copy each field value of `TStudent` to `Student`, which makes me very annoyed when the table has tens of fields. It makes me more upset that I have to write such a injection method for each table :(

Therefore, how can I write a inject method to inject the selected `row` data to a user-defined `model`? So that I can use it like this:

```C++
Student st;
const auto& row = select(all_of(TStudent)).from(TStudent).unconditionally().front();
// inject row data to st
inject(st, row);
```

Thanks.

I think my concern is similar to the following issues:
https://github.com/rbock/sqlpp11/issues/148
https://github.com/rbock/sqlpp11/issues/106

**Comment by rbock** [comment]
There is no canonical way to do this.

There are a number of ways to try, though:

- You could write a script that generates such code based on table definitions.
- sqlpp11 result rows contain meta information about the result columns, including their names. You could attempt to use some template metaprogramming to generate a conversion function based on field names.
- You could write another template metaprogram that passes all fields of a result row into the constructor of a given type (this will silently go wrong if fields of compatible type are differently ordered in the table (compared to the constructor arguments)
- You could use boost fusion (requires you to change the way you declare your structs,  but afterwards you can iterate over members)
- You could use an experimental compiler that supports reflection, e.g. https://github.com/lock3/meta

Personally, I would probably go with the first option (or stick with writing those conversions by hand.

**Comment by zhengminlai** [comment]
Thank you. I also prefer the first option. Trying to implement it today!
