### ISSUE TITLE
Dynamic where cannot support complex sql

### ISSUE THREAD

**Issue by zhengminlai** [rbock/sqlpp11#383]
Hey rbock, sorry to bother you so frequently lately.

I want to write the following `where` code in `dynamic_where`:

```c++
auto dynamic_where = sql.where;
dynamic_where.add(A && B);
auto sub_where = sqlpp::value(true);
if (..) {
   sub_where = C || D;
}

if(..) {
  sub_where = sub_where || E;
}

if(..) {
 sub_where = sub_where || F;
}

where.add(sub_where); // which is sql.where = where && sub_where;
```
I tried my best to write `C++` code to achieve this, but it failed with either type errors or syntax errors, so I am here looking for your help. How can I achieve this complex `where` sql with `sqlpp`?

**Comment by rbock** [comment]
Start with `auto sub_where = sqlpp::boolean_expression(db, true);` instead.

**Comment by rbock** [comment]
And no worries about frequent questions.

**Comment by zhengminlai** [comment]
Thank you so much for your help. `sqlpp::boolean_expression` actually solves my problem! Bravo!
