### ISSUE TITLE
Can we add multi assignments to dynamic update?

### ISSUE THREAD

**Issue by zhengminlai** [rbock/sqlpp11#384]
Hi rbock. 

Currently, we use dynamic_update like this:
```C++ 
 auto sql =
      sqlpp::mysql::dynamic_update(*db_conn, table)
          .dynamic_set(...)
          .where(...)
          .limit(2u);
 if (...) {
    sql.assignments.add(table.alpha = 1);
    sql.assignments.add(table.beta = "test");
    sql.assignments.add(table.gamma = 3);
  }
```
Can we put the three assignments into one statement like:
```C++
sql.assignments.add(table.alpha = 1, 
                table.beta = "test",
                table.gamma = 3
);
```

That would be much better, isn't it?

**Comment by rbock** [comment]
Hi Zhengmin,

It would be possible to change that and it would not be that hard.

Since you are trying to learn about the library code: This might be a good training task :-)

**Comment by zhengminlai** [comment]
Sorry for the late reply. I've been quite busy working on my own project lately. I will try to finish that training task :)
