### ISSUE TITLE
Conversion int to integral

### ISSUE THREAD

**Issue by DenyShew** [rbock/sqlpp11#387]
Hello,
I ran into a problem and I can't solve it myself, please tell me how to execute a query like: SELECT 1 FROM table.
I wrote the following code `db.run(sql::select(sql::value<sql::integer>(1).as(sqlpp::alias::a)).from(tab).where(tab.id = 1))`.
But the compiler cannot compile it and throws an error:
```C++
error: could not convert "1" from "int" to "sqlpp::integral"
for(const auto& row : db.run(sql::select(sql::value<sql::integer>(1).as(sqlpp::alias::a)).from(tab).where(tab.id = 1)))
```

Thank you in advance

**Comment by rbock** [comment]
Hi,

At first glance, I see two issues with the code:

1. In most cases, you should not specialize `sqlpp::value` explicitly.
2. The `where` condition currently contains an assignment.

```C++
for(const auto& row : db.run(select(sqlpp::value(1).as(sqlpp::alias::a)).from(tab).where(tab.id == 1)))
```

Note that if you just want to `SELECT 1`, you could also simply

```C++
for (const auto& row : db(select(sqlpp::value(1).as(sqlpp::alias::a))))
```

Hope this helps

**Comment by DenyShew** [comment]
Thank you very much:)
