### ISSUE TITLE
ddl2cpp does not work with pyparsing 3+

### ISSUE THREAD

**Issue by sjoubert** [rbock/sqlpp11#388]
When using pyparsing 3+ (tested with 3.0.5) to run ddl2cpp I get the following error:
```
Traceback (most recent call last):
  File "/usr/bin/sqlpp11-ddl2cpp", line 379, in <module>
    column.hasAutoValue = column.hasAutoValue or (autoId and sqlColumnName == 'id')
AttributeError: 'ParseResults' object has no attribute 'hasAutoValue'
```
Reverting back to pyparsing 2.4.7 fixes the issue.

It seems things have changed in version 3 in the way new attributes are handled. See entry for version 3.0.4 in https://github.com/pyparsing/pyparsing/blob/master/CHANGES

I'm not sure what needs to be updated in the script though to make it compatible with the last major version of pyparsing.

**Comment by rbock** [comment]
Thanks for the report. The latest Ubuntu is still shipping 2.4.7...

If that's the only error you get, can you try:

```python
        hasAutoValue = column.hasAutoValue or (autoId and sqlColumnName == 'id')
        if hasAutoValue:
```

**Comment by sjoubert** [comment]
:ok_hand: Just tested it, works perfectly. Re-reading the release notes, this patch totally makes sense to me now. Thanks.

**Comment by rbock** [comment]
Cool, thanks for testing, confirming, and creating the PR :-)
