### ISSUE TITLE
Errors while compiling

### ISSUE THREAD

**Issue by Moeplhausen** [rbock/sqlpp11#389]
Hi,

I'm getting the following errors with ggc on the develop branch:

1:
/source/build/_deps/sqlpp11-src/include/sqlpp11/mysql/bind_result.h: In member function 'void sqlpp::mysql::bind_result_t::bind_impl()':
/source/build/_deps/sqlpp11-src/include/sqlpp11/mysql/bind_result.h:403:24: error: 'exception' is not a member of 'sqlpp'; did you mean 'std::exception'?

Can be fixed with adding the following to the bind_result.h file
`#include <sqlpp11/exception.h>
`
2:
/source/build/_deps/sqlpp11-src/include/sqlpp11/mysql/bind_result.h:48:14: error: 'vector' in namespace 'std' does not name a template type
   48 |         std::vector<char> bound_text_buffer;  // also for blobs

Can be fixed with adding the following to the bind_result.h file
`#include <vector>`

Am I doing something wrong or could those two fixes be added to the project?

`gcc --version = 11.1.0`

**Comment by rbock** [comment]
Hi, Thanks for the report. I am surprised that I don't see that myself?

Anyway: Yes, your suggested fix totally makes sense. Do you want to create a PR? Otherwise I am happy to create a commit, too, of course.

Cheers,
Roland

**Comment by Moeplhausen** [comment]
Please just commit it yourself, that would save me the work from forking, etc.

I haven't really analysed it myself but found it strange that I am apparently the only one who experienced this error. 
Maybe it is the compiler or that I'm only compiling sqlp11 with the mysql stuff (no PostgreSQL, etc). As a consequence I didn't get the vector or exception includes in my build.
