### ISSUE TITLE
How to use sqlpp::blob in PostrgeSQL ?

### ISSUE THREAD

**Issue by Axil-ww** [rbock/sqlpp11#392]
PostrgeSQL have not type BLOB, it have BYTEA.
And using sqlpp::blob results in an error:
column "data" is of type bytea but expression is of type bit
LINE 1: ...,col,row,data) VALUES(2,0,0,x'1AED330A...
______________________________________^

Does the library take into consideration the features of database implementations?

**Comment by rbock** [comment]
@matthijs I assume you can answer that better than I can?

**Comment by Axil-ww** [comment]
https://github.com/matthijs/sqlpp11-connector-postgresql/pull/86#issuecomment-762707151
19 jan.

**Comment by rbock** [comment]
Hmm. So we will probably move the postgresql connector into this repository soon (as with mysql and sqlite3 as can be seen on develop). No promises, but the general thinking is that it will be easier to handle changes in the core library and the connectors (which might influence each other, of course).

I admit that I haven't touched PostgreSQL for a couple of years. Could you provide a minimal, but complete example (i.e. DDL, command line for generating code, minimal code exposing the issue)?

**Comment by rbock** [comment]
Postgresql is now supported in the core library directly (see rbock/sqlpp11@4c94260), and I added blob support on develop (see rbock/sqlpp11@310a624).

Please give it a try. Tests work fine for me, but CI support is missing and it might eat your cat or something :-)

**Comment by rbock** [comment]
Friendly ping :-)

Do you have a way to verify if this works for you?

**Comment by Axil-ww** [comment]
Thank you for your work. But our development has taken a different path, and there is no longer an possibility to test it. I'll just close the request.
