### ISSUE TITLE
Why not throw out the error code of database?

### ISSUE THREAD

**Issue by zhengminlai** [rbock/sqlpp11#393]
Hi rbock, our team has used sqlpp11 for two months. Everything goes fine and thanks to your well done ORM framework, our coding efficiency has been improved a lot.  Thanks again for all your kind support and replies :)

But there is one more thing that I confuse about is, why you didn't put error code into `sqlpp::excetion` when designing it? It is very useful to catch the error code thrown by the native database (such as `ROW NOT EXIST`, `PRIMARY KEY CONFLICT WHEN INSERT`), based on which we can flexibly adjust our code logics. Isn't it?

**Comment by rbock** [comment]
Thanks for the feedback. I am happy to read that you are making such good progress :-)

To me, such errors always indicated a logic error in the C++ code that needs to be fixed.

That being said, individual connectors can, of course, add more information to exceptions. See the postgresql connector. It would be possible to add such constructs to other connectors as well.

**Comment by zhengminlai** [comment]
Thank you.

**Comment by Erroneous1** [comment]
> 
> To me, such errors always indicated a logic error in the C++ code that needs to be fixed.

One counter example would be inserting something that has a non-auto incrementing unique key. In that situation it might be best to try to insert, change the key if it fails, and try again. Also there's other issues that might have nothing to do with the code, like lock wait timeouts, full storage, or communication errors. These can often be indistinguishable without getting the full error state.

**Comment by rbock** [comment]
My view on these example is different, but again: if that is what you need, then you could add more specific exceptions in the connectors.

I wouldn't mind.
