### ISSUE TITLE
Is connection pool stable now?

### ISSUE THREAD

**Issue by zhengminlai** [rbock/sqlpp11#396]
Hi rbock, I want to try do use connection pool, but found no documentation and unit test examples yet. 

I tried to refer to the issues like https://github.com/rbock/sqlpp11/issues/168, but I am not sure if it is stable and safe enough to use `connection_pool.h` and `pool_connection.h` in production environment.

Another question is, `sqlpp11-mysql-connector` currently use AUTO_RECONNECT feature from the mysql server. Is it safe enough to totally rely on mysql server to do auto reconnect? I think a better way to do auto_reconnect is to mannually check the connection is alive each time before executing a statement. For example, we can optimize `select_impl` function in `sqlpp11-connector-mysql/src/connection.cpp` from:

```C++
char_result_t connection::select_impl(const std::string& statement) {
  execute_statement(*_handle, statement);
  std::unique_ptr<detail::result_handle> result_handle(
      new detail::result_handle(mysql_store_result(_handle->mysql.get()), _handle->config->debug));
  if (!*result_handle) {
    throw sqlpp::exception("MySQL error: Could not store result set: " +
                           std::string(mysql_error(_handle->mysql.get())));
  }

  return {std::move(result_handle)};
}

```

to:

``` C++
char_result_t connection::select_impl(const std::string& statement) {
  //  if the connection is not alive, mannually reconnect
  if(!is_valid() && !_transaction_active) {
     reconnect(); 
  }
  execute_statement(*_handle, statement);
  std::unique_ptr<detail::result_handle> result_handle(
      new detail::result_handle(mysql_store_result(_handle->mysql.get()), _handle->config->debug));
  if (!*result_handle) {
    throw sqlpp::exception("MySQL error: Could not store result set: " +
                           std::string(mysql_error(_handle->mysql.get())));
  }

  return {std::move(result_handle)};
}

```
and we should do the same for other functions, isn't it better?

**Comment by rbock** [comment]
Hi,

The connection pool is not ready (I am tempted to remove the current code as the contributor is not likely to finish it).

Regarding `AUTO_RECONNECT`: I have not seen issues with it, but that does not mean they don't exist. Another strategy I have seen in a custom-built connection pool was to ping the connection before taking it from the pool. If the ping fails, then drop the connection and use another one.

I would not do a check for every single select. Losing connections should be very rare. In my view it would be better to handle the exception.

**Comment by zhengminlai** [comment]
Thanks for the kind reply.
