### ISSUE TITLE
any sample for  raw sql 

### ISSUE THREAD

**Issue by vanehu** [rbock/sqlpp11#403]
how can i do query like  "select date from tbl_a " ?

**Comment by rbock** [comment]
Hi,

Not sure what you mean? Can you elaborate?

Usually, you would use sql2cpp to generate headers for your tables (and include those), create a connection object for your database and so something like

```C++
constexpr t = TablA{}; // see generated header for the correct name
for (const auto& row : db(select(t.date)).from(t).unconditionallly())) {
   std::cerr <<row.date << '\n';
}
```

**Comment by vanehu** [comment]
thank u for reply but  there is 5000+ tables  only table name is diffrent 
so i wanna query data from  dba.taba   dbb.tabb

**Comment by rbock** [comment]
The library is using the _traits classes to determine what is accepted as table or as column, etc.
Thus, you _could_ replace the generated tables and columns with something that can be assigned the "real" table name.

This is not trivial, but certainly doable.

Whether it is worth the effort, is something you need to determine.

**Comment by vanehu** [comment]
is there any way to change table name during runtime

**Comment by rbock** [comment]
No, that's why I said you could replace the generated tables with something that can be assigned the "real" table name (at runtime).
