### ISSUE TITLE
Basic Usage FetchContent doesn't download sqlpp11 source code or build anything ?

### ISSUE THREAD

**Issue by linrongbin16** [rbock/sqlpp11#405]
Hi, I'm new to sqlpp11, I want to build it from source code and use in my pybind11 modules.

I need to build it both in macOS 10.15.x and ubuntu  20.04.  I split dependencies into two parts: 1. System Denepdencies, 2. Source Code Denepdencies.

For the System Dependencies, I installed them by macOS homebrew or ubuntu apt. For Source Code Dependencies, I use git clone to download source code in a local directory `third_party`.

The project directory structure is like:

```
+ src
   | header.h
   | main.cc
| src.cc
| CMakeLists.txt
+ third_party
   |  pybind11
   | sqlpp11
   | spdlog
   | abseil-cpp
   | fmt
```

I use pkg-config and include_directories, target_link_libraries to add system dependencies, use `add_subdirectory` to add source code dependencies.

Here's my `CMakeLists.txt`:
```
cmake_minimum_required(VERSION 3.13)
project(my_module VERSION 0.0.1 LANGUAGES CXX)
set(CMAKE_CXX_STANDARD 14)
set(CMAKE_CXX_STANDARD_REQUIRED ON)

find_package(PkgConfig REQUIRED)

set(CMAKE_THREAD_PREFER_PTHREAD TRUE)
set(THREADS_PREFER_PTHREAD_FLAG TRUE)
find_package(Threads REQUIRED)

find_package(Python COMPONENTS Interpreter Development)
message("Python_FOUND:${Python_FOUND}")
message("Python_VERSION:${Python_VERSION}")
message("Python_Development_FOUND:${Python_Development_FOUND}")
message("Python_LIBRARIES:${Python_LIBRARIES}")

set(Boost_USE_STATIC_LIBS ON)
set(Boost_USE_DEBUG_LIBS OFF)
set(Boost_USE_RELEASE_LIBS ON)
set(Boost_USE_MULTITHREADED ON)
set(Boost_USE_STATIC_RUNTIME OFF)
find_package(Boost REQUIRED)
message("Boost_FOUND:${Boost_FOUND}")
message("Boost_VERSION:${Boost_VERSION}")
message("Boost_INCLUDE_DIRS:${Boost_INCLUDE_DIRS}")
message("Boost_LIBRARIES:${Boost_LIBRARIES}")

pkg_check_modules(CurlPP REQUIRED curlpp)
message("CurlPP_FOUND:${CurlPP_FOUND}")
message("CurlPP_INCLUDE_DIRS:${CurlPP_INCLUDE_DIRS}")
message("CurlPP_LIBRARIES:${CurlPP_LIBRARIES}")
message("CurlPP_LIBRARY_DIRS:${CurlPP_LIBRARY_DIRS}")

set(CMAKE_POSITION_INDEPENDENT_CODE ON)
add_subdirectory(third_party/pybind11)

set(ABSL_PROPAGATE_CXX_STD ON)
add_subdirectory(third_party/abseil-cpp)

# set(USE_SYSTEM_TZ_DB ON)
# set(BUILD_TZ_LIB ON)
# set(COMPILE_WITH_C_LOCALE ON)
# add_subdirectory(third_party/date)

pkg_check_modules(SQLite3 REQUIRED sqlite3)
message("SQLite3_FOUND:${SQLite3_FOUND}")
message("SQLite3_INCLUDE_DIRS:${SQLite3_INCLUDE_DIRS}")
message("SQLite3_LIBRARY_DIRS:${SQLite3_LIBRARY_DIRS}")
message("SQLite3_LIBRARIES:${SQLite3_LIBRARIES}")
pkg_check_modules(MySQLClient REQUIRED mysqlclient)
message("MySQLClient_FOUND:${MySQLClient_FOUND}")
message("MySQLClient_INCLUDE_DIRS:${MySQLClient_INCLUDE_DIRS}")
message("MySQLClient_LIBRARY_DIRS:${MySQLClient_LIBRARY_DIRS}")
message("MySQLClient_LIBRARIES:${MySQLClient_LIBRARIES}")

include(FetchContent)   # this is from sqlpp11 readme
FetchContent_Declare(sqlpp11
  GIT_REPOSITORY https://github.com/rbock/sqlpp11
  GIT_TAG        2bc89b34ad3cc37b6bca9a44a3529ff2d8fe211f       # I want release/0.61
)
set(BUILD_MYSQL_CONNECTOR ON)
set(BUILD_SQLite3_CONNECTOR ON)
FetchContent_MakeAvailable(sqlpp11)

include_directories(.)
include_directories(SYSTEM /usr/include)
include_directories(SYSTEM /usr/local/include)
include_directories(SYSTEM ${Boost_INCLUDE_DIRS})
include_directories(SYSTEM ${CurlPP_INCLUDE_DIRS})
include_directories(SYSTEM third_party/fmt/include)
include_directories(SYSTEM third_party/pybind11/include)
include_directories(SYSTEM third_party/abseil-cpp)
include_directories(SYSTEM third_party/spdlog/include)
include_directories(SYSTEM third_party/date/include)
include_directories(SYSTEM third_party)

link_directories(/usr/lib)
link_directories(/usr/local/lib)
link_directories(${CurlPP_LIBRARY_DIRS})

add_library(my_module MODULE
        third_party/cpp-base64/base64.cpp
        src/common/counter.cc
        src/common/yadatetime.cc
        src/common/util.cc
        src/config.cc
        src.cc)
target_link_libraries(my_module PRIVATE pybind11::module pybind11::lto pybind11::windows_extras absl::time absl::flat_hash_map ${CurlPP_LIBRARIES} sqlpp11::sqlpp11)
pybind11_extension(my_module)
pybind11_strip(my_module)
set_target_properties(my_module PROPERTIES
        CXX_VISIBILITY_PRESET "hidden"
        CUDA_VISIBILITY_PRESET "hidden")

```

**Comment by rbock** [comment]
@Leon0402 Can you take a look, too?

@linrongbin16 Note that sqlpp11 and the included connector libraries are header-only since 0.61. There is no need to build them.

**Comment by Leon0402** [comment]
> GIT_TAG        2bc89b34ad3cc37b6bca9a44a3529ff2d8fe211f       # I want release/0.61
You can also specify just 0.61 -> All releases are tags as well 

> set(BUILD_SQLite3_CONNECTOR ON)
It's called `BUILD_SQLITE3_CONNECTOR`

I don't quite get what you're doing. Why do you pull sqlpp11 via FetchContent, but not the other ones like spdlog, date or fmt? These all work very well with FetchContent. 

It seems you're mixing up FetchContent and git submodules (or git subtree) perhaps? 

git submodule  will clone a git repo into your repository into some directory. For instance third_party. Your describes setup sounds very much like it. 
You clone a bunch of repos into a directory (third_party) and then do add_subdirectory. 
If this is what you want to achieve, you should do the same thing with sqlpp11 as well. 

FetchContent on the other hand is a native cmake alternative to git submodule. It allows to manage your dependencies from within cmake, doesn't rely on version control and has a couple of advantages like handling transitive dependencies ... 

The difference though is that FetchContent will clone the repositories into your build folder at cmake configure time. So you will find it at `build/_deps/sqlpp11-build` or something like that. 

If you decide to use the cmake approach with FetchContent, you should probably should use it for the others as well and don't mix it with git submodule.

Also you should link against a connector like `sqlpp11::mysql` and not against `sqlpp11::sqlpp11`. 

As said by @rbock it's a header only library, so nothing will be built. If you get some compiler or generator error you should post the error message as well.

**Comment by linrongbin16** [comment]
thanks for reply, and how should I generate model files ? I see the document, it seems there is a tool written in python, but I don't know where to get it

**Comment by linrongbin16** [comment]
Hi @Leon0402 , I see in sqlpp11 CMakeLists.txt file, there's library like `sqlpp11::sqlpp11`, `sqlpp11::sqlpp11_mysql`, `sqlpp11::sqlpp11_sqlite3`, `sqlpp11::sqlpp11_postgresql`, etc. As mentioned, if sqlpp11 is head only, so I don't need to build these libraries, correct ?
