### ISSUE TITLE
How to do transaction/commit/rollback on mysql/sqlite3 ?

### ISSUE THREAD

**Issue by linrongbin16** [rbock/sqlpp11#406]
Hi, is there any document about how to do transaction/commit/rollback on mysql/sqlite3 ?

**Comment by rbock** [comment]
Good point. Need to write that.

In short: You can 

```c++
auto tx = start_transaction(db);
// do something
tx.commit(); // or tx.rollback();
```

If a transaction goes out of scope without `commit` or `rollback` being called on it, it will automatically `rollback`.

**Comment by linrongbin16** [comment]
thanks

**Comment by linrongbin16** [comment]
Hi @rbock , if any thing wrong during the transaction, sqlpp11 will throw sqlpp11::exception, correct ?
So my best practice should be like below, correct ?
```
try {
  auto tx = start_transaction(db);
  tx.commit();
} catch (sqlpp11::exception e) {
  tx.rollback();
}
```

**Comment by rbock** [comment]
`tx` is not defined in the `catch` block this way.

But as mentioned above, you don't need to call `tx.rollback()` yourself. It will automatically rollback in the destructor if it is not committed.

**Comment by linrongbin16** [comment]
Thanks, so I think all I need is something like:
```
auto tx = sqlpp::start_transaction(db);
// do my select/insert/update
tx.commit();
```

Thanks for reply
