### ISSUE TITLE
When should I close mysql/sqlite3 connection ? Or I don't need to close them ?

### ISSUE THREAD

**Issue by linrongbin16** [rbock/sqlpp11#407]
When and how should I close mysql/sqlite3 connection ?

Or they use a static thread local implementation, so actuall every time I write code:
```
	sqlpp::mysql::connection db(config);
```

Actually I get the same mysql/sqlite3 connection on the same thread ? (and when process ends, the connection is closed) So nothing need to be done for close ?

**Comment by rbock** [comment]
Connections close when they go out of scope.

Thread-safety is "inherited" from the underlying library. E.g. if something is safe to do with sqlite3, it is safe to do that with sqlpp11::sqlite3.

**Comment by linrongbin16** [comment]
thanks
