### ISSUE TITLE
Weird namespace comment generated by ddl2cpp

### ISSUE THREAD

**Issue by MrJia1997** [rbock/sqlpp11#423]
It looks like `ddl2cpp` will generate namespace closing comments in the order it opens them. This is weird since according to the [Google C++ Style Guide](https://google.github.io/styleguide/cppguide.html#Namespaces) (or any reasonable guide), these comments should be added in reversed order.

I can submit a PR to fix this. Please let me know if you will accept this.

https://github.com/rbock/sqlpp11/blob/1b10d360309223ba226fc0f4355b171d7c046602/scripts/ddl2cpp#L462-#L466

**Comment by rbock** [comment]
Thanks for pointing this out. Sure, I would accept that :-)
