### ISSUE TITLE
What is CURL and where can I download it from?

### ISSUE THREAD

**Issue by juandent** [rbock/sqlpp11#425]
Upon installing with CMAKE GUI I get this error:

CMake Error at C:/Program Files/CMake/share/cmake-3.22/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find CURL (missing: CURL_LIBRARY CURL_INCLUDE_DIR)

What is this? where can I download it from? 

Also, where can I download the connectors for SQLITE3 and MYSQL?

Thanks!!
Juan

**Comment by rbock** [comment]
See https://en.wikipedia.org/wiki/CURL
It is available for most OSs. Please check paths or install.

The connectors are header-only and come with the sqlpp11 library, see 
https://github.com/rbock/sqlpp11/blob/main/README.md#build-and-install
