### ISSUE TITLE
does sqlpp11 support dynamic from or with statements?

### ISSUE THREAD

**Issue by juandent** [rbock/sqlpp11#429]
I am looking for a SQL DSL that supports dynamic from or WITH statements: does sqlpp11 do this?

**Comment by rbock** [comment]
sqlpp11 supports `dynamic_from`, see for example:
https://github.com/rbock/sqlpp11/blob/main/tests/core/serialize/From.cpp

**Comment by juandent** [comment]
great ! Now i only need to be able to compile MySQL in debug mode
Is it necessary to download the connector for MSql or is sqlpp11 eenough?

**Comment by juandent** [comment]
what do I  need to interact with SQLITE? is it part of sqlpp11 download?

**Comment by rbock** [comment]
The connectors for mariadb/mysql, sqlite3/sqlcipher, and postgresql come with this library.

I suggest you start here: https://github.com/rbock/sqlpp11#build-and-install
There is some documentation here: https://github.com/rbock/sqlpp11/blob/main/docs/Home.md (always happy to see contributions)
And the tests might be quite informative, too.
