### ISSUE TITLE
centos 7 compile error 

### ISSUE THREAD

**Issue by Meigumikato** [rbock/sqlpp11#431]
centos 7
cmake command : cmake3 -B build -DBUILD_MYSQL_CONNECTOR=ON -DCMAKE_INSTALL_PREFIX=./output
use toolchains devtoolset-8 gcc 8.3.1

Scanning dependencies of target sqlpp11_assert_case
[ 64%] Building CXX object tests/core/static_asserts/CMakeFiles/sqlpp11_assert_case.dir/case.cpp.o
In file included from /root/sqlpp11/include/sqlpp11/type_traits.h:33,
                 from /root/sqlpp11/include/sqlpp11/data_types/no_value/data_type.h:30,
                 from /root/sqlpp11/include/sqlpp11/data_types/no_value.h:30,
                 from /root/sqlpp11/tests/core/usage/MockDb.h:32,
                 from /root/sqlpp11/tests/core/static_asserts/case.cpp:26:
/root/sqlpp11/include/sqlpp11/case.h: In instantiation of ‘constexpr sqlpp::assert_case_when_boolean_expression_t::assert_case_when_boolean_expression_t(T&& ...) [with T = {}]’:
/root/sqlpp11/include/sqlpp11/case.h:179:63:   required by substitution of ‘template<class When> decltype (sqlpp::detail::case_when_impl(sqlpp::check_case_when_t<When>{}, when)) sqlpp::case_when(When) [with When = sqlpp::assignment_t<sqlpp::column_t<test::TabBar, test::TabBar_::Gamma>, sqlpp::boolean_operand>]’
/root/sqlpp11/tests/core/static_asserts/case.cpp:54:49:   required from ‘void {anonymous}::when_check(const When&) [with Assert = sqlpp::assert_case_when_boolean_expression_t; When = sqlpp::assignment_t<sqlpp::column_t<test::TabBar, test::TabBar_::Gamma>, sqlpp::boolean_operand>]’
/root/sqlpp11/tests/core/static_asserts/case.cpp:96:76:   required from here
/root/sqlpp11/include/sqlpp11/portable_static_assert.h:41:21: error: static assertion failed: argument is not a boolean expression in case_when()
       static_assert(wrong_t<T...>::value, message); \
                     ^~~~~~~~~~~~~
/root/sqlpp11/include/sqlpp11/case.h:54:3: note: in expansion of macro ‘SQLPP_PORTABLE_STATIC_ASSERT’
   SQLPP_PORTABLE_STATIC_ASSERT(assert_case_when_boolean_expression_t,

**Comment by Meigumikato** [comment]
![image](https://user-images.githubusercontent.com/49133741/158061085-e8a25e14-9c38-466b-8a4a-c491d3ad394f.png)

**Comment by rbock** [comment]
Which compiler version are you using?

**Comment by Meigumikato** [comment]
gcc 8.3.1

**Comment by rbock** [comment]
OK, thanks, I will try to install that, but it will probably take some time.

Note that failures to compile these tests are not necessarily a hard problem and you might be able to use the library nonetheless. They test `static_assert` as described here: https://www.youtube.com/watch?v=zxDzMjfsgjg
