### ISSUE TITLE
why  ddl2cpp not support primary key?

### ISSUE THREAD

**Issue by Meigumikato** [rbock/sqlpp11#432]
why not ddl2cpp not support primary key

**Comment by clamxyz** [comment]
change file ddl2cpp， line 262  "+ pp.Group(pp.delimitedList(ddlColumn | pp.Suppress(ddlConstraint))).setResultsName(" to 
"+ pp.Group(pp.delimitedList(pp.Suppress(ddlConstraint) | ddlColumn)).setResultsName("
it  work fine for me.
