### ISSUE TITLE
 sqlpp::value_or_null with prepared statements

### ISSUE THREAD

**Issue by dirkvdb** [rbock/sqlpp11#435]
Using the latest release I can't use sqlpp::value_or_null in combination with prepared statements.
I was using tvin before, but I get compilation errors now that I had to migrate to value_or_null

```
error C2679: binary '=': no operator found which takes a right-hand operand of type 'sqlpp::value_or_null_t<sqlpp::integer>' (or there is no acceptable conversion)
```

**Comment by rbock** [comment]
I suspect that you might have been the only user of `tvin`...

Adding an assignment operator would be rather simple.
Can you show me a snippet of what you want to do?

**Comment by dirkvdb** [comment]
I wrote a small function to replace the removed tvin
```
inline auto tvin(int64_t val)
{
    if (val == 0) {
        return sqlpp::value_or_null<sqlpp::integer>(sqlpp::null);
    } else {
        return sqlpp::value_or_null(val);
    }
}
```

I use it like this:
```
void InputDataBase::store_wlas_data(const std::vector<WlasInfo>& data)
{
    auto insertQuery = []() {
        return insert_into(WlasTable).set(
            WlasTable.vhsid   = parameter(WlasTable.vhsid),
            WlasTable.naam    = parameter(WlasTable.naam),
            WlasTable.beknaam = parameter(WlasTable.beknaam));
    };

    auto query = _db.prepare(insertQuery());

    for (auto& curData : data) {
        query.params.vhsid   = tvin(curData.vhasId);
        query.params.naam    = curData.name;
        query.params.beknaam = curData.catchment;
        _db(query);
    }
}
```

This works fine for regular queries, but not for prepared statements

**Comment by rbock** [comment]
Thanks for the details. I added the missing assignment operator for parameters and some very basic tests.

Please give it a try.

**Comment by dirkvdb** [comment]
It works, thanks a lot!
