### ISSUE TITLE
ddl2cpp fails to parse CONSTRAINT declaration

### ISSUE THREAD

**Issue by jhunold** [rbock/sqlpp11#437]
After the last rewrite of ddl2cpp on current master, my table definitions fail to parse with
```
Error: datatype of foo.CONSTRAINT is not supported.
Error: unsupported datatypes.
Possible solutions:
A) Implement this datatype (examples: sqlpp11/data_types)
B) Extend/upgrade ddl2cpp (edit types map)
C) Raise an issue on github
```
Everything works fine if I revert the changes and use the old version.
I opt for option C because I don't have any experience with Python's parser logic. 
I guess this went unnoted because none of the `.sql` files in the repositoy contain a CONSTRAINT definition. For what I guess, even declaring UNIQUE columns should fail.

**Comment by rbock** [comment]
Thanks for reporting the issue!
I was away from my computer for a while, but I think I fixed this now. If you still face issues, a small example would be great.

**Comment by rbock** [comment]
Friendly ping :-)
Does this work for you now?

**Comment by jhunold** [comment]
Yes, of course.

**Comment by rbock** [comment]
Thanks for the confirmation :-)
