### ISSUE TITLE
named expression uses tables unknown  --- Dynamic Select with multiple joins 

### ISSUE THREAD

**Issue by chrisoutwright** [rbock/sqlpp11#443]
How can a static query like:
```
auto& query = db(select().columns(count(act.actorId).as(actCount), film.title).
			from(act.join(actfilm).on(act.actorId == actfilm.actorId).
				left_outer_join(film).on(film.filmId == actfilm.filmId)).
			where(film.title.like("%ON%")).group_by(film.title).having(count(act.actorId) > 6))
```

be transformed to a dynamic one?

This would not work (I left out the having, group_by, count parts):

```
auto prepared_insert2 = dynamic_select(db).dynamic_columns().dynamic_from().dynamic_where();


			prepared_insert2.from.add(dynamic_join(actfilm).on(act.actorId == actfilm.actorId));
			prepared_insert2.from.add(dynamic_left_outer_join(film).on(film.filmId == actfilm.filmId));

			prepared_insert2.selected_columns.add(act.actorId);
			prepared_insert2.selected_columns.add(film.title);

			prepared_insert2.where.add(film.title.like("%LL"));

...


```
Apart from this, can parameter(sqlpp...) be used in a dynamic select, or in the having statement as in having(count(act.actorId) > parameter(sqlpp...)) ?

**Comment by rbock** [comment]
Hi Chris,

```C++
// You need to start with a table in the dynamic from. Looking at the rest of your code, I guess act makes sense:
auto prepared_select2 = dynamic_select(db).dynamic_columns().dynamic_from(act).dynamic_where();

// The condition is using a table that is not in the statically known set of tables.
// You need to wrap the expression in sqlpp::without_table_check
			prepared_select2.from.add(dynamic_join(actfilm).on(without_table_check(act.actorId == actfilm.actorId)));
			prepared_select2.from.add(dynamic_left_outer_join(film).on(without_table_check(film.filmId == actfilm.filmId)));

// This just works
			prepared_select2.selected_columns.add(act.actorId);
// Here you need to indicate that you intentionally add something that is not in the statically known set of tables
			prepared_select2.selected_columns.add(without_table_check(film.title));

			prepared_select2.where.add(without_table_check(film.title.like("%LL")));
```

Parameters cannot be used with dynamically added query parts.
In the `having` clause parameters should work just fine.

Hope that helps?

Best,
Roland

**Comment by chrisoutwright** [comment]
Hello Roland,
Thank you very much for the quick reponse.

I'll try with without_table_check as soon as I can.
Is there a reason why the for dynamic statements one can defer (statically known)  until like when:
.from.add(dynamic_join(actfilm).on(...) is actually introducing the table to be known? Or asked other way: can this be programatically solved (by introducing other type traits mechanisms), without "without_table_check" ? What is the particular reason this was not possible, can you tell exactly?

with prepared statement:

I get _assert_having_no_non_aggregates_t_ when trying to set the params in the following query later:

```
		auto& query = db.prepare(select().columns(count(act.actorId).as(actCount), film.title).
			from(act.join(actfilm).on(act.actorId == actfilm.actorId).
			left_outer_join(film).on(film.filmId == actfilm.filmId)).
			where(film.title.like("%ON%")).group_by(film.title).having(count(act.actorId) > parameter(sqlpp::integer(), numAct)));
```
When replacing parameter(sqlpp::integer(), numAct) with say, 6, again, I get query.params ..... as option (due to the assert going  away I assume). Can I we still try to have params in the having part after (after <>= etc. comparison)?

**Comment by rbock** [comment]
Hi Chris,

dynamically added tables are not statically known in the statement. They are added as type-erased data to the statement.
The experimental sqlpp17 shows how this could be done differently (using std::optional), so it _could_ be solved programmatically.

The aggregate check is not correct. A quick way to fix this would be

```diff
diff --git a/include/sqlpp11/parameter.h b/include/sqlpp11/parameter.h
index 8e4cee2..782fcc3 100644
--- a/include/sqlpp11/parameter.h
+++ b/include/sqlpp11/parameter.h
@@ -44,6 +44,7 @@ namespace sqlpp
     using _nodes = detail::type_vector<>;
     using _parameters = detail::type_vector<parameter_t>;
     using _can_be_null = std::true_type;
+    using _is_aggregate_expression = std::true_type;
 
     using _instance_t = member_t<NameType, parameter_value_t<ValueType>>;
 ```

It should help you for now. But that might cause other problems on rare oaccasions (because parameters would now generally be considered aggregates). I need to think about this a bit more...

Best,
Roland

**Comment by rbock** [comment]
I believe this should be fixed now. Please give it a try and let me know.

**Comment by chrisoutwright** [comment]
Hello Roland.
Yes perfect. With that addition it is working now! Thank you.

**Comment by rbock** [comment]
Thanks for the feedback!
