### ISSUE TITLE
Combining sqlpp::remove and sqlpp::select

### ISSUE THREAD

**Issue by mikolajkucinski** [rbock/sqlpp11#448]
Hello everyone. I am trying to reproduce this raw SQL querry.

```
DELETE FROM tableA WHERE idA IN 
(
  SELECT idA FROM tableB WHERE idB = 177
);
```

Currently I create the select statement, prepare vector of IDs in a for loop and use sqlpp::remove_from combined with sqlpp::value_list. Is there a better approach for that?

**Comment by rbock** [comment]
Hi Mikolaj

You can write it almost exactly as the intended SQL (see pushed example). In your case something like 

```
remove_from(tableA).where(tableA.idA.in(select(tableB.idA).from(tableB).where(tableB.idB == 177)));
```

Best,
Roland

**Comment by mikolajkucinski** [comment]
Thanks @rbock !
