### ISSUE TITLE
Union all - different column names

### ISSUE THREAD

**Issue by damiangrzelak** [rbock/sqlpp11#452]
Hi, 
my question is related with: https://github.com/rbock/sqlpp11/issues/124

I want to write a query something like that:

`SELECT tab1.COL_A FROM tab1 UNION ALL SELECT tab2.COL_B FROM tab2 `

`tab1.COL_A` and `tab2.COL_B`  have the same type, but different names. And this caues:

> both arguments in a union have to have the same result columns (type and name)

I'm trying to modify select from https://github.com/rbock/sqlpp11/issues/124#issuecomment-257638067 but I got the same result.

It is possible somehow to write this query using sqlpp?

**Comment by rbock** [comment]
Hi, you have to be more specific than that, since the example from #124 is in tests/core/usage/Union.cpp and works.

**Comment by damiangrzelak** [comment]
Ok, basing on

```
auto select{ sqlpp::select(tab1.COLA)
		              .from(tab1)
		              .unconditionally()
		              .union_all(sqlpp::select(tab2.COLB.as(tab1.COLA))
			              .from(tab2)
			              .unconditionally()) };
```
Above query causes mentioned error

>  both arguments in a union have to have the same result columns (type and name)

`COLA` has type **integer** and tag **require_insert**
`COLB` has type **integer** and tag **can_be_null**

I'm trying to change the order and query works:
```
auto select{ sqlpp::select(tab2.COLB)
		              .from(tab2)
		              .unconditionally()
		              .union_all(sqlpp::select(tab1.COLA.as(tab2.COLB))
			              .from(tab1)
			              .unconditionally()) };
```
Unfortunately, I need the first one.

So can this error be related with tag, column in select in union connot be null?

Both raw queries works, when I run them on database server.

```
SELECT a.COLA
FROM tab1 a 
UNION ALL SELECT a2.COLB FROM tab2 a2 

SELECT a.COLB
FROM tab2 a 
UNION ALL SELECT a2.COLA FROM tab1 a2 
```

**Comment by rbock** [comment]
Thanks for the details. Yes, it is because of `COLB` potentially being null.

In the library, the return type of the query is determined by the first select. If a column cannot be null there, than adding something than can be null is a problem.

Why do you need the first form?

**Comment by damiangrzelak** [comment]
Oh, of course I can use first form. My bad. 

I will try to implement my query using first form. My query is much more complex than this example, so if I meet again this problem, improvement of library may be needed.

At this moment I close this issue. 

Thanks for explanation :)
