### ISSUE TITLE
Issue compiling sqlpp11 for MySQL (installed with vcpkg)

### ISSUE THREAD

**Issue by unsigned-ru** [rbock/sqlpp11#454]
Hello! I have installed sqlpp11 using vcpkg globally.

I set my CMAKE_TOOLCHAIN_FILE to the  .../vcpkg/scripts/buildsystems/vcpkg.cmake

I have installed sqlpp11[mysql] for both x64 and x86 triplets.

my CMakeLists.txt file:
```
# CMakeList.txt : CMake project for sqlpp11Test, include source and define
# project specific logic here.
#
cmake_minimum_required (VERSION 3.8)

project ("sqlpp11Test")

# Add source to this project's executable.
add_executable(sqlpp11Test 
	"sqlpp11Test.cpp" 
	"HeimdallDatabaseSchema.h"
)

find_package(Sqlpp11 REQUIRED COMPONENTS MySQL)

set_property(TARGET sqlpp11Test PROPERTY CXX_STANDARD 20)
target_link_libraries(sqlpp11Test PRIVATE sqlpp11::mysql sqlpp11::sqlpp11)
```

It fails at `find_package(Sqlpp11 REQUIRED COMPONENTS MySQL)` 
With error:

```
1> [CMake] G:/vcpkg/vcpkg/installed/x64-windows/debug;G:/vcpkg/vcpkg/installed/x64-windows
1> [CMake] CMake Error at G:/vcpkg/vcpkg/scripts/buildsystems/vcpkg.cmake:829 (_find_package):
1> [CMake]   By not providing "FindMySQL.cmake" in CMAKE_MODULE_PATH this project has
1> [CMake]   asked CMake to find a package configuration file provided by "MySQL", but
1> [CMake]   CMake did not find one.
1> [CMake] 
1> [CMake]   Could not find a package configuration file provided by "MySQL" with any of
1> [CMake]   the following names:
1> [CMake] 
1> [CMake]     MySQLConfig.cmake
1> [CMake]     mysql-config.cmake
1> [CMake] 
1> [CMake]   Add the installation prefix of "MySQL" to CMAKE_PREFIX_PATH or set
1> [CMake]   "MySQL_DIR" to a directory containing one of the above files.  If "MySQL"
1> [CMake]   provides a separate development package or SDK, be sure it has been
1> [CMake]   installed.
```

Any help or suggestions greatly appreciated,
Thank you!

**Comment by rbock** [comment]
@Leon0402 FYI

Hello Ruben,

Can you check if #434 has been added to vcpkg yet?

If not, then a short term fix would probably be to install FindMySQL.cmake manually from the sources, see also recent messages in https://gitter.im/sqlpp11/Lobby

Best,
Roland

**Comment by unsigned-ru** [comment]
Hello!

First and foremost thank you for the quick reply!

FYI, the vcpkg does not contain the changes committed in PR #434.

I downloaded the `FindMySQL.cmake` from github and added it locally to my project. In my `CMakeLists.txt` i appended path to said file to the CMAKE_MODULE_PATH variable. It now works as it should.

Would be cool if the vcpkg could be updated to the latest commit, since the vcpkg just doesn't work with MariaDB or MySQL unless it has these changes...

Anyways, i'm happy it's fixed,
Thank you!

**Comment by rbock** [comment]
Thanks for the confirmation.

Could you ping the maintainers of the vcpkg, e.g. [here](https://github.com/Microsoft/vcpkg)? I have zero knowledge and no way to test.

Thanks,
Roland

**Comment by unsigned-ru** [comment]
The VCPKG has been updated to the latest commit

**Comment by rbock** [comment]
Great news, thanks!
