### ISSUE TITLE
Not find sqlpp11-connector-sqlcipher in vcpkg

### ISSUE THREAD

**Issue by shishirong** [rbock/sqlpp11#455]
![image](https://user-images.githubusercontent.com/16620315/189495361-60b5bb22-2db4-4f5f-86e5-6aabac4b5b3a.png)

**Comment by shishirong** [comment]
don't need sqlpp11-connector-sqlcipher, use sqlite's connector, add define SQLPP_USE_SQLCIPHER and SQLITE_HAS_CODEC , it works

**Comment by rbock** [comment]
Sorry for not reacting earlier and thanks for figuring this out yourself!
Could you maybe also reach out to the vcpkg team to make the packages less confusing?

**Comment by shishirong** [comment]
> Sorry for not reacting earlier and thanks for figuring this out yourself! Could you maybe also reach out to the vcpkg team to make the packages less confusing?

I am not an expert in `vcpkg`, just post a issue in vcpkg repository, hope some master-hand resolve.

**Comment by rbock** [comment]
Thanks!
