### ISSUE TITLE
How to use COUNT(DISTINCT columnName) querry in Join multiple tables?

### ISSUE THREAD

**Issue by JP10086** [rbock/sqlpp11#463]
I concatenated three tables to query the total of the main table, the query was correct in mysql, but incorrect using sqlpp11.

In mysql use "DISTINCT" querry result is 4 , no use "DISTINCT" is 5:
```
SELECT COUNT(DISTINCT t2.pk_StudyInfo) 
FROM r_qmi_database.igd_studyinfo t2 
JOIN r_qmi_database.igd_seriesinfo t3
ON t2.pk_StudyInfo=t3.fk_IGDSTU_StudyInfo
JOIN r_qmi_database.igd_reportinfo t5
ON t2.pk_StudyInfo=t5.fk_IGDSTU_StudyInfo;
```

In sqlpp11 use "sqlpp::distinct" query result is 5 , no use "sqlpp::distinct" is also 5:
		
```
const auto t2 = QMI::IgdStudyinfo{};
const auto t3 = QMI::IgdSeriesinfo{};
const auto t5 = QMI::IgdReportinfo{};
auto scnt = sqlpp::dynamic_select(*m_db).flags(sqlpp::distinct).columns(sqlpp::count(t2.pkStudyInfo))
					.from(t2
						.join(t3)
						.on(t2.pkStudyInfo == t3.fkIGDSTUStudyInfo)
						.join(t5)
						.on(t2.pkStudyInfo == t5.fkIGDSTUStudyInfo))
					.dynamic_where();   //unconditionally()
auto vec1 = m_db->run(scnt);
if (!vec1.empty())
{
	queryresultinfo.nTotalSize = vec1.begin()->count;
	std::cout << "study total rows count = " << queryresultinfo.nTotalSize << std::endl;
}
```

It looks like the keyword  "sqlpp::distinct" is invalid , because if I change the columns(), like this:
                   `columns(sqlpp::count(t2.pkStudyInfo)) ---> columns(sqlpp::all_of(t2))`
Now the result is correct, "sqlpp::distinct" is valid .
Whether it can not be used the "flags(sqlpp::distinct)" in COUNT(columnName) query?
Or am I using the wrong syntax?
Please give me the correct way to use it........

**Comment by rbock** [comment]
Hi,

You're on the right track: Your current query expression evaluates to `SELECT DISTINCT COUNT(t2.pk_StudyInfo) ...)`.

Please use the `sqlpp::distinct` as parameter for `sqlpp::count`:

```
sqlpp::dynamic_select(*m_db).columns(sqlpp::count(sqlpp::distinct, t2.pkStudyInfo))...
```

**Comment by JP10086** [comment]
> 
Thanks for helping me solve this problem perfectly！

**Comment by rbock** [comment]
Glad to help. Thanks for the confirmation!
