### ISSUE TITLE
nested-select in aggregate is missing braces

### ISSUE THREAD

**Issue by bloerwald** [rbock/sqlpp11#469]
```
    ns::Grp group;
    db.execute ("CREATE TABLE `Grp` (id INTEGER NOT NULL);");
    ns::Entry entry;
    db.execute ("CREATE TABLE `Entry` (groupId INTEGER NOT NULL, value INTEGER NOT NULL);");

    db (select (group.id,
                sum (select (entry.value).
                     from (entry).
                     where (entry.groupId == group.id))).
        from (group).
        unconditionally());
```

generates `SELECT Grp.id,SUM(SELECT Entry.value FROM Entry WHERE (Entry.groupId=Grp.id)) AS sum_ FROM Grp`, which in sqlite3 fails due to braces around the sub-select being missing:

```
sqlite> SELECT Grp.id,SUM(SELECT Entry.value FROM Entry WHERE (Entry.groupId=Grp.id)) AS sum_ FROM Grp;
Error: in prepare, near "SELECT": syntax error (1)
sqlite> SELECT Grp.id,SUM((SELECT Entry.value FROM Entry WHERE (Entry.groupId=Grp.id))) AS sum_ FROM Grp;
|
sqlite>
```

This also makes sense based on [the grammar](https://www.sqlite.org/lang_select.html) (`select-stmt` -> `result-column` -> `expr`):
```
expr := function-name ( expr )
expr := ( select-stmt )
```
i.e.
```
expr := function-name ( ( select-stmt ) )
```

This appears to be the same in MySQL, but I only quickly checked that.

**Comment by rbock** [comment]
Thanks for the report, Bernd!

As a quick-fix, this patch should help:

```
diff --git a/include/sqlpp11/aggregate_functions/sum.h b/include/sqlpp11/aggregate_functions/sum.h
index 56a1e33..5511ca3 100644
--- a/include/sqlpp11/aggregate_functions/sum.h
+++ b/include/sqlpp11/aggregate_functions/sum.h
@@ -91,12 +91,8 @@ namespace sqlpp
     {
       serialize(Flag(), context);
       context << ' ';
-      serialize_operand(t._expr, context);
-    }
-    else
-    {
-      serialize(t._expr, context);
     }
+    serialize_operand(t._expr, context);
     context << ")";
     return context;
   }
```

It has the drawback that `sum(a + b)` would be serialized to `SUM((A + B))`, which is not wrong, but adds noise.

Need to think about this for a bit. Input welcome :-)

Best,
Roland

**Comment by bloerwald** [comment]
Guten Morgen Roland, that was indeed the hackfix I was going to try today. Thanks for pointing me to the line of code!

I think the noise isn't that bad, but I'd love to have it on the SELECT side of things, so that it automagically works fine in _other_ contexts as well since `expr` shows up a lot recursively. Also, `select-stmt` from what I have seen always appears as `'(' select-stmt ')'` unless it is top level.

What about adding a "is top level" flag in `serializer_context_t`?

**Comment by rbock** [comment]
Guten Morgen, Bernd,

I like the idea. I'll play around with it.

Note: It would break folks who have their own `serializer_context_t`. I don't know how many that would affect.

Cheers,
Roland

**Comment by rbock** [comment]
There exceptions (of course): 

`SELECT 7 UNION SELECT 8;`

The two select statements come without braces, even though they are not top-level.

Looking at a couple of serialize functions, it seems to me that the `serialize` and `serialize_operand` functions in combination with the `tag::requires_parens` are sufficient, but aren't used well enough. I think I will work on cleaning those up step by step.

As a first step, committed the fix from comment 2.

**Comment by bloerwald** [comment]
> `SELECT 7 UNION SELECT 8;`

Now that's just rude of SQL.

I updated my dependency to the latest main (82758a20464e2775078fb343cda23da7b73ec482) and it seems to work perfectly. Unless you want to keep this ticket open for sake of beautifying, I suggest closing it. Thanks!

**Comment by rbock** [comment]
> Now that's just rude of SQL.
:rofl: 

Thanks for the feedback!

Yes, I want to do a bit more cleanup, but it goes beyond the scope of this ticket. Closing.
