### ISSUE TITLE
Join table

### ISSUE THREAD

**Issue by alexnorth12** [rbock/sqlpp11#474]
Hi! Can this library ```join``` the same table twice? 
Cuz I tried, but flashing error. 

Thx for answering.

**Comment by rbock** [comment]
Yes, it can, but you need to use the `.as` function to have two different names, just as in regular SQL.

```
    const auto ta = t.as(sqlpp::alias::a);
    const auto tb = t.as(sqlpp::alias::b);
    ... join(ta, tb) ....
```

And of course, you need to use the aliased tables for the selected columns, where clause, etc.

Hope this helps?

**Comment by alexnorth12** [comment]
Yes, it`s working. Thank you!
