### ISSUE TITLE
Having condition

### ISSUE THREAD

**Issue by alexnorth12** [rbock/sqlpp11#475]
Hello! 
I have trouble with my query with ```having```. MySQL query work correctly, but in here I takes error. 
I hope you can help.

```
select(t.date,  t.id,  t.data)
      .from(t)
      .group_by(t.date,  t.id,  t.data)
      .having(t.player_id == 2 and sqlpp::sum(sqlpp::case_when((t.type_id > 15 or t.type_id < 15)).then(1).else_(0)) == 0)
      .limit(std::uint64_t{ 1 }) 
```

**Comment by rbock** [comment]
Hi,

`t.player` is neither an aggregate nor a group-by expression. The result is undefined, iiuc, and the library protects you from that.
It is therefore also  unclear, what you want to express? Maybe `.where(t.player_id == 2)`?

Hope this helps!

Roland

**Comment by alexnorth12** [comment]
I tried to set ```.where(t.player_id == 2)```.  -> Error: "```missing serializer specialization```". 

Do I something wrong?

**Comment by rbock** [comment]
> Do I something wrong?
Probably. But sorry, that's just not enough data.

Which database do you use?
Please provide a minimal, reproducible example, see for instance: https://stackoverflow.com/help/minimal-reproducible-example
