### ISSUE TITLE
Debug logging through a callback function

### ISSUE THREAD

**Issue by MeanSquaredError** [rbock/sqlpp11#479]
Currently when debugging is enabled the database connectors log the debug information through std::cerr. While useful this kind of logging is not well suited for large projects that usually log information to a file.

Thus it makes sense to add logging through a callback (ideally std::function) so that the user would be able to process and/or store the debug messages in any way.

**Comment by rbock** [comment]
How would you do it with a `std::function`, though? First serialize the message into a string, and then pass that string into a function?

Haven't done it in a while, thus am a bit rusty on the topic, but I think you can also modify either `std::cerr` or `stderr` to write to a file.

Best,
Roland
