### ISSUE TITLE
Inserting std::chrono::system_clock::time_point into timestamp with time zone

### ISSUE THREAD

**Issue by MeanSquaredError** [rbock/sqlpp11#481]
Currently when sqlpp11 inserts/updates a timestamp field it generates timestamp literals without a time zone. When such literals are inserted into a field that is a timestamp with time zone, PostgreSQL interprets the generated timestamp literals as having the local time zone, which causes problems.

Let's say that we have the number 1684706721, which is the number of seconds since the start of the UNIX epoch (1970-01-01 00:00:00 UTC), i.e. 2023-05-21 22:05:21 UTC.

This is a simplified version of the code that generates the insert:
```
int myts = 1684706721;
sqlpp::postgresql::insert_into(tgm).set (tgm.message_ts = std::chrono::system_clock::time_point {std::chrono::seconds {myts}})
```

When inserting the timestamp sqlpp11 generates the following SQL query
```
INSERT INTO messages (message_ts) VALUES(TIMESTAMP '2023-05-21 22:05:21.000000000')
```

The above SQL code inserts a timestamp that uses the local time zone (+03). A select of the inserted value returns `2023-05-21 22:05:21+03`, which is obviously the wrong value.

I think a possible workaround would be to change sqlpp11 so that it would generate a timestamp in the +00 timezone. In this case it would be 
```
INSERT INTO messages (message_ts) VALUES(TIMESTAMP WITH TIME ZONE '2023-05-21 22:05:21.000000000+00')
```
This will tell PostgreSQL that we insert a timestamp in the UTC timezone, so the correct value will be inserted.

**Comment by rbock** [comment]
Thanks for the detailed comment. That sounds plausible.

I'd be happy to accept a pull request with this change and unit tests as confirmation.

**Comment by MeanSquaredError** [comment]
I have been using a modified version of sqlpp11 (as per my suggestion above) for about a couple of weeks. The modified version works correctly with PostgreSQL + timestamp with time zone.

The change is available here:
https://github.com/MeanSquaredError/sqlpp11/commit/cc24cfb21da5e6a5e1849dab54ab75099ae873cd

In the next couple of days I will add tests and then will provide a PR.

**Comment by rbock** [comment]
Great! Looking forward to the PR :-)
