### ISSUE TITLE
List of column types

### ISSUE THREAD

**Issue by yasek** [rbock/sqlpp11#483]
Hi!
I am working on a custom connection object for some DB and in order to make a request I need to provide a list of types which are requested by the select statement. How do I get it from the select object? Thanks!

**Comment by rbock** [comment]
Not sure what you are looking for? Something like `std::tuple<std::string, int64_t, bool>`?

**Comment by yasek** [comment]
Yes, or, just to be able to work with dynamic columns, `std::vector<SomeEnum>{SomeEnum::TEXT, SomeEnum::INTEGRAL}`

I was able to do it, manually traversing policies in the same manner as serialize function does, but I am not sure it's a correct way of doing it and it's a lot of boilerplate code

**Comment by rbock** [comment]
Yeah, right now, there is no great access to it. Here's what I would do for static columns:

```
const auto selected_column_tuple = query.selected_columns._data._columns;
```

This gives you a tuple of `column_t` instances.

**Comment by yasek** [comment]
Thanks! It helped to get rid of some code.
And for dynamic columns we can simply set strings, can't we?
BTW, do you have any plans on adding typed versions of dynamic columns?

**Comment by rbock** [comment]
> Thanks! It helped to get rid of some code. 

Glad to read that :-)

> And for dynamic columns we can simply set strings, can't we? 

Yes

> BTW, do you have any plans on adding typed versions of dynamic columns?

Not in sqlpp11. Future versions of sqlpp (see also discussion in #482) will probably use `std::optional` to handle dynamic columns.

**Comment by rbock** [comment]
Closing.
