### ISSUE TITLE
Discussion: Custom Types

### ISSUE THREAD

**Issue by CJCombrink** [rbock/sqlpp11#485]
This is not an issue (yet) but more a question around custom types.

PostgreSQL (which we use) supports creating new types, using [CREATE DOMAIN](https://www.postgresql.org/docs/current/sql-createdomain.html)
Example:
```
CREATE DOMAIN FREQUENCY AS BIGINT;
```

How would be the best to use this in our sql schema, along with sqlpp11?
I am aware of the message stating we should update the script manually, but that is not ideal since I want to be able to use the library without "hacking" the script (we are using the library through a package manager, conan specifically).

In my mind I can think of the following options:
1. Update the ddl2ccp script to understand `CREATE DOMAIN` to extend/update the type conversion lists
   - This might be too PostgreSQL specific and I can't comment about such support in other databases.
   - The following comment in the linked page might make this less of a problem: "The command CREATE DOMAIN conforms to the SQL standard."
2. Add an extension point to the dll2cpp through a command line argument:
   - Suggestion: `--type-mapping-file:     Path to a text file that adds custom type mappings 'extendedDdlIntegerTypes = [FREQUENCY]'`
   - This file is then loaded on startup of the script and the internal types are extended to support these.
   - This allows us to keep the mappings separate without touching the script
 3. Fall back to text and still generate the files
    - My guess is many types can be passed to the database as text, which is not ideal specifically for integer types like my example.

Just supporting `CREATE DOMAIN` does however not cover all uses cases:
1. We use the UUID type which is not our type, but not supported by the script. 
2. Extensions can also add types 
3. We also create our own types which does not fit in with option 1 ([CREATE TYPE](https://www.postgresql.org/docs/current/sql-createtype.html) and supporting that as well can be overly complex.
    - For this specific example we will probably remove the usage of the custom type or use it as a string

Option 2 would be my hope. 1 can be nice addition.

**Comment by rbock** [comment]
Hi Carel,

Thanks for the detailed comments. I was not even aware of `CREATE DOMAIN` :-)

I like the second option2, too. 

In addition to what you wrote: 
The extension should probably issue a warning, if it would overwrite an "existing" type. This could happen, for instance, if we added support for `UUID` to ddl2cpp.

Would you be interested in giving it a try to write such an extension point?

Cheers,
Roland
