### ISSUE TITLE
Broken link to connector API in wiki

### ISSUE THREAD

**Issue by rettichschnidi** [rbock/sqlpp11#49]
The [Database](https://github.com/rbock/sqlpp11/wiki/Database) page in the wiki links to https://github.com/rbock/sqlpp11/blob/master/database_api/api.h, which does no longer exist.

It probably should point to https://github.com/rbock/sqlpp11/blob/master/connector_api/connection.h

**Comment by rbock** [comment]
Thanks :-)

Fixed.
