### ISSUE TITLE
How can I obtain the raw statement for on_conflict and do_update in PostgreSQL?

### ISSUE THREAD

**Issue by qbgbmpty** [rbock/sqlpp11#492]
In PostgreSQL, there are different serializer methods available, and I'm not quite sure how to use them. If my statement looks like this:

auto x = sql::insert_into(DB_dev)
                     .set(DB_dev.Id = parameter(DB_dev.Id), DB_dev.Name = parameter(DB_dev.Name))
                     .on_conflict(DB_dev.Id)
                     .do_update(DB_dev.Name = sqlpp::verbatim<sqlpp::text>("$1"));
                     
How can I use serialize to obtain its raw statement string?

**Comment by rbock** [comment]
You don't need to do anything special to use the connector-specific serializer methods. They are automatically chosen by the compiler based on the type of the connector.

You can obtain the serialized query like this:

```
    sqlpp::postgresql::connection connection;
    sqlpp::postgresql::context_t printer{connection};

    const auto result = serialize(x, printer).str();
```

If you look at the connector code, that is essentially what is happening when you are executing a query:

```
      template <typename Insert>
      size_t insert(const Insert& i) // <-- this is called when you execute your insert statement with postgres connector
      {
        _context_t ctx(*this);
        serialize(i, ctx);
        return insert_impl(ctx.str());
      }
```

**Comment by qbgbmpty** [comment]
I got it! I thought that I needed to call sqlpp::postgresql::serialize, but it seems that I misunderstood. thanks!
