### ISSUE TITLE
Tag Release 0.63

### ISSUE THREAD

**Issue by LvdStokker** [rbock/sqlpp11#497]
Hi @rbock,

Would you be willing to please tag a new release version that includes some of the latest changes added by @CJCombrink ?

**Comment by rbock** [comment]
I want to confirm #498 first (just came in).

You might have to poke me again. These are busy days.

Thanks for your patience!

**Comment by LvdStokker** [comment]
No problem, I will sit tight!

**Comment by rbock** [comment]
Done :-)
