### ISSUE TITLE
clang-format used at all?

### ISSUE THREAD

**Issue by rettichschnidi** [rbock/sqlpp11#50]
There is a clang-format [configuration file](https://github.com/rbock/sqlpp11/blob/master/.clang-format) in the repository, but the formatting of the sources files does not match it at all.

Which one should be corrected? The sources or the configuration file?

**Comment by rbock** [comment]
clang-format is currently not used at all. I intend to do so, soon.

Does this current mismatch create problems for you?

**Comment by rettichschnidi** [comment]
No problem at all. I was just wondering.

**Comment by rbock** [comment]
OK, thanks for the hint anyway :-)

I'll try to get this done soon.

**Comment by rettichschnidi** [comment]
Looking forward to having spaces instead of tabs. :D
