### ISSUE TITLE
Query: SQLPP11 way to insert table data from JSON into PostreSQL

### ISSUE THREAD

**Issue by CJCombrink** [rbock/sqlpp11#507]
What is the best "sqlpp11" way to insert table data from JSON into a PostgreSQL database?

The query is something like:
```
INSERT INTO my_table SELECT * FROM JSON_POPULATE_RECORD(NULL::my_table, '{ ... }');
```

The following works: 
```
const auto query = sqlpp::custom_query(sqlpp::verbatim("INSERT INTO my_table SELECT * FROM JSON_POPULATE_RECORD(NULL::my_table, '{ ... }')"))
                                   .with_result_type_of(insert_into(sqlpp::verbatim_table("my_table")));
```

Is there an alternative or better way to do so or is that as good as I will get?

PS: I am reading data from a json file, thus I don't have the associated table as a generated structure.

**Comment by rbock** [comment]
There is no good JSON support in the library. Your way is about as good as it gets.
