### ISSUE TITLE
Is there a generic container type for a value?

### ISSUE THREAD

**Issue by CJCombrink** [rbock/sqlpp11#522]
Hi,

I want to create a function as follow:
```
json as_json( auto column_val ) { 
    return column_val.is_null()? json{}: json{std::string{column_val}};
}
```
And use it as 
```
auto res = db(select(t.info).from(my_table).unconditionally());

some_type s;
s.info = as_json(res.front().info);
```

`auto` works in the function definition, but I am wondering if there is a more generic type that can be used.
  - `sqlpp::text` can't work
  - `std::string` is not ideal since I loose the option to check for null vs empty string. 
  - `auto` behaves like a template and thus I must define the function body in the header file. Ideally I want to define a function in a header and implement in  a source file, which is not possible for templates.

Edit: Fix ~~row~~ for `column_value` in `as_json()` function

**Comment by MeanSquaredError** [comment]
sqlpp11 does not have a union data type which could change at runtime, similar to `std::variant`. Having such a data type would be against its main purpose of the library which is enforcing type checks at runtime.

However if I understand correctly your example you don't need a full-fledged `std::variant`, but instead need a nullable data type that you could hold the corresponding values from the table fields. In your case it is a nullable string simialr to `std::optional<std::string>`

For data types sent to the database you can use `sqlpp::value_or_null_t`, e.g.
`sqlpp::value_or_null_t<sqlpp::integral>` is a nullable `int`
`sqlpp::value_or_null_t<sqlpp::text>` is a nullable `std::string`

For data types read from the database it is more difficult. The actual data types are could complex types based on `result_field_base`, which depend on the database, field type, nullability, etc. I don't think it makes sense to use these data types.

Right now I would say is that your best option is to use `std::optional` as a parameter type of your function, e.g. 
`json as_json( std::optional<std::string> row ) {`

and then pass the values as 
```
some_type s;
const auto& field = res.front().info;
s.info = as_json(field.is_null() ? std::nullopt : field.value());
```

@rbock suggested that in the future we need support for `std::optional` or rather `sqlpp::optional`, which on `C++17` will be an alias for `std::optional` and before `C++17` it would be a custom (probably simplified) implementation of `std::optional`. Then you could just (implicitly) cast `res.front().info` to `sqlpp::optional<std::string>` and use that data type.
Alas we don't have support for `sqlpp::optional` yet. I would like to implement it somewhere in the future, but I don't know if I will find the time for that before rbock actually writes sqlpp26 :-)

**Comment by rbock** [comment]
In addition to @MeanSquaredError 's comments:

From the original post

```
json as_json( auto row ) { 
    return row.is_null()? json{}: json{std::string{row}};
}
```

What do you want to express with `row.is_null()`? Each result field can be null, of course, and a more modern way would be to express this with an `optional` as mentioned above. Not sure about rows, though?

**Comment by CJCombrink** [comment]
> What do you want to express with `row.is_null()`? ... Not sure about rows, though?

@rbock Sorry it was a typo, it should have been either column or field, not row. I updated the original post.

@MeanSquaredError Yes you are 100% correct, I want the functionality of `std::optional` as you have explained for a specific type and a specific field.

I am already using `sqlpp::value_or_null_t<std::string>` for putting the data into the table (that specific column). But did not find something similar when reading that specific field again.

**Comment by rbock** [comment]
Thanks for the explanation!

The way result rows are represented is one of the major differences between sqlpp11 and sqlpp17. The latter simply has values or optional values as result fields.

It would certainly be possible to port that idea back into sqlpp11. I have not looked into whether that's hard or not, though.
