### ISSUE TITLE
Compilation error with c++11 and gcc 4.8.5

### ISSUE THREAD

**Issue by Piogar** [rbock/sqlpp11#523]
Hello,

I tried to compile library with c++11 (centos, gcc 4.8.5, clean repo without any modifications, just cmake and make run) and faced following error:
`[  2%] Building CXX object tests/core/usage/CMakeFiles/sqlpp11_core_tests.dir/BooleanExpression.cpp.o
In file included from /root/tmp/sqlpp/sqlpp11/tests/core/usage/MockDb.h:29:0,
                 from /root/tmp/sqlpp/sqlpp11/tests/core/usage/BooleanExpression.cpp:28:
/root/tmp/sqlpp/sqlpp11/include/sqlpp11/connection.h: In constructor 'sqlpp::pooled_connection<ConnectionBase>::pooled_connection(const _config_ptr_t&, sqlpp::pooled_connection<ConnectionBase>::_pool_core_ptr_t)':
/root/tmp/sqlpp/sqlpp11/include/sqlpp11/connection.h:124:26: error: 'make_unique' is not a member of 'std'
         : ConnectionBase{std::make_unique<_handle_t>(config)}, _pool_core{pool_core}`

Error seems obvious as std::make_unique is available in c++14 whereas gcc I have to use supports only c++11.

Is that expected and I'm missing something or is it a bug making building with c++11 impossible?

**Comment by MeanSquaredError** [comment]
It is a bug introduced by one of my PRs. Can you please try this branch:
https://github.com/MeanSquaredError/sqlpp11/tree/fix_make_unique
It should build with C++11. If it works correctly for you then I will open a PR with the fix.

**Comment by Piogar** [comment]
Thanks for quick answer. Commit seems to resolve this issue, however now I face issues #431 . I'll check #431 thread for details.

**Comment by MeanSquaredError** [comment]
@Piogar 
Opening an issue here (what you already did) is probably the fastest way to get support.
There is also a chat on gitter:
https://gitter.im/sqlpp11/Lobby?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge
but it seems to be less active than the support here.

**Comment by MeanSquaredError** [comment]
@Piogar 
Regarding issue #431
It doesn't seem to be one of the things that I broke with my patches :-)

gcc 4.8.5 seems to be relatively old. The oldest gcc which I was able to find on one of my Linux boxes was 8.3.1 which builds sqlpp11 without a problem. I will try installing gcc 4.8.5 but it could take a few days until I find the time to install it.

Meanwhile you could try building and installing sqlpp11 without `-DBUILD_TESTING=ON` (you seem to be using that define when building the library)
As @rbock mentioned in the reply to that issue, it seems to be a failing non-critical static_assert, so there is a chance that the library will work even with that failing assert.

**Comment by rbock** [comment]
Considering this resolved. Please open a new bug in case of lingering issues.
