### ISSUE TITLE
Declared but not defined methods

### ISSUE THREAD

**Issue by MeanSquaredError** [rbock/sqlpp11#529]
Hi,
I was looking into the SQLPP11 code today and found several methods which are declared but not implemented

Each of the three connectors' connection class (`sqlpp::xxxxx::connection`) has a method declaration
```
template <typename Check, typename T>
auto _run(const T& t, Check) -> Check;
```
These three methods have been declarated but I don't see them being implemented anywhere. For example for the MySQL connector has this method in file
`include/sqlpp11/mysql/connection.h` on line 427 and it was added with commit 5e16f32e about 2 years ago.

The situation is the same with the other 2 connectors - the same method was declared in them but not implemented about 2 years ago.

What is the reason for the addition of this method? Is it just a copy&paste error or are there any other reasons, e.g. improved error reporting for errors detected at compile time, or maybe something else?

Additionally I was looking into the definition of `SQLPP_PORTABLE_STATIC_ASSERT` and I found its definition in `include/sqlpp11/portable_static_assert.h` to be
```
#define SQLPP_PORTABLE_STATIC_ASSERT(name, message) \
  struct name : std::false_type                     \
  {                                                 \
    template <typename... T>                        \
    constexpr explicit name(T&&...)                 \
    {                                               \
      static_assert(wrong_t<T...>::value, message); \
    }                                               \
    template <typename... T>                        \
    static constexpr void verify(T&&...)                 \
    {                                               \
      static_assert(wrong_t<T...>::value, message); \
    }                                               \
    auto begin() const -> void;                     \
    auto end() const -> void;                       \
  }
```

Again there are two methods, `begin()` and `end()` which are declared but don't seem to be implemented anywhere. They look similar to the methods used to make an object behave like a sequential iterator, e.g. in range-loops, but obviously they are not because they return `void`. I thought that maybe they could make the static assert definitions display nicer in some IDEs but couldn't find anything about that.  What is the rationale behind these method declarations? 

@rbock can you please shed some light on these declarations in the connectors and in `SQLPP_PORTABLE_STATIC_ASSERT` ?

**Comment by rbock** [comment]
`being` and end `end`:\
Having these methods helps suppressing error messages in a number of cases, because compilers often carry on even after hitting `static_assert`. Try this:

```
  for (const auto& row : db(select(all_of(t)).from(t))) // missing where condition
  {
  }
```

And then remove the begin/end from the static assert. On my machine, with clang, the difference is 3.5kB, with gcc it is 9.5kB.
As you noticed, the returning something better than void could help even more (but note that normally stuff will happen in the body of the for-loop and diminish the effect).

```
template <typename Check, typename T>
auto _run(const T& t, Check) -> Check;
```

This is similar. It can suppress error messages in case the "correct" `_run` method is not a match. Interestingly, clang actually has a shorter error message without this construct, while gcc has a longer error message.

**Comment by MeanSquaredError** [comment]
@rbock 
Thank you for the clarification. Now that you explained it, it makes perfect sense. Also adding a couple of short comments explaining the purpose of those methods will probably help those reading the code.

I am currently getting more familiar with the details of the core code so that is how I came across those methods. Once I am more confident in my knowledge I will continue providing PRs with improvements.

**Comment by rbock** [comment]
Thanks! I really appreciate your thoroughness, questions and contributions!
