### ISSUE TITLE
how to express "Fmy_time < NOW() - INTERVAL 5 SECOND"

### ISSUE THREAD

**Issue by ZerQAQ** [rbock/sqlpp11#531]
hi,

I want to express this sql, but i don't know how to express "Fmy_time < NOW() - INTERVAL 5 SECOND",
It should be noted that 5 here is a runtime variable
```
UPDATE my_table
SET Fmy_time = NOW()
WHERE Fmy_time < NOW() - INTERVAL 5 SECOND;
```

**Comment by MeanSquaredError** [comment]
I think that sqlpp does not support SQL functions like `now()`, so you can either use custom queries or perform the date/time computations in your C++ code and pass the computed values to sqlpp.

This is an example of how I do the interval checks in my code
```
db_model::records records{};
const auto now = ::date::floor<::std::chrono::microseconds>(std::chrono::system_clock::now());
const auto rows = g_db(
	select(records.record_id)
	.from(records)
	.where(records.record_ts < now - std::chrono::seconds{5}) 
);
```

**Comment by rbock** [comment]
considering this answered.
