### ISSUE TITLE
PostgreSQL's LISTEN, UNLISTEN, NOTIFY

### ISSUE THREAD

**Issue by MeanSquaredError** [rbock/sqlpp11#534]
Currently SQLPP11 does not support the PostgreSQL-specific commands `LISTEN`, `UNLISTEN`, `NOTIFY` and it does not have any helper functions to simplify calling `PQnotifies()`.

Overall it is not a major problem because `LISTEN`, `UNLISTEN`, `NOTIFY` are simple commands and I am not really interested in any data that they may return so I can just execute these commands by calling `sqlpp::postgresql::connection::execute()`. And I can call `PQnotifies()` via the native handle. Of course it would be simpler if sqlpp11 supported these natively, so that I wouldn't to add the same custom helper functions in each project that uses PostgreSQL events.

@rbock
If you think that it makes sense to add to `sqlpp::postgresql` the three commands (`LISTEN`, `UNLISTEN`, `NOTIFY`) and a helper function to fetch the notifications, e.g. `get_notifies()`, then I can provide a PR with this functionality. What do you think?

**Comment by rbock** [comment]
I have no strong opinion here, mostly because I have zero experience with those commands. What would be a use case?

**Comment by MeanSquaredError** [comment]
Essentially PostgreSQL notifications are a basic message bus provided by the server. They allow two applications that are connected to the same database to exchange messages.

Usually it goes like this:

Application 1: `LISTEN my_event_name`

Application 2: `NOTIFY my_event_name`. Optionally NOTIFY can be called with a an additional data string, up to 8192 characters in length, i.e. `NOTIFY my_event_name, `my message to the recipients`

Application 1: Waits for events on the connection socket using socket `select()`. Once there is some data, it calls `PQnotifies()` to fetch notification data. It is possible for `PQnotifies()` to return no data because the `select()` call from earlier detects all data, not just notifications. So `select()` and `PQnotifies()` are usually put in a loop.

Application 1: After the communication is finished the Application 1, issues `UNLISTEN my_event_name`

It is useful when there are multiple applications reading/writing to the database. A basic example would be one application reading data from multiple sources and inserting the read data into a database table. After each insert or batch of inserts the application sends a `NOTIFY` and another listening application receives the notification fetches the newly inserted rows and processes the data further.

**Comment by rbock** [comment]
Thanks for the explanation. I would use other IPC means myself as I am usually trying to keep the business logic outside of the database.

IIUC, it is relatively painless to run these commands today, I would prefer to keep them out of the library.

**Comment by MeanSquaredError** [comment]
Indeed from an architecture point of view IPC does not belong to the database, but PostgreSQL provides it "for free" and for small to mid-size projects it is tempting to use the one from PostgreSQL, because it is one less service to take care of and make sure that it is running properly, one less library to use in the code, etc.

Executing `LISTEN`, `UNLISTEN`, `NOTIFY` is trivial, just one line of code calling `sqlpp::postgresql::connection::execute()`, so I guess I can live with calling `execute()`, instead of the specialized 'listen()', 'unlisten()' and 'notify()'.

The only slightly more complex code is the one that fetches the notifications with a timeout and/or interruptions (similar to `std::stop_token`). Currently I am keeping it in a custom library with other helper functions, so I guess it doesn't make a big difference if it is in sqlpp11 or in that library.

If in the future it turns out that there are more people requesting support for PostgreSQL notifications, I will provide the code as a PR.
