### ISSUE TITLE
dynamic_select error

### ISSUE THREAD

**Issue by Lee123123** [rbock/sqlpp11#537]
how to get data by dynamic_select, use **for (const auto& row : db(s)){}** report _error: ?begin? was not declared in this scope_

**Comment by MeanSquaredError** [comment]
`begin()` and `end()` are intentionally left undefined. They help to catch incorrectly formed queries at compile time. So most likely your dynamic query is incorrect, e.g. it lacks a `where` clause or maybe has some other problem.

The sample code that you provided does not show the building of the actual query `s`, so it is not clear what exactly is wrong. If you can post a sample (and simple) program which exhibits the problem, then someone might be able to tell what is the problem.

**Comment by rbock** [comment]
Closing due to lack of information.
