### ISSUE TITLE
PostgreSQL: dynamic_remove_from() and returning

### ISSUE THREAD

**Issue by CJCombrink** [rbock/sqlpp11#538]
Is there a `dynamic_remove_from()` that supports `returning()` for PostgreSQL or I am just overlooking it?

**Comment by rbock** [comment]
Hmm. There is not. Can you try this:

https://github.com/rbock/sqlpp11/tree/postgresql_remove_returning

I added it, but untested.

**Comment by CJCombrink** [comment]
@rbock Thank you for the file, I works as expected. Also thanks for the prompt response.
If you can get that into the main branch I guess you can close this ticket.

**Comment by rbock** [comment]
Thanks for the feedback. Done.
