### ISSUE TITLE
Is it possible to combine insert_into() and select()

### ISSUE THREAD

**Issue by CJCombrink** [rbock/sqlpp11#539]
I have a query two tables where the one references the other

```
constexpr MyTable1 t{};
constexpr MyTable2 u{};


auto query = sqlpp::postgresql::insert_into(t)
                     .columns(t.name);


// Some checks and logic and loops

std::string name = connection(select(u.name).from(u).where(u.id == id_to_add)).at(0).name;
query.values.add(t.name = name);
```

is it possible to combine the first select into the add as 1 database query?
```
query.values.add(t.name = select(u.name).from(u).where(u.id == id_to_add));
```
It feels like it should be possible, but I am missing something.

**Comment by rbock** [comment]
Yes, you can do something like

```
sqlpp::postgresql::insert_into(t).set(t.name = select(u.name).from(u).where(u.id == id_to_add));
```
(it is your responsibility to guarantee that the select yields exactly one result)

However, `.columns` is used for multi=line insert. If you want that, then the answer is no, I am afraid. The values are stored in a `std::vector<std::tuple>` where the tuple elements types match the respective column types (e.g. `int64_t` or `std::string`).

It would be possible to change that using some kind of type erasure, I think.

**Comment by CJCombrink** [comment]
@rbock Thanks, I do multi-line inserts.
For now what I have is working thus not really a priority.
