### ISSUE TITLE
dynamic_select sub dynamic_select alias error!

### ISSUE THREAD

**Issue by guosuying2012** [rbock/sqlpp11#542]
Hello,
I have a piece of SQL that will report an error when implemented through sqlpp.
```
SELECT
	id,
	order_id,
	(SELECT COUNT( id ) AS count_ 
	FROM orders 
	WHERE status IN ( 1, 2, 3 )) as count
FROM
	orders 
WHERE
	status IN ( 1, 2, 3 ) 
	LIMIT 15 OFFSET 15
```

The compiler prompts me that the` selected_columns.add()` method is wrong:
`In template: static assertion failed due to requirement 'integral_constant<bool, false>::value': invalid named expression argument in selected_columns::add()`

This is my sqpp implementation:
```
auto queryBuild = dynamic_select(*m_db)
            .dynamic_columns(all_of(orders))
            .dynamic_from(orders)
            .dynamic_where()
            .dynamic_limit()
            .dynamic_offset();

auto queryCount = dynamic_select(*m_db, count(orders.id))
            .from(orders)
            .dynamic_where();

queryBuild.selected_columns.add(queryCount.as(total_data));
```

After I deleted the alias `as()`, it worked fine, but I need an alias for `as()`. 
Please tell me how to do it? Thanks.

**Comment by rbock** [comment]
Sorry for the late reply. I somehow missed this.

The expression `queryCount.as(total_data)` creates a named sub-select (i.e. a dynamic table) that could be used in `from`.

What you need is an alias for `count`, e.g.

```
auto queryCount = dynamic_select(*m_db, count(orders.id).as(total_data))
            .from(orders)
            .dynamic_where();
```

Hope this helps?

**Comment by guosuying2012** [comment]
@rbock 
Thank you for taking the time to respond to my query amidst your busy schedule. Your proposed solution looks really good, but it might not be suitable for me. The reason being, the SQL connector I use is not based on `sqlpp11`. I use `sqlpp11` for constructing SQL statements, just as your project description mentions:
`Construct type-safe queries checked at compile time for syntax errors, type errors, name errors, and even some semantic errors.`

So, I chose `sqlpp11` to avoid various issues that arise from using hardcoded strings, such as spelling mistakes or oversights due to multiple functional modules when adding or modifying field names. Indeed, `sqlpp11` has performed surprisingly well in this regard, which is fantastic. Therefore, the database connector I actually use is related to [Drogon](https://github.com/drogonframework/drogon) functionality. I prefer not to overcrowd my project with too many database connectors.

[Drogon](https://github.com/drogonframework/drogon) uses index-based retrieval when fetching query results, for instance: ```result["count"]```. However, your code cannot fetch results in this manner. This is because, in MySQL, the column name for the count subquery becomes the subquery's SQL statement or needs to be retrieved using the index position, like ```result[result.size() - 1]```. However, I'd prefer not to do this as it might lead to out-of-bounds exceptions.

During the process of addressing this issue, I discovered a SQL function that could help me - the `over()` function. To my surprise, while preparing to use `'verbatim'` I found that `sqlpp11` supports the `over()` function, which is simply amazing. If possible, could you enhance the `partition by`  `order by` part of the `over()` function? Thank you for your work this is incredibly cool. 

I wish you a wonderful day!

**Comment by rbock** [comment]
Thank you for sharing these details of how you are using sqlpp11. The combination with Drogon is quite fascinating!

Turns out that it was reasonably simple to allow what you were looking for originally, i.e.

```
queryBuild.selected_columns.add(queryCount.as(total_data));
```

should work with the latest commit.

**Comment by guosuying2012** [comment]
Awesome, this method works well for me. Thank you for your efforts. Wishing you a pleasant life!
