### ISSUE TITLE
Length of the blob received by "select" 

### ISSUE THREAD

**Issue by YukunXia** [rbock/sqlpp11#546]
Hi Roland,

First of all, thank you so much for writing and maintaining such an awesome library! 

I have a question about the mechanism of receiving objects with dynamic length. Specifically, let's say, the blobs. Sending a `std::vector<uint8>` to a key `foo` is straightforward. But as I tried to read the same content back via `select`, there were two seemingly equivalent ways, either `blob` with `len`, or simply `value()`. In the test with sqlite3 and pgsql, `blob` with `len` is used, rather than `value()`, Is there any particular reason why this version is preferred?

Best,
Yukun

**Comment by rbock** [comment]
Hi Yukun,

Thanks for the praise :-)

And thanks for the question, of course. Both variants work just fine. `value()` returns a copy of the value, though.

Background:\
In the early days, I decided to return a default-constructed value if you asked for the value of a NULL result. From today's perspective, that was probably a mistake. Every now and then I am thinking of changing that, but it is hard to do so without breaking everybody.

Cheers,
Roland

**Comment by YukunXia** [comment]
Thank you for the timely reply! Now I understand it much better :)
