### ISSUE TITLE
SQLite3 connection pool error using

### ISSUE THREAD

**Issue by AVerutin** [rbock/sqlpp11#549]
Hi! I try to build application with connection pool and have this errors in headers files:

`In file included from D:/msys64/mingw64/include/sqlpp11/sqlite3/connection_pool.h:30,
                 from E:/Projects/CPP/WaterFoul/src/modules/database.h:7,
                 from E:/Projects/CPP/WaterFoul/src/modules/database.cpp:2:
D:/msys64/mingw64/include/sqlpp11/connection_pool.h:50:41: error: 'pooled_connection' in namespace 'sqlpp' does not name a template type
   50 |     using _pooled_connection_t = sqlpp::pooled_connection<ConnectionBase>;
      |                                         ^~~~~~~~~~~~~~~~~`
![sqlite_conn_pool](https://github.com/rbock/sqlpp11/assets/20885703/8aa9b46c-5c33-4657-a302-55b4ada2141e)

**Comment by MeanSquaredError** [comment]
It lacks an include. For now it should be possible to workaround this by replacing
`
#include <sqlpp11/sqlite3/conneciton_pool.h>
#include <sqlpp11/sqlite3/sqlite3.h>
`
with
`
#include <sqlpp11/sqlite3/sqlite3.h>
#include <sqlpp11/sqlpp11.h>
`

**Comment by MeanSquaredError** [comment]
Actually I am not sure if the current codebase needs a fix, maybe it is OK the way it is now. Maybe users should just include the database-specific include (`sqlpp11/sqlite3/sqlite3.h`) and the generic one (`sqlpp11/sqlpp11.h`) and not try to cherry-pick the included files.

**Comment by AVerutin** [comment]
> It lacks an include. For now it should be possible to workaround this by replacing
> 
> ```
> #include <sqlpp11/sqlite3/conneciton_pool.h>
> #include <sqlpp11/sqlite3/sqlite3.h>
> ```
> 
> in your code with
> 
> ```
> #include <sqlpp11/sqlite3/sqlite3.h>
> #include <sqlpp11/sqlpp11.h>
> ```

Thank you, is working for me!

**Comment by rbock** [comment]
Btw, I think this was also fixed with #548
