### ISSUE TITLE
MS Visual Studio 2015 support

### ISSUE THREAD

**Issue by peterritter** [rbock/sqlpp11#55]
Hi Roland

Does your project compile with the new Visual Studion 2015 version?  Has anyone chequed this? I can't use your code unless I can also compile it on Windows with Visual Studio. 
Peter

**Comment by rbock** [comment]
Hi Peter,

Last I checked, it did not compile, but that was a few months back. The last known problem is fixed to the extent that you can tell the compiler to ignore a faulty error message:

http://blogs.msdn.com/b/vcblog/archive/2015/06/02/constexpr-complete-for-vs-2015-rtm-c-11-compiler-c-17-stl.aspx?PageIndex=3

By adding #pragma warning(disable: 4579) at the top of your file, you might get around this constexpr issue. I suspect that there are more, but I don't have a windows machine to test.

I'd appreciate compiler output from the latest RTM.

Best,

Roland

**Comment by studoot** [comment]
FYI - I've just tried compiling the sqlpp11 examples with Visual Studio 2015 Update 1(which was released on Monday) and they don't compile, raising the following errors:

1. In column.h (it doesn't like the partial specialisation of `serializer_t` for `column_t`, complaining that `column_t<...>` has too few template arguments - it doesn't appear to like the use of variadic template parameters here)

2. As far as I can tell, every definition of the form

			static constexpr const char _literal[] =  "concat_";

3. In table.h, compiling `table_t`, it's unable to specialize `member_t`. Again, an issue with variadic template parameters, I think...

Oh - and compiling any of the source files causes an internal compiler error while compiling table.h.

However - this version of Visual Studio *also* ships with 'clang/C2', which is a hybrid clang/msvc with a clang 3.7 frontend and an MSVC code generator, and *that* compiles the sample code fine (apart from `sample.cpp`, which I'm guessing is there to illustrate compile-time detection of incorrect use of the database?).

**Comment by rbock** [comment]
Thanks for the report!

   1. Can you send me sample output?
   2. Sigh, now that error is a bit annoying. 
       - They planned to fix this in Update 1, see here: https://connect.microsoft.com/VisualStudio/feedback/details/1290476/static-constexpr-const-char-literal-delta-not-working-inside-struct 
       - Maybe you can add a comment there?
       - Also, have you tried to use "#pragma warning(disable: 4579)" at the top of an example? Not exactly a reassuring technique, but it could help to isolate the remaining issues.
   3. Again, some sample output might help. If the pragma thing works, maybe you could just attach the compiler output to your reply?

Internal compiler error does not sound too promising, but who knows? One fine day...

The clang news is great!
sample.cpp has to fail to compile (although I have to admit that that is a result of negligence rather than intention).

Best regards,

Roland

**Comment by studoot** [comment]
1. [Here you go](https://github.com/rbock/sqlpp11/files/50639/build-errors.txt) - this is the compiler output for `examples/*.cpp` and `tests/*.cpp` with warning 4579 disabled (at the command-line, with `-wd4579`.

    

2. If you [look at the Connect issue](https://connect.microsoft.com/VisualStudio/feedback/details/1290476/static-constexpr-const-char-literal-delta-not-working-inside-struct) again, someone's already reported that it's only partially fixed in Update 1 :-(

**Comment by rbock** [comment]
I saw the report at MS Connect this morning, I thought that was you :-)

Thanks for the compiler output. I'll try to figure something out (no promises though).

**Comment by isliser** [comment]
Hello! I've found another bug while trying to build sqlpp with msvc https://connect.microsoft.com/VisualStudio/Feedback/Details/2086629

**Comment by rbock** [comment]
@isliser Thanks. That looks so basic...

**Comment by isliser** [comment]
Another bug in msvs compiler https://connect.microsoft.com/VisualStudio/Feedback/Details/2087449

**Comment by rbock** [comment]
Nice, thanks again :-)

Replacing the variadic template arguments of the serializer with Table and ColumnSpec should fix the issue in column.h. Could you prepare a pull request for the develop branch (I currently have no way of testing with MSCV)?

**Comment by isliser** [comment]
Sure I'll do it tomorrow.

**Comment by isliser** [comment]
One nore bug https://connect.microsoft.com/VisualStudio/feedback/details/2091069

**Comment by rbock** [comment]
Yikes! That's awful...

**Comment by fire** [comment]
Could someone test this with Clang inside of VS 2015? http://blogs.msdn.com/b/vcblog/archive/2015/12/04/introducing-clang-with-microsoft-codegen-in-vs-2015-update-1.aspx

**Comment by rbock** [comment]
@studoot tested clang in MSVC successfully about three weeks ago.

BTW: How can I convince cmake to use the clang frontend in MSVC? I would like to add an apveyor instance for that, too.

**Comment by isliser** [comment]
Wow it works now!!! Thank you!

**Comment by rbock** [comment]
Just finished the appveyor branch (everything compiles and all tests work).

Many thanks to @isliser for the great effort in finding most of the workarounds.

**Comment by rbock** [comment]
The above is meant to say: sqlpp11 develop branch now compiles with MSVC 2015 Update 1.

Yay!

I'll add badges and create a new release, soon.

**Comment by rbock** [comment]
Release 0.35 can be compiled using MSVC 2015 Update 1.

Closing this issue, thanking @isliser again for the effort to find the workarounds!
