### ISSUE TITLE
how to get a column by string?

### ISSUE THREAD

**Issue by scutLaplace** [rbock/sqlpp11#555]
Hi, i hava a situation like this. 

void search(std::vector<std::string> columns)
{
      //search table.column by which columns specify
}

how can i solve this problem by using sqlpp11? wish for u help.

**Comment by rbock** [comment]
The main use case for sqlpp11 is for situations in which the structure of the queries (including the selected fields) is largely known at compile time. This allows for all the checks the library performs at compile time for you.

The way it is designed, in sqlpp11, tables are structs and columns are members of these structs. I don't think you can lookup member of a struct via `string`? Same with result rows. These are structs with fields being members of the struct.

The only exception are runtime-added fields in dynamic `select`. Those can (have to) be selected by `string`. See https://github.com/rbock/sqlpp11/blob/main/docs/Dynamic-Select.md#dynamic-select

Let me know if this helps or describe what you are trying to accomplish in more detail.

Thanks
Roland

**Comment by scutLaplace** [comment]
Thanks for u answer.
