### ISSUE TITLE
sqlite connector: execute() silently ignores statements after the first one

### ISSUE THREAD

**Issue by jgehrcke** [rbock/sqlpp11#558]
Thanks for the lovely library.

Adding this here quickly mainly for visibility (might be helpful for others). The sqlite connector [uses](https://github.com/rbock/sqlpp11/blob/dccf3438d3615d064372d5fe5e02124ce30ce439/include/sqlpp11/sqlite3/connection.h#L77C19-L77C37) the sqlite API call `sqlite3_prepare_v2()` when processing a statement string via `connection.execute(statement)`.

Sqlite docs for this API call [state](https://www.sqlite.org/c3ref/prepare.html) (emphasis mine)

>  If pzTail is not NULL then `*pzTail` is made to point to the first byte past the end of the first SQL statement in `zSql`. **These routines only compile the first statement in `zSql`**, so *pzTail is left pointing to what remains uncompiled.

I found this because I was debugging a situation where I called `execute()` with a string with more than one `CREATE TABLE ...` statement (separated by semicolon), and only the table corresponding to the first statement was created.

As a user, I can of course work around that. I don't want to recommend any specific action item here. But of course we may want to adjust docs, or do some magic given `pzTail` mentioned in the sqlite docs.

**Comment by MeanSquaredError** [comment]
Maybe we should just change `sqlpp::sqlite3::connection_base::execute()` to use `sqlite3_exec()` instead of calling `prepare_statement()` and then executing the prepared statement.

[Here](https://www.sqlite.org/c3ref/exec.html) they claim that `sqlite3_exec()` is able to handle correctly multiple statements separated by semi-colon(s):
>The sqlite3_exec() interface runs zero or more UTF-8 encoded, semicolon-separate SQL statements passed into its 2nd argument, in the context of the [database connection](https://www.sqlite.org/c3ref/sqlite3.html) passed in as its 1st argument.

**Comment by rbock** [comment]
Thanks for the report and the discussion so far! And sorry for the late reply, I was offline for a bit.

My preference is to 

1. document that this is for one statement only
2. fail explicitly if there is more than one statement (probably using `pzTail`).

Rationale: Executing one statement is supported by all backends and the behavior is pretty much the same in that case. Executing multiple statements is conditionally possible and the behavior is non-uniform. See for instance

* https://dev.mysql.com/doc/c-api/8.0/en/mysql-query.html
* https://www.postgresql.org/docs/current/libpq-exec.html

The rationale is  a bit weak as postgres supports multiple statements by default. But I would rather look into ways how to restrict that then allowing multiple statements for all backends.

WDYT?

Thanks,
Roland

**Comment by MeanSquaredError** [comment]
@rbock 

> My preference is to
> 
>     1. document that this is for one statement only
> 
>     2. fail explicitly if there is more than one statement (probably using `pzTail`).

I am OK with either approach as long as it is uniform across all the connectors. So basically I am OK, with your suggestion.

However it should be noted that PostgreSQL supports natively multi-command queries, where commands are separated by semi-colons. From the libpq documentation  for [`PQexec`](https://www.postgresql.org/docs/current/libpq-exec.html#LIBPQ-PQEXEC)
> The command string can include multiple SQL commands (separated by semicolons). Multiple queries sent in a single [PQexec](https://www.postgresql.org/docs/current/libpq-exec.html#LIBPQ-PQEXEC) call are processed in a single transaction, unless there are explicit BEGIN/COMMIT commands included in the query string to divide it into multiple transactions.

So maybe we should change the PostgreSQL connector to use `[PQexecParams](https://www.postgresql.org/docs/current/libpq-exec.html#LIBPQ-PQEXECPARAMS)`, for which they say:
> Unlike [PQexec](https://www.postgresql.org/docs/current/libpq-exec.html#LIBPQ-PQEXEC), [PQexecParams](https://www.postgresql.org/docs/current/libpq-exec.html#LIBPQ-PQEXECPARAMS) allows at most one SQL command in the given string. (There can be semicolons in it, but not more than one nonempty command.) This is a limitation of the underlying protocol, but has some usefulness as an extra defense against SQL-injection attacks.

What do you think?

**Comment by rbock** [comment]
Switching to `PQexecParams` is tempting to get uniform behavior as you mention.

However, it will almost certainly break existing code. So this will require some transition and/or communication strategy.

**Comment by rbock** [comment]
I dealt with the immediate issue first: instead of silently ignoring following statements, the sqlite3 connector now throws an exception.

The others are unchanged except for documentation.

**Comment by rbock** [comment]
Considering the reported issue fixed.
