### ISSUE TITLE
how to use binary equal in where

### ISSUE THREAD

**Issue by adjfangjiawei** [rbock/sqlpp11#559]
I want to use binary = in where,but I get an error. It  tell me the custom query is not a bool expression.how to resolve it?
![1709622411547](https://github.com/rbock/sqlpp11/assets/22865562/d020d99b-52f7-4454-97ca-90cf64b077f4)

**Comment by rbock** [comment]
Admittedly, I am not certain what it actually means, but try

```
.where(sqlpp::verbatim<sqlpp::boolean>("binary name = '" + name + "'))
```

`custom_query` is used to build an executable query. This can be used as a sub-query, too, but you don't seem to need that here (and you would need to declare the "return type").

**Comment by adjfangjiawei** [comment]
Yes,It works.
