### ISSUE TITLE
How to retrieve the row count of a query result?

### ISSUE THREAD

**Issue by qq1174159858** [rbock/sqlpp11#562]
example 
result=mysqldb(select)
result.row()？

**Comment by CJCombrink** [comment]
`result.size()` should be what you are looking for

**Comment by qq1174159858** [comment]
> `result.size()` should be what you are looking for

In MySQL connector, `size()` function does not return a value, as its return type is `void`.

**Comment by CJCombrink** [comment]
Ok I was not aware, I use the PostgreSQL connector.

Maybe provide a more complete reproducible example, for example the full `select` query?

**Comment by rbock** [comment]
The sqlpp::mysql::char_result_t::size` is not implemented yet. This is mostly an oversight, I think.

It should be easy to do, though, using `mysql_num_rows`. Do you want to give it a try, @qq1174159858 ?

**Comment by rbock** [comment]
It should work now for `char_result_t`, e.g.

```c++
const auto result = db(select(all_of(tab)).from(tab).unconditionally());
const auto num_rows = result.size();
```

**Comment by rbock** [comment]
Considering this fixed.
