### ISSUE TITLE
Multiple table query error

### ISSUE THREAD

**Issue by zcmaye** [rbock/sqlpp11#564]
In the same source file, two multi-table queries were written, one working properly and the other with an error.
The normal query is as follows:
```
        auto t = emp.join(salgrade).on(emp.sal >= salgrade.losal && emp.sal <= salgrade.hisal);
		for (const auto& row : db(
			select(emp.ename, emp.sal, salgrade.grade)
			.from(emp.join(salgrade).on(emp.sal >= salgrade.losal && emp.sal <= salgrade.hisal))
			.unconditionally()))
		{
			std::cout << row.ename << " " << row.sal << " " << row.grade << std::endl;
		}
```
The following code, however, has an error at compile time.
```
		for (const auto& row : db(
			select(emp.ename, emp.sal, dept.dname)
			.from(emp.join(dept).on(emp.deptno == dept.deptno))
			.unconditionally()))
		{
			std::cout << row.ename << " " << row.sal << " " << row.grade << std::endl;
		}
```
Error content:
```
C:\Program Files (x86)\sqlpp11\detail\type_set.h(272): error C2510:"alias t" : The left side of "::" must be class/struct/union
C:\Program Files (x86)\sqlpp11\include\sqlpp11\detail\type_set.h(272): error C2146: 语法错误: 缺少“>”(在标识符“_name_t”的前面)
```

`emp.join(dept)` return type is sqlpp::assert_pre_join_unique_names_t.

**Comment by rbock** [comment]
`assert_pre_join_unique_names_t` indicates that the types of `emp` and `dept` contain identical `_literal`.

This could happen, for instance if you adjusted the table definitions manually.

If that's not the case, please provide a https://en.wikipedia.org/wiki/Minimal_reproducible_example

**Comment by zcmaye** [comment]
> `assert_pre_join_unique_names_t` indicates that the types of `emp` and `dept` contain identical `_literal`.
> 
> This could happen, for instance if you adjusted the table definitions manually.
> 
> If that's not the case, please provide a https://en.wikipedia.org/wiki/Minimal_reproducible_example

I just found the problem. _alias_t in dept table changed to _alias_p

**Comment by rbock** [comment]
Thanks for the confirmation.
