### ISSUE TITLE
How do I get record with count of references from one to many?

### ISSUE THREAD

**Issue by v-val** [rbock/sqlpp11#566]
Thanks a lot @rbock for great product in public domain 🙏
Question: I don't quite get how to select record from table A and count of refs to above record from table B when A connects B as one-to-many?
```SQL
SELECT
    A.field, count(*)
FROM
    A, B
WHERE
    A.id = B.a_id
GROUP BY
    A.field
```
I tried ways looking straightforward, such as
```cpp
auto query = sqlpp::select( A.field, sqlpp::count(B), )
				.group_by(A.field)
				.from(B.join(A).on(B.aId == A.id))
				;
sqlpp::sqlite3::connection_config cf{app_::DATABASE, SQLITE_OPEN_READONLY};
sqlpp::sqlite3::connection c{cf};
c(query);
```
...but no luck.
Sorry if I missed something obvious.

**Comment by v-val** [comment]
I was able to get it in a bit dodgy way:
```cpp
auto query = sqlpp::select(A.field, sqlpp::count(B.aId))
                .where(A.field.is_not_null())        // This helped, not sure why.
		.from(B.join(A).on(B.aId == A.id))
		.group_by(A.field)
		;
```
Seems `.where(...)` is needed, although `.where(true)` I tried first didn't work.
It would be great if this could be clarified.

**Comment by rbock** [comment]
Thanks for the report and for figuring out a first solution.

`select` requires a `where` clause or an explicit hint that this is an unconditional request by calling `.unconditionally()`. This is to prevent folks to accidentally forget the `where` clause. And you should have seen a static assert saying `calling where() or unconditionally() required`.

So in your example, this would be written as 

```C++
auto query = sqlpp::select(A.field, sqlpp::count(B.aId))
		.from(B.join(A).on(B.aId == A.id))
		.unconditionally()
		.group_by(A.field)
		;
```
I noticed that `unconditionally` is not documented in the /docs. Fixed that.

Thanks,
Roland

**Comment by v-instrumentix** [comment]
Thanks a lot for the quick answer and for clarification.
Regards!

**Comment by rbock** [comment]
Thanks for the confirmation.
