### ISSUE TITLE
scripts/sqlite2cpp.py requires insert of nullable column

### ISSUE THREAD

**Issue by rbock** [rbock/sqlpp11#569]
Running `scripts/sqlite2cpp.py` on this ddl

```sql
CREATE TABLE IF NOT EXISTS users (
    id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    pid INTEGER
);
```

results in `sqlpp::tag::require_insert` for column pid:

```c++
    struct Pid
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "pid";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T pid;
            T& operator()() { return pid; }
            const T& operator()() const { return pid; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::integer, sqlpp::tag::require_insert>;  // <------- HERE
    };
```

@egorpugin FYI
@shishirong FYI

**Comment by egorpugin** [comment]
Hi,

What result line should be?

`using _traits = sqlpp::make_traits<sqlpp::integer, sqlpp::tag::require_insert>;`
or
`using _traits = sqlpp::make_traits<sqlpp::integer, sqlpp::tag::can_be_null>;`
or both
`using _traits = sqlpp::make_traits<sqlpp::integer, sqlpp::tag::can_be_null, sqlpp::tag::require_insert>;`
?

**Comment by rbock** [comment]
> `using _traits = sqlpp::make_traits<sqlpp::integer, sqlpp::tag::can_be_null>;`

This is correct (result of the linked commit, b92a9a7). I was wondering if there are versions of sqlite3 that return a string for the `notnull` column (that was the previous behavior). If unclear, then we should keep it this way.

**Comment by rbock** [comment]
The old code used `column[3] == '0'`. That did not work correctly on my machine since `column[3]` a numeric value.

That's why the new code uses `column[3] == 0` in addition.

My question is: Are there versions of sqlite3 that yield a string in `column[3]`?

**Comment by egorpugin** [comment]
I had always `"0"` in my code.
https://github.com/egorpugin/primitives/blob/master/src/tools/sqlpp11.sqlite2cpp.cpp#L222
Sqlite returns `char *` value `0` or `1`, so I compare it with "0";

**Comment by rbock** [comment]
Interesting. In python the result is numeric. At least on my machine.

Thanks for looking into it. I'll leave as is.
