### ISSUE TITLE
[Need assistance] Common Table Expressions with update

### ISSUE THREAD

**Issue by CJCombrink** [rbock/sqlpp11#576]
The first question is probably: is CTE possible/supported for UPDATE?

I have a rather complex query that makes use of CTE to update a specific table (at least it works in native PostgreSQL tested in pgAdmin)

I have managed to destruct my query into 3 parts, first a filter, then a join to form the CTE result that is then used to update a specific table (if this generalisation makes sense)

The first two queries work as expected, but when I try to combine it with the CTE expression I get the following error
```
sqlpp11/statement.h:71:75: error: static assertion failed: policies update for non-policy class detected
[build]    71 |         static_assert(make_type_set_t<Policies...>::template count<Needle>(),
[build]       |                       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~
```

This is my code (obfuscated as much as I can)
```
constexpr table_a_t table_a{};
constexpr table_b_t table_b{};
constexpr table_c_t table_c{};

auto query_a = select(table_a.uuid) //
                                .from(table_a
                                            .left_outer_join(table_b) //
                                            .on(table_a.uuid == table_b.observation))
                                .where((table_b.observation.is_null()) && (table_a.uuid.in(sql_uuids)));
// Sanity check
auto res_a = connection(query_a);
for (auto& e: res_a)
    fmt::print("UUID: {}\n", std::string{e.uuid});

auto alias_a = query_a.as(sqlpp::alias::a);

auto query_2 = select(table_c.carrier, sqlpp::all_of(alias_a))
                                .from(table_c.join(alias_a)
                                        .on(alias_a.uuid == table_c.origin_uuid));
// Sanity check
auto res_b = connection(query_2.unconditionally());
for (auto& e: res_b) {
    fmt::print("UUID: {}\n", std::string{e.uuid});
}
```

When I run the above queries I get the results that I am expecting.

The code that does not compile that tries to combine those and update is
```
constexpr table_d_t table_d{};
auto initialCte = ::sqlpp::cte(sqlpp::alias::b).as(query_2);
auto query = with(initialCte)(sqlpp::postgresql::update(table_d)
                                            .set(table_d.secondary_uuid = initialCte.uuid)
                                            .where(initialCte.primary_uuid== table_d.uuid));
auto res = connection(query);
```

Quick explain of the tables.
- `table_a` contains all secondary UUIDs 
- `table_b` contains external secondary UUIDs (which references `table_a`)
- `table_c` is a 1:Many mappings for secondary to primary UUIDS
- `table_c` is primary UUIS with a secondary_uuid that can only point to a UUID in `table_a` that is not in `table_b` (thus not external)

Any help or ideas are welcome.
This is my first time trying to use CTE's, not to mention my first CTEs in sqlpp11

**Comment by rbock** [comment]
Thanks for the report.

1. As of today, `with` is not supported for `update`. According to [this](https://bugs.mysql.com/bug.php?id=88397) that seems OK *"In the 2015 version of the SQL standard, a CTE cannot be defined in UPDATE;"*
2. I have not looked at your query in detail [1], but afaict, most CTE things can be expressed with sub queries as well.

[1] Please try to reduce examples to the bare minimum, see also https://stackoverflow.com/help/minimal-reproducible-example

**Comment by CJCombrink** [comment]
@rbock Thank you for the response.

From some familiarity with the sqlpp11 compile errors I deduced that it is not possible, thus before struggling too much I decided to rather ask.

>  most CTE things can be expressed with sub queries as well.

Yes I got that working thanks again. The CTE was an over complication in the end. 

> Please try to reduce examples to the bare minimum

Thanks I normally do, but in this case I was pretty sure spending the effort would not be worth it. 
I was hoping that if it was supported perhaps by problem was clear like "you need to alias there" or don't do that there, but again was not very hopeful.
