### ISSUE TITLE
Documentation for the in operator is missing.

### ISSUE THREAD

**Issue by slepasteur** [rbock/sqlpp11#58]
I would like to perform the following request ```SELECT * FROM entry WHERE id IN (SELECT id FROM entry WHERE ...);``` but could not find any documentation on how to use the in operator.

**Comment by rbock** [comment]
Added a bit of documentation here: https://github.com/rbock/sqlpp11/wiki/Functions

Not perfect yet. I need to write some examples, but I hope it helps to get started (or to know what to look for in tests.examples).
