### ISSUE TITLE
how to predict const struct sqlpp::result_row_t is or not NULL? 

### ISSUE THREAD

**Issue by edidada** [rbock/sqlpp11#580]
os:linux
sqlpp11 version:0.61
question:
```
    for (const auto& rs : db->run(sqlpp::select(all_of(tb)).from(tb).where(tb.date >= yesStr and tb.date <= yesStr ).order_by(tb.date.asc()).limit(limit))) {
        if (!rs.isNull())  //error
            std::cout << "attendResultId: " << rs.attendResultId.text << "\n";
        if (!rs.personId.isNull()) //error
                std::cout << "personId: " << rs.personId.text << "\n";
        }
    //        std::cout << "firstShouldInTime: " << rs.firstShouldInTime.text << "\n";
    //        std::cout << "firstShouldOutTime: " << rs.firstShouldOutTime.text << "\n";//这里有空异常
            std::cout << "date: " << rs.date.text << "\n";
            std::cout << "--------\n";
        }
    }
```

result_row_t  result_row_impl  result_field member_t
how to predict const struct sqlpp::result_row_t is or not NULL?

**Comment by rbock** [comment]
Result rows cannot be NULL.

In a `for`-loop, result rows are always valid.

However, if you decided to access rows of the result directly (e.g. `db->run(...).front()`) then these could be invalid and evaluate to `false` in a bool context).

Individual columns of a row can be `NULL` depending on their specification in the ddl (you can also see that in the generated code, `sqlpp::tag::can_be_null` in the `_traits`, of the column class). And of course, there are other reasons for a column potentially being `NULL`, e.g. outer joins.

You can check if a column of a row is NULL, by calling `is_null`.

Hope this helps?

**Comment by edidada** [comment]
OK，now I only want to check rs.personId.text is null or not
