### ISSUE TITLE
SQLite: Is order by rowid possible?

### ISSUE THREAD

**Issue by margaretselzer** [rbock/sqlpp11#582]
I am trying to make a select statement be ordered by the implicit SQLite `rowid`. I am not using this id otherwise so adding an extra column for this feels really unnecessary. On the other hand I cannot seem to find a way to add this to my query. The `order_by()` function does not accept an `sqlpp::verbatim` nor can I use an aliased column (e.g. `sqlpp::verbatim<sqlpp::integral>("rowid").as(rowId)`) as I get a compilation error of: `error: static assertion failed: arguments for order_by() must be sort order expressions`.

Is there a solution to this without adding an explicit column to the table?

**Update**
Adding `rowid` to the table with tags `sqlpp::tag::must_not_insert, sqlpp::tag::must_not_update` seems to be a viable workaround. Nevertheless, it is still just a workaround. Is there a generic way to use query-only columns?

**Comment by rbock** [comment]
You need to specify whether you want to sort in ascending or descending order?

I currently can´t try, but `sqlpp::verbatim<sqlpp::integral>("rowid").asc()` should work?

Hope this helps :-)

**Comment by margaretselzer** [comment]
It does indeed work! This was probably the only configuration with `verbatim` that I did not try. :)

Thank you!
