### ISSUE TITLE
Title: Error E0140: Too Many Arguments in Function Call in `for_update.h` with VS2022

### ISSUE THREAD

**Issue by chenqihong001** [rbock/sqlpp11#583]
![image](https://github.com/user-attachments/assets/ab658036-845a-48da-9b1b-f815ca613eb7)

**Comment by rbock** [comment]
Hi!

Just curious: why is the description not a text?

I can't test this right now, but I think this is correct (and wonder why no other compiler noticed that). Can you change the last couple of lines in that file to 

```
  auto for_update() -> decltype(statement_t<no_for_update_t>().for_update())
  {
    return statement_t<no_for_update_t>().for_update();
  }
```

Thanks,
Roland

**Comment by chenqihong001** [comment]
Sorry to bother you, but even after following your instructions, I'm still encountering many issues and unable to compile successfully. However, in a Linux environment, using vcpkg to download the library works fine. Similarly, on Windows, using VSCode and compiling with `cmake .. -G "MinGW Makefiles"` and g++ also works correctly.
![QQ截图20240723143513](https://github.com/user-attachments/assets/f95ba102-0b99-44f5-8792-040b8fc06a1a)
![QQ截图20240723143527](https://github.com/user-attachments/assets/2984cd05-59d9-47a6-84af-93cf97824a85)
![QQ截图20240723143536](https://github.com/user-attachments/assets/86cf34aa-8cd9-4ba3-9cd1-ccfaa2619246)
Thank you very much!

**Comment by rbock** [comment]
Hi,

Those screenshots do not show any actionable error message. Please prepare a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example). Please do not send pictures.

Thank you,
Roland
