### ISSUE TITLE
Using case in select statement.

### ISSUE THREAD

**Issue by slepasteur** [rbock/sqlpp11#59]
Is it possible to perform requests with case statements using sqlpp11?
```sql
SELECT CASE WHEN col < 100 
            THEN col 
            ELSE othercol 
       END AS colname 
FROM table
```

**Comment by rbock** [comment]
Today this is not possible, but it is on my personal wish list. It should not be that hard to do.

**Comment by slepasteur** [comment]
Ok I will do two requests for now and do the test in the code. Let me know if I can be of any help.

**Comment by rbock** [comment]
Hi,

please checkout the develop branch:

```C++
case_when(condition).then(A).else_(B)
```

Please note:
   - there has to be exactly one `condition`, one `then`, one `else`, i.e. there cannot be several `when`/`then` combinations, and the `else_` is not optional
   - there is no `case(variable).when(value).then...`

Let me know if it works for you.

Best,

Roland

**Comment by rbock** [comment]
`case_when(condition).then(expression).else_(expression)` is now supported by release-0.35

**Comment by rbock** [comment]
Yes, that would be possible. Feel free to open a new feature request. 

I would first complete the work on the `optional` branch (progressing fine, but will take while to get it done). And then upgrade `case` statements to allow for multiple branches.
