### ISSUE TITLE
Iterators on const results

### ISSUE THREAD

**Issue by MeanSquaredError** [rbock/sqlpp11#590]
I just noticed that it is not possible to get begin/end iterators on `const` results.
For example:
```
const auto rows = db(select(all_of(foo))...);
rows.begin (); // Fails because rows.begin() cannot be called on const objects
rows.end (); // Fails because rows.end() cannot be called on const objects
for (const auto& one_row : rows) { // Fails too for the same reason
   ...
}
```

It is not a big issue just slightly annoying one that prevents having perfect const-correctness. The obvious workaround is to drop `const` from the `rows`. The proper fix would be making `begin()/end()` const methods.

@rbock Is there any special reason why begin() and end() are not const? Should I provide a fix?

EDIT: 

~~I see that `result_t::begin()` actually moves the result rows into the iterator that it creates and this is the reason why this method is not const.~~

~~And `result_t::end()` seems to move `result_t::_end`  and `result_t::_end_row` into the created end iterator, so that's the reason why it is not const either.~~

~~Maybe it makes sense to change `result_t::iterator` so that it just keeps a pointer or reference to the original `result_t` instead of moving its data?~~

Maybe it makes sense to make `result_t::iterator::_result` and ``result_t::iterator::_result_row`` mutable which will allow making `result_t::begin()` and `result_t::end()` const?

On a side note: I am trying to use result rows, i.e. `result_t` with C++23 ranges and C++23 does not recognize it as a valid range. For example I cannot do something like:
```
auto& rows = db(...);
auto vec = rows | std::views::transform (...) | std::ranges::to<std::vector> ();
```
The problem is caused by the fact that `result_t::iterator` is not default-constructible.

So maybe it makes sense to update the iterator code a bit and:
1. Make `begin()` and `end()` const.
2. Make `result_t::iterator` default-constructible.

What do you think? Should I give it try?

**Comment by rbock** [comment]
Iterating over a result consumes the result (e.g. mysql and sqlite3). I am not a range expert, but I don't think `view` is the right concept to use.

Making the `result_t::iterator::_result` and `result_t::iterator::_result_row` mutable is not a viable option, IMO, since they represent the underlying data structure which is actually changed while iterating.

IIUC, `std::ranges::view_interface` might allow you to write a wrapper.

**Comment by MeanSquaredError** [comment]
C++20 views are essentially movable ranges, so if result_t is a range, it will be pretty much a view too (because I think that it is already movable).

With the current implementation of `begin()` and `end()` `result_t` is almost a range. The only thing currently preventing `result_t` from fulfilling the range requirements is that the `result_t::iterator` is not default-constructible. Looking at the code it seems that the iterator can be made default-constructible relatively easily by replacing the result/row references with pointers and using nullptr to initialize the pointers when default-initializing the iterator.

However my real problem is the broken implementation of the iterator post-increment operator. Even if I make the  iterator default-constructible there is the risk that some of the range algorithms might use the post-increment thus yielding incorrect results or crashing or going into an endless loop or doing who knows what.

Using `std::ranges::view_interface` (instead of turning `result_t` into a range) has pretty much the same problem as turning `result_t` into a range. The view's being() and end() will need either to reuse `result_t::iterator`, with its broken postincrement or implement its own iterator, but then I would need to implement somehow the postincrement properly.

So I guess that for the time being I will use `result_t` with the range-based for loop. I guess it is good enough for now. Further down the road I will try to find the time and make a proper fix the iterator postincrement (although at the moment I don't see an easy way to fix that).

**Comment by MeanSquaredError** [comment]
OK, I think I made a few changes to `result_t` that turn that class into an input range usable with C++20. I will prepare a PR.

**Comment by MeanSquaredError** [comment]
The sql query results are valid C++20 ranges now, but the original problem remains - if the query result is const, then it is not iterable, because its `begin()` and `end()` methods are not const.

If we treat the results as regular C++ containers or ranges, then it probably makes sense to allow iteration of const results.

**Comment by rbock** [comment]
But moving from one row to the next it not const. It involves calling a number of C-functions which I cannot guarantee to be const and in some cases it involves memory allocation. There might more, but I am stopping at memory allocations :-)

Sure, technically we could declare everything mutable, but that does not make it const-correct.

**Comment by MeanSquaredError** [comment]
My argument was more from the point of view of a user, that is how the user sees the interface provided by the library.

From the user point of view the results returned by `db(select...)` are just some kind of fancy list that can be iterated over or accessed via `front()`, which again is a list accessor method. A user wouldn't expect the accessors to modify the list. He doesn't know all the gory internal details and probably thinks that it is OK to pass the results to as a const argument to some function that will iterate through the result rows and process them further.

But thinking about it in more detail, the user wouldn't be able to iterate a second time through the same const object, so it is not really const and has some internal state that changes. Which is a pity.

So I guess it makes sense to leave everything the way it is now  OK, I will close the issue, then.
