### ISSUE TITLE
Suspicious implementation of result_t::iterator::operator++(int)

### ISSUE THREAD

**Issue by MeanSquaredError** [rbock/sqlpp11#591]
After delving into the code that implements result iterators I found the implementation of `result_t::iterator::operator++(int)` a bit suspicious.

In include/sqlpp11/result.h on line 122 we have the following code
```
      iterator& operator++()
      {
        _result.get().next(_result_row.get());
        return *this;
      }

      iterator operator++(int)
      {
        auto previous_it = *this;
        _result.next(_result_row.get());
        return previous_it;
      }
```
Obviously the purpose of these two methods is to implement the prefix increment (`++it`) and postfix incremenet (`it++`) operators. However the problem is with this line:
```
        auto previous_it = *this;
```
Both `previous_it` and `*this` actually reference the same underlying result object, so the two iterators essentially point to the same row in the results sequence.

I don't see an easy fix for this without making intrusive changes to the code, but it is probably worth adding a comment to let users know that the postfix increment operator is actually a prefix increment operator.

**Comment by rbock** [comment]
Good find. Adding documentation seems to be the best option.

And maybe also implementing `iterator operator++(int)` by calling `iterator& operator++()`.

**Comment by MeanSquaredError** [comment]
I provided a PR, but made it into a draft, because I am not sure if we actually need the post-increment. Please see my comment in the PR.

**Comment by MeanSquaredError** [comment]
I guess this issue is resolved, at least for the time being, so I will close it.
