### ISSUE TITLE
Supported types

### ISSUE THREAD

**Issue by matthijs** [rbock/sqlpp11#6]
Hi,

In PostgreSQL there are many types, however in sqlpp11 I only see the types: boolean, integral, floating_point and text.

Take a look at: http://www.postgresql.org/docs/9.3/static/datatype.html

In other words, lots of types.

Is there a possibility to extend the library in such a way that it can support any type? For example, I would like to put a time / date field in an appropriate type (for example boost::posix_time::ptime)

Regards, Matthijs

**Comment by rbock** [comment]
I am closing this one with release 0.35, which brings `day_point` and `time_point` which correspond to `date` and `datetime`. See also the remarks on #23 .

If you are interested in specific types, please open new issues for those.
