### ISSUE TITLE
[postgresql] dynamic_update/insert_into/returning/remove don't assert pooled_connections

### ISSUE THREAD

**Issue by Meetrious** [rbock/sqlpp11#612]
Headers
- include/sqlpp11/postgresql/insert.h
- include/sqlpp11/postgresql/remove.h
- include/sqlpp11/postgresql/returning.h
- include/sqlpp11/postgresql/update.h

each contain dynamic_\<func\> with corresponding operation.

First argument of functions only asserts
`sqlpp::postgresql::normal_connection`, but not `sqlpp::postgresql::pooled_connection`. And so `pooled_connection`-s can't be used to process dynamic queries.

Apparently because there are two connection-id-names in the code (
relatively to postgresql-namespace).
-  `struct connection` from **<sqlpp11/connection.h>**
-  `using connection = sqlpp::normal_connection<connection_base>` from **<sqlpp11/postgresql/connection.h>**.

Can't fully grasp the importance for sqlpp-query-entities to know which connection is established, but if there is, I trust we shouldn't assert passed connection with `is_base_of<sqlpp::connection, PassedConnectionType>`. It will work, though.

So I suggest ![2024-12-17_15-29](https://github.com/user-attachments/assets/d7ff9061-9ef0-4d2b-b962-4c1de50a37d3)

Or to rename `using connection` in posgresql-namespace to negate naming collisions.

**Comment by MeanSquaredError** [comment]
I am using sqlpp11+pooled connections+PostgreSQL and they seem to work for me.

Can you provide a minimal reproducible example of the problem that you encountered?

**Comment by Meetrious** [comment]
Are you sure, you are not using default `sqlpp::dynamic_update(..)`?

I'll provide short example in two days.

For now can only demonstrate in screenshot
![2024-12-18_11-02](https://github.com/user-attachments/assets/14ac4f1f-7cb0-47a5-8f58-46d717696cb9)

**Comment by MeanSquaredError** [comment]
@Meetrious 
Yes, I am using `sqlpp::dynamic_update`

**Comment by MeanSquaredError** [comment]
By the way, the new branch that the library author is working on, doesn't seem to have this issue
https://github.com/rbock/sqlpp11/blob/optional-no-dynamic/include/sqlpp11/postgresql/clause/update.h

**Comment by Meetrious** [comment]
@MeanSquaredError, well no dynamic-query-constriction-with-static-assert - no problem, I guess.

**Comment by rbock** [comment]
Thanks for the discussion so far!

Indeed, the new branch will not have this problem as dynamic query parts will be expressed in a different fashion.

In the current branch, 

  1. yes, dropping the assert would work. It would also lead to pretty nasty compiler error messages if you passed the wrong thing (I am guessing here, haven't tried recently).
  2. I think (again, haven't tried) we could also do \
      `static_assert(std::is_base_of<connection_base, Database>::value, "Invalid database parameter");` \
      (Same in the other connectors)

I would prefer the second option. WDYT?

If this works for you, I'd happily merge a pull request :-)

Thanks,
Roland

**Comment by MeanSquaredError** [comment]
I just checked the mysql and sqlite3 drivers and it seems that the mysql-specific `dynami_update` and `dynamic_remove` have the same problem.

It is probably better to avoid making big changes to this branch, so I would say that instead of removing them, it is better to amend the `static_assert`s so that they would allow `pooled_connection`'s too. In the new branch they are gone, though.

**Comment by Meetrious** [comment]
@rbock, just've checked. If asserting with is_base_of `posgresql::connection_base`, it compiles and works fine.

**Comment by MeanSquaredError** [comment]
BTW, the fact that this bug has only been caught now means that we don't have usage tests for `dynamic_xxxxx` + pooled connections.

Not sure if adding these tests to the current (old) branch is worth the effort, though, given that the new branch handles dynamic queries in a different way.

**Comment by rbock** [comment]
@Meetrious Can you create pull request?

As suggested by @MeanSquaredError , tests would make sense, but are not required.

**Comment by Meetrious** [comment]
I'm a bit new. Just now figured, that in order to create one, I have to fork.

In a minute.

**Comment by rbock** [comment]
Closing this as fixed.

Thanks for the report, the discussion, and the PR to fix the issue!
