### ISSUE TITLE
Banning unconditional joins (aka cartesian or cross joins)

### ISSUE THREAD

**Issue by rbock** [rbock/sqlpp11#62]
Hi,

So we just brought down a server by running something like

```C++
db(select(all_of(tabA)).from(tabA, tabB).where(true));
```

tabA and tabB are quite big, their unconditional join is ginormous. Too big for the server as it turned out.

One of the main purposes of sqlpp11 is to protect developers from those small mistakes that can kill your business if they are not caught. That's why for instance you cannot omit the `where` condition. You have to say `where(true)` to show your intent.

I therefore intend to disallow implicit joins like `from(tabA, tabB)` in future releases. This would enforce explicit joins

```C++
db(select(all_of(tabA)).from(tabA.join(tabB).on(someCondition)).where(true));
```

It would also enforce the join condition, making it much less likely that somebody forgets to add that condition to the where expression.

I guess I should deprecate the old functionality before removing it (although I am not exactly sure how to do this as `[[deprecated]]` is a C++14 feature)

Other thoughts?

Thanks in advance,

Roland

**Comment by Erroneous1** [comment]
Boost seems to use `#pragma message` to indicate header-wide deprecation (see [1.60.0 type_info_wrapper.hpp](http://www.boost.org/doc/libs/1_60_0/boost/log/utility/type_info_wrapper.hpp)). SO has a question with the accepted answer saying to use `__attribute__((deprecated))` or `__declspec(deprecated)` [here](http://stackoverflow.com/questions/295120/c-mark-as-deprecated).

**Comment by rbock** [comment]
Decided to not use deprecated hints and instead improve the error messages to ease the transition.
