### ISSUE TITLE
Cannot build the MySQL connector! Please some help

### ISSUE THREAD

**Issue by juandent** [rbock/sqlpp11#64]
I downloaded the connector for mysql project and ran:

cmake CMakeLists.txt
make

and get this error:

Scanning dependencies of target sqlpp-mysql
[ 6%] Building CXX object src/CMakeFiles/sqlpp-mysql.dir/connection.cpp.o
In file included from /Users/juandent/Programs/C++/sqlpp11-connector-mysql-master/src/connection.cpp:30:
/Users/juandent/Programs/C++/sqlpp11-connector-mysql-master/src/detail/prepared_statement_handle.h:31:10: fatal error: 'mysql/mysql.h' file not
found

**Comment by rbock** [comment]
See answer for the identical mysql issue.
