### ISSUE TITLE
Any way to do outer joins (left outer or right outer or full outer)

### ISSUE THREAD

**Issue by juandent** [rbock/sqlpp11#65]
Hi,

I read on the limitations of outer join... is there a workaround?

Thanks!
Juan

**Comment by rbock** [comment]
Can you be more specific? What do you want to do?

**Comment by juandent** [comment]
How about being able to execute any kind of outer join even though it's not yet part of the framework?
Since l am beginning to play with sqlpp11 I don't have any more specific question
Just a practical one: can you someone get away with outer (left, right, full)?
Thanks

**Comment by rbock** [comment]
For example, you can do: `tabA.left_outer_join(tabB).on(someCondition)`

**Comment by rbock** [comment]
Same with `right_outer_join` and `outer_join`

**Comment by juandent** [comment]
Hi Roland,

Ok, my understanding then... I understood from the wiki that there was yet no support for outer_joins but now I see that there actually VERY MUCH is!

That's such a good news. This library you created is awesome. Are there any important aspects of SQL databases (say standard SQL) that are yet to be incorporated into sqlpp11? If so, are there workarounds for now?

May  I say that I have been coming back to C++ development just recently and that your library is something I dreamt would exist? What do you use for GUI development? Perhaps QT? What OS do you use for development?

Best regards!!

Juan

**Comment by rbock** [comment]
Hi Juan,

Regarding joins: Well, the final support depends on whether or not the database actually supports a feature. For example, SQLite3 does not support outer join.

As for other features: The library certainly does not cover everything you can do in SQL. You can add new clauses quite simply though (if you are into TMP a bit). Just look at existing clauses. Also, in the postgres connector has some development for specific clauses...

I am happy to read that you enjoy the library :-)

My development environment is vim on Linux, switching between several versions of clang and gcc.

Best,

Roland

**Comment by juandent** [comment]
Ok, I understand ... From your presentation I seem to remember that you had not included support for stored procedures. Is this still the case? If it is, are there work arounds?

Best regards!!
Juan

**Comment by rbock** [comment]
Yes, that is still the case. There is always the execute function to execute just a string. There is also the verbatim function to inject some otherwise unsupported stuff into your sql statement.

**Comment by juandent** [comment]
Do you have any plans or timeline estimate for adding this support?

**Comment by rbock** [comment]
There are no concrete plans (and therefore no estimates yet). You are welcome to try and come up with an extension for the library, of course :-)

**Comment by juandent** [comment]
ok, depending on the result of some potentially coming work and my available time, I may try this :-) Will need to start a project where using sqlpp11 enough so that i get to understand its structure and general approach for "uniting" C++ and SQL. Sounds fascinating but will depend on available time... :-)

**Comment by rbock** [comment]
Ok, looking forward to it. Let me know if you need help with it...

Closing this for now
