### ISSUE TITLE
access to connector / native db

### ISSUE THREAD

**Issue by digitalist** [rbock/sqlpp11#70]
Is there any some kind of fallback interface to send raw query through connector to database?
It could be quite useful when some features are not implemented and you agree to loose some speed doing string conversions.
For example, I suppose views are not supported and implementing them within sqlpp is a long work, but  I could still query them using plain "SELECT blah-blah"

**Comment by rbock** [comment]
There are a few, for instance:

  - verbatim<value_type>(string): interprets whatever is contained in string as the type you specified
  - verbatim_table(string) represents a table (might be handy if your verbatim expression requires another table (not sure this was ever used and it might require some work with joins)
  - the custom_query template can be used to compose non-standard queries

For views, you could interpret them as tables (with read-only columns), I think. The ppgen helpers by @niXman might come in handy here.

**Comment by digitalist** [comment]
oh, I should lurk and google more, thanks)

**Comment by rbock** [comment]
Glad to help. I'll close this one then :-)

**Comment by digitalist** [comment]
I have another issue for you in mysql-connector, sorry :3 but if you really wish to make mysqlpp production grade...

**Comment by rbock** [comment]
Never be sorry for raising issues.
