### ISSUE TITLE
Unable to insert into a table which has a field SQLPP_PRIMARY_KEY

### ISSUE THREAD

**Issue by isliser** [rbock/sqlpp11#72]
```
SQLPP_DECLARE_TABLE(
	(clients)
	,
	(login,		int,			SQLPP_PRIMARY_KEY)
	(name,		text,			SQLPP_NOT_NULL)
	(address,	text,			SQLPP_NOT_NULL)
)

const auto clients = clients::clients{};
auto i = insert_into(clients).columns(clients.login, clients.name);
```

Output:

> insert_value_list.h(550): error C2338: at least one column argument has a must_not_insert tag in its definition

In sqlpp11\include\sqlpp11\ppgen\colops\primary_key.h I see such code
```
#define SQLPP_DECLARE_COLUMN_GEN_TRAITS_PROC_SQLPP_PRIMARY_KEY(...) \
  ::sqlpp::tag::must_not_insert, ::sqlpp::tag::must_not_update
```
which prevent from inserting

**Comment by niXman** [comment]
Hi,

Removing the `::sqlpp::tag::must_not_insert` property solves problem?

And yes, `::sqlpp::tag::must_not_insert` should be used for `AUTO_INCREMENT` columns. Sorry.

**Comment by niXman** [comment]
> And yes, ::sqlpp::tag::must_not_insert should be used for AUTO_INCREMENT columns.

Hmm...
```
#define SQLPP_DECLARE_COLUMN_GEN_TRAITS_PROC_SQLPP_AUTO_INCREMENT(...) \
   ::sqlpp::tag::must_not_update
```
Should be `::sqlpp::tag::must_not_insert, ::sqlpp::tag::must_not_update` here?
I am not a specialist in databases.

**Comment by isliser** [comment]
Hello!

> Should be ::sqlpp::tag::must_not_insert, ::sqlpp::tag::must_not_update here?

I suppose it should

> I am not a specialist in databases.

Me too :)

**Comment by isliser** [comment]
Postgres allows insert into field with auto increment declariation, but theoretically others dbms could prohibit it

**Comment by rbock** [comment]
In the end, it is a design decision. If ids have auto increment, do you want your application to mess with that? I haven't had such a case yet. I therefore disallow both insert and update for auto incremented columns.

**Comment by niXman** [comment]
Hi Roland!

Ok, so be it.

**Comment by niXman** [comment]
https://github.com/rbock/sqlpp11/pull/73

**Comment by rbock** [comment]
Done on develop
