### ISSUE TITLE
ddl2cpp issues

### ISSUE THREAD

**Issue by digitalist** [rbock/sqlpp11#75]
ddl2sql generates header with this sql:
```
CREATE TABLE `users`(
...
  `updated` TIMESTAMP NOT NULL DEFAULT '0000-00-00 00:00:00', 
...
) ENGINE=InnoDB  DEFAULT CHARSET=latin1
```
but fails with this (which is common statement to work with update times):
```
CREATE TABLE `users`(
...
  `updated` TIMESTAMP NOT NULL DEFAULT  now(),
...
) ENGINE=InnoDB  DEFAULT CHARSET=latin1
```
I guess the problem is here
```
# PARSER
def ddlWord(string):
    return WordStart(alphanums + "_") + CaselessLiteral(string) + WordEnd(alphanums + "_")
```

If I'll manage to beat it, there will be a pull-request, but for now it's an issue

**Comment by digitalist** [comment]
@rbock also, maybe we should install ddl2cpp to /usr/local/bin as a part of 'make install' ?

**Comment by rbock** [comment]
Yes, that is probably a good idea...

**Comment by digitalist** [comment]
hm, it seems you fixed you fixed the problem with default now(), closing this issue

**Comment by digitalist** [comment]
nah, it just doesn't throw errors while creating database/tables with now(). And it does not generate header file. Sorry (

**Comment by rbock** [comment]
To be honest, I do not even know what this column specification with two defaults is supposed to mean?

**Comment by digitalist** [comment]
oi, I somehow managed to double defaults during editing %)

**Comment by rbock** [comment]
Ah! Now it makes much more sense :-)

Are you still trying to look into it?

**Comment by digitalist** [comment]
as soon as I have some time. As I remember this should be an easy fix - adding "(" and ")" to allowed chars in ddl2cpp and passing empty value while constructing sql query

**Comment by digitalist** [comment]
seems working with #85

**Comment by rbock** [comment]
Looks good to me
