### ISSUE TITLE
Is it possible to add custom keywords to an insert clause?

### ISSUE THREAD

**Issue by isliser** [rbock/sqlpp11#76]
I want to use sql dialect in an insert clause, how can I do it? 
For example 
```
"INSERT OR IGNORE INTO Rates(Id, Rate)"
"VALUES(1, 10)"
```

**Comment by rbock** [comment]
There are several ways. Please take a look at the custom query test to get a first idea. Also, you could create a insert_or_ignore_into statement. Basically you copy insert.h and modify it a bit. If you want to use this more often, I would recommend the latter option.

You could contribute that to the respective connector, of course :-)

**Comment by rbock** [comment]
Hi,

I just realized that not all components are available for custom queries yet. I pushed a small change to develop so that you can write a custom query like this:

```
custom_query(sqlpp::insert(), sqlpp::verbatim(" OR IGNORE"), into(t),
                  insert_set(t.beta = "sample", t.gamma = true));
```

Results into:

```
INSERT   OR IGNORE  INTO tab_bar  (beta,gamma) VALUES('sample',1)
```

If you're working on master, you should be able to cherry-pick this commit.

**Comment by isliser** [comment]
Hello!

This is what I wanted

**Comment by rbock** [comment]
Great :-)

I opened an issue for adding missing functions for custom query components, see #77 
If you need any particular one in advance, please let me know or create a pull request (if you look at insert_value_list.h, you will see that the function is quite simple).

**Comment by vrqq** [comment]
How about to batch INSERT for INSERT IGNORE ?
 (mysql)

**Comment by rbock** [comment]
With the latest commit you can do something like this:

```c++
  auto batch = insert_columns(bar.beta, bar.gamma);
  batch.values.add(bar.beta = "sample", bar.gamma = true);
  batch.values.add(bar.beta = "ample", bar.gamma = false);
  auto query = custom_query(sqlpp::insert(), sqlpp::verbatim(" OR IGNORE"), into(bar), batch);
```

`query` serializes into:

``` SQL
INSERT  OR IGNORE  INTO tab_bar  (beta,gamma) VALUES ('sample',1),('ample',0)
```
