### ISSUE TITLE
get last_insert_id (autoincremented id)

### ISSUE THREAD

**Issue by digitalist** [rbock/sqlpp11#78]
```
 db.run(insert_into(users).set(
                    users.login = user.credentials.login,
                    users.password = user.credentials.password
            ));
```
how to get last inserted id? I grepped through source  and found
` size_t insert(const Insert& i)`

I tried 
```
return insert_into(users).set(
                    users.login = user.credentials.login,
                    users.password = user.credentials.password
            );
```

and got this:
`error: cannot convert ‘sqlpp::no_insert_value_list_t::_base_t<sqlpp::detail::statement_policies_t<void, sqlpp::insert_t, sqlpp::into_t<void, db::Users>, sqlpp::no_insert_value_list_t> >::_new_statement_t<sqlpp::consistent_t, sqlpp::insert_list_t<void, sqlpp::assignment_t<sqlpp::column_t<db::Users, db::Users_::Login>, sqlpp::text_operand>, sqlpp::assignment_t<sqlpp::column_t<db::Users, db::Users_::Password>, sqlpp::text_operand> > > {aka sqlpp::statement_t<void, sqlpp::insert_t, sqlpp::into_t<void, db::Users>, sqlpp::insert_list_t<void, sqlpp::assignment_t<sqlpp::column_t<db::Users, db::Users_::Login>, sqlpp::text_operand>, sqlpp::assignment_t<sqlpp::column_t<db::Users, db::Users_::Password>, sqlpp::text_operand> > >}’ to ‘size_t {aka long unsigned int}’ in return`

**Comment by rbock** [comment]
`lastInsertId = db(insert_into(...));` should work.

**Comment by digitalist** [comment]
thanks, that worked.
