### ISSUE TITLE
count() cannot be used on an aggregate function

### ISSUE THREAD

**Issue by juandent** [rbock/sqlpp11#81]
Hi,
On MSVC 2015 Update 2, I rebuilt the solution with only one problem in the static_assert of:

template <typename T>
  auto count(T t) -> count_t<noop, wrap_operand_t<T>>
  {
    static_assert(not contains_aggregate_function_t<wrap_operand_t<T>>::value,
                  "count() cannot be used on an aggregate function");
    static_assert(is_expression_t<wrap_operand_t<T>>::value, "count() requires an expression as argument");
    return {t};
  }

on Project: sqlpp11_count_of_count, Configuration: Debug Win32

Is this on purpose?

Also, is Microsoft SQLSERVER supported with sqlpp11?

Thanks!
Juan Dent

**Comment by rbock** [comment]
Hi Juan,

Yes, the failure is on purpose. Actually, you should see several compilation failures: The programs in test_constraints are _supposed_ to fail. The pattern given in the respective CMakeLists.txt corresponds to the expected text from a `static_assert`.

If you use cmake, these should only be compiled when running ctest.

Best,

Roland

**Comment by rbock** [comment]
Oh and the second question:

There is an experimental ODBC connector by @Erroneous1: https://github.com/Erroneous1/sqlpp11-connector-odbc

Maybe you can use and improve that one?

Best,

Roland

PS: please open multiple issues for multiple questions. It is much easier to handle.

**Comment by Erroneous1** [comment]
The sqlpp11 odbc connector _should_ work under Windows (unixodbc code compiles in MSVC with no changes in my experience) but please let me know if anything doesn't work. I would mention that wide characters are not currently supported, but I believe it should work fine on 32 or 64 bit.
