### ISSUE TITLE
Necessary change to deal with cero parameters

### ISSUE THREAD

**Issue by juandent** [rbock/sqlpp11#82]
Hi Roland,

I have found a bug in 
```C++
template <typename... Parameter>
  struct parameter_list_t<detail::type_vector<Parameter...>> : public Parameter::_instance_t...
```
Specifically the following line lacks an integer:
```C++
(void)swallow{ (
          static_cast<typename std::tuple_element<Is, const _member_tuple_t>::type&>(*this)()._bind(target, Is), 0)...};
```
this line must have one integer like so:
```C++
(void)swallow{0, (
          static_cast<typename std::tuple_element<Is, const _member_tuple_t>::type&>(*this)()._bind(target, Is), 0)...};
```

this is to deal with the case where the number of parameters is cero (`size::value == 0`) and thus the index sequence is empty an the int array cannot be created (the "swallow instance: `swallow{}`").
```C++
using size = std::integral_constant<std::size_t, sizeof...(Parameter)>;
```
Regards,
Juan

**Comment by rbock** [comment]
Fixed with the latest release
