### ISSUE TITLE
implementing cache interface

### ISSUE THREAD

**Issue by digitalist** [rbock/sqlpp11#86]
In high-load systems we can easily go over the limit of database connections, which is very bad. 

One of the ways (apart from heavy scaling and load-balancing) to prevent this is to use some caching mechanism.
It can be a dumb 'file-based' caching or, for more sophisticated example, memcache.  Typical php-implementation is:
- hash query, store results in cache for limited lifetime
- if new query has a same hash, return cached results.
- otherwise make actual connection and query the database, store results in cache.

I doubt it's a good idea to  insert any concrete caching functionality (except, maybe some filebased example with caching to /tmp/), but I guess some interface/hooks  so user can implement them could be very useful
do you have any plans on implementing such interface and how? (callbacks / mixins / plugins, etc)

**Comment by rbock** [comment]
I have no plans for implementing an interface for hooks. I'll need some time to think about that.

If you have ideas, please let me know.

I do have plans for connection pooling, which is also important for performance/load sensitive applications. That's something for the connector libraries, though.

**Comment by digitalist** [comment]
should I leave this issue open as a reminder/request for comments?

**Comment by rbock** [comment]
Sorry for the long radio silence. I am a bit swamped these days.

Yes, let's leave it open.

**Comment by digitalist** [comment]
linking https://github.com/rbock/sqlpp11/issues/86  as a reminder for myself

**Comment by ruipacheco** [comment]
Has this gone forward? Most ORMs support a form of local cache and its the one issue that keeps me from being able to propose sqlpp11 for evaluation.

**Comment by rbock** [comment]
I added this to the wish list I am currently compiling.

**Comment by tan-tan-kanarek** [comment]
I need it as well and intend to implement it using redis.
The idea is to predefine what objects should be cached, sometimes with their related objects that queried using foreign keys and cache them after migrating the row to DTO, probably by serializing the DTO to JSON.
The cache configuration should enable caching an object or group of objects based on common foreign key, e.g. cache all device objects that associated with the same user id.
Additionally I want to enable cache invalidation mechanism using deletion or even better by setting time value on invalidation key that matching the cache key, the invalidation should be triggered by write actions.

**Comment by rbock** [comment]
@tan-tan-kanarek That sounds like a pretty concrete plan already.

I am curious as to how you intend to do it? Are you going to modify an existing connector? Or write a wrapper for the connector?

**Comment by tan-tan-kanarek** [comment]
I have no plans on how, just the what, any ideas or thoughts will be greatly appreciated. I need it at the moment for mysql only but don't mind to take the extra mile to make it more generic, on few levels:
1. Support any relational db.
2. Support any document store as cache engine.
3. Support any key value store for invalidation keys.
4. Support working with no invalidation.
