### ISSUE TITLE
printable objects

### ISSUE THREAD

**Issue by hartsantler** [rbock/sqlpp11#93]
just getting started with sqlpp11.  i would like to print some of the objects, and see the SQL they are generating is there a simple way to do this?  When trying `std::cout << insert_into(f) << std::endl;` i get this error:
```
error: cannot bind ‘std::ostream {aka std::basic_ostream<char>}’ lvalue to ‘std::basic_ostream<char>&&’
```

**Comment by rbock** [comment]
Hi,

The exact result of serialization depends on the database for some expressions. You therefore need the serializer of your database connector (or the one from MockDb) and then use it like this:


```
  MockDb db = {};
  MockDb::_serializer_context_t printer = {};
  const auto t = test::TabBar{};

  std::cout << serialize(insert_into(t).columns(t.beta, t.gamma), printer).str() << std::endl;
  printer.reset(); // Clean the buffer, if you want to print more expressions with this printer.
```

Best,

Roland
