### ISSUE TITLE
insert_into and set

### ISSUE THREAD

**Issue by hartsantler** [rbock/sqlpp11#94]
Most of the code/syntax is easy to read, and imagine what it would look like as SQL.  Except for `insert_into` and `set`, which can look awkward in some cases. 

On the frontpage, there is this example:
```c++
// A sample insert
db(insert_into(foo).set(foo.id = 17, foo.name = "bar", foo.hasFun = true));
```

Above is clear and simple, `foo` is passed to `insert_into`, and only members of `foo` is used inside of `set`.  Most of the examples are like this.  Except for `/examples/sample.cpp`

examples/sample.cpp : line 37
```c++
 db(insert_into(f).set(f.name = "Loves C++", p.fatal = false));
```

above looks strange because `f` is passed to `insert_into`, but in `set` both `f` and `p` are used.

I did not find much info on insert or set in the wiki, it would be good to document how they both work.
https://github.com/rbock/sqlpp11/wiki/Insert

**Comment by hartsantler** [comment]
actually, i think `p.fatal=false` is a typo bug in `/examples/sample.cpp`.  because the person table doesn't have a member `fatal`.

```
error: ‘struct mydatabase::TabPerson’ has no member named ‘fatal’
	errors: 1
385		file: /tmp/mytest.cpp
			  insert_into(f).set(f.name="Loves C++",p.fatal=false);
```

**Comment by hartsantler** [comment]
i guess that is a typo in sample.cpp, because when i try this:
```
	auto p = mydatabase::TabPerson();
	auto f = mydatabase::TabFeature();
	insert_into(f).set(f.name="Loves C++", f.fatal=false, p.name="Roland", p.feature=1);
```

i get this error:  set() arguments contain assignments from more than one table

```
portable_static_assert.h:40:7: error: static assertion failed: set() arguments contain assignments from more than one table
```

**Comment by rbock** [comment]
Hi,

Actually, the commented out examples where used to demonstrate nice error messages.

I should make this clear with a comment...

Best,

Roland
