### ISSUE TITLE
examples/sample.cpp needs comments

### ISSUE THREAD

**Issue by hartsantler** [rbock/sqlpp11#95]
two things jump out as strange in sample.cpp in the examples folder.

line 42:
`.from(p, q)`

where is `q` defined?

line 50:
`auto x = s.as(sqlpp::alias::x);`

what is sqlpp::alias::x ?
why is the name of the variable `x` also under the alias namespace?

**Comment by rbock** [comment]
Hi,

Thanks for this and the other hints. I need to take better care of the examples and make it clear if something is supposed to not compile. Also, it is tough to keep track of examples that are not compiling.

Line 42: Please ignore. This is wrong in several ways. Should probably be `.from(p.join(f).unconditionally)))`, but I did not test.


Line 50: `sqlpp::alias::x` is a struct that carries a name that can be used as an alias in a select statement, e.g. `SELECT something AS x`. There are several of those: `a` - `z` and `left`, `right`.

`auto x = s.as(sqlpp::alias::x);` therefore is a variable that represents a subselect that has been given the alias `x`.

Pull requests for improving examples are most welcome :-)

Best,

Roland
