### ISSUE TITLE
examples/select.cpp totally confusing

### ISSUE THREAD

**Issue by hartsantler** [rbock/sqlpp11#97]
at the top of select is `SQLPP_ALIAS_PROVIDER(cheesecake)`.  which is used below, but only in code that has been disabled with `#if 0` macros.  What is cheesecake for? just another variable name like `foo` and `bar`?

also confusing is the example defines a function called `select`, and in its body calls `dynamic_select` and `dynamic_columns`.

in order to understand quickly how select works, it would be helpful to have some simple examples, with minimal comments, that also compiles and print something.

**Comment by digitalist** [comment]
I had no troubles with understanding select operation from the [wiki](https://github.com/rbock/sqlpp11/wiki/Select). Did you try it? If it helps you, maybe you can commit some updated/upgraded/simplified examples?

**Comment by rbock** [comment]
As @digitalist mentioned, the documentation is in the Wiki.

The examples were used in my talk at CppCon 2014 and are kept for reference. Outside the context of the talk, they probably do not make much sense, indeed. Thanks for pointing that out!

I added a README that says so.

As I wrote in an earlier conversion and also suggested by @digitalist pull requests with better examples are very welcome.
