### ISSUE TITLE
ddl2cpp ignores names that start with `_`

### ISSUE THREAD

**Issue by hartsantler** [rbock/sqlpp11#98]
the helper script ddl2cpp fails to generate templates if the names in a table start with an underscore.

```ddl
CREATE TABLE Person
(
    _id int PRIMARY KEY,
    _parent int
);
```

**Comment by digitalist** [comment]
@rbock  I can look into this

**Comment by rbock** [comment]
@digitalist Great! I appreciate it!

**Comment by digitalist** [comment]
@hartsantler I'm looking in to this problem and noticed, if it helps you, it creates full header if you quote names like this:
```
CREATE TABLE Person
(
    `_id` int PRIMARY KEY,
    `_parent` int
);
```
though I didn't check yet if it works in C++ code (It should, I think)

**Comment by digitalist** [comment]
@hartsantler you can test my patch in #99

**Comment by digitalist** [comment]
p.s. it's an edge case, because` `columnName` ` syntax works and you always generate correct `CREATE` statements  - with proper quoting with MySQL at least. But yes, it should be fixed, because we allow unquoted alphanums names

**Comment by douyw** [comment]
Thanks the authors for this great project. I have already used it in my projects. 

I created my own code generator tool for sqlpp11 using ruby/rails. It's called **sqlpp11gen**, which can be found [here](https://github.com/douyw/sqlpp11gen). The gem version won't work for now, but you can install it manually as introduced in README.

**Comment by rbock** [comment]
I created a release including @digitalist's patches today (thanks again!).

@douyw Thanks for the link.
